### ISSUE TITLE
Missing row dendrogram

### ISSUE THREAD

**Issue by bitaq** [broadinstitute/inferCNV#12]
Hey,

I tried to run the example but got the following issue.

`2018-03-12 10:49:35 INFO::plot_cnv_references:Writing reference data to quickstart/references.txt
null device 
          1 
Warning message:
In heatmap.cnv(obs_data, Rowv = obs_dendrogram, Colv = FALSE, cluster.by.col = FALSE,  :
  Discrepancy: row dendrogram is asked; cluster.by.row is set to 'TRUE'.`

I got the same issue when I applied it to my data but could not find the issue in the script. Do you have any idea why this is happening?  The _observations_dendrogram.txt_ is there, so it passes that step but apparently the dendrogram is not used for the heatmap function.

**Comment by GeorgescuC** [comment]
Hi bitaq,

This is only a warning and the argument raising it is changed to the correct value at the same time, so the dendrogram should still appear at the bottom left of the figure. I pushed a fix in commit 9b5fa10e637515a9217a6c23169a6e0d5f0f623e to directly use the proper argument so as not to raise a warning anymore.
