### ISSUE TITLE
could not find function "ngchm"

### ISSUE THREAD

**Issue by Jemkon** [broadinstitute/infercnv#122]
Hi,

I have recently installed inferCNV and successfully run 2-step protocol. I have got all the output files . Now I would like to view inferCNV object into interactive heatmap using `ngchm` function.

When I tried running `ngchm` function from R it gave me following error:

    library(NGCHM)
    ngchm(infercnv_obj  = infercnv_obj,
           out_dir              = ".",
           path_to_shaidyMapGen = "./ShaidyMapGen.jar",
           gene_symbol          = "bio.gene.hugo")

    Error in ngchm(infercnv_obj = infercnv_obj, out_dir = ".", path_to_shaidyMapGen = 
    "./ShaidyMapGen.jar") : 
      could not find function "ngchm"

I am using R-3.5 and Java 1.8.  Although it loads inferCNV, NGCHM packages without any error. 

Any help much appreciated. 

Thanks

**Comment by brownmp** [comment]
Hello @Jemkon ,

In the most resent release of infercnv-0.99.0, the function ngchm() was moved to a separate package [infercnvNGCHM](https://github.com/broadinstitute/infercnvNGCHM). 

-Maxwell
