### ISSUE TITLE
Error in matrix(if (is.null(value)) logical() else value, nrow = nr, dimnames = list(rn,  :    length of 'dimnames' [2] not equal to array extent

### ISSUE THREAD

**Issue by nuan604** [broadinstitute/infercnv#137]
When I run the infercnv_obj
infercnv_obj  <- infercnv::CreateInfercnvObject(raw_counts_matrix=data, 
                                               gene_order_file=genes,
                                               annotations_file=annots,
                                               ref_group_names=c("normal"))
the error is in matrix(if (is.null(value)) logical() else value, nrow = nr, dimnames = list(rn,  : 
  length of 'dimnames' [2] not equal to array extent

How to solve this problem ?Thanks!

**Comment by GeorgescuC** [comment]
Hi @nuan604,

Are you trying to run the example data provided? If yes, have you loaded it with `data(data)`, `data(annots)`, `data(genes)` first?
Also, which version/commit are you using?

Regards.

**Comment by nuan604** [comment]
> Hi @nuan604,
> 
> Are you trying to run the example data provided? If yes, have you loaded it with `data(data)`, `data(annots)`, `data(genes)` first?
> Also, which version/commit are you using?
> 
> Regards.

Hi George,

Thanks for your reply! Now I know the reason for the error. The chromatin info should be chr1 instead of 1 in the gene_order_file. Thanks so much for developing the tools!

Ziyi
