### ISSUE TITLE
Installation trouble

### ISSUE THREAD

**Issue by aditisk** [broadinstitute/infercnv#139]
I am having trouble installing infercnv due to a version issue with R. What R version is required to use this package ? In the past I was able to use it with R3.5.3 but I am running into issues now. 

Any assistance with this would be very helpful.

Thanks.

**Comment by GeorgescuC** [comment]
Hi @aditisk ,

We have upgraded the R version requirement because of our submission of the package to BioConductor, which uses the latest devel version of R (3.6). There are two ways you can install it at the moment:
- First you can use the branch `RELEASE_0_99_4` that will allow you to install the package with no changes, but doesn't have the latest fixes. Simply run `devtools::install_github("broadinstitute/infercnv", ref="RELEASE_0_99_4")` to do so.
- Otherwise, you can download the `master` branch and change line 12 in the `DESCRIPTION` file to `Depends: R(>= 3.5)`. You can then install the package with `install.packages("./", repos=NULL, type="source")` from the root folder of the repo.

Regards.

**Comment by aditisk** [comment]
@GeorgescuC Thanks for the suggestions. I was able to install the package.

**Comment by aditisk** [comment]
@GeorgescuC I was able to install the tool as I mentioned yesterday but I am getting this error message:

**Error in nls(y ~ .logistic_midpt_slope(x, midpt = x0, slope = k), data = df,  :
  number of iterations exceeded maximum of 50
Calls: <Anonymous> ... .get_simulated_cell_matrix_using_meanvar_trend -> .get_logistic_params -> nls
Execution halted**


Here is my code (using the simplest version of the run method as per the tutorial:

library(infercnv)


infercnv_obj = CreateInfercnvObject(raw_counts_matrix="mod_matrix.txt",
                                    annotations_file="celltypes_infercnv.txt",
                                    delim="\t",
                                    gene_order_file="gencode.txt",
                                    ref_group_names=NULL)

infercnv_obj = infercnv::run(infercnv_obj,
                             cutoff=0.1,
                             out_dir="output_dir_samples",
                             cluster_by_groups=T,
                             denoise=T,
                             HMM=T)


Is there something I am doing incorrectly ?

**Comment by GeorgescuC** [comment]
Hi @aditisk ,

I believe this should be fixed on our devel branch. You can run `devtools::install_github("broadinstitute/infercnv", ref="09e2f011f7d8cd5ed75f139f75b1a24871952637")` to install the current patch (we are in the process of making some other updates, so using this commit should be safer than getting the latest devel version). If you still get an error, please let me know.

Regards.

**Comment by aditisk** [comment]
Hi @GeorgescuC,

I am getting the same error again even with the new commit that you suggested installing.

**Comment by GeorgescuC** [comment]
Hi @aditisk ,

The error should now be fixed on our devel branch if you can try running things again after installing it with `devtools::install_github("broadinstitute/infercnv", ref="devel")`.

**Comment by aditisk** [comment]
@GeorgescuC Thanks for fixing the issue in the devel branch. I am getting a new error now:

**This is the message in my output file:**

INFO [2019-04-17 14:18:36] Parsing matrix: exprMatrix_epi.tsv
INFO [2019-04-17 14:22:51] Parsing gene order file: gencode.txt
INFO [2019-04-17 14:22:51] Parsing cell annotations file: infer_cells_epi.txt
INFO [2019-04-17 14:22:52] ::order_reduce:Start.
INFO [2019-04-17 14:22:52] .order_reduce(): expr and order match.
INFO [2019-04-17 14:22:53] ::process_data:order_reduce:Reduction from positional data, new dimensions (r,c) = 8068,11846 Total=2256270.65108599 Min=-6.674069 Max=10.
INFO [2019-04-17 14:22:53] num genes removed taking into account provided gene ordering list: 1110 = 13.7580565195835% removed.
INFO [2019-04-17 14:22:53] validating infercnv_obj
INFO [2019-04-17 14:22:53] ::process_data:Start
INFO [2019-04-17 14:22:53]

        STEP 1: incoming data

INFO [2019-04-17 14:22:53]

        STEP 02: Removing lowly expressed genes

INFO [2019-04-17 14:22:53] -restoring infercnv_obj from epi_infercnv/02_reduced_by_cutoff.infercnv_obj
INFO [2019-04-17 14:22:56]

        STEP 03: normalization by sequencing depth

INFO [2019-04-17 14:22:56] normalizing counts matrix by depth
INFO [2019-04-17 14:22:56] Computed total sum normalization factor as median libsize: 507.626085
INFO [2019-04-17 14:22:56] Adding h-spike
INFO [2019-04-17 14:22:56] -no normals defined, using all observation cells as proxy
INFO [2019-04-17 14:22:56] -hspike modeling of normalsToUse
(Error in nls(y ~ .logistic_midpt_slope(x, midpt = x0, slope = k), data = df, : number of iterations exceeded maximum of 50
), couldn't fit logistic, but no worries, going to use a spline

**This is the message in the error file:**

Error in smooth.spline(logv ~ logm) :
  missing or infinite values in inputs are not allowed
Calls: <Anonymous> ... .get_simulated_cell_matrix_using_meanvar_trend_helper -> smooth.spline
In addition: Warning message:
In log(mean_var_table$m + 1) : NaNs produced
Execution halted

**Comment by GeorgescuC** [comment]
Hi @aditisk ,

I am unable to reproduce the issue you encounter with our test sets, would you be willing to share the data privately so we (the infercnv development team) can try and debug the issue? (we won't share the data) If you are, you can send it to cgeorges , broadinstitute org

Regards

**Comment by aditisk** [comment]
@GeorgescuC I have sent you an email. We can discuss further privately.

Thanks.

**Comment by pangxueyu233** [comment]
@aditisk Hi，
Recently, I used the inferCNV inputting my 10X single cell data and meet the same error liek you: 
(Error in nls(y ~ .logistic_midpt_slope(x, midpt = x0, slope = k), data = df, : number of iterations exceeded maximum of 50
), couldn't fit logistic, but no worries, going to use a spline
Error in smooth.spline(x, mean_p0_table$p0) :
  missing or infinite values in inputs are not allowed

So, have you fixed it up and how did you achieved ?
