### ISSUE TITLE
error in R

### ISSUE THREAD

**Issue by DRLaks** [broadinstitute/infercnv#14]
Hello, thanks for this great tool. Unfortunately, I can not get these R commands to work. Is there a tutorial or more elaborate R instructions? This is my current issue/problem:
> order_reduce(Tumor3Only, resb)
Error in genomic_position[2] + genomic_position[3] : 
  non-numeric argument to binary operator
![screen shot 2018-04-17 at 1 32 36 pm](https://user-images.githubusercontent.com/23214127/38886496-1eecf138-4244-11e8-93b7-da1bf1bb9814.png)

**Comment by DRLaks** [comment]
I tried that but it does not seem to be the issue. Have you used infer_CNV in R yet?

**Comment by Puriney** [comment]
Strictly follow the format of the example <https://github.com/broadinstitute/inferCNV/blob/master/example/example_genomic_positions.txt> 

So remove the header. Change the "chr*" to "*" only.
