### ISSUE TITLE
Trouble installing infercnv

### ISSUE THREAD

**Issue by lawrenceli216** [broadinstitute/infercnv#146]
When I try to install infercnv from R 3.6 using the line 
devtools::install_github("broadinstitute/infercnv", ref="RELEASE_0_99_4")

I get the error "No commit found for the ref RELEASE_0_99_4"

I'm very new to this, so it is likely something I'm missing on my part. Could someone help me with this?

**Comment by GeorgescuC** [comment]
Hi @lawrenceli216 ,

We updated our branches with the BioConductor release of the package, so that branch does not exist anymore, I will be updating the wiki to fix that.

You can now install infercnv from BioConductor by running the following (requires R 3.6 and BioConductor 3.9):

```
if (!requireNamespace("BiocManager", quietly = TRUE))
     install.packages("BiocManager")
BiocManager::install("infercnv")
```

If you have an older version of R and cannot update at this time, you will need to download the repository with `git clone https://github.com/broadinstitute/infercnv.git` and then update the DESCRIPTION file to lower the R version required line 10 from `Depends: R(>= 3.6)` to the version you are using. Then run R from the downloaded copy and run `install.packages("./", repos=NULL, type="source")`

Regards,
Christophe.

**Comment by lawrenceli216** [comment]
Thank you, I seem to have been able to install it.

I'm also trying to run inferCNV on the example as provided in the wiki, but I seem to be having trouble with that as well. Would it be possible to help me out with this problem as well although it's off-topic now?

**Comment by GeorgescuC** [comment]
Sure, no problem. Which example are you trying to run?

The easiest example to run (that comes with the BioConductor version) is:

```
library(infercnv)

data(data)
data(annots)
data(genes)

infercnv_obj <- infercnv::CreateInfercnvObject(raw_counts_matrix=data, 
                                               gene_order_file=genes,
                                               annotations_file=annots,
                                               ref_group_names=c("normal"))

infercnv_obj <- infercnv::run(infercnv_obj,
                              cutoff=1,
                              out_dir=tempfile(), 
                              cluster_by_groups=TRUE, 
                              denoise=TRUE,
                              HMM=FALSE)
```

**Comment by lawrenceli216** [comment]
I was trying to run the example as provided in the quick start section of the wiki as provided below: 
"Quick Start

See Installing inferCNV for installation instructions. You have several choices.

Then move into the inferCNV folder and call the following function:

cd inferCNV/example   

Rscript ./run.R

This will run inferCNV on test example data and should produce the figure at the bottom of this page."

However, I was able to run your example. To be honest, I have 0 experience with these types of programs and codes, so I'm just trying to make sure everything is working properly before I start learning. In order to generate the heatmap as shown in the wiki, is there something else I would need to install?

Thank you.

**Comment by GeorgescuC** [comment]
These instructions are if you downloaded the github repository. If you are using the version installed from BioConductor, you can locate the input files by running from within R

```
system.file("extdata", "gencode_downsampled.EXAMPLE_ONLY_DONT_REUSE.txt", package = "infercnv")
system.file("extdata", "oligodendroglioma_annotations_downsampled.txt", package = "infercnv")
system.file("extdata", "oligodendroglioma_expression_downsampled.counts.matrix.gz", package = "infercnv")
```

Which to run the full example becomes:

```
library(infercnv)

infercnv_obj = CreateInfercnvObject(raw_counts_matrix=system.file("extdata", "oligodendroglioma_expression_downsampled.counts.matrix.gz", package = "infercnv"),
                                    annotations_file=system.file("extdata", "oligodendroglioma_annotations_downsampled.txt", package = "infercnv"),
                                    delim="\t",
                                    gene_order_file=system.file("extdata", "gencode_downsampled.EXAMPLE_ONLY_DONT_REUSE.txt", package = "infercnv"),
                                    ref_group_names=c("Microglia/Macrophage","Oligodendrocytes (non-malignant)")) 

infercnv_obj = infercnv::run(infercnv_obj,
                             cutoff=1, # cutoff=1 works well for Smart-seq2, and cutoff=0.1 works well for 10x Genomics
                             out_dir=tempfile(), 
                             cluster_by_groups=TRUE, 
                             denoise=TRUE,
                             HMM=TRUE)
```

Nothing else is required to generate the heatmaps shown in the wiki. I would just make sure to define the "out_dir" to something you define rather than tempfile() (which is a temporary location for R files) so you don't loose the files generated.

**Comment by lawrenceli216** [comment]
If I wanted to change the output directory to lets say, a folder on my desktop, would I just write in the name of the folder, eg. out_dir="C:\Users\lawre\Desktop\Foldername"

**Comment by GeorgescuC** [comment]
Yes, that sounds good.

**Comment by lawrenceli216** [comment]
Thank you so much, you've been amazing!

**Comment by lawrenceli216** [comment]
So I just ran the example you gave me of 
"library(infercnv)

infercnv_obj = CreateInfercnvObject(raw_counts_matrix=system.file("extdata", "oligodendroglioma_expression_downsampled.counts.matrix.gz", package = "infercnv"),
                                    annotations_file=system.file("extdata", "oligodendroglioma_annotations_downsampled.txt", package = "infercnv"),
                                    delim="\t",
                                    gene_order_file=system.file("extdata", "gencode_downsampled.EXAMPLE_ONLY_DONT_REUSE.txt", package = "infercnv"),
                                    ref_group_names=c("Microglia/Macrophage","Oligodendrocytes (non-malignant)")) 

infercnv_obj = infercnv::run(infercnv_obj,
                             cutoff=1, # cutoff=1 works well for Smart-seq2, and cutoff=0.1 works well for 10x Genomics
                             out_dir=tempfile(), 
                             cluster_by_groups=TRUE, 
                             denoise=TRUE,
                             HMM=TRUE)"

Am I to be expecting an image of the heatmap in .png form in the folder I specified?

**Comment by GeorgescuC** [comment]
Yes, although with this command, the out_dir is still `tempfile()`, so you will need to read in the log what the temporary path used was.

**Comment by lawrenceli216** [comment]
Thank you so much, I was able to find the heatmaps. You've helped me a lot!

**Comment by tingxie2020** [comment]
Hi, I have issue on install infercnv in r, I tried BiocManager::install("infercnv"), it showed ERROR: dependencies ‘ape’, ‘phyclust’, ‘parallelDist’, ‘HiddenMarkov’, ‘edgeR’, ‘coin’, ‘rjags’ are not available for package ‘infercnv’
and I am not be able to install any of the dependencies. 

I tried sudo docker pull trinityctat/infercnv:latest, but library(infercnv) it shows
Error in library("infercnv") : there is no package called ‘infercnv’

Please help. Thanks
