### ISSUE TITLE
Errors when running Bayesian Network Model on HMM predicted CNV's

### ISSUE THREAD

**Issue by lijiang825** [broadinstitute/infercnv#147]
Hi,

I ran into an error when infercnv::run is doing Bayesian Network Model on HMM predicted CNV's. Here is the error message:

STEP 13: Run Bayesian Network Model on HMM predicted CNV's

INFO [2019-05-13 13:51:10] Creating the following Directory:  analysis/inferCNV/new/out_dir/BayesNetOutput.HMMi6.hmm_mode-samples
INFO [2019-05-13 13:51:10] Initializing new MCM InferCNV Object.
INFO [2019-05-13 13:51:10] validating infercnv_obj
INFO [2019-05-13 13:51:10] Total CNV's:  804
INFO [2019-05-13 13:51:10] Loading BUGS Model.
INFO [2019-05-13 13:51:11] Running Sampling Using Parallel with  4 Cores
INFO [2019-05-13 16:15:43] Obtaining probabilities post-sampling
**Error in do.call(rbind, mcmc[[j]]) : second argument must be a list**

I am using R-3.5.2 on MacOS (High Sierra 10.13.6). The infercnv version is 1.1.0 (infercnv_1.1.0). 

Many thanks,
Li

**Comment by brownmp** [comment]
Hello @lijiang825,

Sorry to hear about the error. 
Would you happen to have a log for your Infercnv run that gives this error? If so you may post or email it to myself at mbrown@broadinstitute.org. Also for your version of Infercnv, which branch are you using? 

Best, 
-MB

**Comment by lijiang825** [comment]
Hi @brownmp,

Thanks for the reply! 

I reran with `HMM_type=i3` and it worked. I guess the bug might lie in the `i6` mode.  

I think I am using the master branch. I am using R.3.5.2, so I cloned the repo from github by `git clone https://github.com/broadinstitute/infercnv.git`, updated the DESCRIPTION file, and install by `install.packages("./", repos=NULL, type="source")`. The date in the DESCRIPTION file is: 2019-04-30.

Please find the log below for the infercnv run with error:

INFO [2019-05-13 11:37:22] ::process_data:Start
INFO [2019-05-13 11:37:22] 

	STEP 1: incoming data

INFO [2019-05-13 11:38:06] 

	STEP 02: Removing lowly expressed genes

INFO [2019-05-13 11:38:06] ::above_min_mean_expr_cutoff:Start
INFO [2019-05-13 11:38:06] Removing 2472 genes from matrix as below mean expr threshold: 1
INFO [2019-05-13 11:38:07] validating infercnv_obj
INFO [2019-05-13 11:38:07] There are 15562 genes and 5359 cells remaining in the expr matrix.
INFO [2019-05-13 11:38:11] no genes removed due to min cells/gene filter
INFO [2019-05-13 11:38:55] 

	STEP 03: normalization by sequencing depth

INFO [2019-05-13 11:38:55] normalizing counts matrix by depth
INFO [2019-05-13 11:38:57] Computed total sum normalization factor as median libsize: 946633.310000
INFO [2019-05-13 11:38:57] Adding h-spike
INFO [2019-05-13 11:38:57] -hspike modeling of mg
INFO [2019-05-13 11:41:39] -hspike modeling of od
INFO [2019-05-13 11:44:22] validating infercnv_obj
INFO [2019-05-13 11:44:22] normalizing counts matrix by depth
INFO [2019-05-13 11:44:22] Using specified normalization factor: 946633.310000
INFO [2019-05-13 11:44:58] 

	STEP 04: log transformation of data

INFO [2019-05-13 11:44:58] transforming log2xplus1()
INFO [2019-05-13 11:45:00] -mirroring for hspike
INFO [2019-05-13 11:45:00] transforming log2xplus1()
INFO [2019-05-13 11:45:37] 

	STEP 05: Clustering samples (not defining tumor subclusters)

INFO [2019-05-13 11:45:37] define_signif_tumor_subclusters(p_val=0.1
INFO [2019-05-13 11:45:38] define_signif_tumor_subclusters(), tumor: malignant_BT1030
INFO [2019-05-13 11:45:40] cut tree into: 1 groups
INFO [2019-05-13 11:45:40] -processing malignant_BT1030,malignant_BT1030_s1
INFO [2019-05-13 11:45:40] define_signif_tumor_subclusters(), tumor: malignant_BT1313
INFO [2019-05-13 11:45:41] cut tree into: 1 groups
INFO [2019-05-13 11:45:41] -processing malignant_BT1313,malignant_BT1313_s1
INFO [2019-05-13 11:45:41] define_signif_tumor_subclusters(), tumor: malignant_BT1334
INFO [2019-05-13 11:45:43] cut tree into: 1 groups
INFO [2019-05-13 11:45:43] -processing malignant_BT1334,malignant_BT1334_s1
INFO [2019-05-13 11:45:43] define_signif_tumor_subclusters(), tumor: malignant_CPDM0785
INFO [2019-05-13 11:45:45] cut tree into: 1 groups
INFO [2019-05-13 11:45:45] -processing malignant_CPDM0785,malignant_CPDM0785_s1
INFO [2019-05-13 11:45:45] define_signif_tumor_subclusters(), tumor: malignant_MUV006
INFO [2019-05-13 11:45:47] cut tree into: 1 groups
INFO [2019-05-13 11:45:47] -processing malignant_MUV006,malignant_MUV006_s1
INFO [2019-05-13 11:45:47] define_signif_tumor_subclusters(), tumor: malignant_MUV013
INFO [2019-05-13 11:45:51] cut tree into: 1 groups
INFO [2019-05-13 11:45:51] -processing malignant_MUV013,malignant_MUV013_s1
INFO [2019-05-13 11:45:51] define_signif_tumor_subclusters(), tumor: malignant_MUV014
INFO [2019-05-13 11:45:54] cut tree into: 1 groups
INFO [2019-05-13 11:45:54] -processing malignant_MUV014,malignant_MUV014_s1
INFO [2019-05-13 11:45:54] define_signif_tumor_subclusters(), tumor: malignant_MUV018
INFO [2019-05-13 11:45:59] cut tree into: 1 groups
INFO [2019-05-13 11:46:00] -processing malignant_MUV018,malignant_MUV018_s1
INFO [2019-05-13 11:46:00] define_signif_tumor_subclusters(), tumor: malignant_MUV021
INFO [2019-05-13 11:46:03] cut tree into: 1 groups
INFO [2019-05-13 11:46:03] -processing malignant_MUV021,malignant_MUV021_s1
INFO [2019-05-13 11:46:03] define_signif_tumor_subclusters(), tumor: malignant_MUV038
INFO [2019-05-13 11:46:08] cut tree into: 1 groups
INFO [2019-05-13 11:46:09] -processing malignant_MUV038,malignant_MUV038_s1
INFO [2019-05-13 11:46:09] define_signif_tumor_subclusters(), tumor: malignant_MUV043
INFO [2019-05-13 11:46:14] cut tree into: 1 groups
INFO [2019-05-13 11:46:14] -processing malignant_MUV043,malignant_MUV043_s1
INFO [2019-05-13 11:46:14] define_signif_tumor_subclusters(), tumor: malignant_MUV051
INFO [2019-05-13 11:46:16] cut tree into: 1 groups
INFO [2019-05-13 11:46:16] -processing malignant_MUV051,malignant_MUV051_s1
INFO [2019-05-13 11:46:16] define_signif_tumor_subclusters(), tumor: malignant_MUV052
INFO [2019-05-13 11:46:21] cut tree into: 1 groups
INFO [2019-05-13 11:46:21] -processing malignant_MUV052,malignant_MUV052_s1
INFO [2019-05-13 11:46:21] define_signif_tumor_subclusters(), tumor: malignant_MUV053
INFO [2019-05-13 11:46:26] cut tree into: 1 groups
INFO [2019-05-13 11:46:26] -processing malignant_MUV053,malignant_MUV053_s1
INFO [2019-05-13 11:46:26] define_signif_tumor_subclusters(), tumor: malignant_MUV056
INFO [2019-05-13 11:46:31] cut tree into: 1 groups
INFO [2019-05-13 11:46:31] -processing malignant_MUV056,malignant_MUV056_s1
INFO [2019-05-13 11:46:31] define_signif_tumor_subclusters(), tumor: malignant_MUV063
INFO [2019-05-13 11:46:34] cut tree into: 1 groups
INFO [2019-05-13 11:46:34] -processing malignant_MUV063,malignant_MUV063_s1
INFO [2019-05-13 11:46:34] define_signif_tumor_subclusters(), tumor: malignant_MUV068
INFO [2019-05-13 11:46:36] cut tree into: 1 groups
INFO [2019-05-13 11:46:36] -processing malignant_MUV068,malignant_MUV068_s1
INFO [2019-05-13 11:46:36] define_signif_tumor_subclusters(), tumor: malignant_MUV071
INFO [2019-05-13 11:46:42] cut tree into: 1 groups
INFO [2019-05-13 11:46:42] -processing malignant_MUV071,malignant_MUV071_s1
INFO [2019-05-13 11:46:42] define_signif_tumor_subclusters(), tumor: malignant_Peds4
INFO [2019-05-13 11:46:42] cut tree into: 1 groups
INFO [2019-05-13 11:46:42] -processing malignant_Peds4,malignant_Peds4_s1
INFO [2019-05-13 11:46:42] define_signif_tumor_subclusters(), tumor: malignant_BT1678
INFO [2019-05-13 11:46:42] cut tree into: 1 groups
INFO [2019-05-13 11:46:42] -processing malignant_BT1678,malignant_BT1678_s1
INFO [2019-05-13 11:46:42] define_signif_tumor_subclusters(), tumor: mg
INFO [2019-05-13 11:46:43] cut tree into: 1 groups
INFO [2019-05-13 11:46:43] -processing mg,mg_s1
INFO [2019-05-13 11:46:43] define_signif_tumor_subclusters(), tumor: od
INFO [2019-05-13 11:46:43] cut tree into: 1 groups
INFO [2019-05-13 11:46:43] -processing od,od_s1
INFO [2019-05-13 11:46:43] -mirroring for hspike
INFO [2019-05-13 11:46:43] define_signif_tumor_subclusters(p_val=0.1
INFO [2019-05-13 11:46:43] define_signif_tumor_subclusters(), tumor: spike_tumor_cell_mg
INFO [2019-05-13 11:46:43] cut tree into: 1 groups
INFO [2019-05-13 11:46:43] -processing spike_tumor_cell_mg,spike_tumor_cell_mg_s1
INFO [2019-05-13 11:46:43] define_signif_tumor_subclusters(), tumor: spike_tumor_cell_od
INFO [2019-05-13 11:46:44] cut tree into: 1 groups
INFO [2019-05-13 11:46:44] -processing spike_tumor_cell_od,spike_tumor_cell_od_s1
INFO [2019-05-13 11:46:44] define_signif_tumor_subclusters(), tumor: simnorm_cell_mg
INFO [2019-05-13 11:46:44] cut tree into: 1 groups
INFO [2019-05-13 11:46:44] -processing simnorm_cell_mg,simnorm_cell_mg_s1
INFO [2019-05-13 11:46:44] define_signif_tumor_subclusters(), tumor: simnorm_cell_od
INFO [2019-05-13 11:46:44] cut tree into: 1 groups
INFO [2019-05-13 11:46:44] -processing simnorm_cell_od,simnorm_cell_od_s1
INFO [2019-05-13 11:47:21] 

	STEP 06: removing average of reference data (before smoothing)

INFO [2019-05-13 11:47:21] ::subtract_ref_expr_from_obs:Start inv_log=FALSE, use_bounds=TRUE
INFO [2019-05-13 11:47:21] subtracting mean(normal) per gene per cell across all data
INFO [2019-05-13 11:47:27] -subtracting expr per gene, use_bounds=TRUE
INFO [2019-05-13 11:47:34] -mirroring for hspike
INFO [2019-05-13 11:47:34] ::subtract_ref_expr_from_obs:Start inv_log=FALSE, use_bounds=TRUE
INFO [2019-05-13 11:47:34] subtracting mean(normal) per gene per cell across all data
INFO [2019-05-13 11:47:39] -subtracting expr per gene, use_bounds=TRUE
INFO [2019-05-13 11:48:24] 

	STEP 07: apply max centered expression threshold: 3

INFO [2019-05-13 11:48:24] ::process_data:setting max centered expr, threshold set to: +/-:  3
INFO [2019-05-13 11:48:26] -mirroring for hspike
INFO [2019-05-13 11:48:26] ::process_data:setting max centered expr, threshold set to: +/-:  3
INFO [2019-05-13 11:49:12] 

	STEP 08: Smoothing data per cell by chromosome

INFO [2019-05-13 11:49:12] smooth_by_chromosome: chr: chr1
INFO [2019-05-13 11:49:21] smooth_by_chromosome: chr: chr2
INFO [2019-05-13 11:49:28] smooth_by_chromosome: chr: chr3
INFO [2019-05-13 11:49:35] smooth_by_chromosome: chr: chr4
INFO [2019-05-13 11:49:41] smooth_by_chromosome: chr: chr5
INFO [2019-05-13 11:49:48] smooth_by_chromosome: chr: chr6
INFO [2019-05-13 11:49:55] smooth_by_chromosome: chr: chr7
INFO [2019-05-13 11:50:01] smooth_by_chromosome: chr: chr8
INFO [2019-05-13 11:50:08] smooth_by_chromosome: chr: chr9
INFO [2019-05-13 11:50:14] smooth_by_chromosome: chr: chr10
INFO [2019-05-13 11:50:21] smooth_by_chromosome: chr: chr11
INFO [2019-05-13 11:50:27] smooth_by_chromosome: chr: chr12
INFO [2019-05-13 11:50:34] smooth_by_chromosome: chr: chr13
INFO [2019-05-13 11:50:40] smooth_by_chromosome: chr: chr14
INFO [2019-05-13 11:50:46] smooth_by_chromosome: chr: chr15
INFO [2019-05-13 11:50:52] smooth_by_chromosome: chr: chr16
INFO [2019-05-13 11:50:58] smooth_by_chromosome: chr: chr17
INFO [2019-05-13 11:51:05] smooth_by_chromosome: chr: chr18
INFO [2019-05-13 11:51:11] smooth_by_chromosome: chr: chr19
INFO [2019-05-13 11:51:18] smooth_by_chromosome: chr: chr20
INFO [2019-05-13 11:51:23] smooth_by_chromosome: chr: chr21
INFO [2019-05-13 11:51:29] smooth_by_chromosome: chr: chr22
INFO [2019-05-13 11:51:35] -mirroring for hspike
INFO [2019-05-13 11:51:35] smooth_by_chromosome: chr: chrA
INFO [2019-05-13 11:51:35] smooth_by_chromosome: chr: chr_0
INFO [2019-05-13 11:51:35] smooth_by_chromosome: chr: chr_B
INFO [2019-05-13 11:51:36] smooth_by_chromosome: chr: chr_0pt5
INFO [2019-05-13 11:51:36] smooth_by_chromosome: chr: chr_C
INFO [2019-05-13 11:51:37] smooth_by_chromosome: chr: chr_1pt5
INFO [2019-05-13 11:51:37] smooth_by_chromosome: chr: chr_D
INFO [2019-05-13 11:51:38] smooth_by_chromosome: chr: chr_2pt0
INFO [2019-05-13 11:51:38] smooth_by_chromosome: chr: chr_E
INFO [2019-05-13 11:51:38] smooth_by_chromosome: chr: chr_3pt0
INFO [2019-05-13 11:51:39] smooth_by_chromosome: chr: chr_F
INFO [2019-05-13 11:52:29] 

	STEP 09: re-centering data across chromosome after smoothing

INFO [2019-05-13 11:52:29] ::center_smooth across chromosomes per cell
INFO [2019-05-13 11:52:42] -mirroring for hspike
INFO [2019-05-13 11:52:42] ::center_smooth across chromosomes per cell
INFO [2019-05-13 11:53:34] 

	STEP 10: removing average of reference data (after smoothing)

INFO [2019-05-13 11:53:34] ::subtract_ref_expr_from_obs:Start inv_log=FALSE, use_bounds=TRUE
INFO [2019-05-13 11:53:34] subtracting mean(normal) per gene per cell across all data
INFO [2019-05-13 11:53:40] -subtracting expr per gene, use_bounds=TRUE
INFO [2019-05-13 11:53:48] -mirroring for hspike
INFO [2019-05-13 11:53:48] ::subtract_ref_expr_from_obs:Start inv_log=FALSE, use_bounds=TRUE
INFO [2019-05-13 11:53:48] subtracting mean(normal) per gene per cell across all data
INFO [2019-05-13 11:53:52] -subtracting expr per gene, use_bounds=TRUE
INFO [2019-05-13 11:54:42] 

	STEP 11: invert log2(FC) to FC

INFO [2019-05-13 11:54:42] invert_log2(), computing 2^x
INFO [2019-05-13 11:54:43] -mirroring for hspike
INFO [2019-05-13 11:54:43] invert_log2(), computing 2^x
INFO [2019-05-13 11:56:41] ::plot_cnv:Start
INFO [2019-05-13 11:56:41] ::plot_cnv:Current data dimensions (r,c)=15562,5359 Total=84190662.5290992 Min=0.36915849268929 Max=2.81144186086941.
INFO [2019-05-13 11:56:42] ::plot_cnv:Depending on the size of the matrix this may take a moment.
INFO [2019-05-13 11:58:06] plot_cnv(): auto thresholding at: (0.613552 , 1.405487)
INFO [2019-05-13 11:58:09] plot_cnv_observation:Start
INFO [2019-05-13 11:58:09] Observation data size: Cells= 5169 Genes= 15562
INFO [2019-05-13 11:58:09] clustering observations via method: ward.D
INFO [2019-05-13 11:58:11] plot_cnv_observation:Writing observation groupings/color.
INFO [2019-05-13 12:50:15] Colors for breaks:  #00008B,#24249B,#4848AB,#6D6DBC,#9191CC,#B6B6DD,#DADAEE,#FFFFFF,#EEDADA,#DDB6B6,#CC9191,#BC6D6D,#AB4848,#9B2424,#8B0000
INFO [2019-05-13 12:50:15] Quantiles of plotted data range: 0.613552095598489,0.936042865321244,1,1.06742837094263,1.40548712242721
INFO [2019-05-13 12:50:23] plot_cnv_references:Writing observation data to analysis/inferCNV/new/out_dir/infercnv.preliminary.observations.txt
INFO [2019-05-13 12:51:30] plot_cnv_references:Start
INFO [2019-05-13 12:51:30] Reference data size: Cells= 190 Genes= 15562
INFO [2019-05-13 12:51:31] plot_cnv_references:Number reference groups= 2
INFO [2019-05-13 12:51:31] plot_cnv_references:Plotting heatmap.
INFO [2019-05-13 12:51:56] Colors for breaks:  #00008B,#24249B,#4848AB,#6D6DBC,#9191CC,#B6B6DD,#DADAEE,#FFFFFF,#EEDADA,#DDB6B6,#CC9191,#BC6D6D,#AB4848,#9B2424,#8B0000
INFO [2019-05-13 12:51:56] Quantiles of plotted data range: 0.613552095598489,0.952095537575266,1,1.04801398787744,1.40548712242721
INFO [2019-05-13 12:51:56] plot_cnv_references:Writing reference data to analysis/inferCNV/new/out_dir/infercnv.preliminary.references.txt
INFO [2019-05-13 12:51:59] 

	STEP 12: HMM-based CNV prediction

INFO [2019-05-13 12:51:59] predict_CNV_via_HMM_on_whole_tumor_samples
INFO [2019-05-13 12:52:13] -done predicting CNV based on initial tumor subclusters
INFO [2019-05-13 12:52:43] get_predicted_CNV_regions(subcluster)
INFO [2019-05-13 12:52:43] -processing cell_group_name: malignant_BT1030.malignant_BT1030_s1, size: 233
INFO [2019-05-13 12:52:59] -processing cell_group_name: malignant_BT1313.malignant_BT1313_s1, size: 162
INFO [2019-05-13 12:53:15] -processing cell_group_name: malignant_BT1334.malignant_BT1334_s1, size: 239
INFO [2019-05-13 12:53:32] -processing cell_group_name: malignant_CPDM0785.malignant_CPDM0785_s1, size: 171
INFO [2019-05-13 12:53:48] -processing cell_group_name: malignant_MUV006.malignant_MUV006_s1, size: 228
INFO [2019-05-13 12:54:05] -processing cell_group_name: malignant_MUV013.malignant_MUV013_s1, size: 324
INFO [2019-05-13 12:54:22] -processing cell_group_name: malignant_MUV014.malignant_MUV014_s1, size: 267
INFO [2019-05-13 12:54:38] -processing cell_group_name: malignant_MUV018.malignant_MUV018_s1, size: 345
INFO [2019-05-13 12:54:55] -processing cell_group_name: malignant_MUV021.malignant_MUV021_s1, size: 278
INFO [2019-05-13 12:55:10] -processing cell_group_name: malignant_MUV038.malignant_MUV038_s1, size: 364
INFO [2019-05-13 12:55:25] -processing cell_group_name: malignant_MUV043.malignant_MUV043_s1, size: 354
INFO [2019-05-13 12:55:40] -processing cell_group_name: malignant_MUV051.malignant_MUV051_s1, size: 233
INFO [2019-05-13 12:55:54] -processing cell_group_name: malignant_MUV052.malignant_MUV052_s1, size: 302
INFO [2019-05-13 12:56:08] -processing cell_group_name: malignant_MUV053.malignant_MUV053_s1, size: 341
INFO [2019-05-13 12:56:23] -processing cell_group_name: malignant_MUV056.malignant_MUV056_s1, size: 335
INFO [2019-05-13 12:56:38] -processing cell_group_name: malignant_MUV063.malignant_MUV063_s1, size: 259
INFO [2019-05-13 12:56:53] -processing cell_group_name: malignant_MUV068.malignant_MUV068_s1, size: 250
INFO [2019-05-13 12:57:06] -processing cell_group_name: malignant_MUV071.malignant_MUV071_s1, size: 346
INFO [2019-05-13 12:57:22] -processing cell_group_name: malignant_Peds4.malignant_Peds4_s1, size: 109
INFO [2019-05-13 12:57:35] -processing cell_group_name: malignant_BT1678.malignant_BT1678_s1, size: 29
INFO [2019-05-13 12:57:48] -processing cell_group_name: mg.mg_s1, size: 96
INFO [2019-05-13 12:58:02] -processing cell_group_name: od.od_s1, size: 94
INFO [2019-05-13 12:58:16] -writing cell clusters file: analysis/inferCNV/new/out_dir/12_HMM_preds.cell_groupings
INFO [2019-05-13 12:58:16] -writing cnv regions file: analysis/inferCNV/new/out_dir/12_HMM_preds.pred_cnv_regions.dat
INFO [2019-05-13 12:58:19] -writing per-gene cnv report: analysis/inferCNV/new/out_dir/12_HMM_preds.pred_cnv_genes.dat
INFO [2019-05-13 12:58:19] -writing gene ordering info: analysis/inferCNV/new/out_dir/12_HMM_preds.genes_used.dat
INFO [2019-05-13 12:58:19] ::plot_cnv:Start
INFO [2019-05-13 12:58:19] ::plot_cnv:Current data dimensions (r,c)=15562,5359 Total=259236334 Min=2 Max=6.
INFO [2019-05-13 12:58:19] ::plot_cnv:Depending on the size of the matrix this may take a moment.
INFO [2019-05-13 12:59:10] plot_cnv_observation:Start
INFO [2019-05-13 12:59:10] Observation data size: Cells= 5169 Genes= 15562
INFO [2019-05-13 12:59:10] clustering observations via method: ward.D
INFO [2019-05-13 12:59:11] plot_cnv_observation:Writing observation groupings/color.
INFO [2019-05-13 13:49:47] Colors for breaks:  #00008B,#24249B,#4848AB,#6D6DBC,#9191CC,#B6B6DD,#DADAEE,#FFFFFF,#EEDADA,#DDB6B6,#CC9191,#BC6D6D,#AB4848,#9B2424,#8B0000
INFO [2019-05-13 13:49:47] Quantiles of plotted data range: 2,3,3,3,6
INFO [2019-05-13 13:49:55] plot_cnv_references:Writing observation data to analysis/inferCNV/new/out_dir/infercnv.12_HMM_predHMMi6.hmm_mode-samples.observations.txt
INFO [2019-05-13 13:50:42] plot_cnv_references:Start
INFO [2019-05-13 13:50:42] Reference data size: Cells= 190 Genes= 15562
INFO [2019-05-13 13:50:43] plot_cnv_references:Number reference groups= 2
INFO [2019-05-13 13:50:43] plot_cnv_references:Plotting heatmap.
INFO [2019-05-13 13:51:04] Colors for breaks:  #00008B,#24249B,#4848AB,#6D6DBC,#9191CC,#B6B6DD,#DADAEE,#FFFFFF,#EEDADA,#DDB6B6,#CC9191,#BC6D6D,#AB4848,#9B2424,#8B0000
INFO [2019-05-13 13:51:04] Quantiles of plotted data range: 3,3,3,3,3
INFO [2019-05-13 13:51:04] plot_cnv_references:Writing reference data to analysis/inferCNV/new/out_dir/infercnv.12_HMM_predHMMi6.hmm_mode-samples.references.txt
INFO [2019-05-13 13:51:10] 

         STEP 13: Run Bayesian Network Model on HMM predicted CNV's

INFO [2019-05-13 13:51:10] Creating the following Directory: analysis/inferCNV/new/out_dir/BayesNetOutput.HMMi6.hmm_mode-samples
INFO [2019-05-13 13:51:10] Initializing new MCM InferCNV Object.
INFO [2019-05-13 13:51:10] validating infercnv_obj
INFO [2019-05-13 13:51:10] Total CNV's: 804
INFO [2019-05-13 13:51:10] Loading BUGS Model.
INFO [2019-05-13 13:51:11] Running Sampling Using Parallel with 4 Cores
INFO [2019-05-13 16:15:43] Obtaining probabilities post-sampling
**Error in do.call(rbind, mcmc[[j]]) : second argument must be a list**

Thanks again,
Li

**Comment by brownmp** [comment]
Hi @lijiang825,

Reviewing the problem further, I believe there might be an issue allocating enough memory to the CPUs. Are you running infercnv on a server? If so, how much memory are you allocating? 
I might recommend running infercnv on one CPU at the moment as a possible quick fix. 

Best,
-MB
