### ISSUE TITLE
Error with rowMeans using infer_cnv

### ISSUE THREAD

**Issue by ChelseaCHENX** [broadinstitute/infercnv#149]
Hi, I used the typical two-steps of inferCNV but got an Error at the second step:

infercnv_obj = infercnv::run(infercnv_obj,
                              cutoff=0.1,  # use 1 for smart-seq, 0.1 for 10x-genomics
                           out_dir="../inferCNV_out/",  # dir is auto-created for storing outputs
                            cluster_by_groups=F,   # cluster
                             denoise=T,
                             HMM=T)

INFO [2019-05-20 18:01:52] ::process_data:Start
INFO [2019-05-20 18:01:52] 

	STEP 1: incoming data

INFO [2019-05-20 18:01:52] 

	STEP 02: Removing lowly expressed genes

INFO [2019-05-20 18:01:52] -restoring infercnv_obj from ../inferCNV_out//02_reduced_by_cutoff.infercnv_obj
INFO [2019-05-20 18:01:52] 

	STEP 03: normalization by sequencing depth

INFO [2019-05-20 18:01:52] normalizing counts matrix by depth
INFO [2019-05-20 18:01:53] Computed total sum normalization factor as median libsize: 32562.500000
INFO [2019-05-20 18:01:53] Adding h-spike
INFO [2019-05-20 18:01:53] -hspike modeling of macrophage
Error in base::rowMeans(x, na.rm = na.rm, dims = dims, ...) : 
  'x' must be an array of at least two dimensions

I generally do not know what went wrong as the first step works out fine:

 infercnv_obj = infercnv::run(infercnv_obj,
                             cutoff=0.1,  # use 1 for smart-seq, 0.1 for 10x-genomics
                             out_dir="../inferCNV_out/",  # dir is auto-created for storing outputs
                              cluster_by_groups=F,   # cluster
                              denoise=T,
                             HMM=T)
INFO [2019-05-20 18:01:15] ::process_data:Start
INFO [2019-05-20 18:01:15] 

	STEP 1: incoming data

INFO [2019-05-20 18:01:15] 

	STEP 02: Removing lowly expressed genes

INFO [2019-05-20 18:01:15] -restoring infercnv_obj from ../inferCNV_out//02_reduced_by_cutoff.infercnv_obj
INFO [2019-05-20 18:01:16] 

	STEP 03: normalization by sequencing depth

INFO [2019-05-20 18:01:16] normalizing counts matrix by depth
INFO [2019-05-20 18:01:17] Computed total sum normalization factor as median libsize: 32562.500000
INFO [2019-05-20 18:01:18] Adding h-spike
INFO [2019-05-20 18:01:18] -hspike modeling of macrophage

Could you help me with this issue? Thx!

**Comment by GeorgescuC** [comment]
Hi @ChelseaCHENX ,

Does your "macrophage" set of references only include 1 cell? You can run `lengths(infercnv_obj@reference_grouped_cell_indices)` to see the number of cells per group as they were read by infercnv.

If not, could you provide me with a bit more information about the size and type of data you have as input? Running `run()` with the `resume_mode=FALSE` option will also prevent previous results from being loaded back from file in case the issue was due to the first run.

Regards,
Christophe.

**Comment by ChelseaCHENX** [comment]
Hi Christophe!

I had 50 cells labeled as "macrophages" but I do have some labeling that only has one cell. I now changed all other cells labeled as unknown and it worked out. Thanks!

**Comment by pbrazda** [comment]
Hi, I have a similar problem:
I run
```
infercnv_obj = CreateInfercnvObject(raw_counts_matrix = data_to_write_out,
                                       annotations_file = annotation.file,
                                       delim="\t",
                                       gene_order_file="hg19_gen_pos.txt",
                                       ref_group_names = c("6"))
```
for 
```
lengths(infercnv_obj@reference_grouped_cell_indices)

```
I have 
 6 
34 

but for 
```
infercnv_run = infercnv::run(infercnv_obj,
                             cutoff=0.1,
                             out_dir="CNV_noplot", 
                             cluster_by_groups=F,
                             window_length=101 , 
                             plot_steps=F,
                             denoise=F, 
                             no_prelim_plot=T,
                             k_obs_groups = 2,
                             HMM=T) 
```
I get the error nessage:
	STEP 03: normalization by sequencing depth

INFO [2020-04-27 12:22:14] normalizing counts matrix by depth
INFO [2020-04-27 12:22:14] Computed total sum normalization factor as median libsize: 2024.000000
INFO [2020-04-27 12:22:14] Adding h-spike
INFO [2020-04-27 12:22:14] -hspike modeling of 6
Error in base::rowMeans(x, na.rm = na.rm, dims = dims, ...) : 
  'x' must be an array of at least two dimensions

Could you help me with this? 
Thank you!
