### ISSUE TITLE
Error in parameterize_random_cluster_heights_smoothed_trees

### ISSUE THREAD

**Issue by koetjen** [broadinstitute/infercnv#152]
Hello,
I'm consistently running into an error in step 5 when using analysis_mode='subclusters' : 

 infercnv_obj <- CreateInfercnvObject(raw_counts_matrix= MDScounts,
                                     annotations_file="./MDS_infercnv_data/MDS4annotate.txt",
                                     delim="\t",
                                     gene_order_file="GRCh38_93_gtf.txt",
                                     ref_group_names=c("normal"))
 infercnv_obj = infercnv::run(infercnv_obj,
                              cutoff=0.05,
                              out_dir="inferCNVMDS4",
                              cluster_by_groups=FALSE,
                              denoise=TRUE,
                              HMM=TRUE,
                              analysis_mode='subclusters')
....
STEP 05:
....
INFO [2019-05-29 19:50:01] -processing all_observations,all_observations.1.1.1.1
INFO [2019-05-29 19:50:01] -processing all_observations,all_observations.1.1.1.2
INFO [2019-05-29 19:50:01] -processing all_observations,all_observations.1.1.2.1
INFO [2019-05-29 19:50:01] -processing all_observations,all_observations.1.1.2.2
INFO [2019-05-29 19:50:01] -processing all_observations,all_observations.1.2.1.1
INFO [2019-05-29 19:50:01] -processing all_observations,all_observations.1.2.1.2
INFO [2019-05-29 19:50:01] -processing all_observations,all_observations.1.2.2.1
INFO [2019-05-29 19:50:01] -processing all_observations,all_observations.1.2.2.2
INFO [2019-05-29 19:50:01] define_signif_tumor_subclusters(), tumor: all_references
unique tumor clade name: all_references.1
INFO [2019-05-29 20:08:01] random trees, using 4 parallel threads
Error in .parameterize_random_cluster_heights_smoothed_trees(tumor_expr_data,  :
  (list) object cannot be coerced to type 'double'
Calls: <Anonymous> ... .parameterize_random_cluster_heights_smoothed_trees
In addition: Warning message:
In mclapply(argsList, FUN, mc.preschedule = preschedule, mc.set.seed = set.seed,  :
  scheduled core 3 did not deliver a result, all values of the job will be affected
Execution halted

I'm using docker image singlecellportal/infercnv:0.99.7_e80ae2b-rc2

**Comment by brianjohnhaas** [comment]
Hi

Sorry about this.  Can you privately share with us to the infercnv obj file
that was written to disk at step 4?  We could debug it from there.

Thx

-via googleFi

**Comment by koetjen** [comment]
Seems to be a problem with reaching memory limits. Has now successfully completed with increased memory allocation.
