### ISSUE TITLE
Error in if (runif(1) <= padj)

### ISSUE THREAD

**Issue by s2hui** [broadinstitute/infercnv#157]
Hello,

I am receiving the following error when running infercnv as follows with HMM_type="i6" and wasn't sure what the problem was.  I would greatly appreciate any insight.   Note: I ran the following (same infercnv_obj) with HMM_type="i3" and did not encounter any errors.

infercnv_obj = CreateInfercnvObject(
  raw_counts_matrix = counts_matrix,
  annotations_file="celltype.annotations.txt",
  delim="\t",
  gene_order_file="gencode_v21_genes.complete.txt",
  ref_group_names=NULL)

INFO [2019-06-22 17:07:23] Parsing gene order file: gencode_v21_genes.complete.txt
INFO [2019-06-22 17:07:23] Parsing cell annotations file: celltype.annotations.txt
INFO [2019-06-22 17:07:24] ::order_reduce:Start.
INFO [2019-06-22 17:07:24] .order_reduce(): expr and order match.
INFO [2019-06-22 17:07:25] ::process_data:order_reduce:Reduction from positional data, new dimensions (r,c) = 26890,4472 Total=107325675 Min=0 Max=5580.
INFO [2019-06-22 17:07:25] num genes removed taking into account provided gene ordering list: 1601 = 5.95388620304946% removed.
INFO [2019-06-22 17:07:25] validating infercnv_obj

infercnv_obj = infercnv::run(infercnv_obj,
                             cutoff=0.1,  # use 1 for smart-seq, 0.1 for 10x-genomics
                             out_dir=paste0(ROOTDIR,"analysis/cnv/out/",NAME),  # dir is auto-created for storing outputs
                             cluster_by_groups=T, # cluster
                             denoise=T,
                             HMM=T,HMM_type="i6",resume_mode=FALSE)

INFO [2019-06-22 22:07:21] ::process_data:Start
INFO [2019-06-22 22:07:21] 

	STEP 1: incoming data

INFO [2019-06-22 22:07:35] 

	STEP 02: Removing lowly expressed genes

INFO [2019-06-22 22:07:35] ::above_min_mean_expr_cutoff:Start
INFO [2019-06-22 22:07:37] no genes removed due to min cells/gene filter
INFO [2019-06-22 22:07:51] 

	STEP 03: normalization by sequencing depth

INFO [2019-06-22 22:07:51] normalizing counts matrix by depth
INFO [2019-06-22 22:07:52] Computed total sum normalization factor as median libsize: 11794.172605
INFO [2019-06-22 22:07:52] Adding h-spike
INFO [2019-06-22 22:07:52] -no normals defined, using all observation cells as proxy
INFO [2019-06-22 22:07:52] -hspike modeling of normalsToUse
(Error in nls(y ~ .logistic_midpt_slope(x, midpt = x0, slope = k), data = df, : number of iterations exceeded maximum of 50
), couldn't fit logistic, but no worries, going to use a spline
(Error in nls(y ~ .logistic_midpt_slope(x, midpt = x0, slope = k), data = df, : number of iterations exceeded maximum of 50
), couldn't fit logistic, but no worries, going to use a spline
Error in if (runif(1) <= padj) { : missing value where TRUE/FALSE needed

Thank you again for your help,
shui

> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.5

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] en_CA.UTF-8/en_CA.UTF-8/en_CA.UTF-8/C/en_CA.UTF-8/en_CA.UTF-8

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] infercnv_1.0.2              ggplot2_3.2.0               future_1.13.0              
 [4] dplyr_0.8.1                 Seurat_3.0.2                SingleCellExperiment_1.6.0 
 [7] SummarizedExperiment_1.14.0 DelayedArray_0.10.0         BiocParallel_1.18.0        
[10] matrixStats_0.54.0          Biobase_2.44.0              GenomicRanges_1.36.0       
[13] GenomeInfoDb_1.20.0         IRanges_2.18.1              S4Vectors_0.22.0           
[16] BiocGenerics_0.30.0

**Comment by GeorgescuC** [comment]
Hi @s2hui ,

I am not sure why the issue happens from your log. Could you run the following line `options(error = function() traceback(2))`before trying to run infercnv again adding the `debug=TRUE` option to `run()`? The additional logging will hopefully point to why the problem is happening.

Regards,
Christophe.

**Comment by s2hui** [comment]
Well, I cleared my R environment and it seemed to work after that.  If it happens again I will be sure to turn on the traceback as you suggested.
Thanks for your quick reply. 
shui

**Comment by anavia93** [comment]
Hi, I am running into this problem when running the sub-clustering function. I have tried clearing the environment, but it hasn't corrected the problem for me. I've re run the code with debug=TRUE and traceback on and got the following output:

```
INFO [2020-05-07 16:03:17] -hspike modeling of reference_Cells
(Error in nls(y ~ .logistic_midpt_slope(x, midpt = x0, slope = k), data = df, : singular gradient
), couldn't fit logistic, but no worries, going to use a spline
...
DEBUG [2020-05-07 15:52:36] mean.val: 1, dropout_prob: 0, adj_dropout_prob: 0
DEBUG [2020-05-07 15:52:36] mean.val: 1, dropout_prob: 0, adj_dropout_prob: 0
DEBUG [2020-05-07 15:52:36] mean.val: 1, dropout_prob: 0, adj_dropout_prob: 0
DEBUG [2020-05-07 15:52:36] mean.val: 1, dropout_prob: 0, adj_dropout_prob: 0
DEBUG [2020-05-07 15:52:36] mean.val: 1, dropout_prob: 0, adj_dropout_prob: 0
DEBUG [2020-05-07 15:52:36] mean.val: 0, dropout_prob: NaN, adj_dropout_prob: NaN
Error in if (runif(1) <= padj) { : missing value where TRUE/FALSE needed
11: (function () 
    traceback(2))()
10: FUN(X[[i]], ...)
9: lapply(X = X, FUN = FUN, ...)
8: sapply(x, function(y) {
       if (runif(1) <= padj) {
           return(0)
       }
       else {
           return(y)
       }
   })
7: FUN(newX[, i], ...)
6: apply(counts.matrix, 1, function(x) {
       mean.val = mean(x)
       dropout_prob <- predict(dropout_logistic_params$spline, log(mean.val))$y[1]
       nzeros = sum(x == 0)
       ntotal = length(x)
       nremaining = ntotal - nzeros
       padj = ((dropout_prob * ntotal) - (nzeros))/nremaining
       padj = max(padj, 0)
       flog.debug(sprintf("mean.val: %g, dropout_prob: %g, adj_dropout_prob: %g", 
           mean.val, dropout_prob, padj))
       x.adj = sapply(x, function(y) {
           if (runif(1) <= padj) {
               return(0)
           }
           else {
               return(y)
           }
       })
       x.adj
   })
5: .apply_dropout(sim_cell_matrix, dropout_logistic_params)
4: .get_simulated_cell_matrix_using_meanvar_trend_helper(gene_means, 
       mean_var_table, num_cells, dropout_logistic_params)
3: .get_simulated_cell_matrix_using_meanvar_trend(infercnv_obj, 
       hspike_gene_means, num_cells, include.dropout = TRUE)
2: .build_and_add_hspike(infercnv_obj, sim_method = sim_method, 
       aggregate_normals = hspike_aggregate_normals)
1: infercnv::run(infercnv_obj, analysis_mode = "subclusters", hclust_method = "ward.D2", 
       cutoff = 0.1, out_dir = "output_dir_Biliary_subcluster_2", 
       cluster_by_groups = TRUE, denoise = TRUE, tumor_subcluster_partition_method = "random_trees", 
       sd_amplifier = 4, noise_logistic = TRUE, HMM = TRUE, BayesMaxPNormal = 0.3, 
       debug = TRUE)
```

Any input on why I get these NaN values would be appreciated. If you need more context I would be happy to provide it over email. 
Thanks,
Andrew Navia

Graduate Student
Shalek Lab, MIT
