### ISSUE TITLE
Incorrect software dependencies in documentation

### ISSUE THREAD

**Issue by gcday** [broadinstitute/infercnv#159]
Hi,
The project wiki should be updated to reflect that infercnv no longer works with R 3.5.1, and in fact requires R >= 3.6.0.  
https://github.com/broadinstitute/inferCNV/wiki#software-requirements

**Comment by GeorgescuC** [comment]
Hi @gcday ,

Thanks for pointing it out, it is now updated on the wiki.

Note however that if you are limited to R 3.5 for the time being, inferCNV should still work on 3.5 too (although there may come a time when support will break). We upgraded the requirements to 3.6 for the BioConductor release but the package was developed under 3.5 until then. (See last point in https://github.com/broadinstitute/infercnv/issues/139#issuecomment-481398050 for instructions)

Regards,
Christophe.
