### ISSUE TITLE
Error at STEP 13: Run Bayesian Network Model on HMM predicted CNV's

### ISSUE THREAD

**Issue by reshu23** [broadinstitute/infercnv#162]
Hi,
I am running inferCNV by using following parameters:
infercnv_obj = infercnv::run(infercnv_obj,
                             cutoff=0.1, 
                             out_dir=out_dir,
                             cluster_by_groups=TRUE, 
                             denoise=TRUE,
                             HMM=TRUE)

I am getting following error, step 13:

INFO [2019-07-23 11:20:51] Initializing new MCM InferCNV Object.
INFO [2019-07-23 11:20:51] validating infercnv_obj
INFO [2019-07-23 11:20:51] Total CNV's:  1
INFO [2019-07-23 11:20:51] Loading BUGS Model.
INFO [2019-07-23 11:20:51] Running Sampling Using Parallel with  4 Cores
INFO [2019-07-23 11:32:23] Obtaining probabilities post-sampling
INFO [2019-07-23 11:32:52] Gibbs sampling time:  12.0133601228396  Minutes
INFO [2019-07-23 11:33:42] ::plot_cnv:Start
INFO [2019-07-23 11:33:42] ::plot_cnv:Current data dimensions (r,c)=6212,11432 Total=217075.267447994 Min=0 Max=0.789835638155094.
INFO [2019-07-23 11:33:42] ::plot_cnv:Depending on the size of the matrix this may take a moment.
INFO [2019-07-23 11:33:44] plot_cnv_observation:Start
INFO [2019-07-23 11:33:44] Observation data size: Cells= 7428 Genes= 6212
INFO [2019-07-23 11:33:44] clustering observations via method: ward.D
INFO [2019-07-23 11:33:45] plot_cnv_observation:Writing observation groupings/color.
INFO [2019-07-23 12:27:10] Colors for breaks:  #00008B,#24249B,#4848AB,#6D6DBC,#9191CC,#B6B6DD,#DADAEE,#FFFFFF,#EEDADA,#DDB6B6,#CC9191,#BC6D6D,#AB4848,#9B2424,#8B0000
INFO [2019-07-23 12:27:10] Quantiles of plotted data range: 0,0,0,0,0.789835638155094
INFO [2019-07-23 12:27:15] plot_cnv_references:Writing observation data to out_dir/BayesNetOutput.HMMi6.hmm_mode-samples/infercnv.NormalProbabilities.observations.txt
INFO [2019-07-23 12:27:43] plot_cnv_references:Start
INFO [2019-07-23 12:27:43] Reference data size: Cells= 4004 Genes= 6212
INFO [2019-07-23 12:40:04] plot_cnv_references:Number reference groups= 1
INFO [2019-07-23 12:40:05] plot_cnv_references:Plotting heatmap.
INFO [2019-07-23 12:40:19] Colors for breaks:  #00008B,#24249B,#4848AB,#6D6DBC,#9191CC,#B6B6DD,#DADAEE,#FFFFFF,#EEDADA,#DDB6B6,#CC9191,#BC6D6D,#AB4848,#9B2424,#8B0000
INFO [2019-07-23 12:40:19] Quantiles of plotted data range: 0,0,0,0,0
INFO [2019-07-23 12:40:20] plot_cnv_references:Writing reference data to out_dir/BayesNetOutput.HMMi6.hmm_mode-samples/infercnv.NormalProbabilities.references.txt
INFO [2019-07-23 12:41:25] Attempting to removing CNV(s) with a probability of being normal above  0.5
INFO [2019-07-23 12:41:25] Removing  1  CNV(s) identified by the HMM.
Error in obj@cell_gene[[i]] : subscript out of bounds

**Comment by brownmp** [comment]
Hello @reshu23 

Sorry to hear you having troubles. Would you be able to share the data set you are working with so that I may attempt to see why this problem is occurring. In particular would you be able to send me the infercnv object "preliminary.infercnv_obj". All information shared would be kept private. My email is mbrown@broadinstitute.org.

-Maxwell

**Comment by ashrosewood** [comment]
Having the exact same issue after `Removing 1 CNV(s) identified by the HMM.`

**Comment by reshu23** [comment]
OK. I will send you. Thank you. But I think, problem is with HMM_type='i6'
When I use HMM_type='i3', It did not create any problem. I got results.

**Comment by brownmp** [comment]
Thank you so much for bringing this to my attention. 
The lasted updates to the Devel branch should have resolved these issues. Please let me know if you encounter any issues!

Best,
@brownmp
