### ISSUE TITLE
How to get a matrix of data corresponding the final heatmap?

### ISSUE THREAD

**Issue by aleshchyk** [broadinstitute/infercnv#165]
Hello,

I was wondering how to extract the ids of cells corresponding to the rows on the final heatmap. 
This is related to the closed issue https://github.com/broadinstitute/infercnv/issues/158.

Thank you.
Ana

**Comment by GeorgescuC** [comment]
Hi @aleshchyk ,

For each heatmap, as set of text files are also generated from which you can get the cell ids. The ".observations_dendrogram.txt" file contains the newick strings for the dendrogram(s) on the left side of the plot (bottom to top), and ".observations_groupings.txt" that contains the ids and matching color from the annotations, also in bottom to top order.

If you want a more interactive way of exploring the heatmap and selecting cells, you can also give a try to the NGCHM export https://github.com/broadinstitute/infercnv/wiki/Next-Generation-Clustered-Heat-Map .

Regards,
Christophe.
