### ISSUE TITLE
Error in infercnv_obj@expr.data[, infercnv_obj@tumor_subclusters$subclusters[[obs_annotations_names[i]]],  : invalid subscript type 'list'

### ISSUE THREAD

**Issue by gsmithro** [broadinstitute/infercnv#167]
Hi, I am running into this error when running inferCNV (Version: 1.1.0) on my single cell RNA-seq data. It looks like an issue with plotting the heat map:

```
Error in infercnv_obj@expr.data[, infercnv_obj@tumor_subclusters$subclusters[[obs_annotations_names[i]]],  : 
  invalid subscript type 'list'
```

Here is the head of my annotation data:
`
non-malignant_HTAPP-244-SMP-451_EZ_channel1-ACAGCTATCATTGCCC	Endothelial cell
non-malignant_HTAPP-244-SMP-451_EZ_channel1-AGCGTATCAACTGGCC	Endothelial cell
non-malignant_HTAPP-244-SMP-451_NST_channel1-TGTTCCGGTTCTGAAC	Endothelial cell
non-malignant_HTAPP-244-SMP-451_CST_channel1-GCAGTTAAGAGTGAGA	Endothelial cell
non-malignant_HTAPP-244-SMP-451_TST_channel1-AGCTCCTTCAACGGGA	Endothelial cell
`
And here is the input I use for the script:

`
for (i in seq(sampleid.scCloud)){
  
  if (length(list.files(figures.path[i])) > 1){
    ann.use <- read.csv(paste0(file.annotation[i]), sep = "\t")
    
    ref.use <- c("B cell", "NK cell", "T cell", "Macrophage", "Mast cell", "Endothelial cell", "Fibroblast", "Erythrocyte")[which(c("B cell", "NK cell", "T cell", "Macrophage", "Mast cell", "Endothelial cell", "Fibroblast", "Erythrocyte") %in% unique(ann.use[,2]))]
    
    infercnv_obj = CreateInfercnvObject(
      raw_counts_matrix = file.counts[i],
      annotations_file = file.annotation[i],
      delim="\t",
      gene_order_file = file.genomic.position,
      ref_group_names = ref.use)
    
    out_dir <- figures.path[i]
    # Perform infercnv operations to reveal cnv signal.
    infercnv_obj = infercnv::run(infercnv_obj,
                                 cutoff=0.1, 
                                 out_dir=out_dir, 
                                 cluster_by_groups=T, 
                                 plot_steps=F,
                                 denoise=T,
                                 resume_mode = T,
                                 HMM=T,
                                 HMM_type = "i6",
                                 num_threads = 8
    )
  }
}
`

I know the reference and the observations are both non-empty, but I do not know what could be causing this error. Is this an issue with my version of InferCNV?

**Comment by GeorgescuC** [comment]
Fixed in 183378aed2b43b44fc34608fb13ee427a629b669
