### ISSUE TITLE
Extracting features: "map_metadata_from_infercnv.txt", output file missing in version 1.1.2

### ISSUE THREAD

**Issue by zezhuo** [broadinstitute/infercnv#169]
Hi infercnv team, I have noted you recent update for adding extracting featrures. It is amazing. But when I run the infercnv version 1.1.2, I did not get a output file named "map_metadata_from_infercnv.txt". 

R script is as follow: 
```
library(infercnv)

L31.c7_cnv = CreateInfercnvObject(raw_counts_matrix="L31.c7_counts.matrix",
                                 annotations_file="L31.c7_anno.txt",
                                 delim="\t",
                                 gene_order_file="/home/zezhuo/R/infercnv/gencode_v19_gene_pos.txt",
                                 ref_group_names= c("6")) 



L31.c7_cnv = infercnv::run(L31.c7_cnv,
                          cutoff=0.1, 
                          out_dir="L31.c7_infercnv", 
                          cluster_by_groups=TRUE, 
                          denoise=TRUE,
                          HMM=TRUE,
                          num_threads = 12)
```

infercnv output files are as follow:
01_incoming_data.infercnv_obj
02_reduced_by_cutoff.infercnv_obj
03_normalized_by_depthHMMi6.infercnv_obj
04_logtransformedHMMi6.infercnv_obj
08_remove_ref_avg_from_obs_logFCHMMi6.infercnv_obj
09_apply_max_centered_expr_thresholdHMMi6.infercnv_obj
10_smoothed_by_chrHMMi6.infercnv_obj
11_recentered_cells_by_chrHMMi6.infercnv_obj
12_remove_ref_avg_from_obs_adjustHMMi6.infercnv_obj
14_invert_log_transformHMMi6.infercnv_obj
15_no_subclusteringHMMi6.infercnv_obj
17_HMM_predHMMi6.hmm_mode-samples.infercnv_obj
17_HMM_preds.cell_groupings
17_HMM_preds.genes_used.dat
17_HMM_preds.pred_cnv_genes.dat
17_HMM_preds.pred_cnv_regions.dat
18_HMM_pred.Bayes_NetHMMi6.hmm_mode-samples.mcmc_obj
18_HMM_pred.Bayes_NetHMMi6.hmm_mode-samples.Pnorm_0.5.infercnv_obj
19_HMM_pred.repr_intensitiesHMMi6.hmm_mode-samples.Pnorm_0.5.infercnv_obj
21_denoiseHMMi6.NF_NA.SD_1.5.NL_FALSE.infercnv_obj
BayesNetOutput.HMMi6.hmm_mode-samples
expr.infercnv.17_HMM_predHMMi6.hmm_mode-samples.dat
expr.infercnv.18_HMM_pred.Bayes_Net.Pnorm_0.5.dat
expr.infercnv.19_HMM_predHMMi6.hmm_mode-samples.Pnorm_0.5.repr_intensities.dat
expr.infercnv.21_denoised.dat
expr.infercnv.dat
expr.infercnv.preliminary.dat
HMM_CNV_predictions.HMMi6.hmm_mode-samples.Pnorm_0.5.cell_groupings
HMM_CNV_predictions.HMMi6.hmm_mode-samples.Pnorm_0.5.genes_used.dat
HMM_CNV_predictions.HMMi6.hmm_mode-samples.Pnorm_0.5.pred_cnv_genes.dat
HMM_CNV_predictions.HMMi6.hmm_mode-samples.Pnorm_0.5.pred_cnv_regions.dat
infercnv.17_HMM_predHMMi6.hmm_mode-samples.heatmap_thresholds.txt
infercnv.17_HMM_predHMMi6.hmm_mode-samples.observation_groupings.txt
infercnv.17_HMM_predHMMi6.hmm_mode-samples.observations_dendrogram.txt
infercnv.17_HMM_predHMMi6.hmm_mode-samples.observations.txt
infercnv.17_HMM_predHMMi6.hmm_mode-samples.png
infercnv.17_HMM_predHMMi6.hmm_mode-samples.references.txt
infercnv.18_HMM_pred.Bayes_Net.Pnorm_0.5.heatmap_thresholds.txt
infercnv.18_HMM_pred.Bayes_Net.Pnorm_0.5.observation_groupings.txt
infercnv.18_HMM_pred.Bayes_Net.Pnorm_0.5.observations_dendrogram.txt
infercnv.18_HMM_pred.Bayes_Net.Pnorm_0.5.observations.txt
infercnv.18_HMM_pred.Bayes_Net.Pnorm_0.5.png
infercnv.18_HMM_pred.Bayes_Net.Pnorm_0.5.references.txt
infercnv.19_HMM_predHMMi6.hmm_mode-samples.Pnorm_0.5.repr_intensities.heatmap_thresholds.txt
infercnv.19_HMM_predHMMi6.hmm_mode-samples.Pnorm_0.5.repr_intensities.observation_groupings.txt
infercnv.19_HMM_predHMMi6.hmm_mode-samples.Pnorm_0.5.repr_intensities.observations_dendrogram.txt
infercnv.19_HMM_predHMMi6.hmm_mode-samples.Pnorm_0.5.repr_intensities.observations.txt
infercnv.19_HMM_predHMMi6.hmm_mode-samples.Pnorm_0.5.repr_intensities.png
infercnv.19_HMM_predHMMi6.hmm_mode-samples.Pnorm_0.5.repr_intensities.references.txt
infercnv.21_denoised.heatmap_thresholds.txt
infercnv.21_denoised.observation_groupings.txt
infercnv.21_denoised.observations_dendrogram.txt
infercnv.21_denoised.observations.txt
infercnv.21_denoised.png
infercnv.21_denoised.references.txt
infercnv.heatmap_thresholds.txt
infercnv.observation_groupings.txt
infercnv.observations_dendrogram.txt
infercnv.observations.txt
infercnv.png
infercnv.preliminary.heatmap_thresholds.txt
infercnv.preliminary.observation_groupings.txt
infercnv.preliminary.observations_dendrogram.txt
infercnv.preliminary.observations.txt
infercnv.preliminary.png
infercnv.preliminary.references.txt
infercnv.references.txt
preliminary.infercnv_obj
run.final.infercnv_obj

**Comment by GeorgescuC** [comment]
Hi @zezhuo ,

The feature extraction is run through an additional command, in order to allow you to provide a Seurat object with matching data if you have one.

The full documentation is [available on the wiki](https://github.com/broadinstitute/infercnv/wiki/Extracting-features), but in your case, running from the same location, the command you need to run after the infercnv run completion should be:
`infercnv::add_to_seurat(infercnv_output_path="L31.c7_infercnv",
                                     top_n=10)`

You may also want to update infercnv to the latest commit on the master branch as I just added an additional option `bp_tolerance` to the add_to_seurat method to help with top CNVs being identified as different if their start/end positions changes slightly in different subclusters.

Regards,
Christophe.

**Comment by zezhuo** [comment]
Hi Christophe,

Thanks for your quick reply!  infercnv::add_to_seurat works well.

Regards,
Nelson

**Comment by zezhuo** [comment]
Hi @GeorgescuC ,

Following this issue, I get another problem that all the values in "map_metadata_from_infercnv.txt" are "0". 

`> infercnv::add_to_seurat(infercnv_output_path="D:/Nelson/R/L31.c7_infercnv/L31.c7_infercnv/",top_n=10)
INFO [2019-08-17 12:36:40] No Seurat object provided, will only write metadata matrix.
NULL
> 
> L31v3_cnv_mdata <- read.delim("D:/Nelson/R/L31.c7_infercnv/L31.c7_infercnv/map_metadata_from_infercnv.txt", header = T, row.names = 1)
> 
> which(L31v3_cnv_mdata>0)
integer(0)`

By the way, I am working with 10x data. 

Regards,
Nelson

**Comment by zezhuo** [comment]
Hi @GeorgescuC ,

For the default pb_tolerance = 2000000 :

```
> library(infercnv) 
> infercnv::add_to_seurat(infercnv_output_path="D:/Nelson/R/L31.c7_infercnv/L31.c7_infercnv/", 
+                         bp_tolerance = 2000000, 
+                         top_n=10) 
INFO [2019-08-17 13:32:15] No Seurat object provided, will only write metadata matrix. NULL 
> L31v3_cnv_mdata <- read.delim("D:/Nelson/R/L31.c7_infercnv/L31.c7_infercnv/map_metadata_from_infercnv.txt", header = T, row.names = 1) 
> which(L31v3_cnv_mdata>0) 
> integer(0)
```

Look forward to your suggestion.

Regards,
Nelson

**Comment by GeorgescuC** [comment]
Hi @zezhuo ,

When you open `infercnv.18_HMM_pred.Bayes_Net.Pnorm_0.5.png`, does it look like there is any CNV predicted?

Regards,
Christophe.

**Comment by zezhuo** [comment]
Hi @GeorgescuC ,

Yes. Attached png for your reference.

![infercnv 18_HMM_pred Bayes_Net Pnorm_0 5](https://user-images.githubusercontent.com/48099632/63932863-a7249180-ca8a-11e9-8340-2c7e232fc0ac.png)

Regards,
Nelson

**Comment by GeorgescuC** [comment]
Hi @zezhuo ,

Do the `HMM_CNV_predictions.HMMi6.rand_trees.hmm_mode-subclusters.Pnorm_0.5.pred_cnv_regions.dat` and `HMM_CNV_predictions.HMMi6.rand_trees.hmm_mode-subclusters.Pnorm_0.5.pred_cnv_genes.dat` files contain tables that appear to match the figure?

If they, do could you share `run.final.infercnv_obj` as well as those 2 files privately with me so I can debug the issue?

Regards,
Christophe.

**Comment by zezhuo** [comment]
Hi Christophe,

May I have email adress? The files are too big to be uploaded.

Best,
Nelson

**Comment by zezhuo** [comment]
> 
> 
> Hi @zezhuo ,
> 
> Do the `HMM_CNV_predictions.HMMi6.rand_trees.hmm_mode-subclusters.Pnorm_0.5.pred_cnv_regions.dat` and `HMM_CNV_predictions.HMMi6.rand_trees.hmm_mode-subclusters.Pnorm_0.5.pred_cnv_genes.dat` files contain tables that appear to match the figure?
> 
> If they, do could you share `run.final.infercnv_obj` as well as those 2 files privately with me so I can debug the issue?
> 
> Regards,
> Christophe.

Available on google drive now. Thanks!

Nelson
https://drive.google.com/file/d/1HR-nVgNRCPoxKemO4loJTsS-NsGpFrfT/view?usp=sharing

**Comment by zezhuo** [comment]
Hi @GeorgescuC , 

Thanks for your update. I have ever tried analysis_mode = "subclusters". It did separate sub populaitons in each observation groups. 

Regards, 
Nelson
