### ISSUE TITLE
Question re: data integration

### ISSUE THREAD

**Issue by s2hui** [broadinstitute/infercnv#170]
I have two data sets that have I preprocessed separately.  One of the data sets is the normal (reference) cells and the other are the tumour (observation) cells.

In this case, would I have to integrate the two data sets into one matrix and preprocess it all together before putting it through inferCNV?

thanks for your help,
shui

**Comment by GeorgescuC** [comment]
Hi @s2hui ,

This depends on the preprocessing you are doing. If it is independent for each cell, then you should be fine combining the preprocessed matrices you already have. However if your preprocessing involves whole data set metrics/criteria, it would be best to preprocess everything together.

To note is also that the infercnv processing assumes that all the input data has the same characteristics, and so presumably came from the same library or run. If the data comes from different experiments (different libraries, sequencing efforts, etc.), then infercnv may not work properly.

Regards,
Christophe.

**Comment by s2hui** [comment]
Hi @GeorgescuC 
Thanks for your reply.  What I did was I split my original matrix into immune and nonimmune cell populations and preprocessed them separately (for another analysis) - so they are actually from the same experiment.  I have used Seurat's standard log normalization so the normalization should be independent for each cell.  I'll try merging the two without preprocessing and see what happens.
Thanks again,
shui

**Comment by GeorgescuC** [comment]
Hi @s2hui ,

infercnv expects non log transformed data, i.e. raw read counts.

If you have a Seurat object with a 2D representation (tSNE/UMAP), you may also want to take a look at a new feature once your run is complete: https://github.com/broadinstitute/infercnv/wiki/Extracting-features

Regards,
Christophe.

**Comment by s2hui** [comment]
Hi @GeorgescuC 
Yes thanks for the clarifcation/reminder.  I will look at this new features.
shui

**Comment by s2hui** [comment]
Hi @GeorgescuC

I have merged my two data sets via merge() function in Seurat as:

so =merge(so.immune, y = so.nonimmune, project = "test", add.cell.ids = c("Immune","Nonimmune"))

Then I get the count_matrix as:

counts_matrix = as.matrix(so[["RNA"]]@counts)

> dim(counts_matrix)
[1] 45111 35753

I run the following:

# Create inferCNV object
infercnv_obj = CreateInfercnvObject(
  raw_counts_matrix = counts_matrix,
  annotations_file="cellanno.txt",
  delim="\t",
  gene_order_file="gencode_v21_genes.complete.txt",
  ref_group_names=unique(normalClusters))

INFO [2019-08-19 13:10:40] Parsing gene order file: ./input/CNV/gencode_v21_genes.complete.txt
INFO [2019-08-19 13:10:41] Parsing cell annotations file: ./input/CNV/celltype.annotations-integrated.txt
INFO [2019-08-19 13:10:51] ::order_reduce:Start.
INFO [2019-08-19 13:11:05] .order_reduce(): expr and order match.
INFO [2019-08-19 13:11:23] ::process_data:order_reduce:Reduction from positional data, new dimensions (r,c) = 45111,35753 Total=226512083 Min=0 Max=23549.
INFO [2019-08-19 13:11:33] num genes removed taking into account provided gene ordering list: 13016 = 28.8532730376183% removed.
INFO [2019-08-19 13:11:33] validating infercnv_obj

# Run inferCNV
infercnv_obj = infercnv::run(infercnv_obj,
                             cutoff=0.1,  # use 1 for smart-seq, 0.1 for 10x-genomics
                             out_dir=outDir  # dir is auto-created for storing outputs
                             cluster_by_groups=T, # cluster
                             denoise=T,
                             HMM=T,HMM_type="i6",resume_mode=FALSE)

INFO [2019-08-19 13:11:52] ::process_data:Start
INFO [2019-08-19 13:11:52] 

	STEP 1: incoming data

INFO [2019-08-19 13:14:53] 

	STEP 02: Removing lowly expressed genes

INFO [2019-08-19 13:14:53] ::above_min_mean_expr_cutoff:Start
INFO [2019-08-19 13:14:55] Removing 23617 genes from matrix as below mean expr threshold: 0.1
INFO [2019-08-19 13:15:00] validating infercnv_obj
INFO [2019-08-19 13:15:00] There are 8478 genes and 35753 cells remaining in the expr matrix.
INFO [2019-08-19 13:15:19] no genes removed due to min cells/gene filter
INFO [2019-08-19 13:16:26] 

	STEP 03: normalization by sequencing depth

INFO [2019-08-19 13:16:26] normalizing counts matrix by depth
INFO [2019-08-19 13:16:34] Computed total sum normalization factor as median libsize: 1993.000000
INFO [2019-08-19 13:16:36] Adding h-spike
INFO [2019-08-19 13:16:36] -hspike modeling of 11
(Error in numericDeriv(form[[3L]], names(ind), env): Missing value or an infinity produced when evaluating the model
), couldn't fit logistic, but no worries, going to use a spline
Error in smooth.spline(x, mean_p0_table$p0) : 
  missing or infinite values in inputs are not allowed

Questions:
1) Do you know why I am getting the missing or infinite values error? 
2) I am wondering if 35,753 cells is too many cells (i.e. it take too long to run)?  If so what do you recommend in such a situation?

Thanks alot for your help,
shui

**Comment by GeorgescuC** [comment]
Hi @s2hui ,

1. Could you check that the input matrix does not have any missing/NaN values?
`any(!is.finite(infercnv_obj@expr.data))`
  Also, does the median number of reads per cell found, of 1993, look correct? 

2. 35,753 cells should be good to run, as long as you have enough RAM (I would guess 32GB to be enough for that). A couple steps may take a bit longer to run, but since you are not running the subclustering, the longest one is not executed. If you are limited in memory, you can first convert the matrix to a sparse matrix to save some memory (a script is available in scripts/prepare_sparsematrix.R)

Regards,
Christophe.

**Comment by s2hui** [comment]
Hi @GeorgescuC

1.  There doesn't appear to be any infinites
> any(!is.finite(infercnv_obj@expr.data))
[1] FALSE

Re: "Also, does the median number of reads per cell found, of 1993, look correct?"  
Are you referring to the 10X genomics run statistics (ie from web_summary?)

Thanks for your help,
shui

**Comment by GeorgescuC** [comment]
Hi @s2hui ,

Yes, there should be a "Median UMI Counts per Cell" value in web_summary to compare it to.

Could you also let me know how many cells in each reference annotation group there are? You should have the information by running `lengths(infercnv_obj@reference_grouped_cell_indices)`.

Regards,
Christophe.

**Comment by s2hui** [comment]
Hi @GeorgescuC

I forgot to mention the cell populations are an integration of 3 different experiments (nucseq and scrnaseq) - is this a problem?

I also only have access to 2 of the web summaries unfortunately:
* med. UMI counts per cell is 17, 190
* med. UMI counts per cell is 5,283

Also here is the output from the command:
> lengths(infercnv_obj@reference_grouped_cell_indices)
  11    3    4    2   13    5   14    0    1    8   10    7   12    6    9 
 243 1008  822 1295  111  765  102 1698 1377  358  294  666  211  728  344 

Thanks very much,
shui

**Comment by GeorgescuC** [comment]
Hi @s2hui ,

Data generated with nucseq and scrnaseq should not be merged together for infercnv analysis as there are significant differences between them. The way you merged them, are there cells from each experiment in each cluster, or are clusters a single experiment?

Would you be able to run the nucseq and scrnaseq datasets separately?

Regards,
Christophe.

**Comment by s2hui** [comment]
Hi @GeorgescuC

Thanks for your reply.  I have run inferCNV on the datasets separately and it runs well with no problem.  I used Seurat's integration method to perform the integration to combine the nucseq and two scRNASeq data sets:

https://satijalab.org/seurat/v3.0/integration.html#standard-workflow

Specifically I am using the calls:
* FindIntegrationAnchors()
* IntegrateData()

Based on the tSNE plots, there is overlap between all three data sets but there are also rather large and obvious clusters that are only found in one of the scRNAseq datasets and not the other two (nucseq and scRNASeq).  Infact the nucseq and other scRNAseq have more overlapping cells in the tSNE plots.

Since I have two scRNAseq data sets should I try integrating those two and see if inferCNV runs well as they are both scRNAseq OR is it more important the integrated data sets have well integrated cells (in which case I would integrate the two more "similar" nucseq + scRNAseq data sets).

And in general, are you saying it's not appropriate or possible to run inferCNV on integrated data from nucseq and scRNAseq?  If so would I have to run them separately?  I am just wondering what my options are .

Thanks for your insight again,
shui

**Comment by GeorgescuC** [comment]
Hi @s2hui ,

The issue with using infercnv on data integrated with Seurat is that the integration process first requires preprocessing, and hence both log-normalization and z-score transformation, while infercnv expects raw UMI/read counts as input.
It technically would be possible to run the different internal infercnv steps on the integrated data starting after the normalization and log2 transform steps (steps 3 and 4), but as we have not tested using integrated data ourselves, I cannot give any guarantees on the quality/accuracy of the results.

The recommended way of using infercnv for you data would be to run each dataset separately.

If you do decide to try using infercnv on the integrated data, I would be interested in hearing back about the results.

Regards,
Christophe.
