### ISSUE TITLE
Question  about CNV region

### ISSUE THREAD

**Issue by MMriran** [broadinstitute/infercnv#172]
Hello,
Thank you for your work on this wonderful tool! I  learned from an article  about infercnv package, and I had some question in using this package. 
In that article, the author mentioned “The CNV score of each cell was calculated as quadratic
sum of CNVregion and used cells except ductal cells 1/2 and acinar cells as background to eliminate the individual somatic CNV and re-calculated the CNV level with the same cutoff”
Then，I run the code 
###############################
infercnv_obj = CreateInfercnvObject(raw_counts_matrix="sig.txt",
                                    annotations_file="annotations.txt",
                                    delim="\t",
                                    gene_order_file="gene.txt", 
                                    ref_group_names=ref_group_names=c("Microglia/Macrophage","B","T")) 

infercnv_obj = infercnv::run(infercnv_obj,
                             cutoff=0.1, 
                             out_dir=tempfile(), 
                             cluster_by_groups=TRUE, 
                             denoise=TRUE,
                             HMM_type='i6',
                             HMM=TRUE,
                             noise_filter = 0.2)

##sig.txt is matrix of single cell
## annotations.txt is a description of the cells
##Microglia/Macrophage,B,and T are cell type that except ductal cells 1/2 and acinar cells

after run the code ,I got files"HMM_CNV_predictions.HMMi6.hmm_modesamples.Pnorm_0.5.pred_cnv_regions.dat" and 
 the formatting is like so:
cell_group_name                         cnv_name        state   chr     start   end
#############################################
here are my question:
1 Dose this mean that  Microglia/Macrophage,B,and T are cell type are used as ref_group_names？( “cells except ductal cells 1/2 and acinar cells as background”)
2 Is the “state” in my files is the value for CNV region？  

Can you help me solve my question ?
Thanks a lot.

Best wishes!
Yours sincerely, CHEN

**Comment by GeorgescuC** [comment]
Hi @MMriran ,

1) Based on the code you have sent, the part `ref_group_names=c("Microglia/Macrophage","B","T")` defines the "Microglia/Macrophage", "B" and "T" annotated cells (in the "annotations.txt" file) as references yes.

2) The "state" defines the CNV value based on the HMM predictions after filtering by the Bayesian Network. 0.5 means one copy is lost, 0 means both copies are lost. 1.5 means 1 copy is gained, and 2 means 2 copies are gained.
You can also take a look at both the `infercnv.png` and `infercnv.13_HMM_pred.Bayes_Net.Pnorm_0.5.png` heatmaps that should be part of the outputs and compare the predictions to the signal they are based on.


Regards,
Christophe.

**Comment by MMriran** [comment]
I got it！ Thank you very much！！！

**Comment by rgranit** [comment]
@MMriran can you share how you ended up calculating the CNV_score? what file contains the relevant information (CNVregion)?

**Comment by rgranit** [comment]
As for states, It seems that these would not be a good fit for the CNV score, no? since in that case a deletion (0.5) will contribute less to the score vs amplification (1.5) - or am I missing something?
