### ISSUE TITLE
Increase font size in heaetmaps

### ISSUE THREAD

**Issue by rgranit** [broadinstitute/infercnv#173]
Hello, is there an option to control/increase the font size in the generated heatmaps?

Thanks

**Comment by GeorgescuC** [comment]
Hi @rgranit ,

You can control the font size for the chromosome names on the x axis with `contig_cex` when calling `plot_cnv()`. Besides that, for other labels, you can generate the heatmap as a pdf with `output_format="pdf"` and then edit the sizes/layout in the pdf as it's a vectorial format.

Regards,
Christophe.

**Comment by rgranit** [comment]
Thanks @GeorgescuC got it! it would be nice to allow setting this param to the infercnv::run as well.
