### ISSUE TITLE
Cell based CNV state

### ISSUE THREAD

**Issue by mea2712** [broadinstitute/infercnv#175]
Hi!
I'm using v1.1.2 and am after cell based CNV states. When I look at run.final.infercnv_obj@expr.data, I get a matrix of ~30000 rows (genes) and ~300 columns (cells):
`                              A10               A12                  A13               A14
RP11-34P13.3       0.9183132      0.9829124       1.092044      0.9491200
FAM138A            0.9186002      0.9826138       1.091475      0.9508848
OR4F5              0.9186876      0.9821755       1.091720      0.9538763
RP11-34P13.7       0.9186683      0.9816884       1.091959      0.9579894
RP11-34P13.14      0.9189850      0.9816185       1.092707      0.9622377`
                                
 What I would like to get is a matrix with cnvs as rownames and state assignments in the cells.
Is this possible?
Thank you!

**Comment by GeorgescuC** [comment]
Hi @mea2712 ,

If you run inferCNV with the HMM predictions, there are output tables that contain the predicted CNVs in a format similar to what you are looking for, though as they use clusters IDs, you will need to cross it with the infercnv_obj@tumor_subclusters information to get the cell IDs.
The files to look for end in ".pred_cnv_genes.dat" or ".pred_cnv_regions.dat". For the unfiltered HMM predictions, the file names start with "17_HMM_predHMMi6", and for the Bayesian network-filtered results, they start with "HMM_CNV_predictions.HMMi6".

Regards,
Christophe.
