### ISSUE TITLE
score/p-value

### ISSUE THREAD

**Issue by rgranit** [broadinstitute/infercnv#176]
Hello,

Is there a way to extract a score or a p-value for a predicted CNV?

Thanks!

**Comment by brownmp** [comment]
Hello @rgranit, 

In the output directory there should be a file names `CNV_State_Probabilities.dat`, this file should give you the probabilities of each state for each identified CNV. 

Best,
Maxwell

**Comment by rgranit** [comment]
Thanks @brownmp!
