### ISSUE TITLE
How to manually specify the dendrogram colors used on the resultant CNV heatmap

### ISSUE THREAD

**Issue by ziyangliu93** [broadinstitute/infercnv#178]
Dear all contributors to this fantastic and useful tool. I am a new guy to single cell field. I tried to use infercnv to estimate CNV for my 10X data. I followed the instruction posted on the wiki page to successfully create the necessary object for running infercnv::run() command. My question is that,  when plotting heatmap showing final results, how to manually specify colours for each type of cells. Let's say I have 3 types of cells, called primary, meta1, meta2, respectively and I have create the corresponding annotation file linking cell barcodes to cell identities. It's reasonable to know that the resultant heatmap will have 3 annotation colours, each colour for each cell type. How can I change the mapping between cell identity and cell barcodes since the default colours are indistinguishable from each other.

**Comment by GeorgescuC** [comment]
Hi @ziyangliu93 ,

At this time it is not possible to set the colors for annotations. I will note that improvement in the list of things to add, but a quick way to do it for now would be to download the infercnv code and overwrite the function that returns the colors codes located at R/inferCNV_heatmap.R#8, then install your changes and run the plot_cnv method on your data.

`get_group_color_palette <- function(){
    return(colorRampPalette(RColorBrewer::brewer.pal(12,"Set3")))
}`

Note that the call to that method is in the form `get_group_color_palette()(n_groups)`

Regards,
Christophe.
