### ISSUE TITLE
why I met this?           

### ISSUE THREAD

**Issue by liwendong1998** [broadinstitute/infercnv#179]
> infercnv_obj <- infercnv::CreateInfercnvObject(raw_counts_matrix=readcountx,
+                                     annotations_file=a,
+                                     delim="\t",
+                                     gene_order_file=pos,
+                                     ref_group_names=c("normal")
+                                     )
Error in if (rownames(input_classifications)[1] == "V1") { : 
  argument is of length zero

**Comment by GeorgescuC** [comment]
Hi @liwendong1998 ,

Could you send the first few lines of your annotations_file? It looks like infercnv can't read the format properly.

Regards,
Christophe.

**Comment by liwendong1998** [comment]
I modified my annotations_file,but met another error
Error in infercnv::CreateInfercnvObject(raw_counts_matrix = readcountx,  : 
  Error, not identifying cells with classification normal

this is part of my annotation_file
` a[1:4,]
   [,1] [,2]    
v1 "v1" "normal"
v2 "v2" "normal"
v3 "v3" "normal"
v4 "v4" "normal"`

**Comment by joycekang** [comment]
Hi there! I seem to be running into the same issue. The first few lines of my annotations file is: 

![Image](https://github.com/user-attachments/assets/d09060e7-561b-4f5a-81d0-e8700a3fda5b)

Any idea what might be going wrong? Thanks!

**Comment by joycekang** [comment]
Hi there! I seem to be running into the same issue. The first few lines of my annotations file is:

![Image](https://github.com/user-attachments/assets/4b789f32-90f8-4753-ad0b-b0a22b033bf2)

Any idea what might be going wrong? Thanks!

**Comment by joycekang** [comment]
I figured it out, it was actually an issue with my cell classifications file, not the genes file!
