### ISSUE TITLE
Error while creating infercnv.ngchm object

### ISSUE THREAD

**Issue by anka-11** [broadinstitute/infercnv#180]
Dear developers,
I could successfully create a inferCNV object from my 10X scRNA-Seq datasets. However, when I then try to create the object for the interactive analysis with the NGCHM-tool I'm getting the following error:
INFO [2019-10-14 09:40:47] Creating NGCHM as infercnv.ngchm
INFO [2019-10-14 09:40:47] Initializing new NGCHM InferCNV Object.
Error in (function (cl, name, valueClass)  : 
  assignment of an object of class “NULL” is not valid for @‘reference_cells’ in an object of class “NGCHM_inferCNV”; is(value, "character") is not TRUE

I used the following command to create the NGCHM-object:
ngchm(infercnv_obj = infercnv_obj,
      out_dir = "NGCHM_MD/",                                   
      path_to_shaidyMapGen = "../../../Software/ShaidyMapGen.jar", 
      gene_symbol = "bio.gene.entrezid")

And the infercnv object was previously created with the following command:
infercnv_obj = CreateInfercnvObject(raw_counts_matrix="Sample.counts.matrix",
                                                   annotations_file="Sample_annot_woFB.txt",
                                                   gene_order_file="gencode_v19_gene_pos.txt",
                                                   delim="\t",
                                                   ref_group_names=NULL)

Any idea regarding this issue?
Thx in advance for your help!

**Comment by brownmp** [comment]
Hello @anka-11,

Just want to make sure, are you running infercnv's run command `infercnv::run()` or are you only creating the inference object using `infercnv::CreateInfercnvObject()`?

Best,
M. Brown

**Comment by anka-11** [comment]
Hi, I used `infercnv::CreateInfercnvObject()` to create the object and then `infercnv::run()` reveal the cnv signal. 
Best,
Anka

**Comment by brownmp** [comment]
Hello @anka-11 ,

I believe the error is occurring because the argument `ref_group_names` is set to NULL. When creating the infercnv object using `CreateInfercnvObject`, ensure you have the names of the reference cells in the `ref_group_names` argument. 

Best,
M. Brown

**Comment by anka-11** [comment]
Hey,
yes I set it to NULL since I do not have reference cells in my dataset. I did it to what is written in the wiki: "_..you can set ref_group_names=NULL, in which case the average signal across all cells will be used to define the baseline._". I had no issues generating the object and to obtain the corresponding heatmap. However, it obviously does not work for generating the interactive heatmap using ShadyMapGen.

Best,
Anka

**Comment by brownmp** [comment]
@anka-11 ,

The latest updates made to infercnvNGCHM should fix this issue. Let me know if you run into anymore issues.

Best,
M. Brown

**Comment by elderni** [comment]
I received this error today using "NULL" for ref_group_names. Has infercnvNGCHM been updated yet?

**Comment by XYZ-NCI** [comment]
Hi, 
I have some issue creating a NGCHM object. 

I used infercnv::CreateInfercnvObject() to create the object and then infercnv::run() to reveal CNV signals. I did setup ref_group_name to match the sample names that I used. However, when I ran ngchm, the following error message showed up:

Error in initialize(value, ...)  :
cannot use object of class "character" in new(): class "NGCHM_inferCNV" does not extend that class

Any help is greatly appreciated!
XZ

**Comment by brownmp** [comment]
The originally update was made to the `devel` branch. The `master` branch is now up to date.

Best,
M. Brown

**Comment by brownmp** [comment]
@XYZ-NCI what commands are you using to run NGCHM_inferCNV?

- M. Brown

**Comment by XYZ-NCI** [comment]
Thank you so much for getting back to me. I used the attached .r file to run NGCHM_inferCNV

**Comment by brownmp** [comment]
Hello @XYZ-NCI,

Unfortunately I am not seeing an attachment. Feel free to email the .r file to me if that is easier. mbrown@broadinstititue.org 

-M. Brown

**Comment by XYZ-NCI** [comment]
Hi,

Thank you so much for working on this issue. Please find below the code I used to run NGCHM_inferCNV. I can’t send the .r file for some reason. The email was bounced back. Your help is very much appreciated.

Best,
Xiyuan

library(NGCHM)
library(infercnv)
library(infercnvNGCHM)
ngchm(infercnv_obj = "/data/zhangx22/inferCNV_PNF_PDX_individually/cluster_by_group_PNF_CS023740_PDX4/preliminary.infercnv_obj",
      out_dir = "/data/zhangx22/inferCNV_PNF_PDX_individually/cluster_by_group_PNF_CS023740_PDX4/CS023740_PDX4_NGCHM",
      path_to_shaidyMapGen = "/data/zhangx22/ShaidyMapGen.jar")

**Comment by brownmp** [comment]
@ XYZ-NCI,

When running `ngchm()`, `infercnv_obj = ` should be the loaded object, not the path to the object. you can load the object using `readRDS()`.

~ M. Brown

**Comment by XYZ-NCI** [comment]
Hi! I loaded the object and tried again but still failed. Below is the code to run and error message:
infercnv_obj = readRDS("/data/zhangx22/inferCNV_results/inferCNV_PNF_PDX_individually/cluster_by_group_PNF_CS023740_PDX4/preliminary.infercnv_obj")
ngchm(infercnv_obj = infercnv_obj,
      out_dir = "/data/zhangx22/inferCNV_results/inferCNV_PNF_PDX_individually/cluster_by_group_PNF_CS023740_PDX4/CS023740_PDX4_NGCHM",
      path_to_shaidyMapGen = "/data/zhangx22/ShaidyMapGen.jar")

Error in slot(value, what) :
  no slot of name "options" for this object of class "infercnv"
Calls: ngchm ... initialize -> initialize -> as<- -> asMethod -> slot
Execution halted

**Comment by brownmp** [comment]
@XYZ-NCI 

You will need to reinstall `NGCHMR` using the **master** branch from github.
When installing NGCHMR, use `devtools::install_github("bmbroom/NGCHMR", ref="master")` in R.
This should fix that issue.

~M. Brown

**Comment by XYZ-NCI** [comment]
Hi,

I reinstalled NGCHMR as you suggested but still have the same error message:
Error in slot(value, what) :
  no slot of name "options" for this object of class "infercnv"
Calls: ngchm ... initialize -> initialize -> as<- -> asMethod -> slot
Execution halted

Shall I use the library NGCHMR or NGCHM?

Thanks!

**Comment by honghh2018** [comment]
Hi @XYZ-NCI ,
   It was very confused when runing the ngchm with infercnv_obj that generated by infercnv::run.
   The error showing below: it seem like the infercnv_obj generated by the old version?
INFO [2021-05-20 11:50:11] Creating NGCHM as infercnv.ngchm
INFO [2021-05-20 11:50:11] Initializing new NGCHM InferCNV Object.
Error in (function (cl, name, valueClass)  : 
  ‘cuts_color’ is not a slot in class “ngchmLayer”

How to fix this issue? any advice would be appreciated.
Best,
Hanhuihong

**Comment by brownmp** [comment]
hello @honghh2018, 

You need to reinstall NGCHMR , use the following in R:

```R
devtools::install_github("bmbroom/NGCHMR", ref="master")
```

When creating the NGCHM plots for the infercnv output you need to use `infercnvNGCHM`.

You can look at the same issue here #66 and #246 for reference as well. Please let me know if this solves your issue!

~ M.Brown
