### ISSUE TITLE
Error at step Bayesian network model on HMM predicted CNVs, using annotation with no reference cells

### ISSUE THREAD

**Issue by hgeiger-CUNY** [broadinstitute/infercnv#181]
Get the following errors at "STEP 13: Run Bayesian Network Model on HMM predicted CNV's".

INFO [2019-10-17 14:38:12] Creating the following Directory:  Results_inferCNV/HPAF2_output/BayesNetOutput.HMMi6.hmm_mode-samples
INFO [2019-10-17 14:38:12] Initializing new MCM InferCNV Object.
INFO [2019-10-17 14:38:12] validating infercnv_obj
INFO [2019-10-17 14:38:13] Total CNV's:  1
INFO [2019-10-17 14:38:13] Loading BUGS Model.
INFO [2019-10-17 14:38:13] Running Sampling Using Parallel with  4 Cores
INFO [2019-10-17 14:42:19] Obtaining probabilities post-sampling
INFO [2019-10-17 14:42:43] Gibbs sampling time:  4.50045995314916  Minutes
INFO [2019-10-17 14:43:04] ::plot_cnv:Start
INFO [2019-10-17 14:43:04] ::plot_cnv:Current data dimensions (r,c)=5508,5104 Total=57421.9657776176 Min=0 Max=0.937532095376463.
INFO [2019-10-17 14:43:04] ::plot_cnv:Depending on the size of the matrix this may take a moment.
INFO [2019-10-17 14:43:05] plot_cnv_observation:Start
INFO [2019-10-17 14:43:05] Observation data size: Cells= 5104 Genes= 5508
INFO [2019-10-17 14:43:05] clustering observations via method: ward.D
INFO [2019-10-17 14:43:05] plot_cnv_observation:Writing observation groupings/color.
INFO [2019-10-17 14:58:09] Colors for breaks:  #00008B,#24249B,#4848AB,#6D6DBC,#9191CC,#B6B6DD,#DADAEE,#FFFFFF,#EEDADA,#DDB6B6,#CC9191,#BC6D6D,#AB4848,#9B2424,#8B0000
INFO [2019-10-17 14:58:09] Quantiles of plotted data range: 0,0,0,0,0.937532095376463
INFO [2019-10-17 14:58:14] plot_cnv_references:Writing observation data to Results_inferCNV/HPAF2_output/BayesNetOutput.HMMi6.hmm_mode-samples/infercnv.NormalProbabilities.observations.txt
INFO [2019-10-17 14:58:57] Attempting to removing CNV(s) with a probability of being normal above  0.5
INFO [2019-10-17 14:58:57] Removing  0  CNV(s) identified by the HMM.
Error in dimnames(x) <- dn : 
  length of 'dimnames' [2] not equal to array extent
Calls: <Anonymous> ... <Anonymous> -> removeCNV -> removeCNV -> colnames<-

Does this mean that maybe running with HMM=TRUE is not appropriate for this data set? Or do I need to change some other parameter to make it work?

I am not able to annotate any of the cells as reference, so my annotation file looks like this for every cell:

AAACCTGAGGCTAGCA-1<tab>malignant
AAACCTGAGTCTTGCA-1<tab>malignant

I think the error may be related to this specific line in the infercnv::run function:

hmm_states_highPnormCNVsRemoved.matrix <- mcmc_obj_hmm_states_list[[2]]

Or if not, the one a bit before:

 mcmc_obj <- infercnv::inferCNVBayesNet(infercnv_obj = infercnv_obj,
                  HMM_states = hmm.infercnv_obj@expr.data, file_dir = out_dir,
                  postMcmcMethod = "removeCNV", out_dir = file.path(out_dir,
                    sprintf("BayesNetOutput.%s", hmm_resume_file_token)),
                  quietly = TRUE, CORES = num_threads, plotingProbs = plot_probabilities,
                  diagnostics = diagnostics, HMM_type = HMM_type,
                  k_obs_groups = k_obs_groups, cluster_by_groups = cluster_by_groups)

**Comment by GeorgescuC** [comment]
Hi @hgeiger-CUNY ,

Which version of infercnv are you using? I think this is an issue that was fixed, but it may be a slightly different one.

Regards,
Christophe.
