### ISSUE TITLE
How to confrim tumor cells from the results 

### ISSUE THREAD

**Issue by wtj2018** [broadinstitute/infercnv#182]
Hello:
        I use inferCNV to confirm tumor cells in 10x single cell RNAseq data,  and I don't now which cells are normal cells,so i set ref_group_names=NULL in CreateInfercnvObject function. the pipline running normally,So  how could i find tumor cells from the result? Thanks very much !!!

**Comment by GeorgescuC** [comment]
Hi @wtj2018 ,

If you do not provide any set of cells as reference, the average of all your cells will be used as the baseline expression. This means that any apparent CNV will be relative to the most common expression profile. So for example, if 80% of your cells are tumor cells with a CNV on chr1, the 20% cells that are normal will look like the ones with a CNV (opposite event). In this situation, you can use infercnv to identify your subclones, but you will likely need another method to define which subclones are what type of cells.

Regards,
Christophe.

**Comment by tpdesai** [comment]
Hi,
Wanted to ask how to use the subclusters to determine if a cell is considered tumor or normal? Would the above method work which is to not add a reference sample?
