### ISSUE TITLE
How to get the data matrix for the heatmap?

### ISSUE THREAD

**Issue by joonlee3** [broadinstitute/infercnv#184]
Hi,

   I am wondering how to obtain the expression data matrix used for the heat-map. In the previous versions of inferCNV, inferCNV produced two datasets

- expression_pre_vis_transform.txt / expression_post_viz_transform.txt

   Is there anyway to get such data matrices from the latest version of inferCNV? Please let me know. Thank you.

Best,
Joon

**Comment by GeorgescuC** [comment]
Hi @joonlee3 ,

Each figure that is generated by infercnv should have by default (unless you specify `write_expr_matrix=FALSE` in a manual call to `plot_cnv()`) text outputs for the matrices used. For each `figure.png` there will be `figure.observations.txt` and `figure.references.txt` containing respectively the bottom heatmap and the top heatmap.

As we do not scale the residual expression values anymore, there are no pre/post_viz_transform files anymore. You can however look at the plot after each individual step if you specify `plot_steps=TRUE` in `run()`.

Regards,
Christophe.

**Comment by joonlee3** [comment]
@GeorgescuC 
Thank you for the reply.

May I get some details on how to get the residual expression values from those two matrices you mentioned (**figure.observations.txt** and **figure.references.txt**)?

Best,
Joon

**Comment by GeorgescuC** [comment]
Hi @joonlee3 ,

Those two files are simply the matrices of the residual expression values in tab delimited format, there should not be anything particular (editing or transformation) to do to be able to read them.

Regards,
Christophe.
