### ISSUE TITLE
Getting CNV state using add_to_seurat function in seurat_interaction.R

### ISSUE THREAD

**Issue by mehc555** [broadinstitute/infercnv#185]
Hi,

I had problems getting the correct CNV state when using add_to_seurat() with HMMi6, should center_state = 3 at line 50?

Thank you

**Comment by GeorgescuC** [comment]
Hi @mehc555 ,

The numbering of states changed in version 1.1.3 for the Bayesian filtered results, so it now matches that of before. I now added a fix, so you can download the code from github and reinstall infercnv. I will be making a version upgrade to 1.1.4 soon too.

Regards,
Christophe.
