### ISSUE TITLE
troubleshooting

### ISSUE THREAD

**Issue by mgood2** [broadinstitute/infercnv#186]
I have an unknown cancer cell proportion of single-cell data. I used just clusters from the Seurat package. 

> infer_obj = run(infer_obj, cutoff=0.1, out_dir= "./result/", cluster_by_groups=FALSE, denoise=TRUE, HMM=TRUE)
INFO [2019-10-28 14:02:18] ::process_data:Start
INFO [2019-10-28 14:02:18] Checking for saved results.
INFO [2019-10-28 14:02:18] 

	STEP 1: incoming data

INFO [2019-10-28 14:02:19] 

	STEP 02: Removing lowly expressed genes

INFO [2019-10-28 14:02:19] ::above_min_mean_expr_cutoff:Start
INFO [2019-10-28 14:02:19] Removing 11844 genes from matrix as below mean expr threshold: 0.1
INFO [2019-10-28 14:02:19] validating infercnv_obj
INFO [2019-10-28 14:02:19] There are 232 genes and 1783 cells remaining in the expr matrix.
INFO [2019-10-28 14:02:19] no genes removed due to min cells/gene filter
INFO [2019-10-28 14:02:19] 

	STEP 03: normalization by sequencing depth

INFO [2019-10-28 14:02:19] normalizing counts matrix by depth
INFO [2019-10-28 14:02:19] Computed total sum normalization factor as median libsize: 167.000000
INFO [2019-10-28 14:02:19] Adding h-spike
INFO [2019-10-28 14:02:19] -hspike modeling of C0
INFO [2019-10-28 14:02:55] -hspike modeling of C1
INFO [2019-10-28 14:03:32] -hspike modeling of C2
INFO [2019-10-28 14:04:08] -hspike modeling of C3
INFO [2019-10-28 14:04:43] -hspike modeling of C4
INFO [2019-10-28 14:05:19] -hspike modeling of C5
INFO [2019-10-28 14:05:55] -hspike modeling of C6
INFO [2019-10-28 14:06:32] -hspike modeling of C7
INFO [2019-10-28 14:07:07] -hspike modeling of C8
INFO [2019-10-28 14:07:43] -hspike modeling of C9
INFO [2019-10-28 14:08:19] -hspike modeling of C10
INFO [2019-10-28 14:08:55] validating infercnv_obj
INFO [2019-10-28 14:08:55] normalizing counts matrix by depth
INFO [2019-10-28 14:08:56] Using specified normalization factor: 167.000000
INFO [2019-10-28 14:08:58] 

	STEP 04: log transformation of data

INFO [2019-10-28 14:08:58] transforming log2xplus1()
INFO [2019-10-28 14:08:59] -mirroring for hspike
INFO [2019-10-28 14:08:59] transforming log2xplus1()
INFO [2019-10-28 14:09:03] 

	STEP 08: removing average of reference data (before smoothing)

INFO [2019-10-28 14:09:03] ::subtract_ref_expr_from_obs:Start inv_log=FALSE, use_bounds=TRUE
INFO [2019-10-28 14:09:03] subtracting mean(normal) per gene per cell across all data
INFO [2019-10-28 14:09:03] -subtracting expr per gene, use_bounds=TRUE
INFO [2019-10-28 14:09:03] -mirroring for hspike
INFO [2019-10-28 14:09:03] ::subtract_ref_expr_from_obs:Start inv_log=FALSE, use_bounds=TRUE
INFO [2019-10-28 14:09:03] subtracting mean(normal) per gene per cell across all data
INFO [2019-10-28 14:09:06] -subtracting expr per gene, use_bounds=TRUE
INFO [2019-10-28 14:09:12] 

	STEP 09: apply max centered expression threshold: 3

INFO [2019-10-28 14:09:12] ::process_data:setting max centered expr, threshold set to: +/-:  3
INFO [2019-10-28 14:09:12] -mirroring for hspike
INFO [2019-10-28 14:09:12] ::process_data:setting max centered expr, threshold set to: +/-:  3
INFO [2019-10-28 14:09:17] 

	STEP 10: Smoothing data per cell by chromosome

INFO [2019-10-28 14:09:17] smooth_by_chromosome: chr: chr1
INFO [2019-10-28 14:09:18] smooth_by_chromosome: chr: chr10
INFO [2019-10-28 14:09:18] smooth_by_chromosome: chr: chr11
INFO [2019-10-28 14:09:18] smooth_by_chromosome: chr: chr12
INFO [2019-10-28 14:09:18] smooth_by_chromosome: chr: chr13
INFO [2019-10-28 14:09:18] smooth_by_chromosome: chr: chr14
INFO [2019-10-28 14:09:18] smooth_by_chromosome: chr: chr15
INFO [2019-10-28 14:09:18] smooth_by_chromosome: chr: chr16
INFO [2019-10-28 14:09:19] smooth_by_chromosome: chr: chr17
INFO [2019-10-28 14:09:19] smooth_by_chromosome: chr: chr19
INFO [2019-10-28 14:09:19] smooth_by_chromosome: chr: chr2
INFO [2019-10-28 14:09:19] smooth_by_chromosome: chr: chr20
INFO [2019-10-28 14:09:19] smooth_by_chromosome: chr: chr21
INFO [2019-10-28 14:09:19] smooth_by_chromosome: chr: chr22
INFO [2019-10-28 14:09:19] smooth_by_chromosome: chr: chr3
INFO [2019-10-28 14:09:20] smooth_by_chromosome: chr: chr4
INFO [2019-10-28 14:09:20] smooth_by_chromosome: chr: chr5
INFO [2019-10-28 14:09:20] smooth_by_chromosome: chr: chr6
INFO [2019-10-28 14:09:20] smooth_by_chromosome: chr: chr7
INFO [2019-10-28 14:09:20] smooth_by_chromosome: chr: chr8
INFO [2019-10-28 14:09:20] smooth_by_chromosome: chr: chr9
INFO [2019-10-28 14:09:20] -mirroring for hspike
INFO [2019-10-28 14:09:20] smooth_by_chromosome: chr: chrA
INFO [2019-10-28 14:09:23] smooth_by_chromosome: chr: chr_0
INFO [2019-10-28 14:09:25] smooth_by_chromosome: chr: chr_B
INFO [2019-10-28 14:09:28] smooth_by_chromosome: chr: chr_0pt5
INFO [2019-10-28 14:09:30] smooth_by_chromosome: chr: chr_C
INFO [2019-10-28 14:09:32] smooth_by_chromosome: chr: chr_1pt5
INFO [2019-10-28 14:09:35] smooth_by_chromosome: chr: chr_D
INFO [2019-10-28 14:09:37] smooth_by_chromosome: chr: chr_2pt0
INFO [2019-10-28 14:09:40] smooth_by_chromosome: chr: chr_E
INFO [2019-10-28 14:09:42] smooth_by_chromosome: chr: chr_3pt0
INFO [2019-10-28 14:09:44] smooth_by_chromosome: chr: chr_F
INFO [2019-10-28 14:09:53] 

	STEP 11: re-centering data across chromosome after smoothing

INFO [2019-10-28 14:09:53] ::center_smooth across chromosomes per cell
INFO [2019-10-28 14:09:53] -mirroring for hspike
INFO [2019-10-28 14:09:53] ::center_smooth across chromosomes per cell
INFO [2019-10-28 14:10:01] 

	STEP 12: removing average of reference data (after smoothing)

INFO [2019-10-28 14:10:01] ::subtract_ref_expr_from_obs:Start inv_log=FALSE, use_bounds=TRUE
INFO [2019-10-28 14:10:01] subtracting mean(normal) per gene per cell across all data
INFO [2019-10-28 14:10:01] -subtracting expr per gene, use_bounds=TRUE
INFO [2019-10-28 14:10:01] -mirroring for hspike
INFO [2019-10-28 14:10:01] ::subtract_ref_expr_from_obs:Start inv_log=FALSE, use_bounds=TRUE
INFO [2019-10-28 14:10:01] subtracting mean(normal) per gene per cell across all data
INFO [2019-10-28 14:10:03] -subtracting expr per gene, use_bounds=TRUE
INFO [2019-10-28 14:10:09] 

	STEP 14: invert log2(FC) to FC

INFO [2019-10-28 14:10:09] invert_log2(), computing 2^x
INFO [2019-10-28 14:10:09] -mirroring for hspike
INFO [2019-10-28 14:10:09] invert_log2(), computing 2^x
INFO [2019-10-28 14:10:17] 

	STEP 15: Clustering samples (not defining tumor subclusters)

INFO [2019-10-28 14:10:17] define_signif_tumor_subclusters(p_val=0.1
INFO [2019-10-28 14:10:17] define_signif_tumor_subclusters(), tumor: all_observations
INFO [2019-10-28 14:10:17] define_signif_tumor_subclusters(), tumor: all_references
INFO [2019-10-28 14:10:22] cut tree into: 1 groups
INFO [2019-10-28 14:10:22] -processing all_references,all_references_s1
INFO [2019-10-28 14:10:22] -mirroring for hspike
INFO [2019-10-28 14:10:22] define_signif_tumor_subclusters(p_val=0.1
INFO [2019-10-28 14:10:22] define_signif_tumor_subclusters(), tumor: all_observations
INFO [2019-10-28 14:11:04] cut tree into: 1 groups
INFO [2019-10-28 14:11:04] -processing all_observations,all_observations_s1
INFO [2019-10-28 14:11:04] define_signif_tumor_subclusters(), tumor: all_references
INFO [2019-10-28 14:11:45] cut tree into: 1 groups
INFO [2019-10-28 14:11:45] -processing all_references,all_references_s1
INFO [2019-10-28 14:12:00] ::plot_cnv:Start
INFO [2019-10-28 14:12:00] ::plot_cnv:Current data dimensions (r,c)=232,1783 Total=415303.864623757 Min=0.531905451764769 Max=2.75791646149227.
INFO [2019-10-28 14:12:00] ::plot_cnv:Depending on the size of the matrix this may take a moment.
INFO [2019-10-28 14:12:00] plot_cnv(): auto thresholding at: (0.787246 , 1.220721)
INFO [2019-10-28 14:12:01] plot_cnv_observation:Start
INFO [2019-10-28 14:12:01] Observation data size: Cells= 0 Genes= 232
INFO [2019-10-28 14:12:01] clustering observations via method: ward.D
Error in UseMethod("as.phylo") : 
  no applicable method for 'as.phylo' applied to an object of class "NULL"
In addition: Warning messages:
1: In max(nchar(obs_annotations_names)) :
  no non-missing arguments to max; returning -Inf
2: In min(obs_data, na.rm = TRUE) :
  no non-missing arguments to min; returning Inf
3: In max(obs_data, na.rm = TRUE) :
  no non-missing arguments to max; returning -Inf

I wasn't sure why I got this message. 

Thank you.

**Comment by GeorgescuC** [comment]
Hi @mgood2 ,

There are two things that seem to be an issue here. 
First, could you also send the command you used to initially create the infercnv object? It appears that you have set all your groups as references, so there are no observations to cluster or plot.
Second, only 232 genes are kept in the matrix, which is very little. Are you using raw read counts as input?

Regards,
Christophe.

**Comment by mgood2** [comment]
Thank you very much for your help.
