### ISSUE TITLE
problem in STEP 13: Run Bayesian Network Model on HMM predicted CNV's

### ISSUE THREAD

**Issue by reshu23** [broadinstitute/infercnv#187]
Hi,.
I am running following command on my dataset:
infercnv_obj = infercnv::run(infercnv_obj,
                             cutoff=0.1,
                             analysis_mode = "subclusters", out_dir="Results, 
                             denoise=TRUE,
                             HMM=TRUE,
                             tumor_subcluster_pval=0.05,
                             HMM_type = "i3")

I have tried HMM_type="i6"(by default) and "i3" also.But I am getting same error

Here is the error:
STEP 13: Run Bayesian Network Model on HMM predicted CNV's

INFO [2019-10-28 14:48:25] Creating the following Directory:  Results/BayesNetOutput.HMMi3.rand_trees.hmm_mode-subclusters
INFO [2019-10-28 14:48:25] Initializing new MCM InferCNV Object.
INFO [2019-10-28 14:48:25] validating infercnv_obj
Error in (function (cl, name, valueClass)  : 
  assignment of an object of class character is not valid for @ cnv_regions in an object of class MCMC_inferCNV; is(value, "factor") is not TRUE

**Comment by GeorgescuC** [comment]
Hi @reshu23 ,

Are your annotations groups per chance just numbers? If yes, downloading the latest version should fix the issue.
If not, could you post the full run log please? Also, which version are you using?

Regards,
Christophe.

**Comment by reshu23** [comment]
Hi Christophe,
Thank you. Yes, name of my annotation group is like, M12349.Patient , It means, combination of numbers and characters(with dot operator). Do you want me to use some sort of specific syntax for name of group? Right now, I am using infercnv 1.0.4, I think, it is recent release, I installed it through bioconductor. 
Yesterday, I tried development version of infercnv. I installed it through bioconductor:
http://bioconductor.riken.jp/packages/devel/bioc/html/infercnv.html

But I got same error as I got with release 1.0.4. Ya, surprising bit was, after step 12, step 13 was missing. It directly jumped to step 14 and step 17 was  Run Bayesian Network Model on HMM predicted CNV's.(in devel infercnv)

If you think, I have not installed devel version, can you please tell me, how can I install within R easily?

**Comment by reshu23** [comment]
Hi Christophe,

So, I have found problem(I am using again 1.0.4, as I have encountered same problem in devel). Reason of problem was: dot operator in the group name. This time, I have changed group name, I mean, dot operator with "_". And It works. It means, you can replicate error with any data set just by writing group name like "M1234.Patient.PP". ideally, it should work with dot operator.

Another question, 

Whenever I run infercnv 1.0.4, I always get 4 reports:
HMM_CNV_predictions.HMMi6.rand_trees.hmm_mode-subclusters.Pnorm_0.5.cell_groupings
HMM_CNV_predictions.HMMi6.rand_trees.hmm_mode-subclusters.Pnorm_0.5.genes_used.dat
HMM_CNV_predictions.HMMi6.rand_trees.hmm_mode-subclusters.Pnorm_0.5.pred_cnv_genes.dat
HMM_CNV_predictions.HMMi6.rand_trees.hmm_mode-subclusters.Pnorm_0.5.pred_cnv_regions.dat


This time, I have got only two reports:
HMM_CNV_predictions.HMMi6.rand_trees.hmm_mode-subclusters.Pnorm_0.5.pred_cnv_genes.dat
HMM_CNV_predictions.HMMi6.rand_trees.hmm_mode-subclusters.Pnorm_0.5.pred_cnv_regions.dat

why, two reports are missing? cell grouping is available for 12_HMM_preds.cell_groupings
Have I done something wrong? But I used same parameter always.

Thank you

**Comment by GeorgescuC** [comment]
Hi @reshu23 ,

This is something that changed recently with the update that allows the CNV IDs to be kept from the original HMM output to the Bayesian filtered output for consistency. Before the update, all 4 files were generated both times independently. Now that the Bayesian step loads previous IDs, it only outputs the filtered "pred_cnv_genes.dat" and "pred_cnv_regions.dat". The "cell_groupings" and "genes_used.dat" do not change, so outputing them again is redundant. This means you can use "12_HMM_preds.cell_groupings" and "12_HMM_preds.genes_used.dat" (or 17_ in the newest release with BioConductor 3.10)

Regards,
Christophe.

**Comment by reshu23** [comment]
Thank you very much
