### ISSUE TITLE
How to deal with genes at the end of chromosomes?

### ISSUE THREAD

**Issue by HaotengYan** [broadinstitute/infercnv#190]
Hi, 

When `remove_genes_at_chr_ends ` was set to `FALSE`, how do you infer copy number of the window_length/2 genes at both ends of the chromosome? 

Regards, 
Haoteng Yan

**Comment by GeorgescuC** [comment]
Hi @HaotengYan ,

When `remove_genes_at_chr_ends=FALSE` (default), we use the `smooth_method` as usual except that it is limited to the up to window_length/2 genes available on each side.

For example, the smoothed expression value of the 100th gene on a chromosome with at least 150 genes and a window size of 101 can be expressed as `smooth(start=50, center=100, end=150)`. For the 20th gene and the same options, the smoothed expression value is `smooth(start=1, center=20, end=70)`.

Based on the `smooth_method` you use, the actual formula behind smooth() is different (a basic mean or a weighted mean), but this is the general way it works.
Please let me know if my explanation is unclear.

Regards,
Christophe.

**Comment by HaotengYan** [comment]
Hi, 

Thank you for your kindly reply. I have got it.

Best, 
Haoteng Yan
