### ISSUE TITLE
inferCNV: Observation vs Reference

### ISSUE THREAD

**Issue by reshu23** [broadinstitute/infercnv#193]
Hi,

I have one question. Generally for inferCNV, we can provide reference(many also) and observation(many groups also). It will show CNV in observation groups in comparison to reference. But suppose, If I want to compare B with A and then B with C. 

I mean, use "A" as reference and "B" as observation. And use inferCNV, you have got final observation matrix for "B" with inferred CNV(you show it ,in heatmap). After that, use that B(with inferred CNV matrix) as reference and C as observation.

Do you think, It is possible to do such type of comparison with inferCNV?

**Comment by GeorgescuC** [comment]
Hi @reshu23 ,

If I understand correctly what you want to do, I think you can simply run infercnv with "A" and "B" as references, and "C" as observation. The reason for this is that in your first run "A" vs "B", what you see as the results is basically B-A, and if you run "A" & "B" vs "C", the results will be C-(min/max(A,B)). With this your results for "C" will be CNVs unique to it.

Taking the results of your first run into a new run of infercnv would not work as what you see in the heatmap is the residual expression, leftover from comparing the two sets of cells, while your new set of cells would still be raw read counts.

Regards,
Christophe.

**Comment by reshu23** [comment]
Thank you. I have one more question. Now I can see, HMM state has been reported as 1-6. (instead of 0x, 0.5x,1x....)
It means:

State 1:  0x: complete loss      
State 2:  0.5x: loss of one copy
State 3: 1x: neutral
State 4:  1.5x: addition of one copy
State 5:  2x: addition of two copies
State 6: 3x: essentially a placeholder for >2x copies but modeled as 3x.


Am I right?

**Comment by GeorgescuC** [comment]
Yes, those are the correct states meaning.
