### ISSUE TITLE
error when generating NGCHM object

### ISSUE THREAD

**Issue by kerimsecener** [broadinstitute/infercnv#198]
Hello,

I have used the following commands to generate the infercnv.ngchm from the NGCHM library, but I get the following error:

library(infercnvNGCHM)
library(infercnv)
library(NGCHM)

ngchm(infercnv_obj  = infercnv_obj, out_dir = ".",  path_to_shaidyMapGen = "infer_output/ShaidyMapGen.jar",  gene_symbol  = "bio.gene.hugo")

INFO [2019-11-25 03:32:03] Creating NGCHM as infercnv.ngchm
INFO [2019-11-25 03:32:03] Initializing new NGCHM InferCNV Object.
**Error in slot(value, what) : 
  no slot of name "options" for this object of class "infercnv"**

Any idea why this might be happening ?

Thanks,

Kerim

**Comment by GeorgescuC** [comment]
Hi @kerimsecener ,

Which version of infercnv was your object generated with? It seems like you may be using an older version from before the tracking of options used for a run was added, so the field is missing in your object.

Regards,
Christophe.

**Comment by kerimsecener** [comment]
Hi Christophe,

Thanks for the reply. Indeed, I have installed the old version with Option B. I have updated it to the latest version now, so it should be good.

Best,

Kerim
