### ISSUE TITLE
Settings for results output: figure format, colors, etc

### ISSUE THREAD

**Issue by kokonech** [broadinstitute/infercnv#201]
Hi! InferCNV is a nice tool, works good on both SmartSeq2 and 10X data. My question: how to adjust the figure with own parameters? For example, need final result figure infercnv.png  in PDF/SVG format with changed color scale (e.g. green/red instead of blue/red). I did not find such settings in two main functions _CreateInfercnvObject_ and _infercnv::run_. Or should I use some output to generate the figure myself?

**Comment by GeorgescuC** [comment]
Hi @kokonech ,

For the output format, you can set the option `output_format="PDF"` in either run() or plot_cnv().

For the color scale, I have now added an option `custom_color_pal` to plot_cnv() that, in your case you can set to `custom_color_pal=color.palette(c("darkgreen", "white", "darkred"), c(2, 2))`. You will however need to update infercnv to version 1.3.2 for this. 
You can do so right away by pulling the code from github and installing (you can use the method shown [on the wiki](https://github.com/broadinstitute/infercnv/wiki/Installing-infercnv#option-c-install-infercnv-from-within-r-using-devtools) by setting the ref to "master"), or you can wait for the new BioConductor devel build to be ready in a day or two and update through BioConductor devel. (the new option will not be available on BioConductor 3.10 as it is a change to a visible method signature).

Regards,
Christophe.

**Comment by kokonech** [comment]
Hi Christophe,

Thanks a lot for quick adjustment and note about format change! Tested the latest code, novel option works! Just one small additional issue: the function _color.palette_ that is used to generate it and provided in recommendation is actually not exported. I used the code from inferCNV_ops.R to apply it. Is it possible to export it in the NAMESPACE as well? Or is there some alternative to it?

**Comment by GeorgescuC** [comment]
Hi @kokonech ,

That is true. I will be updating that for the next version. For the time being, you should be able to simply call it using `infercnv:::color.palette()` so you don't need to copy/import the method manually.

Regards,
Christophe.

**Comment by kokonech** [comment]
Thanks, that works too! You could close the issue once this is implemented!

**Comment by GeorgescuC** [comment]
The method is now exported in the latest commit. It will be integrated into the next version upgrade.
