### ISSUE TITLE
How to add more than one annotation bar in inferCNV package?

### ISSUE THREAD

**Issue by JiFansen** [broadinstitute/infercnv#203]
inferCNV can generate the final heatmap with only one annotation bar, but I wonder if I could add another annotation bar? and how?

**Comment by GeorgescuC** [comment]
Hi @JiFansen ,

It is possible to add annotation bars, but it requires modifying some code to tune to your needs.
The first thing is to change the layout defined in "infercnvCNV_heatmap.R#.plot_observations_layout" by adding row(s) or column(s) in the "obs_lmat" where you want the additional annotation bars, as well as defining their height below in "obs_lhei". The values within the matrices are the order in which the space is to be filled by new elements. As it is right now, 1-6 are for the observations, 7-12 for the references. More precisely, elements 2 and 3 are the left vertical side annotation bars for observations (cell groups/hclust splits), 4 is the horizontal chromosome annotation bar, 10 is the vertical annotation bar for the reference and 11 is a filler. If you add any new element, you will have to shift the ones that are plotted after accordingly.

To then actually plot the data you want to have in the annotation bar(s), you will have to edit "infercnvCNV_heatmap.R#heatmap.cnv". There are comments within the method to guide you to where each element is plotted, but it can be confusing at first.
You can use these commits as a reference to changes made previously to add an annotation bar: https://github.com/broadinstitute/infercnv/commit/2175fc3e8d6f6f08b3d777060fd80fe3464e26c4
https://github.com/broadinstitute/infercnv/commit/d11836cde5b0a40a6d746394cfbe3952dcbb5f1f

Best,
Christophe.
