### ISSUE TITLE
How to remove the intermediate result? Which parameter I should set?

### ISSUE THREAD

**Issue by singletrips** [broadinstitute/infercnv#204]
Now, I am running the new version of infercnv, and there are so many intermediate results. I don't want to save those results, so I was wondering which parameter I should set to stop the infercnv outputs the intermediate results, and only output the final result to save my space.

**Comment by brownmp** [comment]
Hello @singletrips,

There isn't a way for infercnv to not output the complete intermediate steps, but the options `plot_steps` and `plot_probabilities` in the function  `infercnv::run` can be set to FALSE to limit the outputs at each step though.

~ M. Brown

**Comment by singletrips** [comment]
If your sample is too big, you'll be stuck in step 18 for several days, and finally, maybe fail. My solution is running infercnv separately for each patient if you can separate your samples.  Good luck with your infercnv!

**Comment by GeorgescuC** [comment]
Hi @singletrips ,

There is now a pair of options, "save_rds" and "save_final_rds" that you can set to FALSE in infercnv::run() to disable saving of .rds files after each stop (1st option) or the final results (2nd option) on the master branch.

Regards,
Christophe.
