### ISSUE TITLE
When running plot_cnv() get the following error, which is "ERROR unexpected error, should not happen"

### ISSUE THREAD

**Issue by singletrips** [broadinstitute/infercnv#206]
infercnv::plot_cnv(infercnv_obj,out_dir=out_dir,cluster_by_groups=T,color_safe_pal=FALSE,x.center=1,x.range=c(0.6,1.4),title="inferCNV",obs_title="Observations (Cells)",
+                    ref_title="References (Cells)", output_format="png", output_filename="infercnv.grpF")
INFO [2019-12-23 06:25:06] ::plot_cnv:Start
INFO [2019-12-23 06:25:06] ::plot_cnv:Current data dimensions (r,c)=9968,2728 Total=27420959.5974631 Min=0.17894579059261 Max=8.56586175836465.
INFO [2019-12-23 06:25:06] ::plot_cnv:Depending on the size of the matrix this may take a moment.
INFO [2019-12-23 06:25:07] plot_cnv_observation:Start
INFO [2019-12-23 06:25:07] Observation data size: Cells= 2258 Genes= 9968
INFO [2019-12-23 06:25:07] clustering observations via method: ward.D
ERROR [2019-12-23 06:25:07] Unexpected error, should not happen.
Error in .plot_cnv_observations(infercnv_obj = infercnv_obj, obs_data = obs_data,  : 
  Error

![image](https://user-images.githubusercontent.com/31929730/71340459-edfc3280-2524-11ea-8902-faf4b67e45cd.png)

**Comment by GeorgescuC** [comment]
Hi @singletrips ,

This error message should be related to missing subclusters/hclust information for the observations in the object that should have been calculated beforehand. Did you modify manually the infercnv object? If not, could you please provide details on the commands you ran and the state of the infercnv_obj@tumor_subclusters$subclusters ?

Best,
Christophe.

**Comment by Pentayouth** [comment]
Hi @GeorgescuC , I came up with just the same problem.
I ran infercnv on my lab server, copied the output "preliminary.infercnv_obj" from the output folder and pasted it to my pc for cnvplot customization.
The object I loaded on my pc looks like below. I downloaded different "preliminary.infercnv_obj"  from several output folder and got the same error.
![图片](https://user-images.githubusercontent.com/58732746/77140386-65097e80-6ab4-11ea-9db5-28a5db5197b8.png)

**Comment by GeorgescuC** [comment]
Hi @Pentayouth ,

This is most likely related to the version difference as plotting the references now also tries to reload information stored in the object based on the run settings used, but they are missing in the object generated with the older version.

Regards,
Christophe.

**Comment by Pentayouth** [comment]
Update: 
Other way to trigger the exception:
infercnv version: 1.5.0
R version: 4.0.2
**step:1**
```
infercnv_obj <- infercnv::run(infercnv_obj,
                              cutoff=0.01,
                              sd_amplifier=1.25,
                              window_length = 201,
                              cluster_by_groups = F,
                              out_dir="infercnv_0.01_ref_tweak",
                              cluster_references = T,
                              denoise=T,
                              HMM = F)
```
the tool exceutes ok

**step:2**
Using the infercnv_obj generated above, rerun infercnv::run with **k-subclustering**
```
infercnv_obj <- infercnv::run(infercnv_obj,
                              cutoff=0.01,
                              sd_amplifier=1.25,
                              window_length = 201,
                              cluster_by_groups = F,
                              k_obs_groups=10,
                              out_dir="infercnv_0.01_ref_tweak",
                              cluster_references = T,
                              denoise=T,
                              HMM = F)
```
Error happens and the log is:
	```
STEP 14: invert log2(FC) to FC

INFO [2020-08-24 14:09:09] 

	STEP 15: Clustering samples (not defining tumor subclusters)

INFO [2020-08-24 14:09:09] 

	STEP 21: Denoising

INFO [2020-08-24 14:09:30] 

## Making the final infercnv heatmap ##
INFO [2020-08-24 14:09:31] ::plot_cnv:Start
INFO [2020-08-24 14:09:31] ::plot_cnv:Current data dimensions (r,c)=12369,10069 Total=124652614.129272 Min=0.942867235673996 Max=1.17206602078947.
INFO [2020-08-24 14:09:32] ::plot_cnv:Depending on the size of the matrix this may take a moment.
INFO [2020-08-24 14:14:29] plot_cnv(): auto thresholding at: (0.965953 , 1.034047)
INFO [2020-08-24 14:14:32] plot_cnv_observation:Start
INFO [2020-08-24 14:14:32] Observation data size: Cells= 3953 Genes= 12369
INFO [2020-08-24 14:14:33] plot_cnv_observation:Writing observations by grouping.
INFO [2020-08-24 14:16:28] plot_cnv_observation:Writing observation groupings/color.
INFO [2020-08-24 14:16:28] plot_cnv_observation:Done writing observation groupings/color.
INFO [2020-08-24 14:16:28] plot_cnv_observation:Writing observation heatmap thresholds.
INFO [2020-08-24 14:16:28] plot_cnv_observation:Done writing observation heatmap thresholds.
INFO [2020-08-24 14:16:34] Colors for breaks:  #00008B,#24249B,#4848AB,#6D6DBC,#9191CC,#B6B6DD,#DADAEE,#FFFFFF,#EEDADA,#DDB6B6,#CC9191,#BC6D6D,#AB4848,#9B2424,#8B0000
INFO [2020-08-24 14:16:34] Quantiles of plotted data range: 0.965952827962164,1.00020993496306,1.00020993496306,1.00020993496306,1.03404717203784
INFO [2020-08-24 14:16:38] plot_cnv_observations:Writing observation data to infercnv_0.01_ref_tweak/infercnv.observations.txt
INFO [2020-08-24 14:19:00] plot_cnv_references:Start
INFO [2020-08-24 14:19:00] Reference data size: Cells= 6116 Genes= 12369
ERROR [2020-08-24 14:19:01] Unexpected error, should not happen.
Error in .plot_cnv_references(ref_data = ref_data_t, ref_groups = ref_groups,  : 
  Error
```

**Comment by GeorgescuC** [comment]
Hi @Pentayouth ,

Your case seems different because rather than calling only the plot_cnv() method which does not alter the object, you are trying to use a processed infercnv_obj from step 1 as the start for a new run in step 2, which is an invalid use.
When you run `infercnv_obj <- infercnv::run(infercnv_obj)` in step 1, if the method does not error/crash, the content of infercnv_obj in your main workspace will be modified and not suited to use for a different run. What you can do in this case is have your step 1 `infercnv_obj_done1 <- infercnv::run(infercnv_obj)` and step 2 `infercnv_obj_done2 <- infercnv::run(infercnv_obj)` because `infercnv_obj` will not be altered. However, keep in mind that you will have results get overwritten if you use the same output folder for both runs.

Regards,
Christophe.

**Comment by Ijoanito** [comment]
Hi, I also have similar problem here. 
Currently I am using inferCNV version 1.6 on R version 4.0.3.

Here is how I run it:
![image](https://user-images.githubusercontent.com/52953881/100460788-bfa6b000-3102-11eb-8ad4-aabf4603dda9.png)

and it generates error as follow:
![image](https://user-images.githubusercontent.com/52953881/100460829-d2b98000-3102-11eb-8a55-1ef43a3acbf0.png)

In previous post, you mentioned about version difference, but I have updated my R version and inferCNV package before I run my code. Any suggestion on how to fix this issue?

Many thanks in advance!

**Comment by Pentayouth** [comment]
Hello @Ijoanito 
cluster_by_groups=T
will solve the problem

**Comment by Ijoanito** [comment]
@Pentayouth thanks a lot for your help. Adding cluster_by_groups=T solved my problem!

**Comment by Pentayouth** [comment]
Hi @Ijoanito 

I'm glad I helped. 
If you want to use **"cluster_by_groups=T"**, you can try adding **"cluster_references = FALSE"** at the same time. It works well for me, I wonder if it is a universal solution.
If you are willing to have a try and found the workaround works for you too, please let me know, thanks :) 

Wang

**Comment by GeorgescuC** [comment]
Hi, 

If you install the latest version of the infercnv code from the master branch here, the issue should be solved when using cluster_by_groups=F as well. More discussion on the issue is available here https://github.com/broadinstitute/infercnv/issues/267 .

Regards,
Christophe.

**Comment by mmfalco** [comment]
Hi,
I have the same problem at step 14

>    STEP 14: invert log2(FC) to FC 
      INFO [2021-01-20 14:20:40] invert_log2(), computing 2^x
      INFO [2021-01-20 14:20:41] -mirroring for hspike
      INFO [2021-01-20 14:20:41] invert_log2(), computing 2^x
      INFO [2021-01-20 14:21:08] ::plot_cnv:Start
      INFO [2021-01-20 14:21:08] ::plot_cnv:Current data dimensions (r,c)=5499,821 Total=4534796.41366465 Min=0.751023559995516 Max=2.39034979815337.
      INFO [2021-01-20 14:21:08] ::plot_cnv:Depending on the size of the matrix this may take a moment.
      INFO [2021-01-20 14:21:20] plot_cnv(): auto thresholding at: (0.796549 , 1.212363)
      INFO [2021-01-20 14:21:20] plot_cnv_observation:Start
      INFO [2021-01-20 14:21:20] Observation data size: Cells= 549 Genes= 5499
      INFO [2021-01-20 14:21:21] plot_cnv_observation:Writing observations by grouping.
      INFO [2021-01-20 14:21:29] plot_cnv_observation:Writing observation groupings/color.
      INFO [2021-01-20 14:21:29] plot_cnv_observation:Done writing observation groupings/color.
      INFO [2021-01-20 14:21:29] plot_cnv_observation:Writing observation heatmap thresholds.
      INFO [2021-01-20 14:21:29] plot_cnv_observation:Done writing observation heatmap thresholds.
      INFO [2021-01-20 14:21:31] Colors for breaks:  #00008B,#24249B,#4848AB,#6D6DBC,#9191CC,#B6B6DD,#DADAEE,#FFFFFF,#EEDADA,#DDB6B6,#CC9191,#BC6D6D,#AB4848,#9B2424,#8B0000
      INFO [2021-01-20 14:21:31] Quantiles of plotted data range: 0.796549092680811,0.969110092231346,1,1.03209795932326,1.2123629091092
      INFO [2021-01-20 14:21:32] plot_cnv_observations:Writing observation data to results/infercnv_subclusters_subset/infercnv.preliminary.observations.txt
      INFO [2021-01-20 14:21:41] plot_cnv_references:Start
      INFO [2021-01-20 14:21:41] Reference data size: Cells= 272 Genes= 5499
      ERROR [2021-01-20 14:21:41] Unexpected error, should not happen.
      Error in .plot_cnv_references(infercnv_obj = infercnv_obj, ref_data = ref_data_t,  :
        Error         

When running:
```
infercnv_obj = infercnv::run(infercnv_obj,
                             cutoff=0.1,  
                             out_dir="results/infercnv_subclusters",
                             cluster_by_groups=F,   
                             analysis_mode = "subclusters" ,
                             denoise=T,
                             HMM=T,
                             num_threads=40
)
```
I tried to use the package version 1.7 from Bioconductor, but the problem persists.
I also tried to install develop version (which I don't know if it is for a version higher than the 1.7 that you can download as a source in Bioconductor) as you mentioned using:
```
if (!requireNamespace("BiocManager", quietly = TRUE))
     install.packages("BiocManager")
BiocManager::install(version = "devel")
BiocManager::install("infercnv")
```
But I can't install it because it requires R devel version (4.1) which I cannot change because I'm working on a cluster. I tried to install R_4.1 on a conda environment but I can't find the way to do it. Any suggestions? Is any other problem to solve this with ` cluster_by_groups=F,`?

**Comment by GeorgescuC** [comment]
Hi @mmfalco ,

Did you start a fresh run after updating the package? If you rerun using the already existing results, the error may persist from incorrect data in the object being reloaded.

If this is not the issue, could you send me the data you are using for me to debug?

Regards,
Christophe.

**Comment by mmfalco** [comment]
Yes, I tried several times with a new results folder. Sorry, but I can't share the data. Anyway what I did was to label all the reference cells with the same label and set `cluster_by_groups=T`. Then using the output object I recreated the InferCNV plot with [ComplexHeatmap](https://github.com/jokergoo/ComplexHeatmap) package, restoring the known labels.

**Comment by gufranca** [comment]
> Yes, I tried several times with a new results folder. Sorry, but I can't share the data. Anyway what I did was to label all the reference cells with the same label and set `cluster_by_groups=T`. Then using the output object I recreated the InferCNV plot with [ComplexHeatmap](https://github.com/jokergoo/ComplexHeatmap) package, restoring the known labels.

Dear @mmfalco , thanks for your reply. I am having the same issue as well. I am curious how you are generating your own plot using ComplexHeatmap package. Could you provide some guidance? Which output file from inferCNV do you use for that? I wanted to make several changes on the inferCNV heatmap but it's not possible, so I also wanted to make my own customized one. I appreciate any help!
Thanks

**Comment by mmfalco** [comment]
> > Yes, I tried several times with a new results folder. Sorry, but I can't share the data. Anyway what I did was to label all the reference cells with the same label and set `cluster_by_groups=T`. Then using the output object I recreated the InferCNV plot with [ComplexHeatmap](https://github.com/jokergoo/ComplexHeatmap) package, restoring the known labels.
> 
> Dear @mmfalco , thanks for your reply. I am having the same issue as well. I am curious how you are generating your own plot using ComplexHeatmap package. Could you provide some guidance? Which output file from inferCNV do you use for that? I wanted to make several changes on the inferCNV heatmap but it's not possible, so I also wanted to make my own customized one. I appreciate any help!
> Thanks

@gufranca it is a bit complicated, it took me a few days, but is also a good chance to get proficient with the ComplexHeatmap package. You will need mainly to load the `run.final.infercnv_obj` file where in `infercnv_obj@expr.data` you can get the CNV profiles to plot in the heatmap.
It is worth noticing that if you look in the `plot_cnv()` function from inferCNV they do some transformation to the data that you can also try to apply: 
```
  infercnv_obj<-readRDS("/run.final.infercnv_obj")
  imat<-infercnv_obj@expr.data#extract infercnv values
  
  ### filter extreme values (same function as infercnv::plot_cvn())
  x.center = mean(infercnv_obj@expr.data)
  quantiles = quantile(imat[imat != x.center], 
                       c(0.01, 0.99))
  delta = max(abs(c(x.center - quantiles[1], quantiles[2] - 
                      x.center)))
  low_threshold = x.center - delta
  high_threshold = x.center + delta
  x.range = c(low_threshold, high_threshold)
  
  imat[imat < low_threshold] <- low_threshold
  imat[imat > high_threshold] <- high_threshold
  
  col_fun = colorRamp2(c(min(imat), 1, max(imat)), c("#00008b","#ffffff","#8b0000"))#legend customization
  
  rmat<-t(imat[,unlist(infercnv_obj@reference_grouped_cell_indices)])#reference cells
  imat<-t(imat[,infercnv_obj@observation_grouped_cell_indices[[1]]])#cancer cells
  
```

The detected subclusters can be found in `infercnv_obj@tumor_subclusters$subclusters` . I will also recommend you to run the subcluster analysis using the new implementation of the leiden algorithm. To be honest I haven't tried if using the leiden solves the `cluster_by_groups=F` problem, maybe if you try and works you can mention it here so we know the issue is solved.
Maybe this github page is not the best one to discuss about how to use other package, so if you have any other questions about the plotting, ask in their git page.

**Comment by gufranca** [comment]
> > > Yes, I tried several times with a new results folder. Sorry, but I can't share the data. Anyway what I did was to label all the reference cells with the same label and set `cluster_by_groups=T`. Then using the output object I recreated the InferCNV plot with [ComplexHeatmap](https://github.com/jokergoo/ComplexHeatmap) package, restoring the known labels.
> > 
> > 
> > Dear @mmfalco , thanks for your reply. I am having the same issue as well. I am curious how you are generating your own plot using ComplexHeatmap package. Could you provide some guidance? Which output file from inferCNV do you use for that? I wanted to make several changes on the inferCNV heatmap but it's not possible, so I also wanted to make my own customized one. I appreciate any help!
> > Thanks
> 
> @gufranca it is a bit complicated, it took me a few days, but is also a good chance to get proficient with the ComplexHeatmap package. You will need mainly to load the `run.final.infercnv_obj` file where in `infercnv_obj@expr.data` you can get the CNV profiles to plot in the heatmap.
> It is worth noticing that if you look in the `plot_cnv()` function from inferCNV they do some transformation to the data that you can also try to apply:
> 
> ```
>   infercnv_obj<-readRDS("/run.final.infercnv_obj")
>   imat<-infercnv_obj@expr.data#extract infercnv values
>   
>   ### filter extreme values (same function as infercnv::plot_cvn())
>   x.center = mean(infercnv_obj@expr.data)
>   quantiles = quantile(imat[imat != x.center], 
>                        c(0.01, 0.99))
>   delta = max(abs(c(x.center - quantiles[1], quantiles[2] - 
>                       x.center)))
>   low_threshold = x.center - delta
>   high_threshold = x.center + delta
>   x.range = c(low_threshold, high_threshold)
>   
>   imat[imat < low_threshold] <- low_threshold
>   imat[imat > high_threshold] <- high_threshold
>   
>   col_fun = colorRamp2(c(min(imat), 1, max(imat)), c("#00008b","#ffffff","#8b0000"))#legend customization
>   
>   rmat<-t(imat[,unlist(infercnv_obj@reference_grouped_cell_indices)])#reference cells
>   imat<-t(imat[,infercnv_obj@observation_grouped_cell_indices[[1]]])#cancer cells
>   
> ```
> 
> The detected subclusters can be found in `infercnv_obj@tumor_subclusters$subclusters` . I will also recommend you to run the subcluster analysis using the new implementation of the leiden algorithm. To be honest I haven't tried if using the leiden solves the `cluster_by_groups=F` problem, maybe if you try and works you can mention it here so we know the issue is solved.
> Maybe this github page is not the best one to discuss about how to use other package, so if you have any other questions about the plotting, ask in their git page.

thanks a lot @mmfalco . That helps a lot. I find inferCNV really useful and powerful, but I am struggling with plotting customizations. I will try your suggestions. It would be extremely helpful to many people if you could share somewhere else some of the tricks you used for heatmap plotting!

**Comment by GeorgescuC** [comment]
Hi @gufranca @mmfalco ,

You can also maybe give a try to the NG-CHM interactive heatmaps for which provide an additional infercnv package to link to. The documentation on how to set it up is on the wiki https://github.com/broadinstitute/infercnv/wiki/Next-Generation-Clustered-Heat-Map

Regards,
Christophe.
