### ISSUE TITLE
How to merger infercnv object? 

### ISSUE THREAD

**Issue by singletrips** [broadinstitute/infercnv#207]
I run infercnv separately for each patient using the same reference genome and cells. After that, I need to merger the infercnv objects. Is there any built-in function I can use?  Thanks!

**Comment by GeorgescuC** [comment]
Hi @singletrips , 

There is currently no method to do so. One of the reasons is that after filtering, a significant portion of the genes (the ones with no expression) are removed from the analysis, and this may vary from run to run (mostly based on cell types).

Best,
Christophe.

**Comment by apal6** [comment]
Hi Christophe,

Has there been an update on this as I have also ran infercnv on samples individually and now want to look at as a combined plot. 

Thank you,
Aastha
