### ISSUE TITLE
How can I find the region information?

### ISSUE THREAD

**Issue by ziyangliu93** [broadinstitute/infercnv#210]
Thank you for all your commitments to this wonderful tool. I ran infercnv on my 10x data and it produced a fancy heatmap showing the inferred CNV profile for each cell across whole genome. I also have WES of the same sample and Sequenza was applied to call CNV on it. I tried to use CNV results from Sequenza to validate the inferred results. Sequenza output a segmented.txt in which the genomic regions and corresponding CNV states are recorded. It means that I can use this file to manually plot the CNV status. But for the inferred CNV results, I don't know where to get the region info and the corresponding CNV values of it. AKA, supposed I observed a sharp red band on chromosome 6 from the heatmap, how can I know the genome coordinates of this band?

**Comment by GeorgescuC** [comment]
Hi @ziyangliu93 ,

If you want to use the HMM predictions, the regions are defined in the `17_HMM_predHMMi6.*.pred_cnv_regions.dat` file with coordinates, HMM state (1 = 2 copies loss, 2 = 1 copy loss, 3 = neutral, 4 = 1 copy gain, 5 = 2 copies gain, 6 = 3+ copies gain), and subcluster id (`17_HMM_predHMMi6.*.cell_groupings` gives the subclusters to cells information).

If you want to use the residual expression, you can use the `infercnv.observations.txt` matrix (or `infercnv_obj@expr.data[, unlist(infercnv_obj@observation_grouped_cell_indices)]`) and filter or calculate metrics based on the criteria you choose.

As for plotting the WES directly on to the infercnv figure, I actually have some non-generalized code to do that, but I need to go through it to make it a proper modular method when I have some time.

Regards,
Christophe.

**Comment by living1069** [comment]
@GeorgescuC     HMM is too slow, when I disable it ， will it output the CNV region or genes? Thanks!
