### ISSUE TITLE
Finding inferCNV clusters in the seurat object

### ISSUE THREAD

**Issue by pbrazda** [broadinstitute/infercnv#212]
Hi, 

I am trying to cluster my sets of cells based on CNV to identify the ones with 'abnormal' features and separate the from the 'normals'. I have a reference population in the infercnv_object and I picked k_obs_groups = 2 to separate abnormal vs normal

``infercnv_run = infercnv::run(infercnv_subset,
                                cutoff=0.1, 
                                out_dir="CNV_output", 
                                analysis_mode="subclusters",
                                cluster_by_groups=F,
                                plot_steps=T,
                                denoise=T, 
                                no_prelim_plot=F,
                                k_obs_groups = 2,
                                HMM=T) ``
![templ](https://user-images.githubusercontent.com/14920479/73925287-1f12a580-48ce-11ea-88c1-9ab41107fbd5.png)

I fed it back to the original seurat_object. I can plot the changes per chromosome, etc. The question is **where do I find the k=2 divisions (yellow vs green) **within the seurat meta.data**.** I want to subset the infercnv-identified abnormal cells (yellow, upper cluster) from the seurat_object. 

Any tips for this?

Thank you!

**Comment by pbrazda** [comment]
Maybe if I add "_Dendrogram Group"_ "_Dendrogram Color_" from
 **infercnv.observation_groupings.txt**
 to
**map_metadata_from_infercnv.txt** ?

**Comment by GeorgescuC** [comment]
Hi @pbrazda ,

You are correct that the information about the split (green vs yellow) is stored as "Dendrogram Group" "Dendrogram Color" from **infercnv.observation_groupings.txt** . The reason why the cell count is different between this file and **map_metadata_from_infercnv.txt** is that the later also includes the reference cells.

As for selecting the correct group, they are written from bottom to top in the observation_groupings text file compared to the figure. You can also use the color code to identify it. In this case the yellow should be `#FFED6F` as you can verify here: https://www.color-hex.com/color/ffed6f

Best,
Christophe.

**Comment by pbrazda** [comment]
Thank you! The cell count difference makes sense now :)

 Could you also tell me where to find the k=2 divisions (yellow vs green) within the (infercnv-loaded) seurat meta.data, to do the subsetting there?

**Comment by GeorgescuC** [comment]
Hi @pbrazda ,

The k=2 division information is only calculated "on the fly" when plotting so it can easily be changed to a different value. Since it is deterministic once the clustering (saved within the object) has been done, you can get the information from the final infercnv object by running this:
```R
obs_hcl <- infercnv_obj@tumor_subclusters$hc[["all_observations"]]
split_groups <- cutree(obs_hcl, k=2)
```

If you then want to sort it as in the figure, add the following:
```R
ordered_names <- obs_hcl$labels[obs_hcl$order]
split_groups <- split_groups[ordered_names]
```

I will see to add some helper method to export it in the seurat object.

Best,
Christophe.

**Comment by pbrazda** [comment]
That solved it. Thanks!
