### ISSUE TITLE
ERROR in hspike 

### ISSUE THREAD

**Issue by dreammxy** [broadinstitute/infercnv#213]
infer_obj <- CreateInfercnvObject(raw_counts_matrix = mat,gene_order_file = gene_order_file,annotations_file = annotation_file ,ref_group_names = NULL,delim = "\t") 
#HMM type used default
infercnv_obj <- infercnv::run(infercnv_obj = infer_obj,cutoff = 0.1,out_dir = out_dir,cluster_by_groups = T,denoise = T,HMM = T ) 
#step1 01_incoming_data.infercnv_obj
#step2 02_reduced_by_cutoff.infercnv_obj
#step3: normalization by sequencing depth

INFO [2020-02-11 20:58:13] normalizing counts matrix by depth
INFO [2020-02-11 20:58:15] Computed total sum normalization factor as median libsize: 22590.000000
INFO [2020-02-11 20:58:15] Adding h-spike
INFO [2020-02-11 20:58:15] -no normals defined, using all observation cells as proxy
INFO [2020-02-11 20:58:15] -hspike modeling of normalsToUse
(Error in nls(y ~ .logistic_midpt_slope(x, midpt = x0, slope = k), data = df, : 循环次数超过了50这个最大值
), couldn't fit logistic, but no worries, going to use a spline
Error in smooth.spline(x, mean_p0_table$p0) : 
  missing or infinite values in inputs are not allowed#Error in smooth.spline(x, mean_p0_table$p0) : missing or infinite values in inputs are not allowed

**Comment by GeorgescuC** [comment]
Hi @dreammxy ,

Have you verified that your input matrix does not contain any incorrect/missing values?

You can check by running:
```
any(is.null(infer_obj@expr.data) | is.na(infer_obj@expr.data) | is.infinite(infer_obj@expr.data))
any(is.null(infer_obj@count.data) | is.na(infer_obj@count.data) | is.infinite(infer_obj@count.data))
```

Regards,
Christophe.

**Comment by Zifeng1995** [comment]
I was facing the same problem，and I checked the input matrix.

```
> any(is.null(infercnv_obj@expr.data) | is.na(infercnv_obj@expr.data) | is.infinite(infercnv_obj@expr.data))
[1] FALSE
> any(is.null(infercnv_obj@count.data) | is.na(infercnv_obj@count.data) | is.infinite(infercnv_obj@count.data))
[1] FALSE
```
how can I deal with this situation?

> Hi @dreammxy ,
> 
> Have you verified that your input matrix does not contain any incorrect/missing values?
> 
> You can check by running:
> 
> ```
> any(is.null(infer_obj@expr.data) | is.na(infer_obj@expr.data) | is.infinite(infer_obj@expr.data))
> any(is.null(infer_obj@count.data) | is.na(infer_obj@count.data) | is.infinite(infer_obj@count.data))
> ```
> 
> Regards,
> Christophe.

**Comment by AForsthuber** [comment]
I would be curious what finally solved the problem ???
I am facing the the same error message, however only when I subgroup my ref_group_names= c() into more than two groups. At least with two subgroups it works but not not with a grouping into 9 subgroups of my reference sample.

INFO [2021-03-01 20:28:30] -hspike modeling of Fibroblasts
(Error in nls(y ~ .logistic_midpt_slope(x, midpt = x0, slope = k), data = df, : singular gradient
), couldn't fit logistic, but no worries, going to use a spline



Regards, Agnes

**Comment by GeorgescuC** [comment]
Hi @dreammxy @Zifeng1995 @Aforsthuber ,

Which version of infercnv are you using?

How big are each of the reference groups when you make them into more than 2 groups?

@Aforsthuber do you get any other error after the one you posted? This one is not fatal as it falls back to spline(), so unless you get the 2nd error as the first message in the thread, things should still run properly.

Regards,
Christophe.

**Comment by AForsthuber** [comment]
Hi Christophe!

Thanks for your reply. It finally worked with using a spline, it just took quite a while. At the end I used 6 subgroups in my reference sample with a cell number between 94 and 780 cells per group. I got the error message for each subgroup so I guess the number of cells was too low.
Anyway the results I got at the end seem confident to me.

Thanks, Agnes

**Comment by mailmrcai** [comment]
I solved this bug by filtering out the cluster classification named NA in annotations_file
