### ISSUE TITLE
‘observation data size’ become much fewer than cells I input since STEP 15

### ISSUE THREAD

**Issue by Pentayouth** [broadinstitute/infercnv#219]
**Dear inferCNV collaborators and users:
When doing infercnv::run with default parameters, I notice:**
++++
	STEP 02: Removing lowly expressed genes

INFO [2020-03-17 23:04:22] ::above_min_mean_expr_cutoff:Start
INFO [2020-03-17 23:04:22] Removing 19144 genes from matrix as below mean expr threshold: 0.1
INFO [2020-03-17 23:04:22] validating infercnv_obj
INFO [2020-03-17 23:04:22] **There are 2793 genes and 345 cells remaining in the expr matrix**.
INFO [2020-03-17 23:04:22] Removed 1 genes having fewer than 3 min cells per gene = 0.0358038 % genes removed here
INFO [2020-03-17 23:04:22] validating infercnv_obj
INFO [2020-03-17 23:04:22] 
++++
**and 345 is exactly the number of cells I input.
but when it runs STEP 15, I notice:**
++++
	STEP 15: Clustering samples (not defining tumor subclusters)

INFO [2020-03-17 23:04:40] define_signif_tumor_subclusters(p_val=0.1
INFO [2020-03-17 23:04:40] define_signif_tumor_subclusters(), tumor: all_observations
INFO [2020-03-17 23:04:40] cut tree into: 1 groups
INFO [2020-03-17 23:04:40] -processing all_observations,all_observations_s1
INFO [2020-03-17 23:04:40] define_signif_tumor_subclusters(), tumor: all_references
INFO [2020-03-17 23:04:41] cut tree into: 1 groups
INFO [2020-03-17 23:04:41] -processing all_references,all_references_s1
INFO [2020-03-17 23:04:43] ::plot_cnv:Start
INFO [2020-03-17 23:04:43] ::plot_cnv:Current data dimensions (r,c)=2792,345 Total=963912.048879127 Min=0.813909993822362 Max=1.39430587100808.
INFO [2020-03-17 23:04:43] ::plot_cnv:Depending on the size of the matrix this may take a moment.
INFO [2020-03-17 23:04:44] plot_cnv(): auto thresholding at: (0.894142 , 1.107254)
INFO [2020-03-17 23:04:44] plot_cnv_observation:Start
INFO [2020-03-17 23:04:44] **Observation data size: Cells= 12 Genes= 2792**
INFO [2020-03-17 23:04:44] clustering observations via method: ward.D
INFO [2020-03-17 23:04:44] plot_cnv_observation:Writing observations by grouping.
INFO [2020-03-17 23:04:44] plot_cnv_observation:Writing observation groupings/color.
INFO [2020-03-17 23:04:44] Colors for breaks:  #00008B,#24249B,#4848AB,#6D6DBC,#9191CC,#B6B6DD,#DADAEE,#FFFFFF,#EEDADA,#DDB6B6,#CC9191,#BC6D6D,#AB4848,#9B2424,#8B0000
INFO [2020-03-17 23:04:44] Quantiles of plotted data range: 0.894141850160842,0.969821112744031,0.997974381506962,1.02841156966441,1.10725354222138
INFO [2020-03-17 23:04:44] plot_cnv_references:Writing observation data to P2_inferCNV/infercnv.preliminary.observations.txt
INFO [2020-03-17 23:04:44] plot_cnv_references:Start
INFO [2020-03-17 23:04:44] Reference data size: Cells= 333 Genes= 2792
INFO [2020-03-17 23:04:46] plot_cnv_references:Number reference groups= 1
INFO [2020-03-17 23:04:46] plot_cnv_references:Plotting heatmap.
INFO [2020-03-17 23:04:46] Colors for breaks:  #00008B,#24249B,#4848AB,#6D6DBC,#9191CC,#B6B6DD,#DADAEE,#FFFFFF,#EEDADA,#DDB6B6,#CC9191,#BC6D6D,#AB4848,#9B2424,#8B0000
INFO [2020-03-17 23:04:46] Quantiles of plotted data range: 0.894141850160842,0.975879742736665,0.997942948372816,1.0222404920104,1.10725354222138
INFO [2020-03-17 23:04:46] plot_cnv_references:Writing reference data to P2_inferCNV/infercnv.preliminary.references.txt
INFO [2020-03-17 23:04:47] 
++++
**The observation data size changes to 12, which confused me a lot. Also I get a 'infercnv.observations.txt' output with only 12 observations in it.**
![and the infercnv plot looks strange](https://user-images.githubusercontent.com/58732746/76883642-746fa880-68b7-11ea-97e3-20a73a29f8c4.png)

**I wonder why almost all the cells were dicarded with only a few remain? Any comments or help at your earliest convenience will be highly appreciated.**

**Comment by GeorgescuC** [comment]
Hi @Pentayouth ,

What you see is due to which cells you defined as reference cells ("ref_group_names" argument in `CreateInfercnvObject`). You do have 345 cells in total, but 333 are defined as references, so only 12 are left as observations. You can check the lines you highlighted, plus the line about the reference data size:

INFO [2020-03-17 23:04:22] There are 2793 genes and 345 cells remaining in the expr matrix.
INFO [2020-03-17 23:04:44] Observation data size: Cells= 12 Genes= 2792
INFO [2020-03-17 23:04:44] Reference data size: Cells= 333 Genes= 2792

In addition, I see that you have very few genes kept:
INFO [2020-03-17 23:04:22] Removing 19144 genes from matrix as below mean expr threshold: 0.1

What kind of data are you using? And is it a raw counts matrix?

Regards,
Christophe.

**Comment by Pentayouth** [comment]
Thanks GeorgescuC for your kindly help!
