### ISSUE TITLE
Error: None of the genes in the expression data matched the genes in the reference genomic position file. 

### ISSUE THREAD

**Issue by kysbbubbu** [broadinstitute/inferCNV#22]
Hello!

Thank you for developing wonderful and unique tools for inferring CNV from single cell RNA seq data.

Although all gene names are matched in my expression file and gene position file, 
the below  error persistently occurred in my computer.

<my order>
./inferCNV.R --max_centered_expression 3 --noise_filter 0.3 --output_dir /media/sf_csvfiles/CNVmerge --vis_bound_threshold ' -1,1' /media/sf_csvfiles/F0CNV.txt /media/sf_csvfiles/gtf.txt

<terminal>
2018-05-05 22:01:50 INFO::::order_reduce:Start.
2018-05-05 22:01:50 INFO::::infer_cnv:order_reduce:The position file  and the expression file row (gene) names do not match.
Error: None of the genes in the expression data matched the genes in the reference genomic position file. Analysis Stopped.
Execution halted

Do you have any solution for this?

Below things are my genome position file and expression file example 
(because expression file is too long and big I presented some part of it )

<my genome position file>
[gtf.txt](https://github.com/broadinstitute/inferCNV/files/1976682/gtf.txt)

<my expression file>
![image](https://user-images.githubusercontent.com/38550028/39663581-a9d0ade2-50b0-11e8-8a56-58e913c55f25.png)

**Comment by GeorgescuC** [comment]
Hi @kysbbubbu ,

Is the file F0CNV.txt using tab as the delimiter? If not, you can use the "--delim" option to specify the delimiter you are using.

Regards,
Christophe.

**Comment by GeorgescuC** [comment]
Hi @kysbbubbu 

If you send me the data privately by email (I will not share it), I can look into why the error happens. You can send it to <cgeorges@broadinstitute.org> .

Regards,
Christophe.

**Comment by kysbbubbu** [comment]
Hi @Puriney @GergescuC

Thanks !! Problem solved!
My row names of expression file and row names of genome location files were matched but not same order. It will be better to modify wiki of "infer CNV" 

Gene names in the expression matrix should match **and be in the same order with**  gene names in the genomic positions file.

Thank you

Kim

**Comment by komalsrathi** [comment]
In the examples folder, the gene names are not in the same order for the expression and genomic coordinates. I just ran this without matching the order and it worked fine for me.
