### ISSUE TITLE
Error in rownames when validating infercnv object

### ISSUE THREAD

**Issue by dstueckm** [broadinstitute/infercnv#223]
I am able to successfully create an InferCNV object, but I'm running into an issue with Step 03, the validation of the InferCNV object.
There error that is thrown is:

ERROR [2020-04-08 17:34:17] hmm.... rownames(infercnv_obj@expr.data != rownames(infercnv_obj@gene_order))
ERROR [2020-04-08 17:34:17] The following genes are in @gene_order and not infercnv_obj@expr.data: gene_1,gene_2,gene_3,gene_4,gene_5,gene_6,gene_7,gene_8,gene_9,gene_10...gene_7181

Essentially saying none of the gene names present in gene_order are present in expr.data.

I tried to check this manually, and the names seem to match perfectly. Do you have any idea what might be causing this? My validation is below.

> nrow(infercnv_obj@gene_order)
[1] 21258
> nrow(infercnv_obj@expr.data)
[1] 21258
> rownames(infercnv_obj@gene_order) == rownames(infercnv_obj@expr.data)
[1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE ...
> unique(rownames(infercnv_obj@gene_order) == rownames(infercnv_obj@expr.data))
[1] TRUE

**Comment by dstueckm** [comment]
Managed to solve the issue.
I was passing a numeric vector (of cluster numbers) as my ref_group_names in CreateInferCnvObject().
For some reason, this introduces NAs in infercnv_obj@reference_grouped_cell_indices, and throws a row name error.

**Comment by liangxs7015** [comment]
So how did you solve this problem? by turning ref_group_names to character?
