### ISSUE TITLE
Ways to export the average of inferCNV observation among cells in observation group

### ISSUE THREAD

**Issue by kysbbubbu** [broadinstitute/infercnv#224]
Hello, thanks for developing such nice tool to infer single-cell CNV profiles 

For the reliability inferred single-cell CNV data,  I would like to confirm the concordance between average observation of inferCNV result and CNV inferred from DNA whole exome sequencing. 
To address this problem, is there way to export the average of inferCNV observation among cells in observation group?

Thank you.

**Comment by GeorgescuC** [comment]
Hi @kysbbubbu ,

There is no direct way of exporting that value, but you can calculate it from the final infercnv_obj. 

The `infercnv_obj@expr.data` slot contains the matrix with the values.
The observation cell indices (columns in the matrix) are stored in `infercnv_obj@tumor_subclusters$subclusters` , where you can retrieve them by subcluster or all at once depending on which cells you want to calculate the average for.

Regards,
Christophe.
