### ISSUE TITLE
Error: Running HMM-based CNV prediction on cell level

### ISSUE THREAD

**Issue by mjprzybilla** [broadinstitute/infercnv#226]
Hi guys, 
I was wondering if you could help me with an issue I am facing. 
When running the code below, I get an error, which is related to the specification of the HMM report mode:

```
# perform infercnv operations
infercnv_obj = infercnv::run(infercnv_obj,
                             cutoff= 0.1, 
                             window_length = 201, 
                             out_dir= o.dir,  
                             cluster_by_groups=TRUE,   
                             plot_steps=F,
                             denoise=T,
                             sd_amplifier=1.6, 
                             HMM=T,
                             analysis_mode = "cells",
                             HMM_report_by = "cell")

# ERROR MESSAGE

	STEP 17: HMM-based CNV prediction

INFO [2020-04-12 15:03:36] predict_CNV_via_HMM_on_indiv_cells()
Error in match.arg(by) : 
  'arg' should be one of “consensus”, “subcluster”, “cell”
Calls: <Anonymous> ... generate_cnv_region_reports -> get_predicted_CNV_regions -> match.arg
Execution halted
```
As that the option ` HMM_report_by = c("subcluster", "consensus", "cell")` is specified in the description of the `infercnv::run` function, I am wondering what is going wrong here...in general, setting it to "subcluster" or "consensus" works without problems. Would greatly appreciate your help!

Many thanks, 
Moritz

**Comment by GeorgescuC** [comment]
Hi @mjprzybilla ,

Which version of infercnv are you using?

Regards,
Christophe.

**Comment by mjprzybilla** [comment]
Thanks for your quick reply Christophe! 
I am currently using `1.2.2`. The newest version is `1.3.3`, right? 

Many thanks, 
Moritz

**Comment by GeorgescuC** [comment]
Hi @mjprzybilla ,

`1.2.2` is the version I would have expected to have an effect on this issue. The current newest version is `1.3.6`, and when I run `analysis_mode = "cells"` and `HMM_report_by = "cell"` on the example data, it runs fine for me.

Could you try running the example with those settings or updating to the devel version?

Regards,
Christophe.

**Comment by mjprzybilla** [comment]
Thanks Christophe! Is it right, that version `1.3.6` relies on ´R/4.0.0` already? I'll try to update to the current version of `inferCNV` and see how it goes! 

Many thanks!
