### ISSUE TITLE
how to extract the cnv levels to plot the boxplot for each sample?

### ISSUE THREAD

**Issue by honghh2018** [broadinstitute/infercnv#228]
Hi guys,
    inferCNV have run over from my sample using all clusters, using HMM model.
     I want to draw picture like below:
![image](https://user-images.githubusercontent.com/41668708/79424289-7f227800-7ff2-11ea-9a69-bb016f4c627a.png)
     how can i do for the output result of inferCNV to draw plot like that?
     Thanks for any advices or tip.
      Thanks

**Comment by GeorgescuC** [comment]
Hi @honghh2018 ,

This figure is not generated by infercnv itself, but it may be using its results. This figure looks like it is from a paper, do they not explain in the methods/supplement how this figure was generated?

Regards,
Christophe.

**Comment by honghh2018** [comment]
The paper was 'Single-cell RNA-seq highlights intra-tumoral heterogeneity and malignant progression in pancreatic ductal adenocarcinoma'.
The CNV score generated by below method:
CNV estimation
Initial CNVs for each region were estimated by inferCNV R
package.20 The CNV of total cell types were calculated by
expression level from single-cell sequencing data for each cell
with –cutoff 0 and –noise_filter 0.2. For each sample, gene
expression of cells was re-standardized and values were limited
as −1 to 1. The CNV score of each cell was calculated as quadratic
sum of CNV region.
![image](https://user-images.githubusercontent.com/41668708/79545233-f1628d80-80c2-11ea-899e-7c8ff1e4d013.png)
It was confused that how to use the output's result of inferCNV to create the CNV scores on this method.
 The 'map_metadata_from_infercnv.txt' file or another ?
  Any advices would be appreciated

**Comment by GeorgescuC** [comment]
Hi @honghh2018 ,

The `map_metadata_from_infercnv.txt` file contains the HMM assignments which are discrete states, whereas the paper you mention uses the default results with continuous values.
The way they seem to be doing it is to take the final results (`infercnv_obj@expr.data` field in the final object that can be reloaded from `run.final.infercnv_obj`), scale it to [-1;1] while keeping the center at 0, and then calculate the sum of squared values (which has the effect of grouping deletions and duplications together).
The thing to keep in mind when doing this, is that if there are double deletion or double duplication, a single dupl/del will have a score around 0.5/-0.5, which once squared is only 0.25, vs a squared score of 1 for a doube dupl/del.

Regards,
Christophe.

**Comment by YiweiNiu** [comment]
Hello, sorry to interrupt this thread. I also want get the overall CNV level of individual cell.

@GeorgescuC I have one question about values in `infercnv_obj@expr.data`: if the value is larger than 1, does it mean 'CNV gain'? and if the value is smaller than 1, does it mean 'CNV loss'?

My second question is related the method mentioned by @honghh2018. Is it appropriate to scale data to range [-1, 1] and calculate the sum of squared values?

Any comments and suggestions would be appreciated.

Bests,
Yiwei Niu

**Comment by GeorgescuC** [comment]
Hi @YiweiNiu ,

If the values differ from 1, they will tend to show gain/loss in the directions you said yes. However, depending on the denoising settings/level you used, there can still be non-1 values that are just noise/tails of the base level expression distribution. You should look at the distribution of the values to determine whether there are peaks distinct from the base distribution or not.

If you want to scale the data, you should be careful of the same thing. If your data has no cases of loss CNV, your -1 would just be amplified noise. You should also be careful of the max number of CNV, as it could be either 1 or 2 gain/loss.
As for the sum of squared values, the same comment I made at the end of my last message still applies.

Regards,
Christophe.

**Comment by YiweiNiu** [comment]
Hi @GeorgescuC ,

Thank you very much for your prompt reply!

> You should look at the distribution of the values to determine whether there are peaks distinct from the base distribution or not.

Could you please explain more about this? There are many cells in both reference and potential tumor groups, 

> If you want to scale the data, you should be careful of the same thing. If your data has no cases of loss CNV, your -1 would just be amplified noise. You should also be careful of the max number of CNV, as it could be either 1 or 2 gain/loss.

Maybe it is not a good idea to scale data into [-1, 1]. And do you have any suggestions to get the overall CNV levels of each cell (i.e. to generate plots like the paper above)?

Thank you again for time and comments!

Bests,
Yiwei Niu

**Comment by GeorgescuC** [comment]
Hi @YiweiNiu ,

For the different distributions, you can see the theory behind it in the wiki explanation of the HMM modeling https://github.com/broadinstitute/inferCNV/wiki/infercnv-i6-HMM-type#calibrating-cnvs-residual-intensity-distributions-via-the-hspike .

To get the overall CNV levels, you can try using the HMM prediction which will define genomic regions where CNVs are and assign them specific fold changes. 

Regards,
Christophe.

**Comment by crystal0721** [comment]
hi@YiweiNiu ,
   I also want get the overall CNV level of individual cell. I want to ask  have you  scale  the data into [-1,1]. It is may be not appropriate to scale data to range [-1, 1] because  the values is differ from 1( if the value is larger than 1, it means 'CNV gain', and if the value is smaller than 1, it means 'CNV loss).
  I want to know how to get the overall CNV levels of each cell ，it is  appropriate  to  get  the  CNV score of each cell  to calculated the  quadratic sum of CNV region directly  without re-standardized.  Thanks  for your apply.

**Comment by YiweiNiu** [comment]
Hi @GeorgescuC ,

Thank you for your reply!

> To get the overall CNV levels, you can try using the HMM prediction which will define genomic regions where CNVs are and assign them specific fold changes.

If I understand correctly, the overall CNV levels of each cell could be extracted from file "17_HMM_predHMMi6.hmm_mode-samples.infercnv_obj" (**infercnv version**: 1.2.1)?

Considering that the final values (`infercnv_obj@expr.data` of `run.final.infercnv_obj`) are centered by 1, could I just use `abs(infercnv_obj@expr.data - 1)` as the CNV level? Maybe this values are better in terms of representing CNV levels than the discrete states in `17_HMM_predHMMi6.hmm_mode-samples.infercnv_obj`?

@crystal0721 Sorry for the late reply. I am still seeking for answers.

Bests,
Yiwei

**Comment by crystal0721** [comment]
#

**Comment by crystal0721** [comment]
hi @YiweiNiu , 
      Thanks for your apply.   I  got  the  results  as follows： First   scaled the  infercnv_obj@expr.data  of  run.final.infercnv_obj to [-1,1], and calculated  the  quadratic sum of  CNV  regions ,and the cell sore is the sum of all CNV  regions.  The 
 file  of   'HMM_CNV_predictions.HMMi6.hmm_mode-samples.Pnorm_0.5.pred_cnv_genes.dat'   have the  CNV region and related  genes.    Hope to help you and   provide advice.

**Comment by GeorgescuC** [comment]
Hi @YiweiNiu ,

Yes, you can extract the overcall CNV levels predicted by the HMM from "17_HMM_predHMMi6.hmm_mode-samples.infercnv_obj".
The HMM model however uses values that are not centered on 1, but 6 states. The meaning of states is listed on the wiki and is: 
    State 1: 0x: complete loss
    State 2: 0.5x: loss of one copy
    State 3: 1x: neutral
    State 4: 1.5x: addition of one copy
    State 5: 2x: addition of two copies
    State 6: 3x: essentially a placeholder for >2x copies but modeled as 3x.
So if you want to calculate the levels you would have to use `(state - 3) /2`, with maybe changing all states 6 (if there are any) to 5 beforehand to be symmetrical. 

Regards,
Christophe

**Comment by honghh2018** [comment]
Hi @guys,
     The Hierarchical Clustering output from the inferCNV showing  the maligant cluster and no-maligant cluster when runing over the inferCNV.
      I saw the file,15_no_subclustering.infercnv_obj, on the output result, so can i extract the maligant cluster and non-maligant cluster basing on file-15_no_subclustering.infercnv_obj. or can any other method do this?
      Any advices would be appreciate.

**Comment by honghh2018** [comment]
supplementary , i want to extract the cell like below picture:
    
![image](https://user-images.githubusercontent.com/41668708/87938248-d724bb00-cac8-11ea-85c8-5b4313d75ed6.png)

**Comment by honghh2018** [comment]
Hi @GeorgescuC,
      i want to  extract the cell that i interest in based on hierarchical clustering using file -infercnv.21_denoised.observations_dendrogram.txt- exported from infercnv::run's result. in this case, how could process the  infercnv.21_denoised.observations_dendrogram.txt with R as inputting it and selected the cell barcode that i want on it.
      Any advice would be appreciated

**Comment by ntbeileh** [comment]
> quadratic sum of CNV regions

hi @crystal0721 
I am also trying to accomplish the same results. 

When scaling the final infercnv_obj@expr.data to [-1,1] then taking the quadratic sum of the CNV regions how are you taking the quadratic sum of the CNV regions? I understand that the CNV regions are listed in the HMM_CNV_predictions.HMMi6.hmm_mode-samples.Pnorm_0.5.pred_cnv_genes.dat file but I don't understand how rescaling the final infercnv object will affect the cnv region values listed in that file. Are you rescaling the HMM states to [-1,1] and then taking the quadratic sum of those states?

Mainly confused about what exactly is being rescaled when you rescale the infercnv_obj@expr.data and what data field to take the quadratic sum of from the HMM_CNV_predictions.HMMi6.hmm_mode-samples.Pnorm_0.5.pred_cnv_genes.dat to take the quadratic sum of the CNV region.

I would appreciate your help on this.
