### ISSUE TITLE
Error in if (runif(1) <= padj) { : missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by DirtyHarry80** [broadinstitute/infercnv#233]
Hi, 
I got an issue when running infercnv in a mode where ***analysis_mode='subclusters'***

infercnv.953pt <- infercnv::run(infercnv.953pt,cutoff=0.1,out_dir="output_cnv_953pt_subclust",
                              cluster_by_groups=T, denoise=T, HMM=T,
                              analysis_mode='subclusters')

Following error occurs:

STEP 03: normalization by sequencing depth

INFO [2020-05-15 09:11:07] normalizing counts matrix by depth
INFO [2020-05-15 09:11:07] Computed total sum normalization factor as median libsize: 10959.144363
INFO [2020-05-15 09:11:07] Adding h-spike
INFO [2020-05-15 09:11:07] -hspike modeling of CAF
(Error in nls(y ~ .logistic_midpt_slope(x, midpt = x0, slope = k), data = df, : singular gradient
), couldn't fit logistic, but no worries, going to use a spline
(Error in nls(y ~ .logistic_midpt_slope(x, midpt = x0, slope = k), data = df, : singular gradient
), couldn't fit logistic, but no worries, going to use a spline
Error in if (runif(1) <= padj) { : missing value where TRUE/FALSE needed

*********
If I remove ***analysis_mode='subclusters'*** infercnv runs normally and I get a result.

Any idea?

**Comment by GeorgescuC** [comment]
Hi @DirtyHarry80 ,

Which version of infercnv are you currently using?

Could you also rerun things after running "options(error = function() traceback(2))" in your R session/script? This should provide us with some more information on how the error occurs.

Regards,
Christophe.

**Comment by kylandra** [comment]
Hi Christophe,
I'm having the same error. I report below the information from the traceback. Hope you can help me!!
Thanks



```
STEP 03: normalization by sequencing depth

INFO [2020-08-05 10:18:36] normalizing counts matrix by depth
INFO [2020-08-05 10:18:39] Computed total sum normalization factor as median libsize: 11571.382213
INFO [2020-08-05 10:18:39] Adding h-spike
INFO [2020-08-05 10:18:39] -hspike modeling of 0
(Error in nls(y ~ .logistic_midpt_slope(x, midpt = x0, slope = k), data = df, : singular gradient
), couldn't fit logistic, but no worries, going to use a spline
(Error in nls(y ~ .logistic_midpt_slope(x, midpt = x0, slope = k), data = df, : singular gradient
), couldn't fit logistic, but no worries, going to use a spline
Error in if (runif(1) <= padj) { : missing value where TRUE/FALSE needed
11: (function ()
    traceback(2))()
10: FUN(X[[i]], ...)
9: lapply(X = X, FUN = FUN, ...)
8: sapply(x, function(y) {
       if (runif(1) <= padj) {
           return(0)
       }
       else {
           return(y)
       }
   })
7: FUN(newX[, i], ...)
6: apply(counts.matrix, 1, function(x) {
       mean.val = mean(x)
       dropout_prob <- predict(dropout_logistic_params$spline, log(mean.val))$y[1]
       nzeros = sum(x == 0)
       ntotal = length(x)
       nremaining = ntotal - nzeros
       padj = ((dropout_prob * ntotal) - (nzeros))/nremaining
       padj = max(padj, 0)
       flog.debug(sprintf("mean.val: %g, dropout_prob: %g, adj_dropout_prob: %g",
           mean.val, dropout_prob, padj))
       x.adj = sapply(x, function(y) {
           if (runif(1) <= padj) {
               return(0)
           }
           else {
               return(y)
           }
       })
       x.adj
   })
5: .apply_dropout(sim_cell_matrix, dropout_logistic_params)
4: .get_simulated_cell_matrix_using_meanvar_trend_helper(gene_means,
       mean_var_table, num_cells, dropout_logistic_params)
3: .get_simulated_cell_matrix_using_meanvar_trend(infercnv_obj,
       hspike_gene_means, num_cells, include.dropout = TRUE)
2: .build_and_add_hspike(infercnv_obj, sim_method = sim_method,
       aggregate_normals = hspike_aggregate_normals)
1: infercnv::run(infercnv_obj, cutoff = 0.1, out_dir = "06.InferCNV/ME7_org_plus_met.Subclones",
       cluster_by_groups = T, analysis_mode = "subclusters", denoise = T,
       HMM = T, num_threads = 8)
```

**Comment by DirtyHarry80** [comment]
Hi Guys,
I updated inferCNV to most recent version and the error is gone. @kylandra can you try that?

**Comment by kylandra** [comment]
Hi @DirtyHarry80,
thanks for the suggestion. Which is the version that solved the problem? infercnv release v1.3.3?
I'm using infercnv v1.2.1
Thanks

**Comment by DirtyHarry80** [comment]
Check on their Wiki and go for the latest release. 
Best regards,
Andrei 

--
Dr. Andrei Turtoi
Institut de Recherche en Cancérologie de Montpellier
Inserm U1194 – Université Montpellier
Tumor Microenvironment and Resistance
to Treatment Lab
208 Avenue des Apothicaires
F-34298 Montpellier Cedex 5, France
Tél: +33.(0)4.67.61.37.46
Fax: +33.(0)4.67.61.23.37
https://ircm.fr/index.php?pagendx=1146r

**Comment by Scathacheng** [comment]
> Hi @DirtyHarry80,
> thanks for the suggestion. Which is the version that solved the problem? infercnv release v1.3.3?
> I'm using infercnv v1.2.1
> Thanks

Hi kylandra,
Did you solve the problem?
it seems that update the infercnv to v1.3.3 needs R v4.0.

**Comment by GeorgescuC** [comment]
Hi @Scathacheng ,

With the number of corrections and improvements made to infercnv since it requires R 4.0, I would suggest upgrading or having a separate installation to be able to use the up to date version. If docker/singularity is an option for you, we also provide an image you can use as a standalone.

Regards,
Christophe.

**Comment by marlaherr** [comment]
Hi Christophe,

I am running into the same issues as described above. I work on R v4.0 and infercnv 1.4.0 which I suppose is the most updated version. 
With debug = TRUE I get this message:
...
DEBUG [2021-05-11 15:00:06] mean.val: 1, dropout_prob: 0, adj_dropout_prob: 0
DEBUG [2021-05-11 15:00:06] mean.val: 1, dropout_prob: 0, adj_dropout_prob: 0
DEBUG [2021-05-11 15:00:06] mean.val: 1, dropout_prob: 0, adj_dropout_prob: 0
DEBUG [2021-05-11 15:00:06] mean.val: 1, dropout_prob: 0, adj_dropout_prob: 0
DEBUG [2021-05-11 15:00:06] mean.val: 1, dropout_prob: 0, adj_dropout_prob: 0
DEBUG [2021-05-11 15:00:06] mean.val: 0, dropout_prob: NaN, adj_dropout_prob: NaN
Error in if (runif(1) <= padj) { : missing value where TRUE/FALSE needed

Do you have any suggestions how to solve this?
Thanks in advance
Best
Marla

**Comment by GeorgescuC** [comment]
Hi @marlaherr ,

At the time of your post, the latest stable version was 1.6.0, but 1.8.0 is now also available. You may however need to update your R to 4.1 and Bioconductor to 3.13 first. Alternatively, you can try using one of the docker images.
Could you please try running infercnv with the latest version and see if it works or the same error still occurs?

Regards,
Christophe.

**Comment by cfustero** [comment]
Hi all, 
I am using infercnv 1.8.0 and I got the same error when running:

```
infercnv_obj = infercnv::run(infercnv_obj,
                             cutoff=1, # cutoff=1 works well for Smart-seq2, and cutoff=0.1 works well for 10x Genomics
                             out_dir= out_dir, 
                             cluster_by_groups=TRUE, 
                             denoise=TRUE,
                             HMM=TRUE)
```

Specifically, this is the error message I get and the traceback: 

```
INFO [2021-09-29 10:32:49] ::process_data:Start
INFO [2021-09-29 10:32:49] Checking for saved results.
INFO [2021-09-29 10:32:49] Trying to reload from step 2
INFO [2021-09-29 10:32:50] Using backup from step 2
INFO [2021-09-29 10:32:50] 

	STEP 1: incoming data

INFO [2021-09-29 10:32:50] 

	STEP 02: Removing lowly expressed genes

INFO [2021-09-29 10:32:50] 

	STEP 03: normalization by sequencing depth

INFO [2021-09-29 10:32:50] normalizing counts matrix by depth
INFO [2021-09-29 10:32:50] Computed total sum normalization factor as median libsize: 1509.799805
INFO [2021-09-29 10:32:50] Adding h-spike
INFO [2021-09-29 10:32:50] -hspike modeling of 0
(Error in nls(y ~ .logistic_midpt_slope(x, midpt = x0, slope = k), data = df, : singular gradient
), couldn't fit logistic, but no worries, going to use a spline
(Error in nls(y ~ .logistic_midpt_slope(x, midpt = x0, slope = k), data = df, : singular gradient
), couldn't fit logistic, but no worries, going to use a spline
Error in if (runif(1) <= padj) { : missing value where TRUE/FALSE needed
11: (function () 
    traceback(2))()
10: FUN(X[[i]], ...)
9: lapply(X = X, FUN = FUN, ...)
8: sapply(x, function(y) {
       if (runif(1) <= padj) {
           return(0)
       }
       else {
           return(y)
       }
   })
7: FUN(newX[, i], ...)
6: apply(counts.matrix, 1, function(x) {
       mean.val = mean(x)
       dropout_prob <- predict(dropout_logistic_params$spline, log(mean.val))$y[1]
       nzeros = sum(x == 0)
       ntotal = length(x)
       nremaining = ntotal - nzeros
       padj = ((dropout_prob * ntotal) - (nzeros))/nremaining
       padj = max(padj, 0)
       flog.debug(sprintf("mean.val: %g, dropout_prob: %g, adj_dropout_prob: %g", 
           mean.val, dropout_prob, padj))
       x.adj = sapply(x, function(y) {
           if (runif(1) <= padj) {
               return(0)
           }
           else {
               return(y)
           }
       })
       x.adj
   })
5: .apply_dropout(sim_cell_matrix, dropout_logistic_params)
4: .get_simulated_cell_matrix_using_meanvar_trend_helper(gene_means, 
       mean_var_table, num_cells, dropout_logistic_params)
3: .get_simulated_cell_matrix_using_meanvar_trend(infercnv_obj, 
       hspike_gene_means, num_cells, include.dropout = TRUE)
2: .build_and_add_hspike(infercnv_obj, sim_method = sim_method, 
       aggregate_normals = hspike_aggregate_normals)
1: infercnv::run(infercnv_obj, cutoff = 1, out_dir = out_dir, cluster_by_groups = TRUE, 
       denoise = TRUE, HMM = TRUE)
```

Any idea on how to fix it? 

Thanks in advance!!

**Comment by GeorgescuC** [comment]
Hi @cfustero ,

Can you try deleting the backup objects (from steps 1 and 2) in the output folder, then run things again to see if the error continues?

Regards,
Christophe.

**Comment by GeorgescuC** [comment]
Hi @cfustero ,

The issue may be related to the size/similarity of one of your groups then. How big is each of them?

Also, since groups are disabled in this case, it might be good to at least enable subclustering instead so that the HMM can produce different predictions for each population of cells.

Regards,
Christophe.
