### ISSUE TITLE
Error: ‘min’ not meaningful for factors in STEP 17

### ISSUE THREAD

**Issue by markutz556** [broadinstitute/infercnv#236]
Hi Teams!

I ran infercnv for my data and I got this error when the program was in step 17. 

        STEP 17: HMM-based CNV prediction

INFO [2020-05-21 14:18:53] predict_CNV_via_HMM_on_whole_tumor_samples
INFO [2020-05-21 14:18:58] -done predicting CNV based on initial tumor subclusters
INFO [2020-05-21 14:19:05] get_predicted_CNV_regions(subcluster)
INFO [2020-05-21 14:19:05] -processing cell_group_name: tumor_FL.tumor_FL_s1, size: 1133
Error in Summary.factor(c(184L, 184L, 393L, 450L, 473L, 501L, 633L, 651L,  :
  ‘min’ not meaningful for factors
Calls: <Anonymous> ... .get_cnv_gene_region_bounds -> do.call -> lapply -> FUN -> Summary.factor
In addition: There were 50 or more warnings (use warnings() to see the first 50)
Execution halted

I'm using the mac catalina os and infercnv version 1.2.2. I've been trying to look into this but no success. Any ideas on what might cause this and how I can solve it can help! Thanks!

Best,

**Comment by GeorgescuC** [comment]
Hi @markutz556 ,

Could you verify the format of the data stored in `infercnv_obj@gene_order` by comparing it with the provided example?

Would you be able to share the data privately with me so I can take a look at what is happening?

Regards,
Christophe.

**Comment by markutz556** [comment]
Sorry for the late reply. We figured out the error. Now we are trying to plot the cmv result using plot_cnv function. We wonder if we can add extra labels when plotting the cnv (like adding columns in the left annotation). Thanks!

Best,

**Comment by GeorgescuC** [comment]
Hi @markutz556 ,

Adding columns in the left annotation is in theory possible, but it involves editing the source code in a few locations (layout grid, defining the contents of the column, plotting the column at the proper step) and there are risks of breaking the layout/margins.

If you are only interested in one of the 2 current columns (or neither), it would be easier to edit the source code to have those display different information (only need to edit the part where defining the contents of the column). The part of the code to edit is the definition of `row_groupings` in `R/inferCNV_heatmap.R:::.plot_cnv_observations`. Just be careful that if you are using the current output as a reference to edit the contents of the columns, they are plotted from bottom to top.

Another approach would be to visualize the results using the [interactive viewer](https://github.com/broadinstitute/infercnv/wiki/Next-Generation-Clustered-Heat-Map) and add columns to that.

Best,
Christophe
