### ISSUE TITLE
How to get initial CNV0 values from inferCNV output without any reference defined

### ISSUE THREAD

**Issue by sumitava1992** [broadinstitute/infercnv#238]
Hi,
First of all thanks for developing this tool for inferring CNV from single-cell RNA seq data. I am new in this field and wanted to do a differentiation between malignant and non-malignant cells based on the initial CNV0 values of all cells.
![Picture1](https://user-images.githubusercontent.com/66620829/84471861-da47b280-aca3-11ea-910f-4b4233d2eac1.png)
Basically I want to do this to first confidently assign cells that are non-malignant, then use them as my reference cells. I looked into the output files generated after the inferCNV run but a bit confused. I tried to calculate the above-mentioned scoring method for cells based on the CNV values within **"infercnv.preliminary.observations.txt"** in the output folder, but the result was not as expected.
Thus it will be a great help if you can explain if there is a way to get that CNV0 matrix from inferCNV output. Also, I will be glad to hear about the relevance of my approach.
Thank you.

**Comment by laillern** [comment]
Hello, I am interested in the same approach, from that same publication. I see the ticket closed but without an answer. Can you please share the info you obtained on how to run this analysis to detect malignant cells from a pool of cells, without having a reference of healthy cells? TIA
