### ISSUE TITLE
need help in argument selection

### ISSUE THREAD

**Issue by UmairSeemab** [broadinstitute/infercnv#244]
Hi, I have combined before and after treatment datasets to run infercnv and I need to differentiate that which value (or gene) is coming from which dataset.  what argument is required to get that ?

**Comment by GeorgescuC** [comment]
Hi @UmairSeemab , 

If you want to distinguish the source of the data or cell types before starting a run, you should provide that information through the [input annotation file as shown on the wiki](https://github.com/broadinstitute/inferCNV/wiki/File-Definitions#sample-annotation-file).

Regards,
Christophe.
