### ISSUE TITLE
‘cuts_color’ is not a slot in class “ngchmLayer”

### ISSUE THREAD

**Issue by AidenSb** [broadinstitute/infercnv#246]
Hi all,
I'm getting this error:
"INFO [2020-07-06 10:58:28] Creating NGCHM as infercnv.ngchm
INFO [2020-07-06 10:58:28] Initializing new NGCHM InferCNV Object.
Error in (function (cl, name, valueClass)  : 
  ‘cuts_color’ is not a slot in class “ngchmLayer”
Calls: ngchm ... Create_NGCHM -> setCutsColor -> setCutsColor -> <Anonymous> "
would you please  help me understand whats wrong?

Thanks

**Comment by brownmp** [comment]
Hello @AidenSb,

Turns out you need to reinstall NGCHMR , use the following in R: 
```R 
devtools::install_github("bmbroom/NGCHMR", ref="master")
```
You can look at the same issue here #66  for reference as well.  Please let me know if this solves your issue!

~ M.Brown
