### ISSUE TITLE
Error in dimnames(x) <- dn 

### ISSUE THREAD

**Issue by XYZ-NCI** [broadinstitute/infercnv#253]
Hi,
Thank you for this wonderful tool. It has been extremely helpful. 
In the past, I have been using the tool with minimal problem. However, there is one recent sample (10x single cell RNAseq) that I constantly ran into this same error message:

Error in dimnames(x) <- dn : 
  length of 'dimnames' [2] not equal to array extent
Calls: <Anonymous> ... <Anonymous> -> removeCNV -> removeCNV -> colnames<-
Execution halted

I suspect it has something to do with the low CNV event detected in this sample but I would like to get your input in this...

Here is the code I used:

infercnv_obj_PNF_CS026099 = infercnv::run(infercnv_obj_PNF_CS026099, 
                                                             cutoff=0.1, 
                                                             out_dir="cluster_by_group_PNF_CS026099", 
                                                             cluster_by_groups=TRUE, 
                                                             denoise=TRUE,
                         HMM=TRUE)

And attached is the .r.out file for your reference.

Thank you very much!
<img width="1820" alt="Screen Shot 2020-08-24 at 11 29 01" src="https://user-images.githubusercontent.com/58857299/91064337-1d57c780-e5fd-11ea-9a57-6955952873f5.png">

**Comment by GeorgescuC** [comment]
Hi @XYZ-NCI ,

The error does look like it is linked to not finding any cnv to remove when doing the filtering (as it only finds 1). A quick workaround for this case should be to disable the Bayesian filtering (as nothing gets filtered out anyway) by adding `BayesMaxPNormal=0` to the options. Which version of infercnv are you using?

Regards,
Christophe.
