### ISSUE TITLE
question in subclustering cells by CNV

### ISSUE THREAD

**Issue by Shawn10312** [broadinstitute/infercnv#254]
Hi,

By setting infercnv::run(analysis_mode='subclusters'), inferCNV can help us to partition cells into groups having consistent patterns of CNV.
But my question is how could I know the specific cells to the related CNV-subclusters, because I want to cluster the cells according to their CNVs. 
Is there any generated file or setted index that could help me accompolish this data analysis goal?

Looking forward to hearing from you.

Best,

**Comment by GeorgescuC** [comment]
Hi @Shawn10312 ,

You can find the information in couple different ways:
- the `infercnv_obj@tumor_subclusters` field contains both the hclust objects ( `$hc` subfield )and the lists of cells ( `$subclusters` subfield).
- for each generated figure there is a matching `*.observations_dendrogram.txt` file that contains the newick strings of the subclusters (displayed from bottom to top on the figure)
- you can interactively select cells with the [NGCHM interactive viewer](https://github.com/broadinstitute/infercnv/wiki/Next-Generation-Clustered-Heat-Map).

Regards,
Christophe.

**Comment by salehsereshki** [comment]
I had the same issue, I finally ended up using a python script to parse and extract cell names for each cluster. I used **ete3** package for importing the Newick format file `.observations_dendrogram.txt` and then I converted the imported tree to a list of clusters, here is my code:


```
from ete3 import Tree
import numpy as np

t = Tree(address)

def get_clusters(t):
    if(t.children[0].is_leaf() or t.children[1].is_leaf()):
        clust_temp = []
        for node in t.traverse("postorder"):
            if (node.is_leaf()):
                clust_temp.append(node.name)
        return clust_temp
    else:
        return [get_clusters(t.children[0]),get_clusters(t.children[1])]

clusters = get_clusters(t)


def get_list_of_clusters(ls):
    clust_ls = []
    if len(ls) > 0 and type(ls[0]) != type([]):
        return [ls]
    else:
        for sub_clus in ls:
            temp_clust = get_list_of_clusters(sub_clus)
            for i in temp_clust:
                clust_ls.append(i)
    return clust_ls


cluster_list = get_list_of_clusters(clusters)

count = 0
cluster_annotation = []
for cluster in cluster_list:
    for i in cluster:
        cluster_annotation.append([i, count])
    count += 1

cluster_annotation = np.asarray(cluster_annotation)

```

The final cluster_annotation object is a 2D array with two columns, first column shows the cell names, and second column shows the cluster number.
