### ISSUE TITLE
Unable to install infercnv package

### ISSUE THREAD

**Issue by nicholascwho** [broadinstitute/infercnv#255]
Hi there, I tried installing the package on R with the command:

install.packages("infercnv")

But this error was returned:
Warning in install.packages :
  package ‘infercnv’ is not available (for R version 4.0.2)

Is there any way I can overcome this?

Thank you

**Comment by GeorgescuC** [comment]
Hi @nicholascwho ,

You can find the information in couple different ways:
- the `infercnv_obj@tumor_subclusters` field contains both the hclust objects ( `$hc` subfield )and the lists of cells ( `$subclusters` subfield).
- for each generated figure there is a matching `*.observations_dendrogram.txt` file that contains the newick strings of the subclusters (displayed from bottom to top on the figure)
- you can interactively select cells with the [NGCHM interactive viewer](https://github.com/broadinstitute/infercnv/wiki/Next-Generation-Clustered-Heat-Map).

Regards,
Christophe.

**Comment by GeorgescuC** [comment]
Hi @nicholascwho ,

Infercnv is not part of CRAN, but of BioConductor, [to install you should run](https://github.com/broadinstitute/infercnv/wiki/Installing-infercnv#option-b-install-infercnv-from-bioconductor-devel-latest-version):

```
if (!requireNamespace("BiocManager", quietly = TRUE))  
     install.packages("BiocManager")  
BiocManager::install("infercnv")
```

Regards,
Christophe.

**Comment by nicholascwho** [comment]
Hi @GeorgescuC 

Thank you for your reply. I have installed the package but when I try to call it with
> library("infercnv")

I get this error:
Error: package or namespace load failed for ‘infercnv’:
 .onLoad failed in loadNamespace() for 'rjags', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/rjags/libs/rjags.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.0/Resources/library/rjags/libs/rjags.so, 10): Library not loaded: /usr/local/lib/libjags.4.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/library/rjags/libs/rjags.so
  Reason: image not found

I have tried installing rjags again but to no avail.

Thank you for your help!

**Comment by rsalatin** [comment]
Hello @GeorgescuC  @nicholascwho,
I am having the exact same issue, I tried also updating R but no results. Please let me know if you come up with anything to solve this problem.

Thank you very much for your help!

**Comment by GeorgescuC** [comment]
Hi @nicholascwho and @rsalatin ,

You need to [install JAGS](/seq/regev_genome_portal/RESOURCES/human/Hg19/hg19.refGene.coding.CDS.nr) on your system, outside of R, for rjags and infercnv to work.

Regards,
Christophe.

**Comment by nicholascwho** [comment]
It works now, thank you!
