### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by rsalatin** [broadinstitute/infercnv#256]
Hello,
I am trying to install the infercnv package... I follow the procedure for the installation and got no error but when I try to load the library I get the following error... not really sure why

Error: package or namespace load failed for ‘infercnv’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/libs/Rcpp.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/libs/Rcpp.so, 6): Symbol not found: _EXTPTR_PTR
  Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/libs/Rcpp.so
  Expected in: /Library/Frameworks/R.framework/Resources/lib/libR.dylib
 in /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/libs/Rcpp.so

Any help will be appreciated!
Thank you!

**Comment by GeorgescuC** [comment]
Hi @rsalatin ,

What method did you use to install infercnv?
Does "library(Rcpp)" work on your system?

Regards,
Christophe.

**Comment by rsalatin** [comment]
Hi @GeorgescuC 
Thank you for the response. 
I have used the recommended method from Bioconductor:

if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("infercnv")

Trying to use the library(Rcpp) gives me the same the same error (copied here)

Error: package or namespace load failed for ‘Rcpp’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/libs/Rcpp.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/libs/Rcpp.so, 6): Symbol not found: _EXTPTR_PTR
  Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/libs/Rcpp.so
  Expected in: /Library/Frameworks/R.framework/Resources/lib/libR.dylib
 in /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/libs/Rcpp.so
In addition: Warning message:
package ‘Rcpp’ was built under R version 4.0.2 

Any help will be appreciated!
Thanks!
Roberto

**Comment by GeorgescuC** [comment]
Hi @rsalatin ,

The issue may be with a mismatch in the version of R you are currently using and the version that installed the library. What does `sessionInfo()` display for you when you are unable to load Rcpp?

Regards,
Christophe.

**Comment by rsalatin** [comment]
Hi @GeorgescuC 
here is the the sessionInfo() output:
R version 4.0.0 (2020-04-24)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):

**Comment by rsalatin** [comment]
Hi @GeorgescuC,
I was able to complete the package installation. Compiling from binaries did the trick for me.

Thanks
Roberto
