### ISSUE TITLE
Crash at STEP15...

### ISSUE THREAD

**Issue by Funkoverload** [broadinstitute/infercnv#257]
Hi, 
I am running infercnv on two very similar sets of tumors/normals. For one set it runs through, and for the other it crashes at STEP15. at this point: 
INFO [2020-09-08 13:31:00] Reference data size: Cells= 1144 Genes= 7952
Error in name_ref_groups %in% infercnv_obj@tumor_subclusters$subclusters :
  object 'infercnv_obj' not found
Any idea what this could be? 

Best,

Nils

Here is the full output after STEP15:

INFO [2020-09-08 13:21:08] define_signif_tumor_subclusters(p_val=0.1
INFO [2020-09-08 13:21:08] define_signif_tumor_subclusters(), tumor: malignant_KUL01
INFO [2020-09-08 13:23:13] cut tree into: 1 groups
INFO [2020-09-08 13:23:13] -processing malignant_KUL01,malignant_KUL01_s1
INFO [2020-09-08 13:23:13] define_signif_tumor_subclusters(), tumor: malignant_KUL19
INFO [2020-09-08 13:23:34] cut tree into: 1 groups
INFO [2020-09-08 13:23:34] -processing malignant_KUL19,malignant_KUL19_s1
INFO [2020-09-08 13:23:34] define_signif_tumor_subclusters(), tumor: malignant_KUL21
INFO [2020-09-08 13:25:19] cut tree into: 1 groups
INFO [2020-09-08 13:25:19] -processing malignant_KUL21,malignant_KUL21_s1
INFO [2020-09-08 13:25:19] define_signif_tumor_subclusters(), tumor: malignant_KUL28
INFO [2020-09-08 13:25:20] cut tree into: 1 groups
INFO [2020-09-08 13:25:20] -processing malignant_KUL28,malignant_KUL28_s1
INFO [2020-09-08 13:25:20] define_signif_tumor_subclusters(), tumor: malignant_KUL30
INFO [2020-09-08 13:25:22] cut tree into: 1 groups
INFO [2020-09-08 13:25:22] -processing malignant_KUL30,malignant_KUL30_s1
INFO [2020-09-08 13:25:22] define_signif_tumor_subclusters(), tumor: malignant_KUL31
INFO [2020-09-08 13:25:36] cut tree into: 1 groups
INFO [2020-09-08 13:25:36] -processing malignant_KUL31,malignant_KUL31_s1
INFO [2020-09-08 13:25:36] define_signif_tumor_subclusters(), tumor: normal
INFO [2020-09-08 13:26:16] cut tree into: 1 groups
INFO [2020-09-08 13:26:16] -processing normal,normal_s1
INFO [2020-09-08 13:27:58] ::plot_cnv:Start
INFO [2020-09-08 13:27:58] ::plot_cnv:Current data dimensions (r,c)=7952,6168 Total=49119450.3403406 Min=0.662226265480494 Max=5.66501703876625.
INFO [2020-09-08 13:27:58] ::plot_cnv:Depending on the size of the matrix this may take a moment.
INFO [2020-09-08 13:29:26] plot_cnv(): auto thresholding at: (0.831336 , 1.171580)
INFO [2020-09-08 13:29:27] plot_cnv_observation:Start
INFO [2020-09-08 13:29:27] Observation data size: Cells= 5024 Genes= 7952
INFO [2020-09-08 13:29:29] plot_cnv_observation:Writing observation groupings/color.
INFO [2020-09-08 13:29:29] plot_cnv_observation:Done writing observation groupings/color.
INFO [2020-09-08 13:29:29] plot_cnv_observation:Writing observation heatmap thresholds.
INFO [2020-09-08 13:29:29] plot_cnv_observation:Done writing observation heatmap thresholds.
INFO [2020-09-08 13:29:40] Colors for breaks:  #00008B,#24249B,#4848AB,#6D6DBC,#9191CC,#B6B6DD,#DADAEE,#FFFFFF,#EEDADA,#DDB6B6,#CC9191,#BC6D6D,#AB4848,#9B2424,#8B0000
INFO [2020-09-08 13:29:40] Quantiles of plotted data range: 0.831336078714037,0.963019052667432,0.998418115427739,1.03600179487616,1.17158002117406
INFO [2020-09-08 13:29:49] plot_cnv_observations:Writing observation data to out4/infercnv.preliminary.observations.txt
INFO [2020-09-08 13:31:00] plot_cnv_references:Start
INFO [2020-09-08 13:31:00] Reference data size: Cells= 1144 Genes= 7952
Error in name_ref_groups %in% infercnv_obj@tumor_subclusters$subclusters :
  object 'infercnv_obj' not found

It is 10X data, with this run command: 
cnv_obj <- infercnv::run(cnv_obj, cutoff=0.1, out_dir="out4", cluster_by_groups=T, denoise=F, HMM=F,num_threads=parallel::detectCores()

**Comment by GeorgescuC** [comment]
Hi @Funkoverload ,

Which version of infercnv are you running?
Could you please run `options(error = function() traceback(2))` in your R session before trying to rerun the command that failed to have more details on where the error occurs?

Regards,
Christophe.

**Comment by Funkoverload** [comment]
Thanks Christophe, 
this is the output: 
Error in name_ref_groups %in% infercnv_obj@tumor_subclusters$subclusters : 
  object 'infercnv_obj' not found
5: (function () 
   traceback(2))()
4: name_ref_groups %in% infercnv_obj@tumor_subclusters$subclusters
3: .plot_cnv_references(ref_data = ref_data_t, ref_groups = ref_groups, 
       name_ref_groups = name_ref_groups, cluster_references = cluster_references, 
       hclust_method = hclust_method, grouping_key_coln = grouping_key_coln[2], 
       col_pal = custom_pal, contig_seps = col_sep, file_base_name = out_dir, 
       do_plot = !is.na(output_format), output_filename_prefix = output_filename, 
       cnv_ref_title = ref_title, breaksList = breaksList_t, gene_position_breaks = gene_position_breaks, 
       x.center = x.center, layout_add = TRUE, useRaster = useRaster)
2: plot_cnv(infercnv_obj, k_obs_groups = k_obs_groups, cluster_by_groups = cluster_by_groups, 
       cluster_references = cluster_references, out_dir = out_dir, 
       x.center = final_center_val, x.range = final_scale_limits, 
       title = "inferCNV", output_filename = "infercnv", output_format = output_format, 
       write_expr_matrix = TRUE, png_res = png_res, useRaster = useRaster)
1: infercnv::run(cnv_obj, cutoff = 0.1, out_dir = "out4", cluster_by_groups = T, 
       denoise = F, HMM = F, num_threads = parallel::detectCores())

Best
Nils

**Comment by GeorgescuC** [comment]
Hi @Funkoverload ,

This is very weird. Did you make any changes to the infercnv code or methods?
Can you try reinstalling the latest version of infercnv and see if the error still occurs?

Regards,
Christophe.

**Comment by Funkoverload** [comment]
Dear Christophe, 
yes, I had 1.4 from bioconductor, but updating to the newest code on gitlab (1.5) works. 
Thanks!
Nils
