### ISSUE TITLE
Identifying Dups and Dels from Add-To-Seurat Fxn

### ISSUE THREAD

**Issue by aysouid** [broadinstitute/infercnv#258]
Thanks for the great package: 

I followed the directions in another post to use the `verbose=true` command to identify the locations of top losses. Here is a piece of the output: 

```
![image](https://user-images.githubusercontent.com/66695688/92807336-c84fdb80-f388-11ea-805e-cfc16b605d6b.png)
```

I have two questions:
1) How does region ID correspond to the chromosome sequence? Is Chr10-region_34 the 34th peak (or tile) on chromosome 10? 
2) Why do losses have more than one region, such as the second loss having 5 regions? 

Thanks again -

**Comment by GeorgescuC** [comment]
Hi @aysouid ,

1. The region ID does not mean anything specific, it just comes from a counter when going through the different candidates. You can find a mapping of each region to chromosome/genes in the .dat text outputs. The files should be "17_HMM_pred*.pred_cnv_[regions|genes].dat" before Bayesian filtering and "HMM_CNV_predictions.*.pred_cnv_[regions|genes].dat" after Bayesian filtering.

2. Regions are specific to a (sub)cluster of cells, so if a colocated set of regions is found to be the same CNV across multiple (sub)clusters, they will be grouped together as one (with a +- tolerance in base pairs for the boundaries of the regions that can be given as an option).

Regards,
Christophe.

**Comment by aysouid** [comment]
> Hi @aysouid ,
> 
> 1. The region ID does not mean anything specific, it just comes from a counter when going through the different candidates. You can find a mapping of each region to chromosome/genes in the .dat text outputs. The files should be "17_HMM_pred*.pred_cnv_[regions|genes].dat" before Bayesian filtering and "HMM_CNV_predictions.*.pred_cnv_[regions|genes].dat" after Bayesian filtering.
> 2. Regions are specific to a (sub)cluster of cells, so if a colocated set of regions is found to be the same CNV across multiple (sub)clusters, they will be grouped together as one (with a +- tolerance in base pairs for the boundaries of the regions that can be given as an option).
> 
> Regards,
> Christophe.

Makes sense! Thanks -
