### ISSUE TITLE
inferCNV- two questions!

### ISSUE THREAD

**Issue by beemilmlo** [broadinstitute/infercnv#259]
I am new to inferCNV and am trying to understand how the program works. The way I have it in my head right now is that the reference cell's expression distribution (the average expression?) is subtracted from both the normal cell expression and tumor cell expression, leaving the normal cell expression nearly void and the tumor cell expression showing the CNVs more clearly if they exist.
My first question is, if there is more than one set of reference cells, how are they averaged? Are each of their distributions compared with the tumor cells separately or are their averages averaged again to be subtracted from the respective reference cell expressions and the tumor cell expressions?

My second question : Is it normal for inferCNV to skip steps? For example, steps 5, 6, 7, sometimes 18, etc. are skipped over.

Thank you in advance !

**Comment by GeorgescuC** [comment]
Hi @beemilmlo ,

Basically that is what happens yes. When there is more than one set of reference cells, each set has its own average calculated, and for each observation, the closest reference is used for the difference.

To make it easier to support users, steps are always numbered the same even if you do not use the options that enable some of them, so it is expected to skip some steps yes. For example, step 6 is to split the reference cells based on a hierarchical clustering to a selected number of groups rather the annotations provided (which cells are references is still defined at initialization based on the annotations). Step 7 is to run subclustering using the random trees method, while subclustering with any of the other methods would be step 15, so some steps are mutually exclusive.

Regards,
Christophe.

**Comment by beemilmlo** [comment]
Thank you @GeorgescuC for your clarification !
