### ISSUE TITLE
improve on defining the reference/normal cells

### ISSUE THREAD

**Issue by brianjohnhaas** [broadinstitute/infercnv#26]
Instead of a comma-separated list and numeric ranges of groups, use a simple tab-delimited metadata file that has values:

cell_name (tab) cell_type
...

See the example/__sampled_cells.annotations.dat  file, and consider just the 1st 2 columns.  To be flexible, allow for additional columns, but just use the first two for the above info.

**Comment by komalsrathi** [comment]
@brianjohnhaas How is this file supplied in the inferCNV command?
