### ISSUE TITLE
annotation file conflict

### ISSUE THREAD

**Issue by rsalatin** [broadinstitute/infercnv#260]
Hello,
I am pretty new to using inferCNV and I may be missing something in the input preparation. I have prepared all the files according to the documentation but I am getting the following error: 

> infercnv_obj = CreateInfercnvObject(raw_counts_matrix="normalvs0.10x.counts.matrix",
+                                     annotations_file="annotation_fileOS1.txt",
+                                     delim="\t",
+                                     gene_order_file="gencode_v19_gene_pos.txt",
+                                     ref_group_names=c("normal"))
INFO [2020-09-28 04:31:08] Parsing matrix: normalvs0.10x.counts.matrix
INFO [2020-09-28 04:31:10] Parsing gene order file: gencode_v19_gene_pos.txt
INFO [2020-09-28 04:31:10] Parsing cell annotations file: annotation_fileOS1.txt
Error in CreateInfercnvObject(raw_counts_matrix = "normalvs0.10x.counts.matrix",  : 
  Please make sure that all the annotated cell  names match a sample in your data matrix.  Attention to:  
>

Looks like there is some discrepancy between the the annotation file cell names and the matrix but the error message doesn't output the problematic name. I have no problem running the analysis with the sample data but keep getting this error when I try to input my data.

Any help would be really appreciated!
Thank you, 
Roberto

**Comment by liron27** [comment]
Hi! 

I am getting the exact same issue! I checked the dimension of the all inputs and they perfect match and the missing_cells is "character(0)"

**Comment by liron27** [comment]
check your annotation_file. Use write.table with rownames = FALSE, colname = TRUE.

**Comment by rsalatin** [comment]
Thank you, 
The issue was due to some spacing that I had accidentally inserted at the end of the file and it is now solved.
