### ISSUE TITLE
STEP 18: Run Bayesian Network Model on HMM predicted CNV's

### ISSUE THREAD

**Issue by wuzhigui** [broadinstitute/infercnv#262]
while i run step 18 ,the running is
`INFO [2020-10-04 17:48:04] Creating the following Directory:  `
`/public/workspace/wuzhig/colleboration/wangbingl/infercnvout/out/BayesNetOutput.HMMi6.hmm_mode-samples`
`INFO [2020-10-04 17:48:04] Initializing new MCM InferCNV Object.`
`INFO [2020-10-04 17:48:04] validating infercnv_obj`
`INFO [2020-10-04 17:48:05] Total CNV's:  14`
`INFO [2020-10-04 17:48:05] Loading BUGS Model.`
`INFO [2020-10-04 17:48:05] Running Sampling Using Parallel with  8 Cores`
`INFO [2020-10-04 18:09:36] Obtaining probabilities post-sampling`
`INFO [2020-10-04 18:12:26] Gibbs sampling time:  24.3481641689936  Minutes`
`INFO [2020-10-04 18:16:03] ::plot_cnv:Start`
`INFO [2020-10-04 18:16:03] ::plot_cnv:Current data dimensions (r,c)=8111,31452 Total=626148.57471524 Min=0 `
`Max=0.493860693706684.`
`INFO [2020-10-04 18:16:06] ::plot_cnv:Depending on the size of the matrix this may take a moment.`

then,
i got thois error :
`Error in rep(contig_name, contig_tbl[contig_name]) :
  invalid 'times' argument`
I have no idea ,please help me !

**Comment by wuzhigui** [comment]
Maybe this error is not related with step18 ,beacause i run the same code but got this error and stoped at step17 yesterday .
So,what is just the main reason for this ???

**Comment by wuzhigui** [comment]
Maybe i have found the error .

**Comment by earthminator86** [comment]
Hi, zhigui, could you share your experience. What is the problem of invalid 'times' argument? Thanks
