### ISSUE TITLE
draw the evolutionary tree

### ISSUE THREAD

**Issue by zhangqi234** [broadinstitute/infercnv#269]
Hi
   Which file from infercnv output can I use to draw the evolutionary tree?

**Comment by newbieMars** [comment]
Hi @zhangqi234 ,

According to UPhyloplot2 tools (https://github.com/harbourlab/UPhyloplot2), you should consider to use  "HMM_CNV_predictions.HMMi6.rand_trees.hmm_mode-subclusters.Pnorm_0.5.cell_groupings” files.

Hope this will help.
