### ISSUE TITLE
Label different group of cells with different color

### ISSUE THREAD

**Issue by snoopy-448** [broadinstitute/infercnv#27]
Hi
Thanks for developing such a useful tools! I have a DGE matrix of about 4000 cells and want to plot the CNV heatmap of them. But before inferring CNV and clustering the cells, I have manually divided these cells into 5 groups. And then I want to see if my classification is consistent with the group result given by CNV clustering, so I need to label these five groups with different colors at the left side of the heatmap. I do not know how to achieve my goal. Could you please give me some advice?
Many thanks!
Yang

**Comment by GeorgescuC** [comment]
Hi @snoopy-448 ,

This is currently not possible to do, but it is a feature we are working on adding right now, so it should be available soon. The way we intend to have it work is to have the user provide a file with a grouping for each of their cells that would be used have colors on the side of the heatmap, and to select which groups to use as reference(s).

Regards,
Christophe.
