### ISSUE TITLE
png or pdf file can not be generated

### ISSUE THREAD

**Issue by luolq** [broadinstitute/infercnv#270]
Hello, 
Could you help me with ths error?  After step-18, I got this problem. It seems there is something wrong with the png support, so I used the following code to restart the run and change the output format.
`infercnv_obj = readRDS('preliminary.infercnv_obj')`
`infercnv_obj = infercnv::run(infercnv_obj,cutoff=0.1,out_dir="output",cluster_by_groups=T,denoise=T,HMM=T,output_format="pdf")`
However, I still ran into this error, and no pdf file was generated. What should I do to fix the problem. Thanks very much. 
And the error is like:
```
Error in png(paste(out_dir, paste(output_filename, ".png", sep = ""),  : 
  X11 module cannot be loaded
Calls: <Anonymous> ... postProbNormal -> postProbNormal -> <Anonymous> -> png
In addition: Warning message:
In grSoftVersion() :
  unable to load shared object '/R/4.0.2/lib64/R/modules//R_X11.so':
  libXt.so.6: cannot open shared object file: No such file or directory
Execution halted
```

**Comment by GeorgescuC** [comment]
Hi @luolq ,

It seems like the issue is with the posterior probability plotting, which always uses png. You can try disabling this plotting using the `plot_probabilities=FALSE` option in the run() command.

Regards,
Christophe.
