### ISSUE TITLE
cluster_by_groups=FALSE leading to "Unexpected error, should not happen"

### ISSUE THREAD

**Issue by newbieMars** [broadinstitute/infercnv#273]
Hi @GeorgescuC,

I'm trying to use the latest version of infercnv in order to resolve the problem mentionned in  #271.
However when I tried to use the latest docker image (i.e trinityctat/infercnv:latest), I encountered the same issue mentioned in #267 while my script worked perfectly with infercnv1.2.2.
Thus to eliminate mistakes that could be due to one of my imput files or my scrip, I've opted to try using infercnv example files and exemple script. 
Thus when I used : 
```
# create the infercnv object
infercnv_obj = CreateInfercnvObject(raw_counts_matrix=system.file("extdata","oligodendroglioma_expression_downsampled.counts.matrix.gz", package = "infercnv"),
                                    annotations_file=system.file("extdata", "oligodendroglioma_annotations_downsampled.txt", package = "infercnv"),
                                    delim="\t",
                                    gene_order_file=system.file("extdata", "gencode_downsampled.EXAMPLE_ONLY_DONT_REUSE.txt", package = "infercnv"),
                                    ref_group_names=c("Microglia/Macrophage","Oligodendrocytes (non-malignant)"))

out_dir="output_dir"

# perform infercnv operations to reveal cnv signal
infercnv_obj = infercnv::run(infercnv_obj,
                             cutoff=1, 
                             out_dir=out_dir,
                             cluster_by_groups=TRUE,
                             plot_steps=FALSE,
                             denoise=TRUE,
                             HMM=TRUE
                             )
```
Everything worked well. 
While, when I changed ```cluster_by_groups=FALSE``` parameter, with ```k_obs_groups=4``` and with or without ```analysis_mode="subclusters"``` , it ended with the error : "Unexpected error, should not happen" and only the infercnv.preliminary.png as output with reference heatmap missing (as in #267 ).
Is it normal?
I've added the traceback output.
[test_infercnv_cluster_by_groups_FALSE_analysis_mode_SUBCLUSTERS_nohup.txt](https://github.com/broadinstitute/infercnv/files/5585074/test_infercnv_cluster_by_groups_FALSE_analysis_mode_SUBCLUSTERS_nohup.txt)
[test_infercnv_cluster_by_groups_FALSE_nohup.txt](https://github.com/broadinstitute/infercnv/files/5585075/test_infercnv_cluster_by_groups_FALSE_nohup.txt)

Thanks a lot!

Estelle

**Comment by newbieMars** [comment]
Hi!

I have another question concerning the final infercnv object.
In the ```infercnv_obj@tumor_subclusters$hc``` field, we have access to the dendrogram that led to the tumor subclusters groups found in ```infercnv_obj@tumor_subclusters$subclusters```.
However, when I color one subcluster group in red and the second in black in the dendrogram, it seems that they can not form 2 subclusters.
![subclusters_highlighted](https://user-images.githubusercontent.com/73688181/100240250-a3541900-2f32-11eb-903b-ca104681b8a3.PNG)

Thus, my question is : where do we find the dendrogram of the final tree associated to the subclusters? Does it correspond to the HMM dendrogram ?

Thanks!

Estelle

**Comment by Pentayouth** [comment]
Hi Estelle @newbieMars 

I've come across with exactly the same problem. A workaround I found is at the same time add **"cluster_references = FALSE"** to the infercnv::run() function. I guess the reason is the lack of subcluster for the reference cell groups. I'm Not Sure :)

Besides, I found:
`cluster_by_groups=TRUE,  tumor_subcluster_partition_method =  "random_trees"` works well

`cluster_by_groups=FALSE, tumor_subcluster_partition_method =  "qnorm"` works quick and well, but the result is not as good as that generated by "random_trees" method.

`cluster_by_groups=FALSE, tumor_subcluster_partition_method = "random_trees"` failed with 'Unexpected error, should not happen'

`cluster_by_groups=FALSE, tumor_subcluster_partition_method = "random_trees", cluster_references = FALSE`  works slow but well. The result is good.

**Comment by newbieMars** [comment]
Hi @Pentayouth ,

Thanks for your answer. 
But I still have some questions:
- cluster_references should not be linked to "subcluster research" but to the cluster references annotation. Moreover, when using **infercnv1.2.2** with : 
```
# perform infercnv operations to reveal cnv signal
infercnv_obj = infercnv::run(infercnv_obj,
                             cutoff=1, 
                             out_dir=out_dir,
                             cluster_by_groups=TRUE,
                             cluster_references=TRUE,
                             analysis_mode="subclusters",
                             tumor_subcluster_partition_method = "random_trees",
                             plot_steps=FALSE,
                             denoise=TRUE,
                             HMM=TRUE
                             )
```
it leads to an infercnv plot with references clustered according to their annotation and no error message.

- Thus wich version of infercnv are you using? 
- Are your final infercnv_obj@tumor_subclusters$hc is coherent with your infercnv_obj@tumor_subclusters$subclusters members?

Thanks,

Estelle

**Comment by GeorgescuC** [comment]
Hi, 

Thank you for providing a reproducible case using the example data @newbieMars . I have made changes to the code that are available on the master branch here. Could you try the changes and see if all the issues are solved? It should both fix what groups of references the subclustering is run on and allow results generated using older versions that have the issue to be plotted without changing settings/data.

You can follow the [install instructions from a github branch on the wiki](https://github.com/broadinstitute/infercnv/wiki/Installing-infercnv#option-d-install-infercnv-from-within-r-using-devtools) .

Regards,
Christophe.
