### ISSUE TITLE
Why do the resulting CNV genes (number and regions) differ when rerun with the same input files and options?

### ISSUE THREAD

**Issue by beemilmlo** [broadinstitute/infercnv#274]
Hello,

I was wondering why **HMM_CNV_predictions.HMMi6.hmm_mode-samples.Pnorm_0.5.pred_cnv_genes**, one of the output files predicting cnv genes and their regions, lists different genes and differing numbers of genes when run with the same input files each time. The resulting infercnv.png seems identical (if it's different, I wouldn't have been able to tell), but the gene sets and numbers differ.

Thanks!
beemilmlo

**Comment by GeorgescuC** [comment]
Hi @beemilmlo ,

The infercnv.png is the residual expression figure, if you look at the HMM plots from steps 17/18/19, do they seem identical as well?
How big are the differences you see? There is some variability/non-deterministic behavior involved in generating the data used to calibrate the HMM model for the dropout rate, so it is possible for boundaries of predicted CNVs not to be identical every time.

Regards,
Christophe.
