### ISSUE TITLE
The meaning of infercnv.observation.txt in output files

### ISSUE THREAD

**Issue by daisyyr** [broadinstitute/infercnv#275]
Hi~
There are many files in the output results. And one of them is infercnv.observation.txt, which you have defined as the tumor cell matrix data values [Output files.](https://github.com/broadinstitute/infercnv/wiki/Output-Files)  So I want to know whether this file is expression file of tumor cell or calculated cnv score of cells? 

Thanks for your reply!

**Comment by GeorgescuC** [comment]
Hi @daisyyr ,

Each *.observation.txt is the matrix matching the figure with the same prefix, so in your case, infercnv.observation.txt matches the data in infercnv.png, which is the residual expression, not HMM predictions.

Regards,
Christophe.
