### ISSUE TITLE
Fixed number of subclusters in multiple datasets

### ISSUE THREAD

**Issue by Svanuytven** [broadinstitute/infercnv#278]
Dear developers of inferCNV,

Thank you very much for creating an excellent tool to investigate genomic heterogeneity with scRNA-seq. I am currently analysing 3 datasets (2 with more than 5000 cells) and my interest is to get an idea about heterogeneity in genomic aberrations between the samples. When I run inferCNV in subclusters mode I seem to always find 8 different subclones for each sample. Based on the vignette, we can only specify the manner of partitioning and the associated p-value threshold, so I was wondering if the artificial max of 8 groups can be removed?

Thank you very much in advance.

Sebastiaan

**Comment by GeorgescuC** [comment]
Hi @Svanuytven ,

There is now a new (default) method of subclustering using Leiden clustering available on the github version of infercnv (it should follow in a bit on Bioconductor-devel as well). This method allows you to set a resolution parameter that makes the subclustering make more or less clusters. To use it, simply set the analysis mode to subclustering and leave the tumor subcluster partition method to the default, or set it to "leiden".

Regards,
Christophe.
