### ISSUE TITLE
Order of the cells in the output pdf file? 

### ISSUE THREAD

**Issue by kysbbubbu** [broadinstitute/inferCNV#28]
Hello, 

 I identified two groups of observed cells.

But, I find difficulties in identifying which cell belongs to either group. 

How can i identify the order of the cells in the output pdf file? 

Thanks you for your help!

**Comment by GeorgescuC** [comment]
Hi @kysbbubbu ,

There should be a file named "observations_dendrogram.txt" in your output folder that contains the newick string of the dendrogram appearing on the left of the observations heatmap, in reverse order (so the first cells appearing in the newick string are at the bottom of the dendrogram on the plot).
Additionally, you can use the option "--obs_groups" to specify a number of groups you want the observations to be divided in, based on the hierarchical clustering. The color column next to the dendrogram will reflect the partitioning, and you can find the partitioning information as a space delimited table in your output folder in the file "observation_groupings.txt".

Regards.

**Comment by kysbbubbu** [comment]
Thank you @GeorgescuC for your kind and concrete answer! I resolved the problem.

Best regards.
