### ISSUE TITLE
pred_cnv_genes.dat contains incorrect gene start and end positions

### ISSUE THREAD

**Issue by Lioscro** [broadinstitute/infercnv#280]
Hello,

I have been using inferCNV to detect CNVs in some of our cancer experiments.
I've manually prepared the gene ordering file by running your GTF parsing script. Here is an example:
```
Xkr4    1       3205901 3671498
Gm1992  1       3466587 3513553
Gm37381 1       3905739 3986215
Rp1     1       3999557 4409241
Sox17   1       4490931 4497354
Gm37323 1       4583129 4586252
Mrpl15  1       4773206 4785739
Lypla1  1       4807788 4848410
Gm37988 1       4807892 4886770
Tcea1   1       4857814 4897909
```

And I am running inferCNV with the following command:
```
infercnv_obj = infercnv::run(
    infercnv_obj,
    min_cells_per_gene=1,
    analysis_mode='subclusters',
    hclust_method='ward.D2',
    tumor_subcluster_partition_method='random_trees',
    max_centered_threshold=NA,
    cutoff=0.1,
    out_dir=out_dir,
    cluster_by_groups=TRUE,
    denoise=TRUE,
    HMM=TRUE,
    BayesMaxPNormal=0.2,
    num_threads=8
)
```

When I check the `pred_cnv_genes.dat` file after it finishes running, I notice that all the gene start and end positions are shifted by one. For example, the following is a few lines from `HMM_CNV_predictions.HMMi6.rand_trees.hmm_mode-subclusters.Pnorm_0.2.pred_cnv_genes.dat`:
```
cell_group_name gene_region_name        state   gene    chr     start   end
3730_NT_T1.3730_NT_T1.1.1.1.1   17-region_31    4       Hnrnpm  17      33629090        33631779
3730_NT_T1.3730_NT_T1.1.1.1.1   17-region_31    4       March2  17      33646233        33686860
3730_NT_T1.3730_NT_T1.1.1.1.1   17-region_31    4       Rab11b  17      33685692        33718670
3730_NT_T1.3730_NT_T1.1.1.1.1   17-region_31    4       Angptl4 17      33742484        33760530
```

But in the gene ordering file, the above genes have the following entries
```
Hnrnpm  17      33646233        33686860
March2  17      33685692        33718670
Rab11b  17      33742484        33760530
Angptl4 17      33773750        33781575
```

My intuition is telling me the start and end positions in the `pred_cnv_genes.dat` file should match those in the gene ordering file.
I am running inferCNV 1.2.1 with R 3.6.3. I've also tested this on 1.5.1 and this behavior still exists.

**Comment by yifeisun03** [comment]
Hello

I'm encountering the exact same problem(inferCNV version 1.4.0). Following the tutorial and doing the same at every single step, my run finished successfully, the final inferCNV figure looks good, tumor cells separate well from non-malignant ones. Then I took a look at the HMM_pred_CNV.genes.dat, found out the genomic location of certain genes doesn't make sense, and then realized the gene position shift by one row compared to the gene_order file.

I was trying to locate where thing went wrong, checked all the .obj generated from each step, the gene_order slot contains the correct gene location information to the last run final infercnv.obj, and in the same step18_HMM, the HMM_pred...genes_used.data contains the correct information, but not in the cnv_gene.dat which I was planning to use.

I'm not sure where the problem raised and a bit concerned. If the problem occurred only when generating for HMM...cnv.gene.dat, and the gene list is accurate in that file, I can simply correct those genomic coordinate myself, but how do I know the gene list here is not corrupted. And how does The HMM.regions.dat generated, can I still trust the region locations in this case?

**Comment by chenv3** [comment]
Hello,

I just wanted to commented that I also ran into this same problem. I have tested both version 1.4.0 with R3.6.0 and 1.6.0 with R4.0.2 and I'm observing this shift in both versions. The behavior is the same as what was mentioned above. I would appreciate some insight into just how these pred_cnv_gene dat files can be used and if it the gene names or coordinates are accurate.

**Comment by GeorgescuC** [comment]
Hi @Lioscro @yifeisun03 @chenv3 ,

Thanks for finding and reporting this issue. It should now be fixed in the master branch on github (and to come in the next bioc-devel version).

For a bit of detail about the origin of the issue, it steamed from the method that generates the dataframe to output to the text file. At the part where it pulls the coordinates from the gene order matrix, the index was off by one compared to the gene/state index (which were in proper sync, meaning the gene names were accurate).

Regards,
Christophe.
