### ISSUE TITLE
Error at 18 Step

### ISSUE THREAD

**Issue by earthminator86** [broadinstitute/infercnv#284]
Hi,

This is my first time to use inferCNV. I met a problem when I run my 10X data with inferCNV.

The error is shown as below：

STEP 18: Run Bayesian Network Model on HMM predicted CNV's

INFO [2021-01-06 23:38:26] Creating the following Directory:  F://personal_project/oral/CNV//BayesNetOutput.HMMi6.hmm_mode-samples
INFO [2021-01-06 23:38:26] Initializing new MCM InferCNV Object.
INFO [2021-01-06 23:38:26] validating infercnv_obj
INFO [2021-01-06 23:38:26] Total CNV's:  12
INFO [2021-01-06 23:38:26] Loading BUGS Model.
Error in rep(NA, max(unlist(obj@observation_grouped_cell_indices))) : 
  invalid 'times' argument
In addition: Warning messages:
1: In dir.create(out_dir) : 'F:\\personal_project\oral\CNV' already exists
2: In max(unlist(obj@observation_grouped_cell_indices)) :
  no non-missing arguments to max; returning -Inf

In addition, I show put my running commands here:

infercnv_obj = CreateInfercnvObject(raw_counts_matrix=expFile,
                                    annotations_file=groupFiles,
                                    delim="\t",
                                    gene_order_file= geneFile,
                                    ref_group_names=c("0","1","4"))  #My group names are number from 1 to 16.

infercnv_obj = infercnv::run(infercnv_obj,
                             cutoff=0.1, 
                             out_dir="F://personal_project/oral/CNV/", 
                             cluster_by_groups=TRUE, 
                             denoise=TRUE,
                             HMM=TRUE)

I am looking forward to your reply. Thank you very much.

**Comment by GeorgescuC** [comment]
Hi @earthminator86 , 

Which version of infercnv are you running?
If you are running a recent version (1.6+), could you share your data privately for me to debug the issue?

Regards,
Christophe.
