### ISSUE TITLE
ERROR in setting options

### ISSUE THREAD

**Issue by yomdung** [broadinstitute/infercnv#286]
Hello, 
I feel grateful for development of inferCNV tool, but there is a trouble to use this tool.

I want to set the "analysis mode" as "cells" and also "HMM report by" as "cell".
However, the tool showed error messages when I set "analysis mode" as "cells" and "HMM report by" as "cell" or "consensus". 
How can I set the option if I want to get HMM CNV prediction as cell level and also be reported the results as cell level?

Thank you for reading my issues, and please give me a feedback.

**Comment by GeorgescuC** [comment]
Hi @yomdung ,

Do you have the underscores in the option names? They should be set as `analysis_mode="cells"` and `HMM_report_by="cell"`.
If you do and still get the error, what exactly is the error produced by infercnv, and which version of infercnv are you using?

Regards,
Christophe.
