### ISSUE TITLE
how to do the inferCNV in integrated data and Distribution of Expression are all blue?

### ISSUE THREAD

**Issue by Yinglei1** [broadinstitute/infercnv#287]
Hi, there, 

 I am a new for integration and inferCNV. I have four samples(two from normal people and two from patients with chr20 deletion) . I integrated these four samples together using finding FindIntegrationAnchors, now I want to check if there is any inferCNVs between normal people and patients in one cluster(one cell type). Note: this cell type occurred  in both normal and patients regardless of the chromosome disability.
![image](https://user-images.githubusercontent.com/59709147/104162134-551cab80-53f4-11eb-9f3e-9e25088987e0.png)

This are the codes that I used for integration:
anchors <- FindIntegrationAnchors(object.list = object)
integration <- IntegrateData(anchorset = anchors)

thisare the codes that I used for inferCNV:
1.	extracting the matrix with gene expression:
exprMatrix <- as.matrix(GetAssayData(object1[["RNA"]], slot='counts'))
there are the gene expression data and cells annotation.

![Picture1](https://user-images.githubusercontent.com/59709147/104161307-f30f7680-53f2-11eb-91ee-89a04c00bb60.png)
![image](https://user-images.githubusercontent.com/59709147/104162258-8a28fe00-53f4-11eb-8a95-f79586fde764.png)

2.	running inferCNV 
infercnv_obj = CreateInfercnvObject(delim = '\t',
                                    raw_counts_matrix = 'exprMatrix.txt',
                                    annotations_file = 'cellAnnota.txt',
                                    gene_order_file = gene_pos.txt',
                                    ref_group_names = c("Control1","Control2"))

infercnv_obj1 = infercnv::run(infercnv_obj,
                             cutoff=0.1, 
                             out_dir=" inferCNV/Astroglia/inferCNV1-3", 
                             cluster_by_groups=TRUE, 
                             denoise=TRUE,
                             HMM=TRUE)

here are the outputs:
STEP 1: incoming data

INFO [2021-01-11 10:09:21] 

	STEP 02: Removing lowly expressed genes

INFO [2021-01-11 10:09:21] ::above_min_mean_expr_cutoff:Start
INFO [2021-01-11 10:09:21] Removing 10609 genes from matrix as below mean expr threshold: 0.1
INFO [2021-01-11 10:09:21] validating infercnv_obj
INFO [2021-01-11 10:09:21] There are 5394 genes and 1502 cells remaining in the expr matrix.
INFO [2021-01-11 10:09:22] no genes removed due to min cells/gene filter
INFO [2021-01-11 10:09:24] 

	STEP 03: normalization by sequencing depth

INFO [2021-01-11 10:09:24] normalizing counts matrix by depth
INFO [2021-01-11 10:09:24] Computed total sum normalization factor as median libsize: 3048.500000
INFO [2021-01-11 10:09:24] Adding h-spike
INFO [2021-01-11 10:09:24] -hspike modeling of Control1
INFO [2021-01-11 10:10:16] -hspike modeling of Control2
INFO [2021-01-11 10:11:03] validating infercnv_obj
INFO [2021-01-11 10:11:03] normalizing counts matrix by depth
INFO [2021-01-11 10:11:03] Using specified normalization factor: 3048.500000
INFO [2021-01-11 10:11:06] 

	STEP 04: log transformation of data

INFO [2021-01-11 10:11:06] transforming log2xplus1()
INFO [2021-01-11 10:11:06] -mirroring for hspike
INFO [2021-01-11 10:11:06] transforming log2xplus1()
INFO [2021-01-11 10:11:10] 

	STEP 08: removing average of reference data (before smoothing)

INFO [2021-01-11 10:11:10] ::subtract_ref_expr_from_obs:Start inv_log=FALSE, use_bounds=TRUE
INFO [2021-01-11 10:11:10] subtracting mean(normal) per gene per cell across all data
INFO [2021-01-11 10:11:11] -subtracting expr per gene, use_bounds=TRUE
INFO [2021-01-11 10:11:12] -mirroring for hspike
INFO [2021-01-11 10:11:12] ::subtract_ref_expr_from_obs:Start inv_log=FALSE, use_bounds=TRUE
INFO [2021-01-11 10:11:12] subtracting mean(normal) per gene per cell across all data
INFO [2021-01-11 10:11:13] -subtracting expr per gene, use_bounds=TRUE
INFO [2021-01-11 10:11:19] 

	STEP 09: apply max centered expression threshold: 3

INFO [2021-01-11 10:11:19] ::process_data:setting max centered expr, threshold set to: +/-:  3
INFO [2021-01-11 10:11:19] -mirroring for hspike
INFO [2021-01-11 10:11:19] ::process_data:setting max centered expr, threshold set to: +/-:  3
INFO [2021-01-11 10:11:24] 

	STEP 10: Smoothing data per cell by chromosome

INFO [2021-01-11 10:11:24] smooth_by_chromosome: chr: chr1
INFO [2021-01-11 10:11:25] smooth_by_chromosome: chr: chr2
INFO [2021-01-11 10:11:27] smooth_by_chromosome: chr: chr3
INFO [2021-01-11 10:11:28] smooth_by_chromosome: chr: chr4
INFO [2021-01-11 10:11:29] smooth_by_chromosome: chr: chr5
INFO [2021-01-11 10:11:30] smooth_by_chromosome: chr: chr6
INFO [2021-01-11 10:11:32] smooth_by_chromosome: chr: chr7
INFO [2021-01-11 10:11:33] smooth_by_chromosome: chr: chr8
INFO [2021-01-11 10:11:34] smooth_by_chromosome: chr: chr9
INFO [2021-01-11 10:11:35] smooth_by_chromosome: chr: chr10
INFO [2021-01-11 10:11:36] smooth_by_chromosome: chr: chr11
INFO [2021-01-11 10:11:38] smooth_by_chromosome: chr: chr12
INFO [2021-01-11 10:11:39] smooth_by_chromosome: chr: chr13
INFO [2021-01-11 10:11:40] smooth_by_chromosome: chr: chr14
INFO [2021-01-11 10:11:42] smooth_by_chromosome: chr: chr15
INFO [2021-01-11 10:11:43] smooth_by_chromosome: chr: chr16
INFO [2021-01-11 10:11:44] smooth_by_chromosome: chr: chr17
INFO [2021-01-11 10:11:46] smooth_by_chromosome: chr: chr18
INFO [2021-01-11 10:11:47] smooth_by_chromosome: chr: chr19
INFO [2021-01-11 10:11:48] smooth_by_chromosome: chr: chr20
INFO [2021-01-11 10:11:49] smooth_by_chromosome: chr: chr21
INFO [2021-01-11 10:11:50] smooth_by_chromosome: chr: chr22
INFO [2021-01-11 10:11:51] -mirroring for hspike
INFO [2021-01-11 10:11:51] smooth_by_chromosome: chr: chrA
INFO [2021-01-11 10:11:51] smooth_by_chromosome: chr: chr_0
INFO [2021-01-11 10:11:52] smooth_by_chromosome: chr: chr_B
INFO [2021-01-11 10:11:53] smooth_by_chromosome: chr: chr_0pt5
INFO [2021-01-11 10:11:53] smooth_by_chromosome: chr: chr_C
INFO [2021-01-11 10:11:53] smooth_by_chromosome: chr: chr_1pt5
INFO [2021-01-11 10:11:54] smooth_by_chromosome: chr: chr_D
INFO [2021-01-11 10:11:54] smooth_by_chromosome: chr: chr_2pt0
INFO [2021-01-11 10:11:55] smooth_by_chromosome: chr: chr_E
INFO [2021-01-11 10:11:55] smooth_by_chromosome: chr: chr_3pt0
INFO [2021-01-11 10:11:55] smooth_by_chromosome: chr: chr_F
INFO [2021-01-11 10:12:01] 

	STEP 11: re-centering data across chromosome after smoothing

INFO [2021-01-11 10:12:01] ::center_smooth across chromosomes per cell
INFO [2021-01-11 10:12:02] -mirroring for hspike
INFO [2021-01-11 10:12:02] ::center_smooth across chromosomes per cell
INFO [2021-01-11 10:12:08] 

	STEP 12: removing average of reference data (after smoothing)

INFO [2021-01-11 10:12:08] ::subtract_ref_expr_from_obs:Start inv_log=FALSE, use_bounds=TRUE
INFO [2021-01-11 10:12:08] subtracting mean(normal) per gene per cell across all data
INFO [2021-01-11 10:12:10] -subtracting expr per gene, use_bounds=TRUE
INFO [2021-01-11 10:12:11] -mirroring for hspike
INFO [2021-01-11 10:12:11] ::subtract_ref_expr_from_obs:Start inv_log=FALSE, use_bounds=TRUE
INFO [2021-01-11 10:12:11] subtracting mean(normal) per gene per cell across all data
INFO [2021-01-11 10:12:12] -subtracting expr per gene, use_bounds=TRUE
INFO [2021-01-11 10:12:18] 

	STEP 14: invert log2(FC) to FC

INFO [2021-01-11 10:12:18] invert_log2(), computing 2^x
INFO [2021-01-11 10:12:19] -mirroring for hspike
INFO [2021-01-11 10:12:19] invert_log2(), computing 2^x
INFO [2021-01-11 10:12:26] 

	STEP 15: Clustering samples (not defining tumor subclusters)

INFO [2021-01-11 10:12:26] define_signif_tumor_subclusters(p_val=0.1
INFO [2021-01-11 10:12:26] define_signif_tumor_subclusters(), tumor: Patient1
INFO [2021-01-11 10:12:32] cut tree into: 1 groups
INFO [2021-01-11 10:12:32] -processing Patient1,Patient1_s1
INFO [2021-01-11 10:12:32] define_signif_tumor_subclusters(), tumor: Patient2
INFO [2021-01-11 10:12:45] cut tree into: 1 groups
INFO [2021-01-11 10:12:45] -processing Patient2,Patient2_s1
INFO [2021-01-11 10:12:45] define_signif_tumor_subclusters(), tumor: Control1
INFO [2021-01-11 10:12:48] cut tree into: 1 groups
INFO [2021-01-11 10:12:48] -processing Control1,Control1_s1
INFO [2021-01-11 10:12:48] define_signif_tumor_subclusters(), tumor: Control2
INFO [2021-01-11 10:12:48] cut tree into: 1 groups
INFO [2021-01-11 10:12:48] -processing Control2,Control2_s1
INFO [2021-01-11 10:12:48] -mirroring for hspike
INFO [2021-01-11 10:12:48] define_signif_tumor_subclusters(p_val=0.1
INFO [2021-01-11 10:12:48] define_signif_tumor_subclusters(), tumor: spike_tumor_cell_Control1
INFO [2021-01-11 10:12:49] cut tree into: 1 groups
INFO [2021-01-11 10:12:49] -processing spike_tumor_cell_Control1,spike_tumor_cell_Control1_s1
INFO [2021-01-11 10:12:49] define_signif_tumor_subclusters(), tumor: spike_tumor_cell_Control2
INFO [2021-01-11 10:12:49] cut tree into: 1 groups
INFO [2021-01-11 10:12:49] -processing spike_tumor_cell_Control2,spike_tumor_cell_Control2_s1
INFO [2021-01-11 10:12:49] define_signif_tumor_subclusters(), tumor: simnorm_cell_Control1
INFO [2021-01-11 10:12:49] cut tree into: 1 groups
INFO [2021-01-11 10:12:49] -processing simnorm_cell_Control1,simnorm_cell_Control1_s1
INFO [2021-01-11 10:12:49] define_signif_tumor_subclusters(), tumor: simnorm_cell_Control2
INFO [2021-01-11 10:12:49] cut tree into: 1 groups
INFO [2021-01-11 10:12:49] -processing simnorm_cell_Control2,simnorm_cell_Control2_s1
INFO [2021-01-11 10:13:04] ::plot_cnv:Start
INFO [2021-01-11 10:13:04] ::plot_cnv:Current data dimensions (r,c)=5394,1502 Total=8109332.60491251 Min=0.749570260465397 Max=1.46781862387323.
INFO [2021-01-11 10:13:04] ::plot_cnv:Depending on the size of the matrix this may take a moment.
INFO [2021-01-11 10:13:27] plot_cnv(): auto thresholding at: (0.890175 , 1.111687)
INFO [2021-01-11 10:13:27] plot_cnv_observation:Start
INFO [2021-01-11 10:13:27] Observation data size: Cells= 1079 Genes= 5394
INFO [2021-01-11 10:13:27] plot_cnv_observation:Writing observation groupings/color.
INFO [2021-01-11 10:13:27] plot_cnv_observation:Done writing observation groupings/color.
INFO [2021-01-11 10:13:27] plot_cnv_observation:Writing observation heatmap thresholds.
INFO [2021-01-11 10:13:27] plot_cnv_observation:Done writing observation heatmap thresholds.
INFO [2021-01-11 10:13:28] Colors for breaks:  #00008B,#24249B,#4848AB,#6D6DBC,#9191CC,#B6B6DD,#DADAEE,#FFFFFF,#EEDADA,#DDB6B6,#CC9191,#BC6D6D,#AB4848,#9B2424,#8B0000
INFO [2021-01-11 10:13:28] Quantiles of plotted data range: 0.890174979398446,0.975560729029878,1,1.02363926892263,1.11168747489251
INFO [2021-01-11 10:13:29] plot_cnv_observations:Writing observation data to inferCNV/Astroglia/inferCNV1-3/infercnv.preliminary.observations.txt
INFO [2021-01-11 10:13:45] plot_cnv_references:Start
INFO [2021-01-11 10:13:45] Reference data size: Cells= 423 Genes= 5394
INFO [2021-01-11 10:13:49] plot_cnv_references:Number reference groups= 2
INFO [2021-01-11 10:13:49] plot_cnv_references:Plotting heatmap.
INFO [2021-01-11 10:13:49] Colors for breaks:  #00008B,#24249B,#4848AB,#6D6DBC,#9191CC,#B6B6DD,#DADAEE,#FFFFFF,#EEDADA,#DDB6B6,#CC9191,#BC6D6D,#AB4848,#9B2424,#8B0000
INFO [2021-01-11 10:13:49] Quantiles of plotted data range: 0.890174979398446,0.976493266316419,1,1.02260645130909,1.11168747489251
INFO [2021-01-11 10:13:50] plot_cnv_references:Writing reference data to inferCNV/Astroglia/inferCNV1-3/infercnv.preliminary.references.txt
INFO [2021-01-11 10:13:56] 

	STEP 17: HMM-based CNV prediction

INFO [2021-01-11 10:13:56] predict_CNV_via_HMM_on_whole_tumor_samples
INFO [2021-01-11 10:13:59] -done predicting CNV based on initial tumor subclusters
INFO [2021-01-11 10:14:02] get_predicted_CNV_regions(subcluster)
INFO [2021-01-11 10:14:02] -processing cell_group_name: Patient1.Patient1_s1, size: 435
INFO [2021-01-11 10:14:08] -processing cell_group_name: Patient2.Patient2_s1, size: 644
INFO [2021-01-11 10:14:15] -processing cell_group_name: Control1.Control1_s1, size: 341
INFO [2021-01-11 10:14:21] -processing cell_group_name: Control2.Control2_s1, size: 82
INFO [2021-01-11 10:14:25] -writing cell clusters file: inferCNV/Astroglia/inferCNV1-3/17_HMM_predHMMi6.hmm_mode-samples.cell_groupings
INFO [2021-01-11 10:14:25] -writing cnv regions file: inferCNV/Astroglia/inferCNV1-3/17_HMM_predHMMi6.hmm_mode-samples.pred_cnv_regions.dat
INFO [2021-01-11 10:14:25] -writing per-gene cnv report: inferCNV/Astroglia/inferCNV1-3/17_HMM_predHMMi6.hmm_mode-samples.pred_cnv_genes.dat
INFO [2021-01-11 10:14:25] -writing gene ordering info: inferCNV/Astroglia/inferCNV1-3/17_HMM_predHMMi6.hmm_mode-samples.genes_used.dat
INFO [2021-01-11 10:14:26] ::plot_cnv:Start
INFO [2021-01-11 10:14:26] ::plot_cnv:Current data dimensions (r,c)=5394,1502 Total=24305364 Min=3 Max=3.
INFO [2021-01-11 10:14:26] ::plot_cnv:Depending on the size of the matrix this may take a moment.
INFO [2021-01-11 10:14:37] plot_cnv_observation:Start
INFO [2021-01-11 10:14:37] Observation data size: Cells= 1079 Genes= 5394
INFO [2021-01-11 10:14:37] plot_cnv_observation:Writing observation groupings/color.
INFO [2021-01-11 10:14:37] plot_cnv_observation:Done writing observation groupings/color.
INFO [2021-01-11 10:14:37] plot_cnv_observation:Writing observation heatmap thresholds.
INFO [2021-01-11 10:14:37] plot_cnv_observation:Done writing observation heatmap thresholds.
INFO [2021-01-11 10:14:38] Colors for breaks:  #00008B,#24249B,#4848AB,#6D6DBC,#9191CC,#B6B6DD,#DADAEE,#FFFFFF,#EEDADA,#DDB6B6,#CC9191,#BC6D6D,#AB4848,#9B2424,#8B0000
INFO [2021-01-11 10:14:38] Quantiles of plotted data range: 3,3,3,3,3
INFO [2021-01-11 10:14:38] plot_cnv_observations:Writing observation data to inferCNV/Astroglia/inferCNV1-3/infercnv.17_HMM_predHMMi6.hmm_mode-samples.observations.txt
INFO [2021-01-11 10:14:46] plot_cnv_references:Start
INFO [2021-01-11 10:14:46] Reference data size: Cells= 423 Genes= 5394
INFO [2021-01-11 10:14:49] plot_cnv_references:Number reference groups= 2
INFO [2021-01-11 10:14:49] plot_cnv_references:Plotting heatmap.
INFO [2021-01-11 10:14:49] Colors for breaks:  #00008B,#24249B,#4848AB,#6D6DBC,#9191CC,#B6B6DD,#DADAEE,#FFFFFF,#EEDADA,#DDB6B6,#CC9191,#BC6D6D,#AB4848,#9B2424,#8B0000
INFO [2021-01-11 10:14:49] Quantiles of plotted data range: 3,3,3,3,3
INFO [2021-01-11 10:14:49] plot_cnv_references:Writing reference data to inferCNV/Astroglia/inferCNV1-3/infercnv.17_HMM_predHMMi6.hmm_mode-samples.references.txt
INFO [2021-01-11 10:14:53] 

	STEP 19: Converting HMM-based CNV states to repr expr vals

INFO [2021-01-11 10:14:56] ::plot_cnv:Start
INFO [2021-01-11 10:14:56] ::plot_cnv:Current data dimensions (r,c)=5394,1502 Total=8101788 Min=1 Max=1.
INFO [2021-01-11 10:14:57] ::plot_cnv:Depending on the size of the matrix this may take a moment.
INFO [2021-01-11 10:15:08] plot_cnv_observation:Start
INFO [2021-01-11 10:15:08] Observation data size: Cells= 1079 Genes= 5394
INFO [2021-01-11 10:15:08] plot_cnv_observation:Writing observation groupings/color.
INFO [2021-01-11 10:15:08] plot_cnv_observation:Done writing observation groupings/color.
INFO [2021-01-11 10:15:08] plot_cnv_observation:Writing observation heatmap thresholds.
INFO [2021-01-11 10:15:08] plot_cnv_observation:Done writing observation heatmap thresholds.
INFO [2021-01-11 10:15:09] Colors for breaks:  #00008B,#24249B,#4848AB,#6D6DBC,#9191CC,#B6B6DD,#DADAEE,#FFFFFF,#EEDADA,#DDB6B6,#CC9191,#BC6D6D,#AB4848,#9B2424,#8B0000
INFO [2021-01-11 10:15:09] Quantiles of plotted data range: 1,1,1,1,1
INFO [2021-01-11 10:15:09] plot_cnv_observations:Writing observation data to inferCNV/Astroglia/inferCNV1-3/infercnv.19_HMM_predHMMi6.hmm_mode-samples.Pnorm_0.5.repr_intensities.observations.txt
INFO [2021-01-11 10:15:17] plot_cnv_references:Start
INFO [2021-01-11 10:15:17] Reference data size: Cells= 423 Genes= 5394
INFO [2021-01-11 10:15:20] plot_cnv_references:Number reference groups= 2
INFO [2021-01-11 10:15:20] plot_cnv_references:Plotting heatmap.
INFO [2021-01-11 10:15:20] Colors for breaks:  #00008B,#24249B,#4848AB,#6D6DBC,#9191CC,#B6B6DD,#DADAEE,#FFFFFF,#EEDADA,#DDB6B6,#CC9191,#BC6D6D,#AB4848,#9B2424,#8B0000
INFO [2021-01-11 10:15:20] Quantiles of plotted data range: 1,1,1,1,1
INFO [2021-01-11 10:15:20] plot_cnv_references:Writing reference data to inferCNV/Astroglia/inferCNV1-3/infercnv.19_HMM_predHMMi6.hmm_mode-samples.Pnorm_0.5.repr_intensities.references.txt
INFO [2021-01-11 10:15:24] 

	STEP 21: Denoising

INFO [2021-01-11 10:15:24] ::process_data:Remove noise, noise threshold defined via ref mean sd_amplifier:  1.5
INFO [2021-01-11 10:15:24] denoising using mean(normal) +- sd_amplifier * sd(normal) per gene per cell across all data
INFO [2021-01-11 10:15:24] :: **** clear_noise_via_ref_quantiles **** : removing noise between bounds:  0.942944684299806 - 1.05879392213761
INFO [2021-01-11 10:15:27] ::plot_cnv:Start
INFO [2021-01-11 10:15:27] ::plot_cnv:Current data dimensions (r,c)=5394,1502 Total=8123186.37967838 Min=0.749570260465397 Max=1.46781862387323.
INFO [2021-01-11 10:15:27] ::plot_cnv:Depending on the size of the matrix this may take a moment.
INFO [2021-01-11 10:15:46] plot_cnv(): auto thresholding at: (0.893595 , 1.111687)
INFO [2021-01-11 10:15:46] plot_cnv_observation:Start
INFO [2021-01-11 10:15:46] Observation data size: Cells= 1079 Genes= 5394
INFO [2021-01-11 10:15:46] plot_cnv_observation:Writing observation groupings/color.
INFO [2021-01-11 10:15:46] plot_cnv_observation:Done writing observation groupings/color.
INFO [2021-01-11 10:15:46] plot_cnv_observation:Writing observation heatmap thresholds.
INFO [2021-01-11 10:15:46] plot_cnv_observation:Done writing observation heatmap thresholds.
INFO [2021-01-11 10:15:47] Colors for breaks:  #00008B,#24249B,#4848AB,#6D6DBC,#9191CC,#B6B6DD,#DADAEE,#FFFFFF,#EEDADA,#DDB6B6,#CC9191,#BC6D6D,#AB4848,#9B2424,#8B0000
INFO [2021-01-11 10:15:47] Quantiles of plotted data range: 0.893594909607933,1.00086930321871,1.00086930321871,1.00086930321871,1.11168747489251
INFO [2021-01-11 10:15:48] plot_cnv_observations:Writing observation data to inferCNV/Astroglia/inferCNV1-3/infercnv.21_denoised.observations.txt
INFO [2021-01-11 10:16:01] plot_cnv_references:Start
INFO [2021-01-11 10:16:01] Reference data size: Cells= 423 Genes= 5394
INFO [2021-01-11 10:16:04] plot_cnv_references:Number reference groups= 2
INFO [2021-01-11 10:16:04] plot_cnv_references:Plotting heatmap.
INFO [2021-01-11 10:16:04] Colors for breaks:  #00008B,#24249B,#4848AB,#6D6DBC,#9191CC,#B6B6DD,#DADAEE,#FFFFFF,#EEDADA,#DDB6B6,#CC9191,#BC6D6D,#AB4848,#9B2424,#8B0000
INFO [2021-01-11 10:16:04] Quantiles of plotted data range: 0.893594909607933,1.00086930321871,1.00086930321871,1.00086930321871,1.11168747489251
INFO [2021-01-11 10:16:04] plot_cnv_references:Writing reference data to inferCNV/Astroglia/inferCNV1-3/infercnv.21_denoised.references.txt
INFO [2021-01-11 10:16:13] 

## Making the final infercnv heatmap ##
INFO [2021-01-11 10:16:13] ::plot_cnv:Start
INFO [2021-01-11 10:16:13] ::plot_cnv:Current data dimensions (r,c)=5394,1502 Total=8123186.37967838 Min=0.749570260465397 Max=1.46781862387323.
INFO [2021-01-11 10:16:13] ::plot_cnv:Depending on the size of the matrix this may take a moment.
INFO [2021-01-11 10:16:32] plot_cnv(): auto thresholding at: (0.888313 , 1.111687)
INFO [2021-01-11 10:16:32] plot_cnv_observation:Start
INFO [2021-01-11 10:16:33] Observation data size: Cells= 1079 Genes= 5394
INFO [2021-01-11 10:16:33] plot_cnv_observation:Writing observation groupings/color.
INFO [2021-01-11 10:16:33] plot_cnv_observation:Done writing observation groupings/color.
INFO [2021-01-11 10:16:33] plot_cnv_observation:Writing observation heatmap thresholds.
INFO [2021-01-11 10:16:33] plot_cnv_observation:Done writing observation heatmap thresholds.
INFO [2021-01-11 10:16:34] Colors for breaks:  #00008B,#24249B,#4848AB,#6D6DBC,#9191CC,#B6B6DD,#DADAEE,#FFFFFF,#EEDADA,#DDB6B6,#CC9191,#BC6D6D,#AB4848,#9B2424,#8B0000
INFO [2021-01-11 10:16:34] Quantiles of plotted data range: 0.888312525107489,1.00086930321871,1.00086930321871,1.00086930321871,1.11168747489251
INFO [2021-01-11 10:16:34] plot_cnv_observations:Writing observation data to inferCNV/Astroglia/inferCNV1-3/infercnv.observations.txt
INFO [2021-01-11 10:16:48] plot_cnv_references:Start
INFO [2021-01-11 10:16:48] Reference data size: Cells= 423 Genes= 5394
INFO [2021-01-11 10:16:51] plot_cnv_references:Number reference groups= 2
INFO [2021-01-11 10:16:51] plot_cnv_references:Plotting heatmap.
INFO [2021-01-11 10:16:51] Colors for breaks:  #00008B,#24249B,#4848AB,#6D6DBC,#9191CC,#B6B6DD,#DADAEE,#FFFFFF,#EEDADA,#DDB6B6,#CC9191,#BC6D6D,#AB4848,#9B2424,#8B0000
INFO [2021-01-11 10:16:51] Quantiles of plotted data range: 0.888312525107489,1.00086930321871,1.00086930321871,1.00086930321871,1.11168747489251
INFO [2021-01-11 10:16:51] plot_cnv_references:Writing reference data to inferCNV/Astroglia/inferCNV1-3/infercnv.references.txt

![image](https://user-images.githubusercontent.com/59709147/104163356-92823880-53f6-11eb-86c2-d56760dfa293.png)
![image](https://user-images.githubusercontent.com/59709147/104163241-6070d680-53f6-11eb-81bd-a17e8d3f7970.png)
![image](https://user-images.githubusercontent.com/59709147/104163267-6f578900-53f6-11eb-9fb0-7a9c9b606198.png)

My question are:
1.	because my data is about integration, the matrix with gene expression i extracted is right?
 
2. why the png plot named  “infercnv.18_HMM_pred.Bayes_Net.Pnorm_0.5.png” miss(it exists when i can get the right inferCNV results) and there is no file names “BayesNetOutput.HMMi6.hmm_mode-samples”. Besides, the “infercnv.17_HMM_predHMMi6.hmm_mode-samples.png” and “infercnv.19_HMM_predHMMi6.hmm_mode-samples.Pnorm_0.5.repr_intensities.png” are all blue? If it is because there is no any inferCNV between normal and patients, and Distribution of Expression are even?
 
![image](https://user-images.githubusercontent.com/59709147/104161806-bc862b80-53f3-11eb-9fb5-68cf6981678b.png)
![image](https://user-images.githubusercontent.com/59709147/104163495-cd846c00-53f6-11eb-8142-d417fe4fa47d.png)

3. There are several png plots in out_dir，“ infercnv.17.......”,“ infercnv.18....”,“ infercnv.19.....”, “infercnv”. My question is which one is the final inferCNV results and what do these plots mean?  
 

Thanks in advance!

**Comment by GeorgescuC** [comment]
Hi @Yinglei1 ,

I think the issue you have is that no CNVs are identified, so the color range on the HMM plots gets shifted. This should have been fixed in version 1.5.1 of infercnv. If you are using an older version, please update your installation and try running things again.

Regards,
Christophe.
