### ISSUE TITLE
Example data running: Error in Step 18

### ISSUE THREAD

**Issue by Hinsamoy** [broadinstitute/infercnv#288]
Hi:

Thank you for creating this useful tool.
This is my first time running this software. I am running example data to check if there is any mistake during installation.

Here is the error I got:

STEP 18: Run Bayesian Network Model on HMM predicted CNV's

INFO [2021-01-16 16:57:58] Creating the following Directory:  /var/folders/ps/d0_lvq6j731_s2t8jcvbzczh0000gn/T//RtmpsmGP5R/filebd48593f9809/BayesNetOutput.HMMi6.hmm_mode-samples
INFO [2021-01-16 16:57:58] Initializing new MCM InferCNV Object.
INFO [2021-01-16 16:57:58] validating infercnv_obj
Error in (function (cl, name, valueClass)  : 
  assignment of an object of class “character” is not valid for @‘cnv_regions’ in an object of class “MCMC_inferCNV”; is(value, "factor") is not TRUE

I tried running with HMM=FALSE,
I can finish step 21.

Please help me with this error.

**Comment by GeorgescuC** [comment]
Hi @Hinsamoy ,

Which version of infercnv are you running?
Could you provide me with the exact commands you ran to produce this error?

Regards,
Christophe.
