### ISSUE TITLE
Error message on Step 18 : Error in do.call(rbind, mcmc[[j]]) : second argument must be a list

### ISSUE THREAD

**Issue by PinaColadast** [broadinstitute/infercnv#289]
Hi,

Thank you for creating this great tool for the RNAseq community! I am trying to infer the CNV on my own data, following your instructions everything worked fine until Step 18. Here is the detailed message(the error was highlighted)

STEP 18: Run Bayesian Network Model on HMM predicted CNV's

INFO [2021-01-19 23:27:49] Initializing new MCM InferCNV Object.
INFO [2021-01-19 23:27:49] validating infercnv_obj
INFO [2021-01-19 23:27:49] Total CNV's:  75
INFO [2021-01-19 23:27:49] Loading BUGS Model.
INFO [2021-01-19 23:27:49] Running Sampling Using Parallel with  4 Cores
INFO [2021-01-20 02:09:10] Obtaining probabilities post-sampling
**_Error in do.call(rbind, mcmc[[j]]) : second argument must be a list_**
In addition: Warning message:
In parallel::mclapply(seq_along(obj@cell_gene), FUN = par_func,  :
  scheduled cores 1, 2, 3, 4 did not deliver results, all values of the jobs will be affected

I am wondering whether this is caused by my input data format or some other issues concerning the MCMC object being created during the run.
I'd appreciate it very much if you can provide any insights! 
Thanks a lot!

**Comment by GeorgescuC** [comment]
Hi @PinaColadast ,

This error is linked to multi-threading issues. Because of that it is unfortunately hard to pinpoint why it happens, but changing the number of threads used or increasing the resources available (if you are running on a grid/cloud) usually helps. Weirdly, some people have been able to solve this by increasing the number of threads while keeping resources at the same level, so trying different values may be needed.
I will however look into adding a fallback option to not run through the parallel::mclapply method to try to work around this issue/pinpoint the origin.

Regards,
Christophe.

**Comment by PinaColadast** [comment]
Weirdly it works very well on some machines but some would generate errors. I'll increase the number of threads and see how that goes. Thanks a lot :)

**Comment by Zymaniswenzai** [comment]
> Hi @PinaColadast ,
> 
> This error is linked to multi-threading issues. Because of that it is unfortunately hard to pinpoint why it happens, but changing the number of threads used or increasing the resources available (if you are running on a grid/cloud) usually helps. Weirdly, some people have been able to solve this by increasing the number of threads while keeping resources at the same level, so trying different values may be needed.
> I will however look into adding a fallback option to not run through the parallel::mclapply method to try to work around this issue/pinpoint the origin.
> 
> Regards,
> Christophe.

Hi,Christophe, I have same problem. How can I change the number of threads? 

	```
STEP 18: Run Bayesian Network Model on HMM predicted CNVs

INFO [2021-05-20 20:19:42] Creating the following Directory:  //home/lailab/data/gjw/infercnv/0520/BayesNetOutput.HMMi6.hmm_mode-samples
INFO [2021-05-20 20:19:42] Initializing new MCM InferCNV Object.
INFO [2021-05-20 20:19:42] validating infercnv_obj
INFO [2021-05-20 20:19:42] Total CNV's:  107
INFO [2021-05-20 20:19:42] Loading BUGS Model.
INFO [2021-05-20 20:19:42] Running Sampling Using Parallel with  4 Cores
INFO [2021-05-21 01:10:52] Obtaining probabilities post-sampling
Error in do.call(rbind, mcmc[[j]]) : second argument must be a list
In addition: Warning message:
In parallel::mclapply(seq_along(obj@cell_gene), FUN = par_func,  :
  scheduled core 3 did not deliver a result, all values of the job will be affected
```
That's my code. 
```
infercnv_obj = CreateInfercnvObject(raw_counts_matrix='scrna-count.txt',
                                    annotations_file='cluster_anno.txt',
                                    delim="\t",
                                    gene_order_file='gene_position.txt',
                                    ref_group_names=c('Monocytes','Macrophages'))

dir.create("/home/lailab/data/yz/infercnv/0520")
infercnv_obj = infercnv::run(infercnv_obj,
                             cutoff=0.1,  
                             out_dir="//home/lailab/data/yz/infercnv/0520",
                             cluster_by_groups=T, 
                             denoise=T,
                             HMM=T)
```

I noticed you uploaded a R script.as description, is it used to rerun frome STEP 18?
![image](https://user-images.githubusercontent.com/30076901/119072724-8ea69880-ba1e-11eb-97b8-bbf54c5b4ee2.png)

Thanks for your help!

zyman
