### ISSUE TITLE
Which clustering method used for Subcluster Analysis?

### ISSUE THREAD

**Issue by travelingtomat0** [broadinstitute/infercnv#291]
Hi,

thanks for your great tool! I am using the results of your tumor subcluster analysis and was wondering, which hierarchical clustering algorithm you are using to identify subclusters based on CNV's? Unfortunately https://github.com/broadinstitute/inferCNV/wiki/infercnv-tumor-subclusters does not give an insight into this..

Thanks in advance for your help!

Best,
Philip

**Comment by GeorgescuC** [comment]
Hi @travelingtomat0 ,

For the subclustering we use the hclust() function, with the method argument given through the "hclust_method" option, which by default is "ward.D2". Then the "tumor_subcluster_partition_method" option is used to decide at what branchings to split the hclust.
On the newest version of infercnv (on github) soon available on the devel branch of bioconductor, we also added an option to subcluster using the leiden algorithm on a k nearest neighbor search. Each subcluster then gets an hclust calculated for the purpose of organizing the cells on the figure.

Regards,
Christophe.
