### ISSUE TITLE
Error at step 18 :STEP 18: Run Bayesian Network Model on HMM predicted CNV's  ERROR [2021-01-22 16:21:38] Too many cores previded.

### ISSUE THREAD

**Issue by nlaillerbms** [broadinstitute/infercnv#292]
Hello,

I am running the pipeline on the test files provided and I'm encountering an error at Step 18:

STEP 18: Run Bayesian Network Model on HMM predicted CNV's

ERROR [2021-01-22 16:21:38] Too many cores previded. The following system has  1  cores. Please select an appropriate amount.

How can I change the number of cores assigned to the task, please?
Thanks!

**Comment by GeorgescuC** [comment]
Hi @nlaillerbms ,

The option you need to set is "num_threads" in the "run()" call.

Regards,
Christophe.
