### ISSUE TITLE
How to retrieve the cell order in infercnv.observations.txt

### ISSUE THREAD

**Issue by Lijunyao8** [broadinstitute/infercnv#295]
Hi, I want to generate infercnv.observations.txt from run.final.infercnv_obj. I can get the expression matrix from "object@expr.data[, unlist(object@observation_grouped_cell_indices)]" but how can I obtain the order of genes same to infercnv.observations.txt. If I have to generate infercnv.observations.txt from the infercnv::run, should I choose output_format = "NA" given I don't need plots but *.observations.txt. Thanks!

**Comment by GeorgescuC** [comment]
Hi @Lijunyao8 ,

The genes from @gene_order and the rows in the expr.data slot are already sorted in the same order during the object creation step. Genes later filtered are then also removed from both locations, so you do not need to change anything there.

Setting `output_format="NA"` will try to plot to your graphical interface, so you may get an error if there is none available.

Regards,
Christophe.

**Comment by Lijunyao8** [comment]
Hi, thanks for your reply. How about the order of cells? How to get the order of cells same to infercnv.observations.txt? I noticed that the matrix generated from object@expr.data[, unlist(object@observation_grouped_cell_indices)] is not exactly same to infercnv.observations.txt? Is there a way to get the matrix of infercnv.observations.txt from the object? Thank you!

**Comment by GeorgescuC** [comment]
Hi @Lijunyao8 ,

The order of the cells can change based on the options you have set for the run or for a custom plot. By default, if you check in the object@tumor_subclusters$hc field, you will find a list of hclust objects that are used to define the order of cells on the figure, and thus the matrix you are interested in. You can get the order ids of the cells in the matrix with the following snippet (quick edit based on code in `R/inferCNV_heatmap.R`):


```
ordered_names = NULL
for (obs_group in names(infercnv_obj@observation_grouped_cell_indices)) {
	ordered_names <- c(ordered_names, infercnv_obj@tumor_subclusters$hc[[ obs_group ]]$labels[infercnv_obj@tumor_subclusters$hc[[ obs_group ]]$order])
}
```

Regards,
Christophe.

**Comment by Lijunyao8** [comment]
Hi Christophe,

Thank you! Looks like the cnv value in object@expr.data (from run.final.infercnv_obj) is not the same as that in infercnv.observations.txt for a particular cell. Can you tell me how to generate values of infercnv.observations.txt from the object. Below is options I have set for the run.

infercnv_obj_default = infercnv::run(
    infercnv_obj,
    cutoff=0.1, # cutoff=1 works well for Smart-seq2, and cutoff=0.1 works well for 10x Genomics
    out_dir=paste0(output_path),
    cluster_by_groups=FALSE,
    analysis_mode="subclusters",
    plot_steps=FALSE,
    denoise=TRUE,
    HMM=TRUE,
    no_prelim_plot=TRUE,
    num_threads = 12,
    mask_nonDE_genes = TRUE,
    resume_mode = FALSE,
    no_plot = TRUE  # enable me when the job still fails with the highest stack limit
)
