### ISSUE TITLE
infercnv for bulk RNA-seq data

### ISSUE THREAD

**Issue by reuvenieli00** [broadinstitute/infercnv#296]
Hi, 

I am new to this tool,

First question:
wanted to check if I can use it for bulk data of RNA-seq

Second question:
can I use for the annotation file any genome of interest (not only human), of course that the expression matrix will have equivalent gene name as the annotation.

Thanks!!

**Comment by DarioS** [comment]
Duplicate of #141.

**Comment by GeorgescuC** [comment]
Hi @reuvenieli00 ,

For your second question, yes you can use any genome of interest for the gene order as long as the names match those in the count matrix.

Regards,
Christophe.
