### ISSUE TITLE
run time and parallelization

### ISSUE THREAD

**Issue by hartlama** [broadinstitute/infercnv#297]
I'm having issues with very long run time while using the subclusters method. Is there a way for me to run infercnv on multiple processors? Is the run function set up for parallelization? 

Thank you.

**Comment by GeorgescuC** [comment]
Hi @hartlama ,

There are 2 options to improve run speed.
The first is to change the "num_threads" option to increase the number processes used to calculate the random trees, but there is a limit to how much faster things will go.

The second is to [update your installation with the master branch on github](https://github.com/broadinstitute/infercnv/wiki/Installing-infercnv#option-d-install-infercnv-from-within-r-using-devtools) and use the new default subclustering method which is much faster and uses the leiden algorithm.

Regards,
Christophe.

**Comment by hartlama** [comment]
I combined both of these and it helped a lot. Thank you!
