### ISSUE TITLE
Is it possible to skip plot when using infercnv::run?

### ISSUE THREAD

**Issue by WWJiaxuan** [broadinstitute/infercnv#299]
Hi,

Thanks for your user-friendly software.

I am just wondering whether it is possible to skip plot .png graphs when using `infercnv::run`? Since I am not the administrator, and "X11", 'png" are not working on Linux.

Or is there any option to get the whole result without using "X11" and 'png"?

Thanks in advance and looking forward to your reply!

**Comment by WWJiaxuan** [comment]
Specifically, I would like get the final CNV scores without plotting the .png files. Can I achieve it?

**Comment by WWJiaxuan** [comment]
I found out there're several options to achieve so, e.g. `output_format = "pdf"`, `no_plot = T.` Never mind!

**Comment by zym826** [comment]
infercnv_obj2 = infercnv::run(infercnv_obj,
                             cutoff= 0.1,  
                             out_dir= 'epi_inferCNV_output',
							 cluster_by_groups = FALSE,
                             cluster_references = FALSE,
                             k_obs_groups = 5,
                             output_format = "pdf",
                             plot_steps = FALSE,
                             denoise = FALSE,
                             HMM=FALSE)
this code can obtain .pdf file
