### ISSUE TITLE
Ordering the heatmap figure by chr 1,2,3,4,.....,X,Y not 1,10,11,.....,X,Y.

### ISSUE THREAD

**Issue by mostafa-abbas** [broadinstitute/inferCNV#3]
Greetings! I am wondering if there is any flag to plot the heatmap with ordering the chromosome as 1,2,3,.....,X,Y  or  1,2,3,.....,23,24 as the example in wiki. 
Great Thanks,

**Comment by TimothyTickle** [comment]
Hello Mostafa,

The chromosomes should be ordered by the program in the order of the gen_pos.txt file. This gives you complete control over how the ordering of the chromosomes occurs. Please let me know if this is not the case for you or if this does not answer your question and thanks for using inferCNV!

Happy Science,

Tim

**Comment by mostafa-abbas** [comment]
Hi Tim,
First of all thank you so much for your answer.
These two files represent two examples for the same data: one with position file ordered as 1, 2, 3, ....,X,Y and the other is ordered as chr1, chr10, chr11, .....,chrX, chrY. You can note easily that the two figures are the same exactly with one difference which is the labels of x axis. This means that your script order the chromosomes regardless the gene position file. Based on my data I believe that your order is based on 1,10,11,...,X,Y regardless the position file and from the position file it takes the order of labels.


Kind Regards,
Mostafa


[exMGH_36_new_vg_chrs_numers_ref.pdf]
(https://github.com/broadinstitute/inferCNV/files/608382/exMGH_36_new_vg_chrs_numers_ref.pdf)
[exMGH_36_new_vg_chrs_charcters_ref.pdf](https://github.com/broadinstitute/inferCNV/files/608386/exMGH_36_new_vg_chrs_charcters_ref.pdf)

**Comment by mostafa-abbas** [comment]
Hi Tim,
First of all thanks so much for your help. 
It works with me.
I am so sorry, I have another problem.
But I have an a problem when I am trying to run the reference example which is 

"(
Error in par(mar = margins, mgp = mgp) :
  invalid value specified for graphical parameter "mar"
Calls: infer_cnv ... plot_cnv -> plot_cnv_references -> heatmap.cnv -> par
In addition: Warning message:
In heatmap.cnv(obs_data, Rowv = obs_dendrogram, Colv = FALSE, cluster.by.col = FALSE,  :
  Discrepancy: row dendrogram is asked; cluster.by.row is set to `TRUE'.
Execution halted
 )"

This is plot the heatmap for but the problem in plotting the normal cells in the same file(like the following file: )
[quickstart_test.pdf](https://github.com/broadinstitute/inferCNV/files/608968/quickstart_test.pdf)

Kind Regards,
Mostafa
