### ISSUE TITLE
question about leiden algorithm

### ISSUE THREAD

**Issue by callaL** [broadinstitute/infercnv#306]
Thank you for developing such an excellent tool.When I use the new default subclustering method（leiden） to analyze the heterogeneity, with the same parameters and the same input file, the result of output heterogeneity is different，can you explain it?
This is the first result
![image](https://user-images.githubusercontent.com/52152132/110425094-c4eea000-80de-11eb-83df-cea948c903c2.png)
This is the second result
![image](https://user-images.githubusercontent.com/52152132/110425180-e485c880-80de-11eb-8846-15d9a29ca4de.png)

**Comment by GeorgescuC** [comment]
Hi @callaL ,

Can you provide me with the exact set of options you have used as well as the commit hash or docker tag you are using?

Also, is the data you are using the example one or a publicly available dataset?

Regards,
Christophe.

**Comment by Ezra-Bron** [comment]
Hello, i have a relevant question about the the new default subclustering method leiden. what's the difference between leiden and random trees besides the processing time (leiden is much faster)? do you have any recommendations when deciding on which methods is better, more accurate in computing the copy numbers?

**Comment by GeorgescuC** [comment]
Hi @Ezra-Bron ,

For some details on the random trees method, you can check [this section of the wiki](https://github.com/broadinstitute/infercnv/wiki/infercnv-tumor-subclusters#random_trees-method). As for the Leiden method, it is described [in this paper](https://www.nature.com/articles/s41598-019-41695-z).
One of the effective differences as a user besides run time is that with the random trees method you define a threshold p-value for determining whether a given bifurcation is statistically significant, while for the Leiden method you set a "resolution" parameter that may be less clear, but is explained as follows:
> The interpretation of the resolution parameter γ is quite straightforward. The parameter functions as a sort of threshold: communities should have a density of at least γ, while the density between communities should be lower than γ.

I would recommend running infercnv using the Leiden subclustering with default settings at first (especially if you have >10k cells) and checking with the residual expression plot (so the non HMM one) if the subclustering seems accurate. If the subclustering is not refined enough you can try increasing the resolution parameter, while if they look too subdivided, you can try decreasing it. Either option you decide to go with, make sure you look at the residual expression figure that the subclustering is good.

Regards,
Christophe.
