### ISSUE TITLE
same values in map_metadata_from_infercnv.txt

### ISSUE THREAD

**Issue by hartlama** [broadinstitute/infercnv#307]
Hi, 

I ran inferCNV as shown below. map_metadata_from_infercnv.txt was generated in the output, but all of the values are the same in each column (either 0 or FALSE). infercnv.17_HMM_predHMMi6.leiden.hmm_mode-subclusters.png will not open, but the other HMM figures will. Any ideas on why this may have happened?

`object = CreateInfercnvObject(raw_counts_matrix=GetAssayData(readRDS("Seurat.rds"), slot = "counts"),
                              annotations_file="annotations.txt",
                              delim="\t",
                              gene_order_file="gencode_v19_gene_pos.txt",
                              ref_group_names=c("normal")) 

object = infercnv::run(object,
                       cutoff=0.1,
                       out_dir="", 
                       cluster_by_groups=TRUE,
                       analysis_mode = "subclusters",
                       denoise=TRUE,
                       HMM=TRUE,
                       num_threads=4,
                       tumor_subcluster_partition_method="leiden")`

**Comment by GeorgescuC** [comment]
Hi @hartlama , 

I am not sure about why the figure 17 does not open. Did R return any error for your run? By reloading the backup from that step you can remake the figure if needed (or to check if the error is reproducible and rule out system issues).

For the question about the results, what do the other HMM figures look like? Is there any CNV signal?

Regards,
Christophe.
