### ISSUE TITLE
INFO [2021-03-26 16:52:20] Observation data size: Cells= 0 Genes= 3422 Error in obs_dendrogram[[1]] : 下标出界

### ISSUE THREAD

**Issue by sgh212** [broadinstitute/infercnv#309]
Hi,

Thanks for building this great tool! The following error occurred when I was running. What should I do?
Thanks

STEP 15: Clustering samples (not defining tumor subclusters)
 
INFO [2021-03-26 16:24:27] define_signif_tumor_subclusters(p_val=0.1
INFO [2021-03-26 16:24:27] define_signif_tumor_subclusters(), tumor: normal
INFO [2021-03-26 16:50:48] cut tree into: 1 groups
INFO [2021-03-26 16:50:48] -processing normal,normal_s1
INFO [2021-03-26 16:50:48] -mirroring for hspike
INFO [2021-03-26 16:50:48] define_signif_tumor_subclusters(p_val=0.1
INFO [2021-03-26 16:50:48] define_signif_tumor_subclusters(), tumor: spike_tumor_cell_normal
INFO [2021-03-26 16:50:48] cut tree into: 1 groups
INFO [2021-03-26 16:50:48] -processing spike_tumor_cell_normal,spike_tumor_cell_normal_s1
INFO [2021-03-26 16:50:48] define_signif_tumor_subclusters(), tumor: simnorm_cell_normal
INFO [2021-03-26 16:50:49] cut tree into: 1 groups
INFO [2021-03-26 16:50:49] -processing simnorm_cell_normal,simnorm_cell_normal_s1
INFO [2021-03-26 16:51:20] ::plot_cnv:Start
INFO [2021-03-26 16:51:20] ::plot_cnv:Current data dimensions (r,c)=3422,8822 Total=30214335.4587527 Min=0.771642046482251 Max=1.40356867037487.
INFO [2021-03-26 16:51:20] ::plot_cnv:Depending on the size of the matrix this may take a moment.
INFO [2021-03-26 16:52:20] plot_cnv(): auto thresholding at: (0.887817 , 1.113869)
INFO [2021-03-26 16:52:20] plot_cnv_observation:Start
INFO [2021-03-26 16:52:20] Observation data size: Cells= 0 Genes= 3422
Error in obs_dendrogram[[1]] : 下标出界
此外: Warning messages:
1: In strsplit(conditionMessage(e), "\n") :
  输入的字符串1不适用于此语言环境
2: In strsplit(conditionMessage(e), "\n") :
  输入的字符串1不适用于此语言环境
3: In strsplit(conditionMessage(e), "\n") :
  输入的字符串1不适用于此语言环境
4: In strsplit(conditionMessage(e), "\n") :
  输入的字符串1不适用于此语言环境
5: In strsplit(conditionMessage(e), "\n") :
  输入的字符串1不适用于此语言环境
6: In strsplit(conditionMessage(e), "\n") :
  输入的字符串1不适用于此语言环境
7: In strsplit(conditionMessage(e), "\n") :
  输入的字符串1不适用于此语言环境
8: In strsplit(conditionMessage(e), "\n") :
  输入的字符串1不适用于此语言环境
9: In strsplit(conditionMessage(e), "\n") :
  输入的字符串1不适用于此语言环境
10: In max(nchar(obs_annotations_names)

**Comment by DrZhaoJie** [comment]
@sgh212 Hi, I met the same error as you, do you solve it?

**Comment by GeorgescuC** [comment]
Hi @sgh212 ,

Based on the log, there are no cells part of the observations. Are all your cells assigned to references?

Regards,
Christophe.
