### ISSUE TITLE
Calculating observations.txt from infercnv_obj.rds

### ISSUE THREAD

**Issue by jiayiliujiayi** [broadinstitute/infercnv#311]
Hi, 

I ran running infercnv::run with the argument "no_plot = FALSE, no_prelim_plot = FALSE", and found that the output files does not include "infercnv.observations.txt" file, as well as other ".txt" files. 

I'm just wondering: is there a function to calculate the "observations.txt" from the output file "infercnv_obj.rds"?  

Thank you!  

Best,
Jiayi

**Comment by GeorgescuC** [comment]
Hi @jiayiliujiayi ,

Those files are generated at the same time as the figures, so by disabling the plotting, they are not written. The data itself is contained within the infercnv@expr.data field of the .rds objects, and you can select the cells that are part of the observations using infercnv@observation_grouped_cell_indices . Sorting/subclustering information is stored in infercnv@tumor_subclusters as both hclusts and lists.

Regards,
Christophe.
