### ISSUE TITLE
Error running filterHighPNormals

### ISSUE THREAD

**Issue by yoshihiko1218** [broadinstitute/infercnv#315]
My infercnv version is 1.6 and when I run filterHighPNormals, I got error of: unable to find an inherited method for function ‘setBayesMaxPNormal’ for signature ‘"infercnv"’.

**Comment by GeorgescuC** [comment]
Hi @yoshihiko1218 ,

This is weird as I have not seen other reports of this error before. How did you install infercnv? Could you try reinstalling from Biocondcutor or using the github code?
Instructions for the different methods of installing infercnv can be found [on the wiki.](https://github.com/broadinstitute/infercnv/wiki/Installing-infercnv)

Regards,
Christophe.
