### ISSUE TITLE
How to distinguish non-tumor-derived up-regulated gene reads from CNV? 

### ISSUE THREAD

**Issue by QueenieBear** [broadinstitute/infercnv#317]
@dinvlad Thank you for your awesome package！
But I am a little confused whether inferCNV can explain that the rising or declining reads of certain genes （compared to the ref sample）is due to copy number variety at DNA level or the non-tumor stimulation at mRNA level.

In my case, when I compare the data from normal sample to tumor sample, I find a certain cluster of immune cells has great cnv number(which has never been reported in any literature)

What’s more, mesenchymal cell, which is expected to be one of the cell type of my tumor sample, has little CNV in final heatmap.

On of my concern is the tumor in my case is a pediatric tumor with quite little CNV and would this affect the result when using inferCNV?

Looking for your response!😭

**Comment by GeorgescuC** [comment]
Hi @QueenieBear ,

As I do not know what specific type of tumor you are studying, I can not say for your specific samples, but not all tumors have high number of CNVs. Some have few to none, some have a few hallmarks, and some have them all over. This can even be one of the criteria for the classification of tumor types between tumors affecting the same cell types.

For your question about DNA vs non-tumor stimulation, there is part of the answer [in a different post]( https://github.com/broadinstitute/infercnv/issues/312). However, if you observe results that look odd, the best way to validate them would be to run Whole Exome Sequencing on the cell subpopulation of interest. For other samples where that data type is also available, there is concordance with infercnv results, but that cannot be generalized as a guarantee that it will always be true.
There is however one common known case where infercnv detects signal without cells being malignant, and that is chr6 of immune cells where the MHC genes are located.


Regards,
Christophe.
