### ISSUE TITLE
how to change the colors of sample labels?

### ISSUE THREAD

**Issue by gufranca** [broadinstitute/infercnv#319]
Hi,
Thanks again for developing this very useful tool. I am plotting the cnv heatmaps, but I would like to use custom colors for labeling the samples on the left bar of the heatmaps (figure attached). Is it possible to adjust those colors? I couldn't find any indication from the help of plot_cnv function. 
Thanks,
Gustavo
![infercnv_t1_edit](https://user-images.githubusercontent.com/1247681/114910662-28f63980-9dec-11eb-907f-b82be7ab5dc5.png)

**Comment by GeorgescuC** [comment]
Hi @gufranca ,

There is no direct option to change the color palette at this time, but it is easy to do if you clone the code locally to tweak. The color palette used is defined at the very top of the R/inferCNV_heatmap.R file in this function:

```
get_group_color_palette <- function(){
    return(colorRampPalette(RColorBrewer::brewer.pal(12,"Set3")))
}
```


To make this change, start by cloning the github:
```
git clone https://github.com/broadinstitute/infercnv
cd infercnv
```

Then modify the R/inferCNV_heatmap.R file to use the palette you prefer. Save the file.
Then start an R session and install the package from this version of the code. If you are in an R session where infercnv was already loaded, unload and reload it so it is updated in your workspace:


```
R
> install.packages("./", repos=NULL, type="source")
> detach("package:infercnv", unload=T)
> library(infercnv)
```


Regards,
Christophe.

**Comment by gufranca** [comment]
> Hi @gufranca ,
> 
> There is no direct option to change the color palette at this time, but it is easy to do if you clone the code locally to tweak. The color palette used is defined at the very top of the R/inferCNV_heatmap.R file in this function:
> 
> ```
> get_group_color_palette <- function(){
>     return(colorRampPalette(RColorBrewer::brewer.pal(12,"Set3")))
> }
> ```
> 
> To make this change, start by cloning the github:
> 
> ```
> git clone https://github.com/broadinstitute/infercnv
> cd infercnv
> ```
> 
> Then modify the R/inferCNV_heatmap.R file to use the palette you prefer. Save the file.
> Then start an R session and install the package from this version of the code. If you are in an R session where infercnv was already loaded, unload and reload it so it is updated in your workspace:
> 
> ```
> R
> > install.packages("./", repos=NULL, type="source")
> > detach("package:infercnv", unload=T)
> > library(infercnv)
> ```
> 
> Regards,
> Christophe.

Thanks a lot, Christophe! Sorry for the delayed reply.
