### ISSUE TITLE
inferCNV plot error

### ISSUE THREAD

**Issue by springwellflow** [broadinstitute/infercnv#320]
Hi,
Thanks for developing this very useful tool.  Here, I meet some problems and ask for your help. InferCNV producted blank pngs with any contents after running two-step inferCNV. So I use the 'plot_cnv' function to run again. But it reports a error.  Could you tell me how to solve this problem?
![批注 2021-04-20 142605](https://user-images.githubusercontent.com/80184275/115347889-8c190f00-a1e4-11eb-893e-168bdc451b3f.png)

**Comment by laillern** [comment]
Hello,
I had the same exact problem this morning, starting at Step 15.
The plots generated at earlier steps were produced without issue.

Thanks!

**Comment by GeorgescuC** [comment]
Hi @springwellflow @laillern ,

Which version of infercnv are you using?
What options did you use for the run() method?
Could you provide me with an example backup that I can reproduce the error with (shared privately only for debugging purpose)?
If not, could you send me the clustering results stored in the infercnv_obj@tumor_subclusters slot to try to identify what doesn't match the expected information?

Regards,
Christophe.
