### ISSUE TITLE
HMM pred CNV state

### ISSUE THREAD

**Issue by DrZhaoJie** [broadinstitute/infercnv#321]
Hi, I run HMM pred CNV, but the state in the output file "HMM_CNV_predictions.*.pred_cnv_regions.dat"  were 2/3/4/5, not 
0x: complete loss
0.5x: loss of one copy
1x: neutral
1.5x: addition of one copy
2x: addition of two copies
3x: essentially a placeholder for >2x copies but modeled as 3x.
where was I wrong then? Thank you very much!

**Comment by GeorgescuC** [comment]
Hi @DrZhaoJie ,

Nothing wrong! The 2/3/4/5 correspond to the HMM states, each of them matching to a specific fold change. You can find more [details on the wiki](https://github.com/broadinstitute/infercnv/wiki/infercnv-i6-HMM-type#infercnv-i6-hmm) but the short version is:

    State 1: 0x: complete loss
    State 2: 0.5x: loss of one copy
    State 3: 1x: neutral
    State 4: 1.5x: addition of one copy
    State 5: 2x: addition of two copies
    State 6: 3x: essentially a placeholder for >2x copies but modeled as 3x.



Regards,
Christophe.
