### ISSUE TITLE
Error in saveRDS(infercnv_obj, reload_info$expected_file_names[[step_count]]) of inferCNV v1.7.2

### ISSUE THREAD

**Issue by danshu** [broadinstitute/infercnv#328]
Hi,

I have updated inferCNV to version 1.7.2 and have this error message at step 15:
	STEP 15: computing tumor subclusters via leiden

INFO [2021-05-18 09:31:12] define_signif_tumor_subclusters(p_val=0.1
INFO [2021-05-18 09:31:12] define_signif_tumor_subclusters(), tumor: all_observations
INFO [2021-05-18 10:05:12] define_signif_tumor_subclusters(), tumor: Hep1
INFO [2021-05-18 10:05:25] define_signif_tumor_subclusters(), tumor: Hep2
INFO [2021-05-18 10:05:26] define_signif_tumor_subclusters(), tumor: Hep4
INFO [2021-05-18 10:05:45] define_signif_tumor_subclusters(), tumor: Hep5
INFO [2021-05-18 10:06:13] -mirroring for hspike
INFO [2021-05-18 10:06:13] define_signif_tumor_subclusters(p_val=0.1
INFO [2021-05-18 10:06:13] define_signif_tumor_subclusters(), tumor: all_observations
INFO [2021-05-18 10:06:17] define_signif_tumor_subclusters(), tumor: simnorm_cell_Hep1
INFO [2021-05-18 10:06:17] define_signif_tumor_subclusters(), tumor: simnorm_cell_Hep2
INFO [2021-05-18 10:06:17] define_signif_tumor_subclusters(), tumor: simnorm_cell_Hep4
INFO [2021-05-18 10:06:17] define_signif_tumor_subclusters(), tumor: simnorm_cell_Hep5
Error in saveRDS(infercnv_obj, reload_info$expected_file_names[[step_count]]) : 
  'file' must be non-empty string
Calls: <Anonymous> -> saveRDS
Execution halted

Best,
Quan

**Comment by GeorgescuC** [comment]
Hi @danshu ,

If you can update your installation using the latest commit on github (not yet in BioConductor), the issue should be fixed.

https://github.com/broadinstitute/infercnv/wiki/Installing-infercnv#option-d-install-infercnv-from-within-r-using-devtools

Regards,
Christophe.
