### ISSUE TITLE
The cross samples to estimate the CNV using inferCNV packages 

### ISSUE THREAD

**Issue by honghh2018** [broadinstitute/infercnv#330]
Hi, Dr.
    I wonder that can i use the normal sample's T cells as reference for tumor sample ?  because it was two samples T1 and N1 and they were generated by 10x platform. 
    the result showing the normal sample had CNV cells when I run the test. i guess the batch effective among various samples.
    So i hope can hear the appropriate advice from you
 Best,
hanhuihong

**Comment by honghh2018** [comment]
can anyone hear this?

**Comment by GeorgescuC** [comment]
Hi @honghh2018 ,

I am not sure I understand correctly, what are samples T1 and N1?
What data/samples did you use for the run with the normal sample, and with what reference?

Regards,
Christophe.

**Comment by honghh2018** [comment]
Hi @GeorgescuC，
    On my case, I am looking into the different samples, like two samples,  in which it can run  with combined matrix of these two samples without consider the batch effective.   
    It was right ? when two sample matrixs aggregate into one matrix to run the infercnv.
    Hope hearing from you
Best,
Hanhuihong

**Comment by GeorgescuC** [comment]
Hi @honghh2018 ,

If both use the same sequencing and preparation, if you have a population of cells that can act as a control in your tumor sample, you can try running infercnv with the combined matrix and see if the control looks good. If not, you can try integrating the datasets using another tool and refer to https://github.com/broadinstitute/infercnv/issues/346#issuecomment-898020900 for how to run infercnv while skipping the steps that are already done on the integrated matrix.

Regards,
Christophe.
