### ISSUE TITLE
infercnv.observations_dendrogram.txt contains only part of the cell information to be predicted

### ISSUE THREAD

**Issue by hah2468** [broadinstitute/infercnv#336]
Thanks for developing this great software. But when I use it, I divide all the cells to be inferred into two categories, and select the parameter cluster_by_groups=F. I want to get the clustering results of all the cells to be inferred（all observations）, but there is only one type of cell information in infercnv.observations_dendrogram.txt. What should I do, or can I get the clustering results from other files?

**Comment by GeorgescuC** [comment]
Hi @hah2468 ,

What clustering information are you looking for, the dendrogram/hclust or the results of the subclustering mode?

If you are looking for the dendrogram/hclust, the file you are looking at will contain the tree in the commonly used newick format.
If you are looking for subclustering, done through leiden clustering or random trees for example, you need to run infercnv with the HMM enabled `HMM=TRUE` and the analysis mode set to subclusters `analysis_mode="subclusters"`. You can then find the cluster to cell table in `17_HMM_predHMMi6.*.hmm_mode-subclusters.cell_groupings` with the asterisk being the subclustering method (default is leiden). 

You can also access the results directly in R by looking at the `infercnv_obj@tumor_subclusters` slot in the final object.

Regards,
Christophe.
