### ISSUE TITLE
How to calculate the score of CNV ?

### ISSUE THREAD

**Issue by xiangjiaobunana** [broadinstitute/infercnv#338]
Hi,
Thanks for your useful package!
How do we identify the real malignant cells? Can we calculate the CNV score for each cell from infercnv.observations.txt?
Thanks in advance and looking forward to your reply!

**Comment by zym826** [comment]
Hello,
Do you know how to calculate CNV score?
I have a problem in  identify the real malignant cells, I don't find suitable method.

**Comment by GeorgescuC** [comment]
Hi @xiangjiaobunana @zym826 ,

The HMM option is something that may suit your needs, it will generate a set of CNV predictions for each of your samples/clusters based on the analysis mode option selected, usually subclustering being the best as soon as you have multiple subclones within one sample/annotation.

You can also choose to calculate scores (sum of absolute difference from the mean, or sum squared difference for example) per chromosome or region for each cell and set a threshold based on the values seen in the reference for assigning a state to the tumor sample cells.

Regards,
Christophe.

**Comment by GeorgescuC** [comment]
Hi @BilyanaStoilova ,

The easiest way to do it in R is to directly use the object returned by `infercnv::run()`, which can also be accessed by loading the backup with `infercnv_obj = readRDS("run.final.infercnv_obj")`. The slots `infercnv_obj@reference_grouped_cell_indices` and `infercnv_obj@observation_grouped_cell_indices` will give you the column indices for respectively the reference and tumor cells, subdivided by annotations, allowing you to calculate things for both the references `infercnv_obj@expr.data[, unlist(infercnv_obj@reference_grouped_cell_indices), drop=FALSE]` and the tumor `infercnv_obj@expr.data[, unlist(infercnv_obj@observation_grouped_cell_indices), drop=FALSE]`. You can also do the calculations by chromosome using the information stored in `infercnv_obj@gene_order` to select the rows.

Regards,
Christophe.
