### ISSUE TITLE
out_dir error

### ISSUE THREAD

**Issue by GHAStVHenry** [broadinstitute/infercnv#339]
Had error: #327 

Upgraded to 1.8.0

Then had error #328 

Upgraded to 1.9.0 on master (6cd35a4)

Now I'm getting some version of this error related to `out_dir`:
```
Error in file.path(out_dir, sprintf("%02d_incoming_data.infercnv_obj",  : 
  object 'out_dir' not found
Calls: <Anonymous> ... eval -> eval -> .get_relevant_args_list -> file.path
Execution halted
```

similar error if I set `out_dir` to:
- actual directory
- not set (NULL)
- tempFile()

**Comment by hoyu310** [comment]
I am getting these exact same errors, hope the out_dir error can be fixed soon

**Comment by t-carroll** [comment]
Also getting the same error with 1.9.0, which was bypassed by downgrading to 1.8.0. The error message seems to be coming from the `.get_relevant_args_list` function under inferCNV_ops.R. Does it have something to do with how the default arguments (including `out_dir`) are commented out in ce40e4e? 

Looks like in 1.9.0, the `.get_relevant_args_list` function is expecting the options given to run() to be passed to the dots argument of `.get_relevant_args_list`, but from a basic look at the code I can't work out how that happens. anyway as far as I can work out, it looks like `out_dir` is no longer defined within this internal function even when passed to `run`.

**Comment by GeorgescuC** [comment]
Hi @GHAStVHenry @hoyu310 @t-carroll ,

I have pushed a patch that should address the issue on the github master branch. Could you try updating your install and try running infercnv again?

Regards,
Christophe.

**Comment by t-carroll** [comment]
Hi Christophe,

Have just updated my installation to this patch (c631d06) and everything completes successfully on my dataset now. Thanks very much for the update!

Best,
Tom
