### ISSUE TITLE
GMD install and DESCRIPTION

### ISSUE THREAD

**Issue by orrzor** [broadinstitute/inferCNV#34]
Hi inferCNV team,
Thanks for all your work on this package!

Two quick things-
1.
As previously noted, the GMD package no longer seems to be supported on CRAN, but you can get the archived version. 
https://cran.r-project.org/web/packages/GMD/index.html
Also if you try install.packages("GMD") in R 3.5, you get a warning that GMD is not available. I am running R 3.5 and the following works,
```
packageurl <- "https://cran.r-project.org/src/contrib/Archive/GMD/GMD_0.3.3.tar.gz"
install.packages(packageurl, repos=NULL, type="source")
```
I would suggest adding this to your quick start section.

2.
In DESCRIPTION, can you update the version to 0.3?

Best! -Orr

**Comment by GeorgescuC** [comment]
Hi @orrzor ,

Thanks for both comments! They have now been integrate into the master branch.

Best,
Christophe.
