### ISSUE TITLE
Annotation differences between infercnv.png and ngchm heatmap

### ISSUE THREAD

**Issue by ElenaTT** [broadinstitute/infercnv#340]
Hello,

I am using NGCHM to explore the estimated Copy Number Aberrations obtained by inferCNV, however the heatmap visualized by NGCHM displays different rows annotations compared to the png produced by inferCNV. 
Any suggestions on how to fix the annotations in the NGCHM heatmap? 
I originally obtained the heatmap (in the attached image on the right) with 'cluster_by_groups=T' and converted the R object to an NGCHM object as described [here](https://github.com/broadinstitute/infercnv/wiki/Next-Generation-Clustered-Heat-Map)
I checked a few individual cells extracting rownames from the NGCHM heatmap and the annotation in the original inferCNV heatmap appears correct. 

Thanks in advance for the help, 

Elena 

![image](https://user-images.githubusercontent.com/8389172/124656742-935cca00-de6f-11eb-8ce9-9260c604c1bc.png)

**Comment by brownmp** [comment]
Hello @ElenaTT,

Sorry to hear you're having an issue with infercnv_NGCHM.
Do you have the file `infercnv.observation_groupings.txt` in your infercnv output directory? If so, are the values in the column "Annotation Group" ordered?

~MBrown

**Comment by ElenaTT** [comment]
Hi @brownmp, 

thanks for the reply (and for developing the infercnv_NGCHM package). Yes, I have `infercnv.observation_groupings.txt` in the infercnv output directory and the "Annotation Group" has values in increasing order (from 1 to 6). 
Should the cell order match the cell order in any other file? 

Thanks, 

Elena

**Comment by brownmp** [comment]
Hello @ElenaTT,

So clearly the the rows are in the correct order, but the annotation bars along the side are not. Interestingly, both the ordering of the rows and the annotation bars are taken from `infercnv.observation_groupings.txt`. The samples in `infercnv.observation_groupings.txt` should be in reverse order from what is seen in the heatmap. Given the reverse ordering in `infercnv.observation_groupings.txt`, are the samples in this file ordered correctly by chance?

Best,
~MBrown

**Comment by ElenaTT** [comment]
Hi @brownmp, 

Thanks for clarifying. I have checked and the first cell ids in `infercnv.observation_groupings.txt` are indeed the last samples appearing in the heatmap, following reverse ordering. However, as you can see in the screenshots, these cells all have the same annotation group in the `infercnv.observation_groupings.txt` but they appear as different colors in the NGCHM annotation bar. 

In case it helps, I am running `NGCHM_0.12.6` , `infercnvNGCHM_0.1.0` and while creating the NGCHM object I got no errors but a couple of warnings 
> infercnv_obj = readRDS("run.final.infercnv_obj")
> 
> ngchm(infercnv_obj          = infercnv_obj, 
>       out_dir              = '/Desktop/NGCHM/', 
>       path_to_shaidyMapGen = '/Desktop/NGCHM/ShaidyMapGen.jar')
>
> >Warning: No heat map description provided in properties : chm.info.caption.
> >Warning: Column label type (axisTypes where = col or both) not specified.  Will use generic linkouts menu
> >Warning: Row label type (axisTypes where = row or both) not specified.  Will use generic linkouts menu

Any thought of what could cause the issue? 

Thanks, 

Elena

![image](https://user-images.githubusercontent.com/8389172/125854458-4c100377-9e38-4f6a-bde8-eb20704e77f2.png)

![image](https://user-images.githubusercontent.com/8389172/125854382-ffff89f0-5d96-4f96-a5ba-c28c5d6e4583.png)

**Comment by brownmp** [comment]
Hi @ElenaTT, 

Okay, interesting. So is the `infercnv.observation_groupings.txt` file located in your output directory `out_dir = '/Desktop/NGCHM/',` ? 
NGCHM looks for the `infercnv.observation_groupings.txt` file in the output directory passed to the ngchm function. 
I find it easiest to make the output directory for ngchm the same as the output directory for your infercnv run. 

~MBrown

**Comment by ElenaTT** [comment]
Hi @brownmp, 

Yes, the output folder on the Desktop contains `infercnv.observation_groupings.txt`. 

I have also tried using as output directory for NGCHM the same directory that has all infercnv output but it did not change the result - the NGCHM object looks the same, with the same mismatched annotations.

Thanks for the help, 

Elena

**Comment by brownmp** [comment]
@ElenaTT,

Im still working to recreate this issue. Can you share the commands you used for running infercnv? If you would rather email me for privacy concerns you can email me at mbrown@broadinstitute.org. 

~MBrown

**Comment by ElenaTT** [comment]
@brownmp I used infercnv 1.5.1 and the following commands:

> infercnv_obj = CreateInfercnvObject(raw_counts_matrix="XYZ.counts.matrix",
>                                     annotations_file="XYZ_annotation.txt",
>                                     delim="\t",
>                                     gene_order_file="GRCh38_genomic_positions.txt",
>                                     ref_group_names=NULL)
> 
> infercnv_obj = infercnv::run(infercnv_obj,
>                              cutoff=0.1,  
>                              out_dir="XYZ",  
>                              cluster_by_groups=T,   
>                              denoise=T,
>                              HMM=T, 
>                              analysis_mode='subclusters', 
>                             num_threads =4)

If it helps I can give you access to the inferCNV object, `infercnv.observation_groupings.txt` and any other relevant files. 

Best, 

Elena

**Comment by brownmp** [comment]
@ElenaTT  Yeah it looks like I'm having a hard time recreating the issue on my own. So if you could share your infercnv object and the document that would be great!

~MBrown

**Comment by ElenaTT** [comment]
@brownmp Sure -- you have mail!

**Comment by brownmp** [comment]
@ElenaTT 
Thank you for the email! I was able to recreate the issue and fix the issue. I have updated the Master branch for infercnvNGCHM with the corrections. 
Please let me know if everything works correctly with the latest update!

~MBrown

**Comment by ElenaTT** [comment]
Hi @brownmp, 

Great news - thanks for helping with this. 

I have updated infercnvNGCHM to version 0.1.1 and I still get an error (below), even when I use the inferCNV folder as the output directory. 
Any suggestion on how to fix this? 

Elena

> INFO [2021-07-19 14:12:37] Creating NGCHM as infercnv.ngchm
> INFO [2021-07-19 14:12:37] Initializing new NGCHM InferCNV Object.
>  Error in file(con, "r") : cannot open the connection
> In addition: Warning message:
> In file(con, "r") :
>   cannot open file '/var/folders/rk/3gb9_8c1427ggwtbgk1jxgr528dxd5/T//Rtmp9rJDgc/shaidy52c431690d9/label/bdc95a07aeb4fdadac2cf5472e11f9cdd555b478/labels.txt': No such file or directory
>

**Comment by brownmp** [comment]
@ElenaTT 
Sorry to hear this. Were you getting this error prior to the most recent update?
~MBrown

**Comment by ElenaTT** [comment]
Hi @brownmp, 
No - I did not get this error prior to updating. It is bizarre, as I am running the same code (on the same data) and it previously worked..
Thanks, 

Elena

**Comment by brownmp** [comment]
Hi @ElenaTT,

That is very bizarre. 
Could you do me a favor and run the test data that is provided by infercnv in the `example` directory, then run infercnvNGCHM on the test data to see if this error still occurs?

~MBrown

**Comment by ElenaTT** [comment]
Hi @brownmp, 

Thanks for the suggestion - I tried on the `example` data provided with infercnv and the code runs fine. 
Can you confirm that you were you able to successfully create the NGCHM object on the R object I sent you via email and share which version of `infercnv` and `NGCHM` did you use? 
I can try to have the same exact versions as you and try again..

**Comment by brownmp** [comment]
Hi @ElenaTT,

Sorry again about the issue. 
Yes of course, here is a picture of the ngchm that I created using the infercnv object you provided to me:
<img width="938" alt="Screen Shot 2021-07-23 at 1 45 58 PM" src="https://user-images.githubusercontent.com/35315693/126821285-6b4b41c0-fc16-46f3-8891-2223eccfa1bc.png">

The library versions I have loaded:
- infercnvNGCHM_0.1.1 
- NGCHM_0.12.6
- infercnv_1.9.0
