### ISSUE TITLE
Argument "include.spike" in infercnv version 1.8

### ISSUE THREAD

**Issue by chayanit1234** [broadinstitute/infercnv#348]
I would like to run infercnv analysis using argument "include.spike = T"
I got an error unused argument (include.splike = T)

How can i run the analysis with include.spike = T?

**Comment by GeorgescuC** [comment]
Hi @chayanit1234 ,

This option has been removed a while back as a hidden spike is automatically generated as part of the HMM modeling/predicting. You can access it by looking at the infercnv_obj@.hspike field on the final object.

Regards,
Christophe.
