### ISSUE TITLE
How to modify the left color bar?

### ISSUE THREAD

**Issue by cqz7633** [broadinstitute/infercnv#351]
I want to add new annotations and corresponding colors here like the color bar on the rigtht. I didn't find the corresponding parameters. How can I modify the source code. Thanks! 
![50d3eaac217f2637203365ddae41adf](https://user-images.githubusercontent.com/45682275/128833482-744d9d55-389f-4b66-a211-1f4c092f1d47.png)

**Comment by GeorgescuC** [comment]
Hi @cqz7633 ,

At this time, the color of the first bar represents the splits from k_obs_groups if that option is set, but we have plans to make it show the subclustering information instead when it is generated. If you want to manually edit the code, the part that handles that is in `R/inferCNV_heatmap.R` in the `.plot_cnv_observations` method. The vector `split_groups` is the one that contains the information for defining the color groups for the first column, however you have to be careful about how you change it if you want to manually provide that information as the cells are reordered based on the hclust displayed on the side, and cells are plotted from bottom to top.

Regards,
Christophe.

**Comment by cqz7633** [comment]
> Hi @cqz7633 ,
> 
> At this time, the color of the first bar represents the splits from k_obs_groups if that option is set, but we have plans to make it show the subclustering information instead when it is generated. If you want to manually edit the code, the part that handles that is in `R/inferCNV_heatmap.R` in the `.plot_cnv_observations` method. The vector `split_groups` is the one that contains the information for defining the color groups for the first column, however you have to be careful about how you change it if you want to manually provide that information as the cells are reordered based on the hclust displayed on the side, and cells are plotted from bottom to top.
> 
> Regards,
> Christophe.

Thanks for your detailed reply. There is a new problem for me. What does the result of different states (0.5,1,1.5,2) obtained by performing step 20 mean? I didn't find the introduction of step 20. Do they correspond to 0.5x, 1x, 1.5x, 2x?

**Comment by GeorgescuC** [comment]
HI @cqz7633 ,

At steps 17/19, the values are the HMM states as described in https://github.com/broadinstitute/infercnv/wiki/infercnv-i6-HMM-type. These values are then converted in step 20 to the matching fold change, so the values are indeed 0.5x, 1x, 1.5x, 2x, 3x+ .

Regards,
Christophe.
