### ISSUE TITLE
Step 15 Error

### ISSUE THREAD

**Issue by bigape1** [broadinstitute/infercnv#352]
Hi,

I am running InferCNV 1.8 on a data set of about 6500 cells and 20,000 genes.

The following error was thrown during step 15:

> STEP 15: computing tumor subclusters via leiden
> 
> INFO [2021-08-15 12:52:37] define_signif_tumor_subclusters(p_val=0.1
> INFO [2021-08-15 12:52:37] define_signif_tumor_subclusters(), tumor: all_observations
> INFO [2021-08-15 13:06:38] define_signif_tumor_subclusters(), tumor: endothelial_normal
> INFO [2021-08-15 13:06:46] define_signif_tumor_subclusters(), tumor: fibroblast_normal
> INFO [2021-08-15 13:06:55] -mirroring for hspike
> INFO [2021-08-15 13:06:55] define_signif_tumor_subclusters(p_val=0.1
> INFO [2021-08-15 13:06:55] define_signif_tumor_subclusters(), tumor: all_observations
> INFO [2021-08-15 13:06:56] define_signif_tumor_subclusters(), tumor: simnorm_cell_endothelial_normal
> INFO [2021-08-15 13:06:57] define_signif_tumor_subclusters(), tumor: simnorm_cell_fibroblast_normal
> Error in saveRDS(infercnv_obj, reload_info$expected_file_names[[step_count]]) : 
>   'file' must be non-empty string

I called infercnv with the following arguments:

> infercnv_all = infercnv::run(infercnv_obj = infercnv_obj,
>                              cutoff = 1,
>                              out_dir=  here("new"),  
>                              window_length = 101,
>                              num_ref_groups = NULL,
>                              denoise = T,
>                              ref_subtract_use_mean_bounds = TRUE,
>                              cluster_by_groups = FALSE,
>                              cluster_references = TRUE,
>                              k_obs_groups = 1,
>                              hclust_method = "ward.D2",
>                              max_centered_threshold = 3,
>                              scale_data = FALSE,
>                              HMM = TRUE,
>                              HMM_transition_prob = 1e-06,
>                              HMM_report_by = c("subcluster"),
>                              HMM_type = c("i6"),
>                              BayesMaxPNormal = 0.5,
>                              sim_method = "meanvar",
>                              sim_foreground = FALSE,
>                              reassignCNVs = TRUE,
>                              analysis_mode = c("subclusters"),
>                              tumor_subcluster_pval = 0.1,
>                              k_nn = 30,
>                              leiden_resolution = 1,
>                              png_res = 500,
>                              plot_probabilities = TRUE,
>                              save_rds = TRUE,
>                              save_final_rds = TRUE,
>                              diagnostics = FALSE,
>                              resume_mode = TRUE,
>                              num_threads = 4,
>                              )     
> 

I am not sure if it is relevant but prior to this error I was prompted to install miniconda during Step 15 - and did so:

> STEP 15: computing tumor subclusters via leiden
> 
> INFO [2021-08-15 12:00:44] define_signif_tumor_subclusters(p_val=0.1
> INFO [2021-08-15 12:00:44] define_signif_tumor_subclusters(), tumor: all_observations
> No non-system installation of Python could be found.
> Would you like to download and install Miniconda?
> Miniconda is an open source environment management system for Python.
> See https://docs.conda.io/en/latest/miniconda.html for more details.
> 
> Would you like to install Miniconda? [Y/n]: Y

My final session info is below:

> R version 4.1.1 (2021-08-10)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Debian GNU/Linux 10 (buster)
> 
> Matrix products: default
> BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.8.0
> LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.8.0
> 
> locale:
>  [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8        LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8   
>  [6] LC_MESSAGES=C.UTF-8    LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C           LC_TELEPHONE=C        
> [11] LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
>  [1] leiden_0.3.9    infercnv_1.8.0  here_1.0.1      forcats_0.5.1   stringr_1.4.0   dplyr_1.0.7     purrr_0.3.4    
>  [8] readr_2.0.1     tidyr_1.1.3     tibble_3.1.3    ggplot2_3.3.5   tidyverse_1.3.1
> 
> loaded via a namespace (and not attached):
>   [1] TH.data_1.0-10              colorspace_2.0-2            ellipsis_0.3.2              modeltools_0.2-23          
>   [5] rprojroot_2.0.2             futile.logger_1.4.3         XVector_0.32.0              GenomicRanges_1.44.0       
>   [9] fs_1.5.0                    rstudioapi_0.13             listenv_0.8.0               fansi_0.5.0                
>  [13] mvtnorm_1.1-2               lubridate_1.7.10            coin_1.4-1                  xml2_1.3.2                 
>  [17] codetools_0.2-18            splines_4.1.1               doParallel_1.0.16           libcoin_1.0-8              
>  [21] jsonlite_1.7.2              broom_0.7.9                 argparse_2.0.4              dbplyr_2.1.1               
>  [25] rjags_4-10                  png_0.1-7                   compiler_4.1.1              httr_1.4.2                 
>  [29] backports_1.2.1             assertthat_0.2.1            Matrix_1.3-4                cli_3.0.1                  
>  [33] limma_3.48.3                formatR_1.11                tools_4.1.1                 igraph_1.2.6               
>  [37] coda_0.19-4                 gtable_0.3.0                glue_1.4.2                  GenomeInfoDbData_1.2.6     
>  [41] RANN_2.6.1                  rappdirs_0.3.3              Rcpp_1.0.7                  Biobase_2.52.0             
>  [45] cellranger_1.1.0            vctrs_0.3.8                 ape_5.5                     nlme_3.1-152               
>  [49] iterators_1.0.13            fastcluster_1.2.3           globals_0.14.0              rvest_1.0.1                
>  [53] lifecycle_1.0.0             gtools_3.9.2                future_1.21.0               edgeR_3.34.0               
>  [57] zlibbioc_1.38.0             MASS_7.3-54                 zoo_1.8-9                   scales_1.1.1               
>  [61] hms_1.1.0                   MatrixGenerics_1.4.2        parallel_4.1.1              SummarizedExperiment_1.22.0
>  [65] sandwich_3.0-1              lambda.r_1.2.4              RColorBrewer_1.1-2          SingleCellExperiment_1.14.1
>  [69] reticulate_1.20             gridExtra_2.3               stringi_1.7.3               reshape_0.8.8              
>  [73] S4Vectors_0.30.0            foreach_1.5.1               caTools_1.18.2              BiocGenerics_0.38.0        
>  [77] GenomeInfoDb_1.28.1         rlang_0.4.11                pkgconfig_2.0.3             matrixStats_0.60.0         
>  [81] bitops_1.0-7                lattice_0.20-44             tidyselect_1.1.1            parallelly_1.27.0          
>  [85] plyr_1.8.6                  magrittr_2.0.1              R6_2.5.0                    IRanges_2.26.0             
>  [89] gplots_3.1.1                generics_0.1.0              multcomp_1.4-17             DelayedArray_0.18.0        
>  [93] DBI_1.1.1                   pillar_1.6.2                haven_2.4.3                 withr_2.4.2                
>  [97] fitdistrplus_1.1-5          survival_3.2-12             RCurl_1.98-1.3              modelr_0.1.8               
> [101] crayon_1.4.1                futile.options_1.0.1        phyclust_0.1-30             KernSmooth_2.23-20         
> [105] utf8_1.2.2                  tzdb_0.1.2                  locfit_1.5-9.4              grid_4.1.1                 
> [109] readxl_1.3.1                reprex_2.0.1                digest_0.6.27               stats4_4.1.1               
> [113] munsell_0.5.0    

Thank you for your time.

**Comment by GeorgescuC** [comment]
Hi @bigape1 ,

This issue should be fixed on the github version, but I pushed the fix to Bioconductor today so updating an install from BioConductor should solve the issue after the builds are updated (daily). To make sure your version has updated when you will try, the version should be 1.8.1 (bioconductor release 3.13) or 1.9.1 (bioconductor devel).

Regards,
Christophe.

**Comment by bigape1** [comment]
Thank you @GeorgescuC

**Comment by Sa753** [comment]
I am having a nearly similar issue. I am using infercnv version 1.9.1


Error: Python module igraph was not found.

Detected Python configuration:

python:         /usr/bin/python
libpython:      /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config/libpython2.7.dylib
pythonhome:     /System/Library/Frameworks/Python.framework/Versions/2.7:/System/Library/Frameworks/Python.framework/Versions/2.7
version:        2.7.10 (default, Feb 22 2019, 21:55:15)  [GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.37.14)]
numpy:          /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy
numpy_version:  1.8.0
numpy:          /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy

python versions found: 
 /Users/opt/anaconda3/envs/r-reticulate/bin/python
 /usr/bin/python
 /Users/opt/anaconda3/envs/anaconda3/bin/python
 /Users/opt/anaconda3/envs/Python3/bin/python
 /Users/cpdb-venv/bin/python

Could you please help?
