### ISSUE TITLE
how to download the gene_position_data for inferCNV

### ISSUE THREAD

**Issue by honghh2018** [broadinstitute/infercnv#354]
Hi guys,
    I want to download the gene_position_data, but i can not find the website ?
   So, where the site i can download the gene_position_data file ?
Any advices would be appreciated.
Best,
Hanhuihong

**Comment by GeorgescuC** [comment]
Hi @honghh2018 ,

You can find pre-generated files at https://data.broadinstitute.org/Trinity/CTAT/cnv/ .

If you want to use a different gene list/organism, you can generate one using the `scripts/gtf_to_position_file.py` utility.

Regards,
Christophe.
