### ISSUE TITLE
CNV predictions not reproducible when running the same analysis again

### ISSUE THREAD

**Issue by NBeumer** [broadinstitute/infercnv#355]
Dear InferCNV developers,

many thanks for providing this nice tool!

During my analyses, I stumbled across the finding that the CNV predictions (InferCNV version 1.6.0) looked different when I re-ran the same analysis pipeline. This happened despite using the random number generator "L'Ecuyer-CMRG" (which normally ensures reproducible results in parallel computing) and setting a random seed.
The problem appears to occur during step 18 (Bayesian Mixture Model) as the plots generated in step 17 (HMM) and 21 (denoising) are identical between runs.

Below you can find a small example that produced different output when I ran it twice.

```
library(infercnv)

counts <- system.file("extdata", "oligodendroglioma_expression_downsampled.counts.matrix.gz", package = "infercnv")
annotations <- system.file("extdata", "oligodendroglioma_annotations_downsampled.txt", package = "infercnv")
gene_order <- system.file("extdata", "gencode_downsampled.EXAMPLE_ONLY_DONT_REUSE.txt", package = "infercnv")

sc_data_infercnv <- CreateInfercnvObject(raw_counts_matrix = counts,
                                         gene_order_file = gene_order,
                                         annotations_file = annotations,
                                         ref_group_names = c("Microglia/Macrophage","Oligodendrocytes (non-malignant)"))

RNGkind("L'Ecuyer-CMRG")
set.seed(2021)
sc_data_infercnv_results <- infercnv::run(sc_data_infercnv,
                                          cutoff = 1,
                                          cluster_by_groups = T,
                                          analysis_mode = "subclusters",
                                          denoise = T,
                                          HMM = T,
                                          out_dir = paste0("infercnv_results"),
                                          resume_mode = F)


cat("\n\n\n\n")
print(sessionInfo())
```

The CNV profiles detected during step 18 look like this (substantial changes are visible on chromosomes 2 and 9):

![infercnv 18_HMM_pred Bayes_Net Pnorm_0 5_run_1](https://user-images.githubusercontent.com/49677058/131494017-8d0cb2c5-346d-4aae-b17b-244f4b1d613e.png)
![infercnv 18_HMM_pred Bayes_Net Pnorm_0 5_run_2](https://user-images.githubusercontent.com/49677058/131494016-d65066b7-d9a0-4c03-a2ae-c522d3207f54.png)

The stout from my two consecutive runs, the sessionInfo and all the generated heat maps are attached.

Do you have an idea how one could potentially circumvent this problem?

Many thanks in advance and best wishes!

[infercnv preliminary_run_1](https://user-images.githubusercontent.com/49677058/131494880-2a1ed292-5a4c-41f5-89b2-f25ce62ac96c.png)
[infercnv_run_2](https://user-images.githubusercontent.com/49677058/131494893-836e685f-9d6b-4a1e-850d-676ec8eb1847.png)
[infercnv 17_HMM_predHMMi6 rand_trees hmm_mode-subclusters_run_1](https://user-images.githubusercontent.com/49677058/131494926-ddddf4ec-a209-417d-9610-d557da2abd01.png)
[infercnv 17_HMM_predHMMi6 rand_trees hmm_mode-subclusters_run_2](https://user-images.githubusercontent.com/49677058/131494932-ae0bad0e-2329-42f6-b764-5bd86b5ca54f.png)
[infercnv 18_HMM_pred Bayes_Net Pnorm_0 5_run_1](https://user-images.githubusercontent.com/49677058/131494017-8d0cb2c5-346d-4aae-b17b-244f4b1d613e.png)
[infercnv 18_HMM_pred Bayes_Net Pnorm_0 5_run_2](https://user-images.githubusercontent.com/49677058/131494016-d65066b7-d9a0-4c03-a2ae-c522d3207f54.png)
[infercnv 19_HMM_predHMMi6 rand_trees hmm_mode-subclusters Pnorm_0 5 repr_intensities_run_1](https://user-images.githubusercontent.com/49677058/131494948-ae68aa9c-50c3-4c3b-95f3-b6acce871b74.png)
[infercnv 19_HMM_predHMMi6 rand_trees hmm_mode-subclusters Pnorm_0 5 repr_intensities_run_2](https://user-images.githubusercontent.com/49677058/131494969-6642599e-e2a2-4957-a8b8-7ba6b0c061dd.png)
[infercnv 21_denoised_run_1](https://user-images.githubusercontent.com/49677058/131494986-b260d59f-f649-47fb-8e8f-ed54c824ad10.png)
[infercnv 21_denoised_run_2](https://user-images.githubusercontent.com/49677058/131494990-8a3b3900-aef5-4b1f-88d4-ffb3d307301d.png)
[infercnv_run_1](https://user-images.githubusercontent.com/49677058/131494998-5435b792-1041-4767-9070-018624e7fd8e.png)
[infercnv_run_2](https://user-images.githubusercontent.com/49677058/131495004-5a9918f3-9312-4569-a3d9-8d649c218dab.png)
[stout_and_sessioninfo_run_1.txt](https://github.com/broadinstitute/infercnv/files/7083471/stout_and_sessioninfo_run_1.txt)
[stout_and_sessioninfo_run_2.txt](https://github.com/broadinstitute/infercnv/files/7083472/stout_and_sessioninfo_run_2.txt)

**Comment by GeorgescuC** [comment]
Hi @NBeumer ,

Although you specifically used this random number generator, step 18 calls a tool that is external to R, JAGS, through the "rjags" package, which does not use that same generator unless explicitly requested. You can find more information about how to do this on page 10 of the rjags documentation [here](https://cran.r-project.org/web/packages/rjags/rjags.pdf), but this is not something we are using as setting a random seed is not the usual way to go.

Regards,
Christophe.

**Comment by NBeumer** [comment]
Dear Cristophe,
many thanks for the explanation and the link to the rjags documentation. 
Now it is much clearer to me how this issue comes about.
Many thanks again and best wishes!
