### ISSUE TITLE
Long time for this step "plot_cnv_observation:Writing observation groupings/color"

### ISSUE THREAD

**Issue by anchormok** [broadinstitute/infercnv#363]
Hi, thanks for your excellent package.

Recently I employed this package and find a problem that this step ("plot_cnv_observation:Writing observation groupings/color") would last for several hours while several seconds from other users. What's the matter? Should I continue waiting?

Looking forward to your reply. Thank you very much.

**Comment by anchormok** [comment]
STEP 1: incoming data

INFO [2021-09-25 19:31:42] 

	STEP 02: Removing lowly expressed genes

INFO [2021-09-25 19:31:42] ::above_min_mean_expr_cutoff:Start
INFO [2021-09-25 19:31:44] Removing 25181 genes from matrix as below mean expr threshold: 0.1
INFO [2021-09-25 19:31:45] validating infercnv_obj
INFO [2021-09-25 19:31:45] There are 8799 genes and 25885 cells remaining in the expr matrix.
INFO [2021-09-25 19:31:49] no genes removed due to min cells/gene filter
INFO [2021-09-25 19:32:39] 

	STEP 03: normalization by sequencing depth

INFO [2021-09-25 19:32:39] normalizing counts matrix by depth
INFO [2021-09-25 19:32:42] Computed total sum normalization factor as median libsize: 6421.000000
INFO [2021-09-25 19:33:38] 

	STEP 04: log transformation of data

INFO [2021-09-25 19:33:38] transforming log2xplus1()
INFO [2021-09-25 19:34:40] 

	STEP 08: removing average of reference data (before smoothing)

INFO [2021-09-25 19:34:40] ::subtract_ref_expr_from_obs:Start inv_log=FALSE, use_bounds=TRUE
INFO [2021-09-25 19:34:40] subtracting mean(normal) per gene per cell across all data
INFO [2021-09-25 19:34:46] -subtracting expr per gene, use_bounds=TRUE
INFO [2021-09-25 19:36:16] 

	STEP 09: apply max centered expression threshold: 3

INFO [2021-09-25 19:36:16] ::process_data:setting max centered expr, threshold set to: +/-:  3
INFO [2021-09-25 19:37:40] 

	STEP 10: Smoothing data per cell by chromosome

INFO [2021-09-25 19:37:40] smooth_by_chromosome: chr: chr1
INFO [2021-09-25 19:38:01] smooth_by_chromosome: chr: chr10
INFO [2021-09-25 19:38:21] smooth_by_chromosome: chr: chr11
INFO [2021-09-25 19:38:44] smooth_by_chromosome: chr: chr12
INFO [2021-09-25 19:39:02] smooth_by_chromosome: chr: chr13
INFO [2021-09-25 19:39:21] smooth_by_chromosome: chr: chr14
INFO [2021-09-25 19:39:40] smooth_by_chromosome: chr: chr15
INFO [2021-09-25 19:39:59] smooth_by_chromosome: chr: chr16
INFO [2021-09-25 19:40:18] smooth_by_chromosome: chr: chr17
INFO [2021-09-25 19:40:38] smooth_by_chromosome: chr: chr18
INFO [2021-09-25 19:40:56] smooth_by_chromosome: chr: chr19
INFO [2021-09-25 19:41:15] smooth_by_chromosome: chr: chr2
INFO [2021-09-25 19:41:37] smooth_by_chromosome: chr: chr3
INFO [2021-09-25 19:41:58] smooth_by_chromosome: chr: chr4
INFO [2021-09-25 19:42:18] smooth_by_chromosome: chr: chr5
INFO [2021-09-25 19:42:40] smooth_by_chromosome: chr: chr6
INFO [2021-09-25 19:43:00] smooth_by_chromosome: chr: chr7
INFO [2021-09-25 19:43:22] smooth_by_chromosome: chr: chr8
INFO [2021-09-25 19:43:43] smooth_by_chromosome: chr: chr9
INFO [2021-09-25 19:45:27] 

	STEP 11: re-centering data across chromosome after smoothing

INFO [2021-09-25 19:45:27] ::center_smooth across chromosomes per cell
INFO [2021-09-25 19:47:19] 

	STEP 12: removing average of reference data (after smoothing)

INFO [2021-09-25 19:47:19] ::subtract_ref_expr_from_obs:Start inv_log=FALSE, use_bounds=TRUE
INFO [2021-09-25 19:47:19] subtracting mean(normal) per gene per cell across all data
INFO [2021-09-25 19:47:30] -subtracting expr per gene, use_bounds=TRUE
INFO [2021-09-25 19:49:08] 

	STEP 14: invert log2(FC) to FC

INFO [2021-09-25 19:49:08] invert_log2(), computing 2^x
INFO [2021-09-25 19:51:14] 

	STEP 15: Clustering samples (not defining tumor subclusters)

INFO [2021-09-25 19:51:14] define_signif_tumor_subclusters(p_val=0.1
INFO [2021-09-25 19:51:14] define_signif_tumor_subclusters(), tumor: Fibroblasts-C1
INFO [2021-09-25 19:51:26] cut tree into: 1 groups
INFO [2021-09-25 19:51:26] -processing Fibroblasts-C1,Fibroblasts-C1_s1
INFO [2021-09-25 19:51:26] define_signif_tumor_subclusters(), tumor: Hepatic stellate cells-C2
INFO [2021-09-25 20:00:16] cut tree into: 1 groups
INFO [2021-09-25 20:00:16] -processing Hepatic stellate cells-C2,Hepatic stellate cells-C2_s1
INFO [2021-09-25 20:00:16] define_signif_tumor_subclusters(), tumor: Myofibroblasts-C2
INFO [2021-09-25 20:00:26] cut tree into: 1 groups
INFO [2021-09-25 20:00:26] -processing Myofibroblasts-C2,Myofibroblasts-C2_s1
INFO [2021-09-25 20:00:26] define_signif_tumor_subclusters(), tumor: Myofibroblasts-C1
INFO [2021-09-25 20:00:37] cut tree into: 1 groups
INFO [2021-09-25 20:00:37] -processing Myofibroblasts-C1,Myofibroblasts-C1_s1
INFO [2021-09-25 20:00:37] define_signif_tumor_subclusters(), tumor: Hepatic stellate cells-C3
INFO [2021-09-25 20:00:40] cut tree into: 1 groups
INFO [2021-09-25 20:00:40] -processing Hepatic stellate cells-C3,Hepatic stellate cells-C3_s1
INFO [2021-09-25 20:00:40] define_signif_tumor_subclusters(), tumor: Fibroblasts-C2
INFO [2021-09-25 20:00:43] cut tree into: 1 groups
INFO [2021-09-25 20:00:43] -processing Fibroblasts-C2,Fibroblasts-C2_s1
INFO [2021-09-25 20:00:43] define_signif_tumor_subclusters(), tumor: Proliferating hepatic stellate cells-C2
INFO [2021-09-25 20:08:33] cut tree into: 1 groups
INFO [2021-09-25 20:08:33] -processing Proliferating hepatic stellate cells-C2,Proliferating hepatic stellate cells-C2_s1
INFO [2021-09-25 20:08:33] define_signif_tumor_subclusters(), tumor: Hepatic stellate cells-C1
INFO [2021-09-25 20:44:03] cut tree into: 1 groups
INFO [2021-09-25 20:44:03] -processing Hepatic stellate cells-C1,Hepatic stellate cells-C1_s1
INFO [2021-09-25 20:44:03] define_signif_tumor_subclusters(), tumor: Proliferating hepatic stellate cells-C1
INFO [2021-09-25 20:53:11] cut tree into: 1 groups
INFO [2021-09-25 20:53:11] -processing Proliferating hepatic stellate cells-C1,Proliferating hepatic stellate cells-C1_s1
INFO [2021-09-25 20:53:11] define_signif_tumor_subclusters(), tumor: Liver progenitor cells
INFO [2021-09-25 20:55:17] cut tree into: 1 groups
INFO [2021-09-25 20:55:17] -processing Liver progenitor cells,Liver progenitor cells_s1
INFO [2021-09-25 20:55:17] define_signif_tumor_subclusters(), tumor: Proliferating liver progenitor cells
INFO [2021-09-25 20:55:19] cut tree into: 1 groups
INFO [2021-09-25 20:55:19] -processing Proliferating liver progenitor cells,Proliferating liver progenitor cells_s1
INFO [2021-09-25 20:55:19] define_signif_tumor_subclusters(), tumor: Endothelial cells
INFO [2021-09-25 21:15:43] cut tree into: 1 groups
INFO [2021-09-25 21:15:43] -processing Endothelial cells,Endothelial cells_s1
INFO [2021-09-25 21:19:14] ::plot_cnv:Start
INFO [2021-09-25 21:19:14] ::plot_cnv:Current data dimensions (r,c)=8799,25885 Total=228422194.286818 Min=0.712516575198132 Max=1.69581302546337.
INFO [2021-09-25 21:19:15] ::plot_cnv:Depending on the size of the matrix this may take a moment.
INFO [2021-09-25 21:26:30] plot_cnv(): auto thresholding at: (0.796676 , 1.209121)
INFO [2021-09-25 21:26:35] plot_cnv_observation:Start
INFO [2021-09-25 21:26:35] Observation data size: Cells= 21033 Genes= 8799
INFO [2021-09-25 21:26:35] clustering observations via method: ward.D
INFO [2021-09-25 21:26:39] plot_cnv_observation:Writing observation groupings/color.



This is my running record.

**Comment by GeorgescuC** [comment]
Hi @anchormok ,

Which version of infercnv are you running?

In the current version of infercnv, the only thing that happens after that line of logging and before the next one is combining the columns for the matrix to output, then outputting the matrix, which may take a bit of time but not remain stuck on for too long. The only thing I could see happening is the disk infercnv is trying to write to being under heavy load or slow. Could that be an issue on the machine you are using?

Regards,
Christophe.
