### ISSUE TITLE
 plot_cnv()：Error in rep(contig_name, contig_tbl[contig_name]) : 'times'参数不对

### ISSUE THREAD

**Issue by shijianasdf** [broadinstitute/infercnv#364]
When I run infercnv::run(),I got the error as follow:
> ```r
>INFO [2021-09-27 08:40:40] ::plot_cnv:Depending on the size of the matrix this may take a moment.
>INFO [2021-09-27 08:41:23] plot_cnv(): auto thresholding at: (0.834789 , 1.165211)
>Error in rep(contig_name, contig_tbl[contig_name]) : 'times'参数不对
> ```
my cell annotation file like this:
>AAACCTGAGATGCCTT-1	4
>AAACCTGAGCTAAACA-1	11
>AAACCTGAGTGCGTGA-1	0
>AAACCTGAGTGGCACA-1	15

my gene order file like this:
>FAM138A	chr1	34554	36081
>OR4F5	chr1	65419	71585
>AL627309.1	chr1	89295	133723
>AL627309.3	chr1	89551	91105

**Comment by GeorgescuC** [comment]
Hi @shijianasdf ,

Can you run `which(is.na(infercnv_obj@gene_order$chr))` to see if any of the chromosomes is not properly assigned? If any index is returned, you can check which gene it matches and what it looks like in the gene order file.

Regards,
Christophe.
