### ISSUE TITLE
which output file represent CNV value？

### ISSUE THREAD

**Issue by linanabc123** [broadinstitute/infercnv#367]
I want to find the file which represent CNV value within  the output files. And the output files represent what individually.

**Comment by GeorgescuC** [comment]
Hi @linanabc123 ,

You can find details about the different outputs of infercnv on the wiki.
Figures and matrices:
https://github.com/broadinstitute/infercnv/wiki/Output-Files

HMM tables:
https://github.com/broadinstitute/infercnv/wiki/inferCNV-HMM-based-CNV-Prediction-Methods

Regards,
Christophe.
