### ISSUE TITLE
including known normal cells as observations

### ISSUE THREAD

**Issue by igordot** [broadinstitute/infercnv#370]
Are there any benefits or drawbacks to including known normal cells as observations? It seems like a good control to check if they are being properly classified with a flat copy number profile. Are there some problems with this approach?

For background, sometimes all of my non-reference cells end up with an aberrant copy number profile. This may be real, but it could be due to some normalization artifact. I include multiple cell types in the reference, so I doubt it's something related to the specific cell type of my observations. Including some normal cells as observations may help to determine if the results are real.

**Comment by GeorgescuC** [comment]
Hi @igordot ,

As long as the cell types you are adding in the observations are also represented in the normal, there should be no issue in having normal cells as observations to use as control. The one thing that you may want to pay attention to is not adding too many different cell types, and their relative proportions, as that is something that can affect the initial filtering of genes that are expressed above the threshold. This can lead to signal from low proportion cell population to be filtered out, or genes with no expression in certain cells being kept and diluting the actual signal after smoothing.

Regards,
Christophe.
