### ISSUE TITLE
Blue HMM State Colors For Amplifications

### ISSUE THREAD

**Issue by tjbencomo** [broadinstitute/infercnv#373]
I recently ran inferCNV v1.7.1 on 10x data for a single patient, grouping tumor cells by their subpopulations. When I examine the final HMM heatmap image (`infercnv.19_HMM_predHMMi6.hmm_mode-samples.Pnorm_0.5.repr_intensities.png`), there
are a few distinct blue CNVs in the TSK subpopulation in chromosomes 3, 9, and 11. 

I assumed these CNVs would be deletions due to their blue color, but looking at `HMM_CNV_predictions.HMMi6.hmm_mode-samples.Pnorm_0.5.pred_cnv_regions.dat` indicates that they are amplifications (state = 2). Should all of these CNVs be red as they are all amplified, or can amplifications be both red and blue?

![infercnv 19_HMM_predHMMi6 hmm_mode-samples Pnorm_0 5 repr_intensities](https://user-images.githubusercontent.com/26121995/139343072-ef7786a9-7a6e-4d57-97bc-549e94f52327.png)

```
# HMM_CNV_predictions.HMMi6.hmm_mode-samples.Pnorm_0.5.pred_cnv_regions.dat
cell_group_name cnv_name        state   chr     start   end
Tumor_KC_Basal.Tumor_KC_Basal_s1        chr1-region_2   4       chr1    151540305       154627999
Tumor_KC_Basal.Tumor_KC_Basal_s1        chr6-region_22  4       chr6    31546870        33298401
Tumor_KC_Cyc.Tumor_KC_Cyc_s1    chr1-region_28  4       chr1    151340640       155173475
Tumor_KC_Cyc.Tumor_KC_Cyc_s1    chr14-region_35 2       chr14   104085679       105480170
Tumor_KC_Cyc.Tumor_KC_Cyc_s1    chr6-region_49  4       chr6    31686949        33206831
Tumor_KC_Diff.Tumor_KC_Diff_s1  chr1-region_55  4       chr1    150730196       155262430
Tumor_KC_Diff.Tumor_KC_Diff_s1  chr14-region_62 2       chr14   104085679       105480170
TSK.TSK_s1      chr1-region_80  4       chr1    151291797       154963853
TSK.TSK_s1      chr11-region_84 2       chr11   110174880       134253370
TSK.TSK_s1      chr3-region_97  2       chr3    196596  73069199
TSK.TSK_s1      chr9-region_104 2       chr9    121038  37778972
TSK.TSK_s1      chr9-region_106 4       chr9    100427156       128542288
```

**Comment by GeorgescuC** [comment]
Hi @tjbencomo ,

Yes the HMM states are as you described.

The page you referred to was indeed outdated as only the "infercnv i6 HMM type" had been updated. The "infercnv HMM based CNV prediction methods" is now also up to date. Thank you for reporting this!

Regards,
Christophe.
