### ISSUE TITLE
problem creating inferCNV object

### ISSUE THREAD

**Issue by bpitarchj** [broadinstitute/infercnv#375]
Hi everyone,

I am trying to use inferCNV to analyze some 10X data I have. I used python scanpy to preprocess the file and generate the annotation file and the matrix just as it appears in the examples. However, it seems like something is not working properly:

```
Error in CreateInfercnvObject(raw_counts_matrix = matrix, annotations_file = note,  : 
  Please make sure that all the annotated cell  names match a sample in your data matrix.
```
I checked if the names of the samples were the same in both matrix and annotation file. I also checked the gene names and the possible presence of unwanted spaces (all my files are saved as .tsv) and everything seemed to be okay. Does anybody know a possible explanation?

Thanks

**Comment by bpitarchj** [comment]
I solved it already. The problem was with the annotation file: samples names must be in the index of the data.table, not in a new column.

**Comment by SenicLight** [comment]
Thanks!!! you solve this problem that make me terrible and angry one all night.

**Comment by SenicLight** [comment]
i sware that the package inferCNV is a rotten litter and the dogshit with a lot of inexplicable errors and inflexible requirments.
