### ISSUE TITLE
Step 15 error: Error in unlist(object) : long vectors not supported yet:

### ISSUE THREAD

**Issue by adhisadi** [broadinstitute/infercnv#379]
Hi,
I am running infercnv_1.10.1 on 10X dataset in over 80k cells. 
infercnv_run = infercnv::run(infercnv_obj = infercnv_obj, cutoff=0.1, out_dir="nov_22_output_files", analysis_mode="subclusters", cluster_by_groups=F, plot_steps=F, denoise=T, no_prelim_plot=F, HMM=T)

I am running through this error in  step15:
        STEP 15: computing tumor subclusters via leiden

INFO [2021-11-23 11:00:46] define_signif_tumor_subclusters(p_val=0.1
INFO [2021-11-23 11:00:46] define_signif_tumor_subclusters(), tumor: all_observations
Error in unlist(object) :
  long vectors not supported yet: ../../src/include/Rinlinedfuns.h:537
Calls: <Anonymous> ... .single_tumor_leiden_subclustering -> leiden -> leiden.matrix -> unlist
Execution halted

Could you provide some instruction on how to solve this issue?
Thank you.

**Comment by GeorgescuC** [comment]
Hi @adhisadi ,

This issue should be fixed in the latest devel version 1.11.1 that you can find on BioConductor, or the master branch on GitHub.

Regards,
Christophe.
