### ISSUE TITLE
observation groups incomplete in heatmap

### ISSUE THREAD

**Issue by andynkili** [broadinstitute/infercnv#382]
I am running infercnv 1.8.1, the observations are grouped by patient and for some reasons the observation group labels at the bottom are cropped at the bottom of the plot (**please ignore the red circle at the top, it is related to another [issue](https://github.com/broadinstitute/infercnv/issues/361))**:
![infercnv 17_HMM_predHMMi6 hmm_mode-samples](https://user-images.githubusercontent.com/49782275/145846622-f1e9d05a-b3db-47a3-8a2a-b0b9c5735e85.png)
 
Here is the command I used:
`infercnv_obj = infercnv::run(infercnv_obj,
                             cutoff=0.1,  # use 1 for smart-seq, 0.1 for 10x-genomics
                             out_dir="inferCNV_noPlotIntermediate_noMHC",
                             num_threads = 17, cluster_by_groups = T,
                             save_rds = F, save_final_rds = T,
                             plot_steps = F,plot_probabilities = F,
                             remove_genes_at_chr_ends = T,no_prelim_plot = T,                                 denoise=T,
                             sd_amplifier=1.5,noise_logistic = T,
                             analysis_mode = "samples",
                             HMM=T, BayesMaxPNormal = 0.8, HMM_type = 'i6')`

What should I do to correct that part of the plot?

**Comment by GeorgescuC** [comment]
Hi @andynkili ,

Could you try updating your infercnv install to the latest commit on the master branch on github? I changed the formula to calculate the width/height for the labels and this might fix this kind of issue.

Best,
Christophe.

**Comment by andynkili** [comment]
Thank you very much for your prompt response.
Unfortunately I have to let infercnv run until the end since I have used options to save only the last infercnv object (as you can see above).
As soon as I have that the object and an updated install, I will plot again and will let you know how it went.

Best,
Andy

**Comment by andynkili** [comment]
Hi @GeorgescuC ,

The run has finished and I have updated my install to the master branch.
However, when I try to plot I have this error:
`plot_cnv(
    infercnv_obj,
    out_dir = ".",
    title = "inferCNV",
    obs_title = "Observations (Cells per sample)",
    ref_title = "References (Cells per sample)",
    cluster_by_groups = TRUE,
    cluster_references = TRUE,
    plot_chr_scale = FALSE,
    color_safe_pal = TRUE,
    output_filename = "infercnv_test",
)`
**Error in if ((getOption("bitmapType") == "cairo") & (png_height > 32768/png_res)) { : 
  argument is of length zero**
I tried the un-updated plot_cnv on the same object and that error don't come up.

**Comment by GeorgescuC** [comment]
Hi @andynkili ,

What does running `getOption("bitmapType")` return in your R session? It would seem like an element of that `if` statement is `NA`, and I do not see why either `png_height` or `png_res` would, unless you added the argument `png_res=NA` to the command you ran.

Regards,
Christophe.

**Comment by Sa753** [comment]
Hi Christophe,

Is there any update on the issue of the missing part of the chromosome bar in the first query?. I am running 1.11.1 version

**Comment by GeorgescuC** [comment]
Hi @Sa753 , 

I followed up on the missing part of the chromosome bar in issue https://github.com/broadinstitute/infercnv/issues/361 where we were already discussing it to keep each bug tracking separate.

Regards,
Christophe.

**Comment by andynkili** [comment]
Hi @GeorgescuC,

`getOption("bitmapType")` returns **NULL**.
As for the resolution, I use the default `png_res = 300`.

Best,
Andy

**Comment by andynkili** [comment]
@GeorgescuC ,

I am running R on windows 10 Pro for workstations.
Now I have another error `Error in if (!is.null(getOption("bitmapType")) || (getOption("bitmapType") ==  : 
  missing value where TRUE/FALSE needed`.

Best,
Andy

**Comment by GeorgescuC** [comment]
Hi @andynkili ,

Good to know, thanks!
My bad, that should have been an && instead. You can try updating again.

Best,
Christophe.

**Comment by andynkili** [comment]
Hi @GeorgescuC ,

I am closing it , Issues SOLVED!
The labels at the bottom are completely displayed.
Thank you for your help.

Have a great day,
Andy
