### ISSUE TITLE
Alternative to dendrogram for viewing sample grouping 

### ISSUE THREAD

**Issue by komalsrathi** [broadinstitute/infercnv#39]
Hi,

I ran inferCNV like this:

```
system("inferCNV.R \\
--cutoff 4 \\
--noise_filter 0.3 \\
--output_dir results/inferCNV/output \\
--vis_bound_threshold ' -1,1' \\
results/inferCNV/mouse850_expr_matrix.txt \\
data/gencode_vM12_gene_pos.txt")
```

In the output plot, I am interested in seeing how my samples are grouped and I know there is a dendrogram file generated to see that. But is there a simpler way to see the groupings instead of the dendrogram file? It gets too confusing when there are many samples.

**Comment by GeorgescuC** [comment]
Hi,

I have written detailed instructions for you to run the branch currently in late development at https://github.com/broadinstitute/inferCNV/issues/38#issuecomment-414756634 as that version includes the feature you are looking for. It will display a color bar where the grouping of each sample will be indicated.

The output should look similar to the example set:

![infercnv_downsampled](https://user-images.githubusercontent.com/12964363/44421424-73955a00-a54e-11e8-8372-7bf51a4cdd51.png)
