### ISSUE TITLE
Plot labels of malignant cells in a predefined order

### ISSUE THREAD

**Issue by massonix** [broadinstitute/infercnv#391]
Dear infercnv team,

I have a series of sequential clinical samples per patient. I would like them to appear in order in the heatmap (1.diagnosis, 2. progression, 3. relapse...). Is there anyway I can do this with the plot_cnv function, or should I create the heatmap myself from scratch?

Thanks a lot!

**Comment by GeorgescuC** [comment]
Hi @massonix ,

In the very last commit on the master branch of github, sorting of the observation groups by alphanumerical order was added, so updating to that version should allow you to easily organize the groups by adding a number at the start of the annotation name. However, the image() method used for plotting does so from bottom to top, so if that is important to you, just invert the numbering.

Regards,
Christophe.

**Comment by massonix** [comment]
amazing, thank you!!!
