### ISSUE TITLE
17_HMM_predHMMi6.hmm_mode-samples.pred_cnv_genes.dat file is empty 

### ISSUE THREAD

**Issue by raybueno** [broadinstitute/infercnv#394]
Hello, 

I ran inferCNV to completion, however when reading in the 17_HMM_predHMMi6.hmm_mode-samples.pred_cnv_genes.dat file it is empty. The file just has the column names - (cell_group_name | gene_region_name | state | gene | chr | start | end) but no values in the rows. Why is this file empty? I am using infercnv version 1.11.2. Thank you.

**Comment by GeorgescuC** [comment]
Hi @raybueno ,

If you look at the HMM png/pdf figures, do you see any predicted CNVs? Do the residual expression figures have signal?

Regards,
Christophe.

**Comment by raybueno** [comment]
Hi Christophe,

Yes I do see predicted CNVS from the png figure. I was hoping to see what the regions are predicted to have CNV using the files mentioned however these files are empty.

**Comment by GeorgescuC** [comment]
Hi @raybueno ,

Could you privately share with me the infercnv outputs from steps 15 and 17 so I can explore the issue? (my email can be found in the DESCRIPTION file)

Regards,
Christophe.
