### ISSUE TITLE
step 15 Error "NAs are not allowed in subscripted assignments"

### ISSUE THREAD

**Issue by andynkili** [broadinstitute/infercnv#396]
Here are the commands I have run:
```
infercnv_obj = CreateInfercnvObject(raw_counts_matrix=mydata@assays$RNA@counts,
                                    annotations_file='cellType_annotation_inferCNV.tsv',
                                    delim="\t",
                                    gene_order_file="GRCh38_gene_position_MOD.txt",
                                    ref_group_names=c("Microglia/Macrophage"))

```
And then:

```
infercnv_obj = infercnv::run(infercnv_obj,
                             cutoff=0.1,  # use 1 for smart-seq, 0.1 for 10x-genomics
                             out_dir="O_A_CNV_output",num_threads = 19,
                             HMM_type = 'i6',BayesMaxPNormal = 0.8,
                             plot_steps = F, plot_probabilities = F, save_rds = F, save_final_rds = T, remove_genes_at_chr_ends = T,
                             cluster_by_groups=T,  
                             denoise=T,
                             analysis_mode = "subcluster",
                             HMM=T)
```

I don't understand the error I get at step 15:
```
STEP 15: computing tumor subclusters via leiden

INFO [2022-02-20 23:43:24] define_signif_tumor_subclusters(p_val=0.1
INFO [2022-02-20 23:43:24] define_signif_tumor_subclusters(), tumor: Cancer
INFO [2022-02-21 00:38:09] define_signif_tumor_subclusters(), tumor: Endothelial
INFO [2022-02-21 00:38:29] define_signif_tumor_subclusters(), tumor: Oligodendrocytes
INFO [2022-02-21 00:48:45] define_signif_tumor_subclusters(), tumor: T/NK
INFO [2022-02-21 00:49:07] define_signif_tumor_subclusters(), tumor: Microglia/Macrophage
Error in m[match(oldnodes, m)] <- 1:(N - 1) : 
  NAs are not allowed in subscripted assignments
```

I tried to look for NAs values in the annotation file, but there are none.
Can someone give a clue about what went wrong?

**Comment by GeorgescuC** [comment]
Hi @andynkili ,

How many cells are there in the "Microglia/Macrophage" annotation? Such an issue can happen if there is only 1 cell in one of the annotations (the fact that other groups are processed without error makes this case more likely).

Regards,
Christophe.

**Comment by andynkili** [comment]
Dear Christophe,

First, thank you for taking time to respond.

Second, in the annotation file, I have 58,333 cells for 'Microglia/Microphage'.
Also, other annotations groups have over 1,000 cells.
Do you see any other reasons that could lead to such error?

I forgot to mention that the object I am processing is the result of merging 2 Seurat objects (both having the same genes). The only way around I have found is running inferCNV seprately on each object (which is working).
But still, I would like to know why that error is happening.

Regards,
Andy

**Comment by GeorgescuC** [comment]
Hi @andynkili ,

Now that you mention the number of cells, the issue in this case might be R changing the notation of indices to scientific annotation, so index 100,000 (cell index for a distance table) becomes 1e5 which is then not recognized. Can you try running `options(scipen = 100)` in your R session before trying to run infercnv again?

Regards,
Christophe.

**Comment by Breathofdying** [comment]
> Hi @andynkili ,
> 
> Now that you mention the number of cells, the issue in this case might be R changing the notation of indices to scientific annotation, so index 100,000 (cell index for a distance table) becomes 1e5 which is then not recognized. Can you try running `options(scipen = 100)` in your R session before trying to run infercnv again?
> 
> Regards, Christophe.

> Thank you so much for your answer! This question has also troubled me for a week!
