### ISSUE TITLE
Plotting Error

### ISSUE THREAD

**Issue by RichardsLaura** [broadinstitute/inferCNV#4]
invalid value specified for graphical parameter "mar"
Calls: infer_cnv ... plot_cnv -> plot_cnv_references -> heatmap.cnv -> par

**Comment by TimothyTickle** [comment]
Hello RichardsLaura,

I was hoping you could check and make sure you are using the supported version of R for inferCNV. Which are you using?

Cordially,

Tim

**Comment by RichardsLaura** [comment]
Hi Timothy,


Thanks for getting back so quickly. I was using R version 3.2.2 (I realize on the wiki it mentioned 3.2.1 is the optimal version). I was able to get the data to plot out with no reference, but as soon as I specify the reference set and re-run the script, I receive the plotting error.


Thanks again,


Laura

________________________________

**Comment by TimothyTickle** [comment]
Hello Laura,

Unfortunately the library we used for plotting has requires 3.2.1, we are currently working on removing that library dependency with new plotting code.

Cordially,
Tim
