### ISSUE TITLE
Infercnv failing on step 15;Error in hclust(dist(t(tumor_expr_data)), method = hclust_method) :   N must be at least 2.

### ISSUE THREAD

**Issue by ninashenker** [broadinstitute/infercnv#402]
Hello,

Infercnv is failing on step 15:

STEP 15: computing tumor subclusters via leiden

INFO [2022-03-21 12:10:37] define_signif_tumor_subclusters(p_val=0.1
INFO [2022-03-21 12:10:37] define_signif_tumor_subclusters(), tumor: all_observations
INFO [2022-03-21 12:11:43] define_signif_tumor_subclusters(), tumor: Myeloid-cells
INFO [2022-03-21 12:11:44] define_signif_tumor_subclusters(), tumor: Endothelial-cells
INFO [2022-03-21 12:11:44] define_signif_tumor_subclusters(), tumor: Fibroblasts
INFO [2022-03-21 12:11:44] define_signif_tumor_subclusters(), tumor: T-NK-cells
INFO [2022-03-21 12:11:44] define_signif_tumor_subclusters(), tumor: B-lymphocytes
INFO [2022-03-21 12:11:44] define_signif_tumor_subclusters(), tumor: MAST-cells
INFO [2022-03-21 12:11:44] Less cells in group MAST-cells than k_nn setting. Keeping as a single subcluster.
Error in hclust(dist(t(tumor_expr_data)), method = hclust_method) :
  N must be at least 2.

Is there anyway to fix this? And is N the number of cells?

It only fails on some samples, I think ones that have only 1 or 2 of a specific cell type (ex. MAST).

Thanks!

**Comment by GeorgescuC** [comment]
Hi @ninashenker ,

This does seem like a case where the "MAST-cells" annotation only has 1 cell, meaning no hierarchical clustering can be done. I have pushed a commit to make Leiden subclustering be able to handle groups with only 1 or 2 cells, however it is probably best to still remove those cells from the analysis. Any information that could be found when only looking at 1-2 cells will most likely not be accurate as there is too much noise in single cell data.

Regards,
Christophe.

**Comment by ninashenker** [comment]
Hi Christophe, 

Thanks for getting back to me. 

In the case of removing the cells with very low numbers, it fails on the step before when creating the infercnv object using infercnv::CreateInfercnvObject. It says:

"Error in !all.equal(ref_group_names, orig_ref_group_names)". 

It works on samples that have all of the reference cell types but not if it has for ex. no MAST cells. 

How would you proceed?

**Comment by GeorgescuC** [comment]
Hi @ninashenker ,

After removing the cells with very low numbers, have you removed the "MAST-cells" name from the list of reference group names in the CreateInfercnvObject call? That step should simply be checking that all the names you provided as references are present in the annotation file.
If this isn't the issue, could you please let me know what argument you provided for the reference group names, and all the unique(annotations) in your file/table?

Regards,
Christophe.

**Comment by ninashenker** [comment]
Hi Christophe,

To solve it, I've simply combined cell types (e.g. combining all immune cells into one category), so that each sample has an adequate amount for each category.

So in conclusion it's not possible to make a cell type that is present in only some samples, a reference group? 

Best,
Nina

**Comment by GeorgescuC** [comment]
Hi @ninashenker ,

Yes, references groups are given per run/dataset, so they should always be present in the runs you provide them to.

Regards,
Christophe.
