### ISSUE TITLE
ModuleNotFoundError: No module named 'math'

### ISSUE THREAD

**Issue by kirakoko** [broadinstitute/infercnv#403]
Hey inferCNV team, 

thanks for the nice tool. Recently my infercnv calling fails on step 15 with this error code: 
During startup - Warning message:
Setting LC_CTYPE failed, using "C"
Warning: Your system is mis-configured: '/etc/localtime' is not a symlink
Warning: It is strongly recommended to set envionment variable TZ to 'localtime' (or equivalent)
Traceback (most recent call last):
  File "/cluster/home/kkornien/anaconda3/bin/conda", line 12, in <module>
    from conda.cli import main
  File "/cluster/home/kkornien/anaconda3/lib/python3.8/site-packages/conda/__init__.py", line 22, in <module>
    from .common.compat import text_type, iteritems
  File "/cluster/home/kkornien/anaconda3/lib/python3.8/site-packages/conda/common/compat.py", line 14, in <module>
    from tempfile import mkdtemp
  File "/usr/lib/python3.8/tempfile.py", line 184, in <module>
    from random import Random as _Random
  File "/usr/lib/python3.8/random.py", line 41, in <module>
    from math import log as _log, exp as _exp, pi as _pi, e as _e, ceil as _ceil
ModuleNotFoundError: No module named 'math'
/cluster/home/kkornien/.local/share/r-miniconda/envs/r-reticulate/.tmpo5nm67_c: line 2: conda: command not found
/cluster/home/kkornien/.local/share/r-miniconda/envs/r-reticulate/.tmpo5nm67_c: line 3: python: command not found
ERROR conda.cli.main_run:execute(33): Subprocess for 'conda run ['python', '-c', "import os; print(os.environ['PATH'])"]' command failed.  (See above for error)
Traceback (most recent call last):
  File "/cluster/home/kkornien/anaconda3/bin/conda", line 12, in <module>
    from conda.cli import main
  File "/cluster/home/kkornien/anaconda3/lib/python3.8/site-packages/conda/__init__.py", line 22, in <module>
    from .common.compat import text_type, iteritems
  File "/cluster/home/kkornien/anaconda3/lib/python3.8/site-packages/conda/common/compat.py", line 14, in <module>
    from tempfile import mkdtemp
  File "/usr/lib/python3.8/tempfile.py", line 184, in <module>
    from random import Random as _Random
  File "/usr/lib/python3.8/random.py", line 41, in <module>
    from math import log as _log, exp as _exp, pi as _pi, e as _e, ceil as _ceil
ModuleNotFoundError: No module named 'math'
/cluster/home/kkornien/.local/share/r-miniconda/envs/r-reticulate/.tmp0ap_muo4: line 2: conda: command not found
/cluster/home/kkornien/.local/share/r-miniconda/envs/r-reticulate/.tmp0ap_muo4: line 3: python: command not found
ERROR conda.cli.main_run:execute(33): Subprocess for 'conda run ['python', '-c', "import os; print(os.environ['PATH'])"]' command failed.  (See above for error)
Error in system2(conda, c("run", in_env, run_args, shQuote(cmd), args),  :
  error in running command
Calls: <Anonymous> ... python_config -> python_munge_path -> conda_run -> system2
Execution halted

could you help? it fails on step 15: 

An object of class Seurat
660196 features across 51758 samples within 5 assays
Active assay: integrated (3000 features, 0 variable features)
 4 other assays present: RNA, ATAC, SCT, GeneActivity
 5 dimensional reductions calculated: integrated_lsi, ATACIntegrated_UMAP, pca, RNAIntegrated_UMAP, wnn.umap
An object of class Seurat
660196 features across 51758 samples within 5 assays
Active assay: integrated (3000 features, 0 variable features)
 4 other assays present: RNA, ATAC, SCT, GeneActivity
 5 dimensional reductions calculated: integrated_lsi, ATACIntegrated_UMAP, pca, RNAIntegrated_UMAP, wnn.umap
Pat4_LN1_AAACAGCCACAAACTT-1 Pat4_LN1_AAACAGCCACAATGTT-1
                          3                           0
Pat4_LN1_AAACAGCCATGAATCT-1 Pat4_LN1_AAACATGCAAGGTATA-1
                    T-cells                           3
Pat4_LN1_AAACATGCACATAACT-1 Pat4_LN1_AAACATGCACCTGTAA-1
                    T-cells                          14
35 Levels: Monolytic B-cells T-cells BE Fibroblasts Endothelial Mast 0 1 ... 9
INFO [2022-03-21 22:59:30] Parsing gene order file: /cluster/projects/lupiengroup/Kira/test-pat2-analysis/gencode.v32.annotation_gen_pos.txt
INFO [2022-03-21 22:59:30] ::order_reduce:Start.
INFO [2022-03-21 22:59:34] .order_reduce(): expr and order match.
INFO [2022-03-21 23:00:01] ::process_data:order_reduce:Reduction from positional data, new dimensions (r,c) = 36601,51758 Total=374789989 Min=0 Max=21967.
INFO [2022-03-21 23:00:02] num genes removed taking into account provided gene ordering list: 52 = 0.14207262096664% removed.
INFO [2022-03-21 23:00:03] -filtering out cells < 100 or > Inf, removing 0 % of cells
WARN [2022-03-21 23:00:11] Please use "options(scipen = 100)" before running infercnv if you are using the analysis_mode="subclusters" option or you may encounter an error while the hclust is being generated.
INFO [2022-03-21 23:00:20] validating infercnv_obj
INFO [2022-03-21 23:00:20] ::process_data:Start
INFO [2022-03-21 23:00:20] Checking for saved results.
INFO [2022-03-21 23:00:20]

        STEP 1: incoming data

INFO [2022-03-21 23:02:28]

        STEP 02: Removing lowly expressed genes

INFO [2022-03-21 23:02:28] ::above_min_mean_expr_cutoff:Start
INFO [2022-03-21 23:02:42] Removing 28116 genes from matrix as below mean expr threshold: 0.1
INFO [2022-03-21 23:02:52] validating infercnv_obj
INFO [2022-03-21 23:02:52] There are 8433 genes and 51758 cells remaining in the expr matrix.
INFO [2022-03-21 23:03:32] no genes removed due to min cells/gene filter
INFO [2022-03-21 23:05:37]

        STEP 03: normalization by sequencing depth

INFO [2022-03-21 23:05:37] normalizing counts matrix by depth
INFO [2022-03-21 23:06:32] Computed total sum normalization factor as median libsize: 4555.000000
INFO [2022-03-21 23:06:33] Adding h-spike
INFO [2022-03-21 23:06:33] -hspike modeling of B-cells
INFO [2022-03-21 23:11:18] -hspike modeling of Mast
INFO [2022-03-21 23:15:47] -hspike modeling of T-cells
INFO [2022-03-21 23:20:16] -hspike modeling of Fibroblasts
INFO [2022-03-21 23:24:50] -hspike modeling of Endothelial
INFO [2022-03-21 23:29:17] -hspike modeling of Monolytic
INFO [2022-03-21 23:33:45] validating infercnv_obj
INFO [2022-03-21 23:33:45] normalizing counts matrix by depth
INFO [2022-03-21 23:33:46] Using specified normalization factor: 4555.000000
INFO [2022-03-21 23:35:50]

        STEP 04: log transformation of data

INFO [2022-03-21 23:35:50] transforming log2xplus1()
INFO [2022-03-21 23:36:11] -mirroring for hspike
INFO [2022-03-21 23:36:11] transforming log2xplus1()
INFO [2022-03-21 23:38:14]

        STEP 08: removing average of reference data (before smoothing)

INFO [2022-03-21 23:38:14] ::subtract_ref_expr_from_obs:Start inv_log=FALSE, use_bounds=TRUE
INFO [2022-03-21 23:38:14] subtracting mean(normal) per gene per cell across all data
INFO [2022-03-21 23:38:44] -subtracting expr per gene, use_bounds=TRUE
INFO [2022-03-22 07:28:52] -mirroring for hspike
INFO [2022-03-22 07:28:52] ::subtract_ref_expr_from_obs:Start inv_log=FALSE, use_bounds=TRUE
INFO [2022-03-22 07:28:52] subtracting mean(normal) per gene per cell across all data
INFO [2022-03-22 07:28:58] -subtracting expr per gene, use_bounds=TRUE
INFO [2022-03-22 07:32:28]

        STEP 09: apply max centered expression threshold: 3

INFO [2022-03-22 07:32:28] ::process_data:setting max centered expr, threshold set to: +/-:  3
INFO [2022-03-22 07:32:43] -mirroring for hspike
INFO [2022-03-22 07:32:43] ::process_data:setting max centered expr, threshold set to: +/-:  3
INFO [2022-03-22 07:36:13]

        STEP 10: Smoothing data per cell by chromosome

INFO [2022-03-22 07:36:13] smooth_by_chromosome: chr: chr1
INFO [2022-03-22 07:37:18] smooth_by_chromosome: chr: chr2
INFO [2022-03-22 07:38:22] smooth_by_chromosome: chr: chr3
INFO [2022-03-22 07:39:26] smooth_by_chromosome: chr: chr4
INFO [2022-03-22 07:40:24] smooth_by_chromosome: chr: chr5
INFO [2022-03-22 07:41:23] smooth_by_chromosome: chr: chr6
INFO [2022-03-22 07:42:27] smooth_by_chromosome: chr: chr7
INFO [2022-03-22 07:43:26] smooth_by_chromosome: chr: chr8
INFO [2022-03-22 07:44:26] smooth_by_chromosome: chr: chr9
INFO [2022-03-22 07:45:24] smooth_by_chromosome: chr: chr10
INFO [2022-03-22 07:46:22] smooth_by_chromosome: chr: chr11
INFO [2022-03-22 07:47:23] smooth_by_chromosome: chr: chr12
INFO [2022-03-22 07:48:23] smooth_by_chromosome: chr: chr13
INFO [2022-03-22 07:49:17] smooth_by_chromosome: chr: chr14
INFO [2022-03-22 07:50:14] smooth_by_chromosome: chr: chr15
INFO [2022-03-22 07:51:10] smooth_by_chromosome: chr: chr16
INFO [2022-03-22 07:52:08] smooth_by_chromosome: chr: chr17
INFO [2022-03-22 07:53:04] smooth_by_chromosome: chr: chr18
INFO [2022-03-22 07:53:58] smooth_by_chromosome: chr: chr19
INFO [2022-03-22 07:54:59] smooth_by_chromosome: chr: chr20
INFO [2022-03-22 07:55:49] smooth_by_chromosome: chr: chr21
INFO [2022-03-22 07:56:35] smooth_by_chromosome: chr: chr22
INFO [2022-03-22 07:57:30] smooth_by_chromosome: chr: chrX
INFO [2022-03-22 07:58:25] smooth_by_chromosome: chr: chrY
INFO [2022-03-22 07:58:34] -mirroring for hspike
INFO [2022-03-22 07:58:34] smooth_by_chromosome: chr: chrA
INFO [2022-03-22 07:58:36] smooth_by_chromosome: chr: chr_0
INFO [2022-03-22 07:58:37] smooth_by_chromosome: chr: chr_B
INFO [2022-03-22 07:58:38] smooth_by_chromosome: chr: chr_0pt5
INFO [2022-03-22 07:58:39] smooth_by_chromosome: chr: chr_C
INFO [2022-03-22 07:58:41] smooth_by_chromosome: chr: chr_1pt5
INFO [2022-03-22 07:58:42] smooth_by_chromosome: chr: chr_D
INFO [2022-03-22 07:58:43] smooth_by_chromosome: chr: chr_2pt0
INFO [2022-03-22 07:58:45] smooth_by_chromosome: chr: chr_E
INFO [2022-03-22 07:58:46] smooth_by_chromosome: chr: chr_3pt0
INFO [2022-03-22 07:58:48] smooth_by_chromosome: chr: chr_F
INFO [2022-03-22 08:02:22]

        STEP 11: re-centering data across chromosome after smoothing

INFO [2022-03-22 08:02:22] ::center_smooth across chromosomes per cell
INFO [2022-03-22 08:03:56] -mirroring for hspike
INFO [2022-03-22 08:03:56] ::center_smooth across chromosomes per cell
INFO [2022-03-22 08:07:35]

        STEP 12: removing average of reference data (after smoothing)

INFO [2022-03-22 08:07:35] ::subtract_ref_expr_from_obs:Start inv_log=FALSE, use_bounds=TRUE
INFO [2022-03-22 08:07:35] subtracting mean(normal) per gene per cell across all data
INFO [2022-03-22 08:08:03] -subtracting expr per gene, use_bounds=TRUE
INFO [2022-03-22 08:09:04] -mirroring for hspike
INFO [2022-03-22 08:09:04] ::subtract_ref_expr_from_obs:Start inv_log=FALSE, use_bounds=TRUE
INFO [2022-03-22 08:09:04] subtracting mean(normal) per gene per cell across all data
INFO [2022-03-22 08:09:08] -subtracting expr per gene, use_bounds=TRUE
INFO [2022-03-22 08:12:22]

        STEP 14: invert log2(FC) to FC

INFO [2022-03-22 08:12:22] invert_log2(), computing 2^x
INFO [2022-03-22 08:12:29] -mirroring for hspike
INFO [2022-03-22 08:12:29] invert_log2(), computing 2^x
INFO [2022-03-22 08:16:32]

        STEP 15: computing tumor subclusters via leiden

INFO [2022-03-22 08:16:32] define_signif_tumor_subclusters(p_val=0.1
INFO [2022-03-22 08:16:32] define_signif_tumor_subclusters(), tumor: all_observations

THANK You!

**Comment by GeorgescuC** [comment]
Hi @kirakoko ,

It seems there is an issue either with R having access to conda, or the python environment being used. Can you try the following in an R session:

> [library](https://rdrr.io/r/base/library.html)([reticulate](https://rstudio.github.io/reticulate/))
> [py_install](https://rstudio.github.io/reticulate/reference/py_install.html)("leidenalg")

Regards,
Christophe.

**Comment by kirakoko** [comment]
Hey Christophe, thanks for coming back to me. 
If i do so: 
> library(reticulate)
> py_install("leidenalg")
Traceback (most recent call last):
  File "/cluster/home/kkornien/anaconda3/bin/conda", line 12, in <module>
    from conda.cli import main
  File "/cluster/home/kkornien/anaconda3/lib/python3.8/site-packages/conda/__init__.py", line 22, in <module>
    from .common.compat import text_type, iteritems
  File "/cluster/home/kkornien/anaconda3/lib/python3.8/site-packages/conda/common/compat.py", line 14, in <module>
    from tempfile import mkdtemp
  File "/usr/lib/python3.8/tempfile.py", line 184, in <module>
    from random import Random as _Random
  File "/usr/lib/python3.8/random.py", line 41, in <module>
    from math import log as _log, exp as _exp, pi as _pi, e as _e, ceil as _ceil
ModuleNotFoundError: No module named 'math'
/cluster/home/kkornien/.local/share/r-miniconda/envs/r-reticulate/.tmp6ado1jo7: line 2: conda: command not found
/cluster/home/kkornien/.local/share/r-miniconda/envs/r-reticulate/.tmp6ado1jo7: line 3: python: command not found
ERROR conda.cli.main_run:execute(33): Subprocess for 'conda run ['python', '-c', "import os; print(os.environ['PATH'])"]' command failed.  (See above for error)
Collecting package metadata (current_repodata.json): done
Solving environment: done

**Comment by GeorgescuC** [comment]
Hi @kirakoko ,

Can you try running:
> reticulate::py_install("math")

If this still produces an error, there may be an issue with the python environment created by R reticulate, or your import paths. If you have a Python environment you know works properly outside of R, you can install "leidenalg" in it then try to make R use it with 
> [use_condaenv](https://rstudio.github.io/reticulate/reference/use_python.html)("python_env_with_leidenalg")

Regards,
Christophe.

**Comment by kirakoko** [comment]
Hey Christophe, 
so i had to reinstall my environment.
Does inferCNV need python it worked always fine for me purely in R I guess 
Eversince i used reticulate once something got weird, so the new error is this 
In dir.create(out_dir_name) :
  'inferCNV_test_henry_via_merged24032022' already exists
Error: Python module igraph was not found.

Detected Python configuration:

python:         /cluster/home/kkornien/miniconda3/envs/r-reticulate/bin/python
libpython:      /cluster/home/kkornien/miniconda3/envs/r-reticulate/lib/libpython3.6m.so
pythonhome:     /cluster/home/kkornien/miniconda3/envs/r-reticulate:/cluster/home/kkornien/miniconda3/envs/r-reticulate
version:        3.6.15 | packaged by conda-forge | (default, Dec  3 2021, 18:49:41)  [GCC 9.4.0]
numpy:          /cluster/home/kkornien/miniconda3/envs/r-reticulate/lib/python3.6/site-packages/numpy
numpy_version:  1.19.5
numpy:          /cluster/home/kkornien/miniconda3/envs/r-reticulate/lib/python3.6/site-packages/numpy

python versions found:
 /cluster/home/kkornien/miniconda3/envs/r-reticulate/bin/python
 /usr/bin/python3
 /cluster/home/kkornien/anacondaold/bin/python
 /cluster/home/kkornien/miniconda3/bin/python

Execution halted

I tried to export PATH to  /cluster/home/kkornien/miniconda3/bin/ where i successfully installed igraph but it keeps me this error. I know it is more a reticulate issue obviously but i would be happy to get your input. 
thanks, kira

**Comment by kirakoko** [comment]
Hey Christophe, 

so i figured it out! thanks for your help!
