### ISSUE TITLE
X11 problem

### ISSUE THREAD

**Issue by tlz4320** [broadinstitute/infercnv#407]
I think some one have submit this issue before, but it seem you didn't fix all of your code to fit PDF format.
No matter what parameter I gave to "output_format", PDF or NA , X11 problem will till there and stop inferCNV.

**Comment by GeorgescuC** [comment]
Hi @tlz4320 ,

What version of infercnv are you running?

Could you also post any error or warnings you get from infercnv?

Regards,
Christophe.
