### ISSUE TITLE
Tumour heterogeneity - visualising loss/gain in phylogenetic tree format

### ISSUE THREAD

**Issue by angkoomin** [broadinstitute/infercnv#409]
Hi there,

I am currently using Uphyloplot2 to visualise the tumour heterogeneity using output from inferCNV. I was wondering, how can I map the loss/gain seen in my HMM random tree file and to the branches of the tree (See figure 2 below as an example)? 

**Figure 1**
Top left: file from HMM prediction region file
Bottom left: Branches of dendogram/phylogenetic tree with proportion of cells in each branch
Right: Phylogenetic tree generated using Uphyloplot2 with inferCNV output file
![image](https://user-images.githubusercontent.com/61758903/162092004-5919435f-7c57-4fcd-b303-dfb47260a9b7.png)

This is an example of a paper using InferCNV output in Uphyloplot2 package:

**Figure 2**
<img width="892" alt="image" src="https://user-images.githubusercontent.com/61758903/162092233-5f36e89c-729b-496e-b6d5-dab294896b8e.png">
From: Durante, M.A., Rodriguez, D.A., Kurtenbach, S. et al. Single-cell analysis reveals new evolutionary complexity in uveal melanoma. Nat Commun 11, 496 (2020). https://doi.org/10.1038/s41467-019-14256-1

I

**Comment by GeorgescuC** [comment]
Hi @angkoomin ,

I am not sure how Uphyloplot2 generates the tree (mainly if it generates one based on the CNV calls or just makes a tree based on the infercnv dendrogram). Does it have any other outputs that would give you the match between their nodes and the infercnv branchings? For infercnv, beside the file you have open in the top left which gives you the CNVs for each cluster, there is also an `.observations_dendrogram.txt` file generated with each plot that gives you a newick string for each dendrogram.

Regards,
Christophe.

**Comment by angkoomin** [comment]
I will keep you posted when I get a reply from Uphyloplot2 developers. 

Thanks

**Comment by skye187** [comment]
> I will keep you posted when I get a reply from Uphyloplot2 developers.
> 
> Thanks

hi, there,
Recently I also want to construct the clone tree. However, i could get the same file that looks like the top left of yours, which i know is the base for Uphyloplot2. Very sad..... I would appreciate it a lot if you could kindly share your method or code?
My are as follows and i don not know whether it is the rght way. I currently stuck at the STEP 07.

`infercnv_obj <- infercnv::run(
  infercnv_obj,
  cutoff = 0.1,
  out_dir = "try3",           # 改成你原来用的路径！
  cluster_by_groups = FALSE,
  analysis_mode = "subclusters",
  denoise = TRUE,
  HMM = TRUE, 
  HMM_type = "i6",
  tumor_subcluster_partition_method = "random_trees",  # 构建克隆进化树所需
  resume_mode = TRUE              # ⬅️ 关键参数，只运行未完成部分
  )`

`STEP 07: computing tumor subclusters via random_trees

INFO [2025-05-10 06:14:41] define_signif_tumor_subclusters(p_val=0.1
INFO [2025-05-10 06:14:41] ::subtract_ref_expr_from_obs:Start inv_log=TRUE, use_bounds=TRUE
INFO [2025-05-10 06:14:41] subtracting mean(normal) per gene per cell across all data
INFO [2025-05-10 06:14:47] -subtracting expr per gene, use_bounds=TRUE
INFO [2025-05-10 06:14:53] -mirroring for hspike
INFO [2025-05-10 06:14:53] ::subtract_ref_expr_from_obs:Start inv_log=TRUE, use_bounds=TRUE
INFO [2025-05-10 06:14:53] subtracting mean(normal) per gene per cell across all data
INFO [2025-05-10 06:14:55] -subtracting expr per gene, use_bounds=TRUE
INFO [2025-05-10 06:14:55] define_signif_tumor_subclusters(), tumor: all_observations
unique tumor clade name: all_observations.1
INFO [2025-05-10 06:29:11] random trees, using 4 parallel threads`
