### ISSUE TITLE
error with infer_cnv

### ISSUE THREAD

**Issue by joonlee3** [broadinstitute/infercnv#41]
Hi,

I've tried to run the following commandline but I've got an error.

**infer_cnv(data = InferCNV.data$data.inferCNV,
gene_order = gene.info.data,
cutoff = 1, noise_threshold = 0.2,
reference_obs = InferCNV.data$ref.cell.ids,
num_ref_groups = 1,
transform_data = FALSE,
max_centered_threshold = 3,
window_length = 100)**

_Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘filter’ for signature ‘"numeric"’_

Would you please help me with this?

Thanks,
J

**Comment by GeorgescuC** [comment]
Hi @joonlee3 ,

The recommended method of running inferCNV at this time is to use scripts/inferCNV.R with the command line arguments. You can find an example in the [quick start section](https://github.com/broadinstitute/inferCNV/wiki#quick-start).
If you are still getting errors using this method, please answer here with the command you ran and an example of the input files format.

Best,
Christophe.

**Comment by tallulandrews** [comment]
I got the same error, traced it to the smooth_window_helper function which calls "filter" function which doesn't seem to be defined anywhere.
