### ISSUE TITLE
how to load infercnv.observations_dendrogram.txt file in R

### ISSUE THREAD

**Issue by Feng-Zhang** [broadinstitute/infercnv#411]
I want to custom plot cnv heatmap using ComplexHeatmap. How can we read the  infercnv.observations_dendrogram.txt file and convert it as dendrogram class in R?
I use the read.dendrogram function but failed because  infercnv.observations_dendrogram.txt file contains multiple trees. 
```
library(phylogram)
dend <- phylogram::read.dendrogram("infercnv.observations_dendrogram.txt")
```
The  error would be throwed : Error in phylogram::read.dendrogram("infercnv.observations_dendrogram.txt") : 
  Only single trees are supported
Thank you in advance.

**Comment by plijnzaad** [comment]
Works fine for me using the `ape` or `phytools` package. After doing

`trees <- phytools::read.newick(file)` the variable `trees` is a `multiPhylo` which is just a `list()` of  trees. To plot the one of them (e.g. the 2nd), simply do `plot(trees[[2]])`
