### ISSUE TITLE
Several times the results predicted by CNV cannot be repeated

### ISSUE THREAD

**Issue by wanglx1998** [broadinstitute/infercnv#414]
Dear InferCNV developers,
Thank you very much for developing such a useful and convenient tool！

While using it for analysis, I found myself running Infercnv several times over (version: 1.10.1) .The total CNV quantity obtained after is different, the input file used has not changed, and the CNV area is not consistent, I did not set the control group, the following are my main operating parameters, I would like to ask what causes the inconsistent results each time, thank you! 

infercnv_obj = CreateInfercnvObject(raw_counts_matrix=expFile,
                                    annotations_file=groupFiles,
                                    delim="\t",
                                    gene_order_file= geneFile,
                                    ref_group_names=NULL)
infercnv_obj = infercnv::run(infercnv_obj,
                             cutoff=0.1, 
                             out_dir='output/', 
                             cluster_by_groups=TRUE,
                             analysis_mode="subclusters", 
                             denoise=TRUE,
                             HMM=TRUE)

![ISGIYWYL2K7%~GFW5MOA%PR](https://user-images.githubusercontent.com/85326871/165048476-6f2795f4-6299-4fe6-bd8c-92ced350b80d.png)
![9$EC)D5(II6T~I9M` 8V4}R](https://user-images.githubusercontent.com/85326871/165048468-876eeb35-b37d-4d76-b359-a7a1a08cc1e5.png)

Many thanks in advance and best wishes!

**Comment by GeorgescuC** [comment]
Hi @wanglx1998 ,

Based on the captures you sent of the predictions, the first thing I can see is that the clustering is different. The first run has 5 subclusters with predicted CNVs in cells annotated "3.3", and the second run has only 4. With the set of options and version you used, the subclustering is done via the Leiden algorithm, which is not deterministic. Since predictions are done over all the cells in a subcluster, this affects the results you are getting. However if all cells within a subcluster do not display similar signal, there should be more uncertainty and thus be more likely for the predicted CNVs to get filtered out after the Bayesian network filtering.

Regards,
Christophe.

**Comment by wanglx1998** [comment]
Hi GeorgescuC,

Thank you for your reply！
I have another question I hope you can help me:If I don't set analysis_mode="subclusters"，use default.But the number of total CNVs is also different in step 18,and I found that the output file started to be different at step 17.

infercnv_obj = CreateInfercnvObject(raw_counts_matrix=expFile,
annotations_file=groupFiles,
delim="\t",
gene_order_file= geneFile,
ref_group_names=NULL)

infercnv_obj = infercnv::run(infercnv_obj,
cutoff=0.1,
out_dir='output/',
cluster_by_groups=TRUE,
denoise=TRUE,
HMM=TRUE)

![Q2C)_ZO~W@YY_(01JW26_@O](https://user-images.githubusercontent.com/85326871/166614942-3095b98e-6129-4cfc-947f-92fd45d03d89.png)
![RVAVM)3`EBM(T4C(J~_8AT5](https://user-images.githubusercontent.com/85326871/166615095-ed920831-3921-4bb9-a746-75348a018d98.png)

![WX`2@}A{@J BPC0IX~SJAQL](https://user-images.githubusercontent.com/85326871/166615049-cd6a6c65-ee33-4b4b-ae78-e7b718a4bb21.png)
Thank you very much again！

**Comment by GeorgescuC** [comment]
Hi @wanglx1998 ,

If you look at the other outputs, mainly the preliminary residual expression plot and associated matrices, do you see differences?

Also, do the results after the Bayesian filtering at step 19 still look as dissimilar?

Regards,
Christophe.

**Comment by wanglx1998** [comment]
Hi @GeorgescuC,

The mainly the preliminary residual expression plot（infercnv.png) and associated matrices(infercnv.observations.txt) are same,don`t see difference.
The results after the Bayesian filtering at step 19 still look as dissimilar.

Sincerely.
wanglx1998.

**Comment by GeorgescuC** [comment]
Hi @wanglx1998 ,

Would you be able to privately share the 2 runs you have dissimilarities in so I can inspect differences and try to find where they start to occur?

Regards,
Christophe.
