### ISSUE TITLE
How to intepret box plot of cnvProbs.0.*.pdf?

### ISSUE THREAD

**Issue by jsialar** [broadinstitute/infercnv#420]
Hi @GeorgescuC, I understand that the boxplot shows the posterior probability of each CNV state for each region and is obtained from MCMC_inferCNV_obj@cnv_probabilities. I don't understand why are there 3000 values for each box plot. Are those the sampled values from Gibbs sampling?

**Comment by brownmp** [comment]
hello @jsialar,

Yes these values come from the sampling process. The box plots show the distribution of the theta values coming from the sampling process. 

~~ brownmp

**Comment by jsialar** [comment]
Would taking the median value of this distribution as a gauge for the posterior probability of a CNV call make sense? 
Also, I thought the sampling process is supposed to give probabilities for each cell. So this distribution of theta values is for one cell?
