### ISSUE TITLE
infercnv final object does not have cell name in the 'subcluster' slot

### ISSUE THREAD

**Issue by andynkili** [broadinstitute/infercnv#422]
I have in the past I have successfully retrieve cells from specific subluster using the run.final.infercnv_obj:
![infercnv_cellname](https://user-images.githubusercontent.com/49782275/170345418-987f1a61-a1eb-45d6-8023-994c7d916ecc.png)
 
However in a more recent run, here is what I have:
![infercnvnoCellname](https://user-images.githubusercontent.com/49782275/170345554-37bd3f7b-f2dd-490c-8f19-e66ab90b26bc.png)

As you can see, the sublusters are lists of integers with NO cell names.
How come?
I thought that I used causing this but I don't see any:
```
infercnv@option:
$chr_exclude
[1] "chrX" "chrY" "chrM"

$max_cells_per_group
NULL

$min_max_counts_per_cell
[1] 100 Inf

$counts_md5
[1] "015bc5ec59caaf5de825ebbf59419afc"

$cutoff
[1] 0.1

$out_dir
[1] "porjetMening_refMyelo_win101_modeSubclusters_sd2"

$window_length
[1] 101

$cluster_by_groups
[1] TRUE

$HMM
[1] TRUE

$HMM_type
[1] "i6"

$BayesMaxPNormal
[1] 0.5

$analysis_mode
[1] "subclusters"

$denoise
[1] TRUE

$sd_amplifier
[1] 2

$num_threads
[1] 18

$plot_steps
[1] FALSE

$plot_probabilities
[1] FALSE

$save_rds
[1] FALSE

$save_final_rds
[1] TRUE

$no_prelim_plot
[1] TRUE

$smooth_method
[1] "pyramidinal"

$HMM_report_by
[1] "subcluster"

$tumor_subcluster_partition_method
[1] "leiden"

$max_centered_threshold
[1] 3

$remove_genes_at_chr_ends
[1] FALSE

$prune_outliers
[1] FALSE

$mask_nonDE_genes
[1] FALSE

$noise_filter
[1] NA

$noise_logistic
[1] FALSE
```

**Comment by GeorgescuC** [comment]
Hi @andynkili ,

Are these newer runs using an up to date version of infercnv? This issue should have been fixed in version 1.10.2 and I don't think any more recent changes should have affected this point.

Regards,
Christophe.
