### ISSUE TITLE
Incomplete  heatmap

### ISSUE THREAD

**Issue by Gerde89** [broadinstitute/infercnv#43]
Hi,
    I got an incomplete heatmap after all steps done, without errors, could you help me? Thanks~
`2018-09-11 17:51:08 INFO::Observation data size: Cells= 7777 Genes= 15065`
`2018-09-11 17:51:08 INFO::clustering observations via method: complete`
`2018-09-11 21:43:48 INFO::plot_cnv_observation:Writing observation groupings/color.`
`2018-09-11 21:43:48 INFO::plot_cnv_observation:Writing observations by grouping.`
`2018-09-12 01:37:05 INFO::plot_cnv_references:Writing observation data to result_noRef2/observations.txt`
`null device`
`          1`
the image:
![infercnv](https://user-images.githubusercontent.com/34473278/45462163-3bda9600-b739-11e8-9b80-8926e4ffe3ef.png)

Best,
Gerde

**Comment by GeorgescuC** [comment]
Hi @Gerde89,

Could you provide me the commands you ran and a description of the input files?

Regards,
Christophe.
