### ISSUE TITLE
Error in readRDS(reload_info$expected_file_names[[i]]) :    error reading from connection

### ISSUE THREAD

**Issue by naddoun** [broadinstitute/infercnv#435]
Hi InferCNV team,

I've been trying to iterate through inferCNV. It seems to work for iteration 0 and iteration 1. However, when I try looping through a second time, I get an error during step 8. A part of the directory is already populated, and the code produces the following error:

Error in readRDS(reload_info$expected_file_names[[i]]) : 
  error reading from connection

I've tried re-installing inferCNV as some previous posts have suggested, to no avail. I was wondering if someone could help me troubleshoot this.

Thanks so much,

**Comment by TIPPLERXIE** [comment]
@Roeply Because I had previously run the code and generated an output directory, the error occurred when I ran it again. However, when I deleted that directory, the code ran without any issues.
