### ISSUE TITLE
Error in CreateInfercnvObject function 

### ISSUE THREAD

**Issue by Victor-K27** [broadinstitute/infercnv#436]
Hi! 

Thanks for making this package. 

I have an issue with creating the infercnvobject, which I have been trying to troubleshoot unsuccessfully for some time now.  

I am using the attached files as raw_counts_matrix, annotations_file, and gene_order_file (please have a look bellow). 

`infercnv_obj <- CreateInfercnvObject(
  raw_counts_matrix = "raw_counts_matrix_test.txt",
  annotations_file = "annotations_file_test.txt",
  gene_order_file = "gene_order_file_test.txt", delim = "\t",
  ref_group_names = c("nonTumor"),
)`

The error I am getting is:

`Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  : 
  line 1 did not have 2 elements`

I think it might have something to do with the formatting of my files, however, I have made it identical to that of the examples. 

Thank you in advance for your precious time and help,

Sincerely,
Victor 

[raw_counts_matrix_test.txt](https://github.com/broadinstitute/infercnv/files/9128593/raw_counts_matrix_test.txt)
[annotations_file_test.txt](https://github.com/broadinstitute/infercnv/files/9128579/annotations_file_test.txt)
[gene_order_file_test.txt](https://github.com/broadinstitute/infercnv/files/9128580/gene_order_file_test.txt)

**Comment by GeorgescuC** [comment]
Hi @Victor-K27 , 

The annotation file you provided starts with the line `"annotations_file[, 2]"` which is not expected.

Regards,
Christophe.

**Comment by Victor-K27** [comment]
Hi @GeorgescuC,

Thank you for your reply. 

I have now fixed the annotations file (I think). Please find attached the new annotation, raw count matrix, and gene order file. I am getting a new error with these: `Error in FUN(left, right) : non-numeric argument to binary operator`

Any advice would be very helpful and extremely appreciated. 

Thank you for your time, 
Best wishes,

Victor 
[annotations_file_test_helen.txt](https://github.com/broadinstitute/infercnv/files/9400798/annotations_file_test_helen.txt)
[gene_order_file_test.txt](https://github.com/broadinstitute/infercnv/files/9400799/gene_order_file_test.txt)
[raw_counts_matrix_test_helen.txt](https://github.com/broadinstitute/infercnv/files/9400801/raw_counts_matrix_test_helen.txt)

**Comment by Victor-K27** [comment]
I found the error, don't worry!

**Comment by Cristinex** [comment]
> I found the error, don't worry!

I encountered the same error. How did you solve the problem?

**Comment by fangjialing** [comment]
@Victor-K27 , sorry, I have the same problem, can you tell me how did you solve the problem which is important for my project. thank you very much.
