### ISSUE TITLE
Minimum normal sample as reference ？

### ISSUE THREAD

**Issue by bitcometz** [broadinstitute/infercnv#437]
Hello，

[Inferring copy number variation from gene expression data: methods, comparisons, and applications to oncology](https://www.biorxiv.org/content/10.1101/2021.10.18.463991v1.full.pdf)

The aboved published paper suggests that:

```
Each method had their own limitations and
strengths: InferCNV was a robust method, provided that at least some (as few as 5) normal
samples were provided.
```

Is that right ?

Can I use multiple cell types from normal samples as a reference ？？

In my project, I found the results with using the Epithelial Cells from normal sample as reference is very different from the results based with using the Macrophages Cells from normal sample as reference.

Thanks ！！！

**Comment by GeorgescuC** [comment]
Hi @bitcometz,

You can indeed have multiple cell types from normal samples as references. The annotation file provided will allow you to specify which cells are part of the same type (known or unknown), and which of those cell types should be used as references. Ideally, you would have a matching set of normal cells to match each of the cell types encountered in the tumor.

Infercnv looks at the cells you provided as normal to find large scale differences in expression in the observations (tumor sample cells), however if you have different cell types in both that have type specific expression patterns, those will likely be identified as well. This is why it is best to have a reference for each cell type present in the tumor.

Regards,
Christophe.

**Comment by bitcometz** [comment]
Thanks !!!
