### ISSUE TITLE
Error in step 15: Error in irlba(A = t(x = object), nv = npcs, ...)

### ISSUE THREAD

**Issue by sheilak97** [broadinstitute/infercnv#487]
Hello, I recently updated my R studio to the latest version, and I tried to re-run to the infercnv codes I previously ran successfully, and got the following error warning after "Centering and scaling data matrix" in step 15: 

Error in irlba(A = t(x = object), nv = npcs, ...) : 
  max(nu, nv) must be strictly less than min(nrow(A), ncol(A))

Also when I tried to remove infercnv and reinstall I couldn't find it using remove.packages. Any idea how I can fix this? Thanks.

My command used:
infercnv_obj6 = infercnv::run(infercnv_obj6,
                             cutoff=0.1,
                             out_dir=paste0("/Users/sheilak/Desktop/CNV_lib2_noChrXY"),
                             cluster_by_groups = T,
                             cluster_references = F,
                             final_center_val = 1,
                             denoise = T,
                             HMM = T,
                             num_threads=4,
                             output_format = "png",
                             useRaster = T)

Below is the printing of my console:

	STEP 15: computing tumor subclusters via leiden

INFO [2022-12-09 16:50:24] define_signif_tumor_subclusters(p_val=0.1
INFO [2022-12-09 16:50:24] define_signif_tumor_subclusters(), tumor: 0
Calculating gene variances
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating feature variances of standardized and clipped values
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Centering and scaling data matrix
  |=====================================================================================| 100%
PC_ 1 
Positive:  SP3, OLA1, ITGA6, CIR1, HAT1, MTX2, HNRNPA3, DYNC1I2, NFE2L2, DCAF17 
	   AGPS, METTL8, SESTD1, TLK1, CWC22, GORASP2, UBE2E3, DNAJC10, NCKAP1, UBR3 
	   NUP35, ZC3H15, METTL5, AC007319.1, SSB, TFPI, GULP1, KLHL23, PPIG, WDR75 
Negative:  MBD3, UQCR11, MEX3D, TCF3, ABHD17A, RPS15, CSNK1G2, MKNK2, AP3D1, PLEKHJ1 
	   OAZ1, DAZAP1, LSM7, NDUFS7, TIMM13, CIRBP, LMNB2, MIDN, GADD45B, GPX4 
	   SLC39A3, POLR2E, CNN2, SGTA, TMEM259, THOP1, WDR18, ARID3A, NCLN, PTBP1 
PC_ 2 
Positive:  WEE1, ZNF143, SWAP70, IPO7, SBF2, TMEM41B, PARVA, MICAL2, USP47, EIF4G2 
	   DENND5A, CTR9, TEAD1, MTRNR2L8, TMEM9B, AMPD3, ADM, RPL27A, LINC00958, EIF3F 
	   BTBD10, PPFIBP2, FAR1, MRPL17, RRAS2, TAF10, COPB1, ILK, PSMA1, TIMM10B 
Negative:  MALAT1, NEAT1, RNASEH2C, OVOL1, FIBP, CFL1, CCDC85B, DRAP1, SART1, DPF2 
	   EIF1AD, BANF1, SF3B2, CAPN1, PACS1, RAB1B, S100A14, S100A13, YIF1A, MRPL49 
	   CHTOP, S100A16, BRMS1, ILF2, GATAD2B, MRPL11, S100A6, RBM4, SLC39A1, FAU 
PC_ 3 
Positive:  WNT6, FARSB, USP37, ACSL3, WDFY1, MRPL44, TMBIM1, SERPINE2, PNKD, CUL3 
	   AAMP, MFF, AGFG1, ARPC2, PID1, TRIP12, CAB39, IGFBP2, ITM2C, PSMD1 
	   RPL37A, NCL, PTMA, XRCC5, DIS3L2, EIF4E2, MREG, GIGYF2, DGKD, LINC00607 
Negative:  CGA, ZNF292, RARS2, ORC3, AKIRIN2, RNGTT, SNHG5, PNRC1, UBE2J1, SYNCRIP 
	   LYRM2, SNX14, MDN1, PGM3, UBE3D, CASP8AP2, TPBG, UFL1, TTK, NDUFAF4 
	   ELOVL4, MMS22L, SH3BGRL2, PNISR, HMGN3, USP45, PHIP, CCNC, MYO6, ASCC3 
PC_ 4 
Positive:  RHOG, RRM1, PGAP2, NUP98, TRIM5, ZNF195, CARS, CCKBR, NAP1L4, ARFIP2 
	   PHLDA2, TIMM10B, CDKN1C, KCNQ1OT1, TSSC4, ILK, CD81, H19, TAF10, MRPL23 
	   CTSD, MRPL17, MOB2, PPFIBP2, AP2A2, EIF3F, CHID1, NUMA1, RNF121, DHCR7 
Negative:  RNF34, KDM2B, ANAPC5, C12orf43, ORAI1, SPPL3, MLEC, TMEM120B, POP5, PSMD9 
	   RNF10, DYNLL1, VPS33A, SRSF9, CLIP1, GATC, TRIAP1, ZCCHC8, COX6A1, RSRC2 
	   PXN, DENR, RPLP0, RAB35, ARL6IP4, HSPB8, SUDS3, PITPNM2, TAOK3, PEBP1 
PC_ 5 
Positive:  ABCF1, PPP1R10, GNL1, MRPS18B, DHX16, HLA-E, TUBB, RPP21, FLOT1, PPP1R11 
	   IER3, POU5F1, TRIM27, HLA-C, HIST1H1B, DDX39B, HIST1H2AH, BAG6, ABT1, GPANK1 
	   HMGN4, CSNK2B, HIST1H1D, CLIC1, HIST1H1E, VARS, HIST1H4C, HIST1H1C, LSM2, HIST1H3B 
Negative:  PPFIBP2, EIF3F, MRPL17, RPL27A, TAF10, TMEM9B, ILK, DENND5A, TIMM10B, TMEM41B 
	   ARFIP2, IPO7, CCKBR, ZNF143, TRIM5, RRM1, WEE1, RHOG, SWAP70, PGAP2 
	   SBF2, NUP98, ADM, AMPD3, ZNF195, MTRNR2L8, CARS, CTR9, NAP1L4, EIF4G2 
Computing nearest neighbor graph
Computing SNN
INFO [2022-12-09 16:50:26] define_signif_tumor_subclusters(), tumor: 1
Calculating gene variances
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating feature variances of standardized and clipped values
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Centering and scaling data matrix
  |=====================================================================================| 100%
PC_ 1 
Positive:  KIAA1217, PIP4K2A, ARHGAP21, BMI1, ABI1, DNAJC1, YME1L1, MLLT10, RAB18, NEBL 
	   MPP7, UBE2H, MEST, NRF1, MKLN1, AHCYL2, PODXL, CHCHD3, WAC, EXOC4 
	   TNPO3, PLXDC2, SLC35B4, ATP6V1F, AKR1B1, CALU, CALD1, BAMBI, CNOT4, METTL2B 
Negative:  RPS11, NOSIP, IRF3, BCL2L12, RPL13A, PRMT1, AP2A1, PIH1D1, PTOV1, SNRNP70 
	   AKT1S1, NUP62, CGB7, ATF5, CGB8, NR1H2, EMC10, CGB5, RUVBL2, C19orf48 
	   GYS1, ETFB, FTL, BAX, PPP2R1A, NUCB1, ZNF480, PPP1R15A, RPL18, ZNF808 
PC_ 2 
Positive:  TEAD1, LINC00958, BTBD10, RPL27A, TMEM9B, PARVA, DENND5A, EIF3F, TMEM41B, IPO7 
	   FAR1, MICAL2, ZNF143, USP47, EIF4G2, WEE1, RRAS2, PPFIBP2, SWAP70, MRPL17 
	   CTR9, COPB1, TAF10, SBF2, PSMA1, ILK, ADM, AMPD3, MTRNR2L8, TIMM10B 
Negative:  S100A14, S100A16, S100A6, S100A13, PRR9, CHTOP, S100A11, S100A10, ILF2, MRPL9 
	   GATAD2B, SLC39A1, SNX27, JTB, POGZ, RAB13, PSMB4, RPS27, PSMD4, TPM3 
	   C1orf43, PIP5K1A, UBAP2L, VPS72, HAX1, SCNM1, ADAR, MLLT11, APOA1, SHC1 
PC_ 3 
Positive:  DPPA5, KHDC3L, KHDC1L, OOEP, EEF1A1, SMAP1, COX7A2, FAM135A, TMEM30A, PHF3 
	   SENP6, MYO6, PRIM2, PHIP, BAG2, HMGN3, ZNF451, SH3BGRL2, ELOVL4, DST 
	   TTK, COL21A1, TPBG, LRRC1, UBE3D, GCLC, PGM3, ELOVL5, SNX14, GCM1 
Negative:  BIN2, SMAGP, SLC4A8, DAZAP2, KRT80, TFCP2, KRT7, SLC11A2, KRT8, ATF1 
	   KRT18, DIP2B, LARP4, EIF4B, LIMA1, PFDN5, CERS5, C12orf10, COX14, PRR13 
	   SMARCD1, PCBP2, MAP3K12, RACGAP1, CBX5, CCT3, TMBIM6, HNRNPA1, SMG5, COPZ1 
PC_ 4 
Positive:  DYRK1A, PSMG1, BRWD1, TTC3, HLCS, MORC3, HMGN1, CBR1, MX1, RUNX1 
	   WDR4, SLC5A3, NDUFV3, MRPS6, ITSN1, ERVH48-1, DONSON, PKNOX1, SON, GART 
	   TMEM50B, RRP1B, PAXBP1, SYNJ1, PDXK, MIS18A, SOD1, CSTB, TIAM1, BACH1 
Negative:  SNHG5, CGA, SYNCRIP, SNX14, PGM3, ZNF292, UBE3D, RARS2, ORC3, TPBG 
	   NDUFAF4, AKIRIN2, UFL1, MMS22L, CASP8AP2, RNGTT, PNISR, MDN1, TTK, PNRC1 
	   UBE2J1, LYRM2, USP45, ELOVL4, CCNC, ASCC3, SH3BGRL2, LIN28B, PREP, ATG5 
PC_ 5 
Positive:  NDUFC1, ELF2, SLC7A11, SCLT1, NAA15, PGRMC2, LARP1B, SETD7, SPATA5, CCNA2 
	   MGST2, EXOSC9, MAML3, ANXA5, SCOC, PRDM5, ZNF330, MAD2L1, GAB1, SMARCA5 
	   C4orf3, ANAPC10, ABCE1, LSM6, USP53, SLC10A7, ARHGAP10, SEC24D, LRBA, RPS3A 
Negative:  THOC3, SIMC1, SFXN1, NOP16, MSX2, CPEB4, BOD1, STC2, HIGD2A, ATP6V0E1 
	   RPL26L1, CLTB, SH3PXD2B, UBTD2, FAF2, STK10, FBXW11, UIMC1, NPM1, RANBP17 
	   NSD1, SPDL1, PANK3, PRELID1, RARS, LMAN2, TMED9, WWC1, N4BP3, NHP2 
Computing nearest neighbor graph
Computing SNN
INFO [2022-12-09 16:50:28] define_signif_tumor_subclusters(), tumor: 2
Calculating gene variances
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating feature variances of standardized and clipped values
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Centering and scaling data matrix
  |=====================================================================================| 100%
PC_ 1 
Positive:  FTL, GYS1, BAX, RUVBL2, CGB5, CGB8, PIH1D1, SNRNP70, NUCB1, CGB7 
	   RPL13A, RPS11, NOSIP, PPP1R15A, RPL18, IRF3, GRWD1, BCL2L12, NAPA, ZNF114 
	   SAE1, KDELR1, ZC3H4, PRMT1, TMEM160, AP2S1, AP2A1, SLC1A5, PTOV1, CALM3 
Negative:  STK24, DOCK9, FARP1, UBAC2, IPO5, TM9SF2, PCCA, MBNL2, TPP2, UGGT2 
	   TEX30, DNAJC3, ARGLU1, GPC6, COL4A1, NDFIP2, COL4A2, CARS2, RBM26, ING1 
	   EDNRB, ANKRD10, MYCBP2, ARHGEF7, FBXL3, TUBGCP3, CLN5, ATP11A, LMO7, UCHL3 
PC_ 2 
Positive:  RFC3, ALG5, PDS5B, N4BP2L2, EXOSC8, UFM1, HSPH1, PROSER1, HMGB1, COG6 
	   UBL3, POMP, MRPS31, PAN3, POLR1D, ELF1, LNX2, MTIF3, WBP4, GTF3A 
	   VWA8, RPL21, DNAJC15, CDK8, TSC22D1, RNF6, NUFIP1, ATP8A2, GTF2F2, MTMR6 
Negative:  TRIO, DAP, ZNF622, MARCH6, MYO10, CCT5, NSUN2, MED10, BASP1, IRX2 
	   IRX4, C5orf17, NDUFS6, GOLPH3, MRPL36, MTMR12, LPCAT1, CLPTM1L, ZFR, TRIP13 
	   BRD9, PDCD6, SDHA, PLEKHG4B, SUB1, TARS, RAI14, EPB41L3, ARHGAP28, RAD1 
PC_ 3 
Positive:  B4GALNT3, KDM5A, WNK1, ERC1, ADIPOR2, FKBP4, FOXM1, TEAD4, TSPAN9, RAD51AP1 
	   NDUFA9, CD9, TNFRSF1A, LTBR, MRPL51, GAPDH, NOP2, CHD4, MLF2, PTMS 
	   CDCA3, TPI1, LRRC23, C12orf57, EMG1, PHB2, LPCAT3, DPPA3, NANOG, SLC2A3 
Negative:  LGMN, RIN3, CPSF2, GOLGA5, NDUFB1, BTBD7, ATXN3, TRIP11, DDX24, RPS6KA5 
	   GLRX5, TTC7B, GSKIP, PAPOLA, CALM1, PSMC1, VRK1, TDP1, SETD3, EFCAB11 
	   CCNK, FOXN3, YY1, ZC3H14, MEG3, MSX2, CPEB4, CEP128, SFXN1, FAM193A 
PC_ 4 
Positive:  LYRM2, MDN1, CASP8AP2, UBE2J1, PNRC1, UFL1, RNGTT, NDUFAF4, AKIRIN2, MMS22L 
	   ORC3, PNISR, RARS2, USP45, ZNF292, CCNC, CGA, ASCC3, SNHG5, SYNCRIP 
	   LIN28B, SNX14, PREP, PGM3, UBE3D, ATG5, TPBG, TTK, QRSL1, ELOVL4 
Negative:  ORMDL2, PMEL, SARNP, GDF11, CDK2, CD63, RAB5B, BLOC1S1, RPS26, ERBB3 
	   GTSF1, PA2G4, ITGA5, COPZ1, RPL41, HNRNPA1, MYL6B, CBX5, MYL6, MAP3K12 
	   SMARCC2, PCBP2, RNF41, PRR13, CNPY2, C12orf10, RBMS2, PFDN5, BAZ2A, EIF4B 
PC_ 5 
Positive:  PFDN5, C12orf10, PRR13, EIF4B, PCBP2, KRT18, KRT8, MAP3K12, CBX5, KRT7 
	   KRT80, HNRNPA1, SLC4A8, COPZ1, BIN2, ITGA5, SMAGP, GTSF1, DAZAP2, BLOC1S1 
	   TFCP2, CD63, SLC11A2, GRWD1, RPL18, PTDSS1, UQCRB, KDELR1, MTDH, LAPTM4B 
Negative:  PUS1, SFSWAP, RAN, BRI3BP, GTF2H3, DHX37, NCOR2, EP400, UBC, EIF2B1 
	   DDX55, POLE, TMED2, PXMP2, RILPL1, PGAM5, SNRNP35, ANKLE2, RILPL2, ZNF195 
	   CARS, NUP98, NAP1L4, SBNO1, GOLGA3, PGAP2, PHLDA2, RHOG, CDKN1C, CHFR 
Computing nearest neighbor graph
Computing SNN
INFO [2022-12-09 16:50:29] define_signif_tumor_subclusters(), tumor: 3
Calculating gene variances
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating feature variances of standardized and clipped values
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Centering and scaling data matrix
  |=====================================================================================| 100%
PC_ 1 
Positive:  UCHL3, COMMD6, TBC1D4, LMO7, CLN5, KLF5, MZT1, PIBF1, DIS3, LINC00383 
	   FBXL3, TDRD3, MYCBP2, DIAPH3, EDNRB, LINC00458, RBM26, SUGT1, NDFIP2, GPC6 
	   CKAP2, DNAJC3, VPS36, UGGT2, ATP7B, MBNL2, WDFY2, IPO5, SWT1, IVNS1ABP 
Negative:  RPS28, NDUFA7, CD320, ELAVL1, HNRNPM, TIMM44, ZNF121, PET100, TRAPPC5, INSR 
	   TRIP10, UBL5, TUBB4A, KHSRP, GTF2F1, ALKBH7, PIN1, CLPP, MLLT1, NDUFA11 
	   PPAN, RPS26, LONP1, ERBB3, PA2G4, RPL41, RPL36, TGFB1, EXOSC5, HNRNPUL1 
PC_ 2 
Positive:  KPNA6, KHDRBS1, TXLNA, PTP4A2, EIF3I, TINAGL1, HDAC1, ZBTB8OS, MARCKSL1, RBBP4 
	   SYNC, ZCCHC17, YARS, TMEM54, RNF19B, SNRNP40, AK2, PHC2, SMIM12, SFPQ 
	   PUM1, ZMYM4, PSMB2, CLSPN, SRSF4, AGO1, AGO3, EPB41, TRAPPC3, MAP7D1 
Negative:  NDUFC1, ELF2, SLC7A11, SCLT1, PGRMC2, LARP1B, SPATA5, CCNA2, EXOSC9, SH3D19 
	   ANXA5, PRDM5, FAM160A1, FBXW7, MAD2L1, TMEM154, C4orf3, ARFIP1, FHDC1, USP53 
	   SEC24D, TRIM2, SNHG8, CAMK2D, PLRG1, ANK2, LARP7, PPID, ENPEP, ELOVL6 
PC_ 3 
Positive:  MTAP, FOCAD, RPS6, CAAP1, DENND4C, PLAA, PLIN2, HAUS6, RRAGA, PSIP1 
	   SNAPC3, MPDZ, RUFY1, HNRNPH1, KDM4C, CANX, HNRNPAB, NHP2, GLDC, MGAT4B 
	   N4BP3, SQSTM1, TMED9, LMAN2, PRELID1, UIMC1, NSD1, UHRF2, FAF2, TBC1D9B 
Negative:  TRIML2, SLC25A4, ZFP42, UFSP2, FRG1, CASP3, RWDD4, ING2, DCTD, WWC2 
	   TENM3, AC078881.1, SPCS3, HPGD, NDUFC1, ANK2, LARP7, ENPEP, CAMK2D, HMGB2 
	   ELOVL6, ELF2, SNHG8, GAR1, SLC7A11, SEC24D, AADAT, SCLT1, PLA2G12A, ANXA5 
PC_ 4 
Positive:  ZFR, SUB1, MTMR12, GOLPH3, TARS, C5orf17, RAI14, RAD1, BASP1, MYO10 
	   BRIX1, ZNF622, TRIO, DAP, MARCH6, CCT5, NSUN2, MED10, IRX2, IRX4 
	   NDUFS6, MRPL36, MYL12B, LPCAT1, MYL12A, CLPTM1L, LPIN2, TRIP13, SMCHD1, BRD9 
Negative:  NDUFC1, ELF2, SLC7A11, SCLT1, PGRMC2, SH3D19, LARP1B, SPATA5, FAM160A1, CCNA2 
	   FBXW7, TMEM154, EXOSC9, ARFIP1, ANXA5, FHDC1, PRDM5, TRIM2, MAD2L1, PLRG1 
	   C4orf3, PPID, USP53, FNIP2, SEC24D, RAPGEF2, NAF1, TMA16, SNHG8, MSMO1 
PC_ 5 
Positive:  EXOSC4, MAF1, CYC1, GRINA, MROH1, PLEC, BOP1, HSF1, SLC52A2, JAM3 
	   ZBTB44, APLP2, VPS28, THYN1, ST3GAL4, ARHGAP32, CHEK1, RPL8, STT3A, C8orf33 
	   EI24, HMGN1, TTC3, HLCS, DYRK1A, PSMG1, BRWD1, MORC3, CBR1, RUNX1 
Negative:  SNRPA1, TM2D3, CHSY1, IGF1R, CHD2, NR2F2, MEF2A, PRC1, UNC45A, FURIN 
	   BLM, CRTC3, IQGAP1, NGRN, IDH2, FANCI, AEN, WIPI2, SDK1, TNRC18 
	   MRPS11, ACTB, FSCN1, GNA12, CAMK2N1, RNF216, MRPL46, CHST12, OTUD3, AIMP2 
Computing nearest neighbor graph
Computing SNN
INFO [2022-12-09 16:50:30] define_signif_tumor_subclusters(), tumor: 4
Calculating gene variances
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating feature variances of standardized and clipped values
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Centering and scaling data matrix
  |=====================================================================================| 100%
PC_ 1 
Positive:  C19orf48, ETFB, EMC10, PPP2R1A, NR1H2, ZNF480, ATF5, NUP62, AKT1S1, ZNF808 
	   PTOV1, AP2A1, PRMT1, ZNF83, BCL2L12, IRF3, ZNF611, NOSIP, RPS11, ZNF600 
	   RPL13A, PIH1D1, SNRNP70, CGB7, ZNF28, CGB8, CGB5, RUVBL2, GYS1, ZNF468 
Negative:  UBE2D3, CISD2, CENPE, TET2, MANBA, PPA2, INTS12, PPP3CA, GSTCD, H2AFZ 
	   TBCK, DNAJB14, AIMP1, LAMTOR3, GOLPH3L, CERS2, ENSA, PAPSS1, C1orf56, CDC42SE1 
	   MLLT11, MCL1, SCNM1, VPS72, RPRD2, TRMT10A, PIP5K1A, HADH, PRPF3, PSMD4 
PC_ 2 
Positive:  NUCB2, PIK3C2A, ZDHHC13, SPTY2D1, SAA1, LDHA, GTF2H1, E2F8, TSG101, RPS13 
	   PLEKHA7, C11orf58, CALCB, PSMA1, COPB1, RRAS2, FAR1, BTBD10, LINC00958, MPHOSPH8 
	   PSPC1, TEAD1, ZMYM2, AL161772.1, PARVA, ARID3A, XPO4, SAP18, PTBP1, LATS2 
Negative:  KLF10, UBR5, AZIN1, RRM2B, GRHL2, ZNF706, ATP6V1C1, YWHAZ, CTHRC1, PABPC1 
	   RNF19A, POLR2K, DCAF13, COX6C, VPS13B, STK3, ZFPM2, RPL30, LAPTM4B, MTDH 
	   OXR1, PTDSS1, UQCRB, EIF3E, NDUFAF6, ESRP1, EMC2, OTUD6B, NUDCD1, RIPK2 
PC_ 3 
Positive:  SDC4, STK4, SYS1, TOMM34, DBNDD2, DNTTIP1, YWHAB, PKIG, UBE2C, SERINC3 
	   PLTP, SLC35C2, TP53RK, ZMYND8, NCOA3, PREX1, ARFGEF2, CSE1L, STAU1, DDX27 
	   ZFAS1, B4GALT5, RNF114, UBE2V1, TMEM189, CEBPB, PTPN1, PARD6B, ADNP, DPM1 
Negative:  XPNPEP3, RBX1, ST13, SLC25A17, EP300, ADSL, L3MBTL2, TNRC6B, RANGAP1, RPS19BP1 
	   TOB2, ATF4, MIEF1, PHF5A, ACO2, SYNGR1, POLR3H, RPL3, PMM1, TOMM22 
	   DDX17, DESI1, CSNK1E, TMEM184B, XRCC6, MAFF, SREBF2, POLR2F, MICALL1, SMDT1 
PC_ 4 
Positive:  RPS26, ERBB3, PA2G4, RAB5B, RPL41, CDK2, MYL6B, PMEL, MYL6, ORMDL2 
	   SMARCC2, SARNP, RNF41, GDF11, CNPY2, CD63, RBMS2, BLOC1S1, BAZ2A, GTSF1 
	   ITGA5, PTGES3, COPZ1, NACA, HNRNPA1, PRIM1, CBX5, LRP1, MAP3K12, PCBP2 
Negative:  GNAS, NELFCD, VAPB, CTSZ, TAF4, RAB22A, PSMA7, RBM38, MTG2, RPS25 
	   HYOU1, HMBS, CCDC84, BCL9L, H2AFX, DDX6, RAE1, ARCN1, CBL, OSBPL2 
	   KMT2A, MCAM, UBE4A, BMP7, ADRM1, RNF214, PCSK7, ARHGEF12, TAGLN, TFAP2C 
PC_ 5 
Positive:  COPZ1, HNRNPA1, ITGA5, GTSF1, CBX5, BLOC1S1, ERBB3, CD63, GDF11, RPS26 
	   PA2G4, SARNP, MAP3K12, RAB5B, ORMDL2, PMEL, CDK2, PCBP2, RPL41, PRR13 
	   MYL6B, C12orf10, PFDN5, MYL6, EIF4B, KRT7, KRT18, KRT8, KRT80, SLC4A8 
Negative:  SH3GL1, CHAF1A, MAP2K2, ZBTB7A, DPP9, PLIN3, EEF2, DAPK3, SAFB2, MRPL54 
	   PIP5K1C, SAFB, HMG20B, MFSD12, RPL36, DOHH, LONP1, NCLN, THOP1, NDUFA11 
	   SGTA, MLLT1, SLC39A3, CLPP, GADD45B, ALKBH7, LMNB2, GTF2F1, TIMM13, ETFA 
Computing nearest neighbor graph
Computing SNN
INFO [2022-12-09 16:50:32] define_signif_tumor_subclusters(), tumor: doublet
Calculating gene variances
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating feature variances of standardized and clipped values
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Centering and scaling data matrix
  |=====================================================================================| 100%
PC_ 1 
Positive:  SLC39A3, SGTA, GADD45B, THOP1, LMNB2, NCLN, TIMM13, DOHH, LSM7, MFSD12 
	   OAZ1, HMG20B, PLEKHJ1, PIP5K1C, AP3D1, MKNK2, MRPL54, CSNK1G2, DAPK3, ABHD17A 
	   TCF3, EEF2, UQCR11, ZBTB7A, MBD3, MAP2K2, MEX3D, RPS15, SH3GL1, DAZAP1 
Negative:  NCKAP1, NUP35, DNAJC10, UBE2E3, CWC22, ZC3H15, SESTD1, AC007319.1, AGPS, NFE2L2 
	   TFPI, HNRNPA3, MTX2, GULP1, CIR1, OLA1, SP3, ITGA6, WDR75, HAT1 
	   DYNC1I2, DCAF17, METTL8, TLK1, GORASP2, UBR3, METTL5, SSB, KLHL23, SLC40A1 
PC_ 2 
Positive:  NUP107, SLC35E3, RAP1B, MDM2, CAND1, CPM, GRIP1, TMBIM4, LLPH, CPSF6 
	   RASSF3, TBK1, XPOT, YEATS4, SRGAP1, FRS2, PPM1H, CCT2, MON2, RAB3IP 
	   USP15, CNOT2, TSFM, ZFC3H1, RAB21, METTL1, TBC1D15, CDK4, TRHDE, KRR1 
Negative:  EEF1B2, FASTKD2, NDUFS1, CREB1, CCNYL1, RPE, INO80D, BARD1, FZD5, IDH1 
	   ATIC, RAPH1, FN1, ABI2, CYP20A1, LINC00607, NBEAL1, MREG, XRCC5, WDR12 
	   RPL37A, BMPR2, IGFBP2, NOP58, ARPC2, SUMO1, AAMP, NDUFB3, PNKD, ORC2 
PC_ 3 
Positive:  MLEC, POP5, SPPL3, RNF10, C12orf43, DYNLL1, ANAPC5, RNF34, SRSF9, KDM2B 
	   ORAI1, GATC, TMEM120B, TRIAP1, PSMD9, COX6A1, VPS33A, PXN, CLIP1, RPLP0 
	   ZCCHC8, RAB35, RSRC2, HSPB8, DENR, ARL6IP4, SUDS3, RIMKLB, A2ML1-AS1, SLC2A3 
Negative:  ODC1, HPCAL1, NOL10, RRM2, GRHL1, ATP6V1C2, TAF1B, YWHAQ, PDIA6, ADAM17 
	   ROCK2, IAH1, NBAS, CPSF3, ITGB1BP1, DDX1, ID2, MYCN, RPS7, RNASEH1 
	   FAM49A, TMEM41B, ADI1, IPO7, DENND5A, ZNF143, TMEM18, TMEM9B, WEE1, ACP1 
PC_ 4 
Positive:  HIST1H3B, HIST1H1A, HIST1H1C, GMNN, HIST1H4C, C6orf62, HIST1H1E, ACOT13, HIST1H1D, TDP2 
	   HMGN4, MRS2, CASC15, ABT1, SOX4, HIST1H2AH, CDKAL1, HIST1H1B, E2F3, TRIM27 
	   DEK, TPMT, PPP1R11, KIF13A, RPP21, NUP153, HLA-E, CAP2, GNL1, DTNBP1 
Negative:  FGFR2, ATE1, NSMCE4A, TACC2, BUB3, OAT, ZRANB1, CTBP2, BCCIP, DHX32 
	   RILPL1, SNRNP35, TMED2, EIF2B1, DDX55, RILPL2, DOCK1, GTF2H3, SBNO1, NCOR2 
	   CDK2AP1, PITPNM2, ARL6IP4, DENR, UBC, RSRC2, ZCCHC8, CLIP1, DHX37, PTPRE 
PC_ 5 
Positive:  SNRNP70, CGB7, CGB8, CGB5, ATF5, RUVBL2, NR1H2, GYS1, EMC10, FTL 
	   C19orf48, BAX, NUCB1, ETFB, PPP1R15A, RPL18, PPP2R1A, GRWD1, KDELR1, ZNF480 
	   ZNF114, ZNF808, NAPA, SAE1, ZNF83, ZC3H4, TMEM160, ZNF611, AP2S1, SLC1A5 
Negative:  NOL7, TBC1D7, RANBP9, HIVEP1, MCUR1, JARID2, SMIM13, DTNBP1, TMEM14B, CAP2 
	   NUP153, TMEM14C, KIF13A, PAK1IP1, TPMT, DEK, GCNT2, PRRC2B, E2F3, NUP214 
	   RAPGEF1, AIF1L, MED27, SETX, ABL1, TFAP2A, DDX31, GTF3C4, FUBP3, SURF6 
Computing nearest neighbor graph
Computing SNN
INFO [2022-12-09 16:50:33] define_signif_tumor_subclusters(), tumor: unassigned
INFO [2022-12-09 16:50:33] Less cells in group unassigned than k_nn setting. Keeping as a single subcluster.
Calculating gene variances
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating feature variances of standardized and clipped values
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Centering and scaling data matrix
  |=====================================================================================| 100%
Error in irlba(A = t(x = object), nv = npcs, ...) : 
  max(nu, nv) must be strictly less than min(nrow(A), ncol(A))

**Comment by GeorgescuC** [comment]
Hi @sheilak97 ,

Looking at the log, it appears the issue happens when trying to run a PCA (which we now do as default preprocessing before running the Leiden algorithm when building the neighbors graph). Since the "unassigned"  annotation has less than 20 cells (default k_nn) it should not try to run the PCA on it at all and simply return one cluster for that annotation, but no other log message indicates it has moved on to another annotation or the per chromosome subclustering.

Could you check that you are running the latest version of infercnv (1.14.0)?
If you are, would you be able to privately share the backup object from the last step that successfully completed so I can look into the issue?

Regards,
Christophe.

**Comment by GeorgescuC** [comment]
Issue fixed in c8419cb5178b6a626e884aaf002354877a0671ca thanks to @sheilak97 sharing their data.
