### ISSUE TITLE
Replacing read.table with data.table::fread() 

### ISSUE THREAD

**Issue by SNOL2** [broadinstitute/infercnv#489]
Hi, thanks for this great tool.
I think using data.table::fread() to load file may be faster when reading large files.
Thanks again!

**Comment by GeorgescuC** [comment]
Hi @SNOL2 ,

Yes, that is true. We actually have an extra script to read the counts matrix using fread() and make a sparse matrix rds file to use in infercnv available in [scripts/](https://github.com/broadinstitute/infercnv/blob/master/scripts/prepare_sparsematrix.R). The code has not been included in the main methods but I will try to get around to do it.

Regards,
Christophe.

**Comment by SNOL2** [comment]
@GeorgescuC ,
Thanks!
