### ISSUE TITLE
I have something wrong in running infercnv

### ISSUE THREAD

**Issue by antho199** [broadinstitute/infercnv#532]
INFO [2023-04-26 09:32:05] ::process_data:Start
INFO [2023-04-26 09:32:05] Creating output path cnv1/
INFO [2023-04-26 09:32:05] Checking for saved results.
INFO [2023-04-26 09:32:05] 

	STEP 1: incoming data

INFO [2023-04-26 10:13:55] 

	STEP 02: Removing lowly expressed genes

INFO [2023-04-26 10:13:55] ::above_min_mean_expr_cutoff:Start
INFO [2023-04-26 10:14:39] Removing 11432 genes from matrix as below mean expr threshold: 0.1
INFO [2023-04-26 10:16:04] validating infercnv_obj
INFO [2023-04-26 10:16:04] There are 8490 genes and 232361 cells remaining in the expr matrix.
INFO [2023-04-26 10:26:47] no genes removed due to min cells/gene filter
INFO [2023-04-26 10:55:57] 

	STEP 03: normalization by sequencing depth

INFO [2023-04-26 10:55:57] normalizing counts matrix by depth
INFO [2023-04-26 11:06:16] Computed total sum normalization factor as median libsize: 4650.000000
INFO [2023-04-26 11:32:16] 

	STEP 04: log transformation of data

INFO [2023-04-26 11:32:16] transforming log2xplus1()
INFO [2023-04-26 11:55:57] 

	STEP 08: removing average of reference data (before smoothing)

INFO [2023-04-26 11:55:57] ::subtract_ref_expr_from_obs:Start inv_log=FALSE, use_bounds=TRUE
INFO [2023-04-26 11:55:58] -no reference cells specified... using mean of all cells as proxy
INFO [2023-04-26 12:10:05] -subtracting expr per gene, use_bounds=TRUE
INFO [2023-04-26 13:08:57] 

	STEP 09: apply max centered expression threshold: 3

INFO [2023-04-26 13:08:57] ::process_data:setting max centered expr, threshold set to: +/-:  3
INFO [2023-04-26 13:58:33] 

	STEP 10: Smoothing data per cell by chromosome

INFO [2023-04-26 13:58:33] smooth_by_chromosome: chr: chr1
INFO [2023-04-26 14:18:16] smooth_by_chromosome: chr: chr2
INFO [2023-04-26 14:37:27] smooth_by_chromosome: chr: chr3
INFO [2023-04-26 14:52:42] smooth_by_chromosome: chr: chr4
INFO [2023-04-26 15:06:00] smooth_by_chromosome: chr: chr5
INFO [2023-04-26 15:19:29] smooth_by_chromosome: chr: chr6
INFO [2023-04-26 15:32:22] smooth_by_chromosome: chr: chr7
INFO [2023-04-26 15:47:08] smooth_by_chromosome: chr: chr8
INFO [2023-04-26 15:59:47] smooth_by_chromosome: chr: chr9
INFO [2023-04-26 16:13:31] smooth_by_chromosome: chr: chr10
INFO [2023-04-26 16:29:36] smooth_by_chromosome: chr: chr11
INFO [2023-04-26 16:45:46] smooth_by_chromosome: chr: chr12
INFO [2023-04-26 16:58:51] smooth_by_chromosome: chr: chr13
INFO [2023-04-26 17:08:50] smooth_by_chromosome: chr: chr14
INFO [2023-04-26 17:20:21] smooth_by_chromosome: chr: chr15
INFO [2023-04-26 17:32:36] smooth_by_chromosome: chr: chr16
INFO [2023-04-26 17:45:38] smooth_by_chromosome: chr: chr17
INFO [2023-04-26 17:55:07] smooth_by_chromosome: chr: chr18
INFO [2023-04-26 18:06:22] smooth_by_chromosome: chr: chr19
INFO [2023-04-26 18:16:31] smooth_by_chromosome: chr: chr20
INFO [2023-04-26 18:25:48] smooth_by_chromosome: chr: chr21
INFO [2023-04-26 18:33:52] smooth_by_chromosome: chr: chr22
INFO [2023-04-26 19:11:12] 

	STEP 11: re-centering data across chromosome after smoothing

INFO [2023-04-26 19:11:12] ::center_smooth across chromosomes per cell
INFO [2023-04-26 19:51:26] 

	STEP 12: removing average of reference data (after smoothing)

INFO [2023-04-26 19:51:26] ::subtract_ref_expr_from_obs:Start inv_log=FALSE, use_bounds=TRUE
INFO [2023-04-26 19:51:26] -no reference cells specified... using mean of all cells as proxy
INFO [2023-04-26 19:55:43] -subtracting expr per gene, use_bounds=TRUE
INFO [2023-04-26 20:29:29] 

	STEP 14: invert log2(FC) to FC

INFO [2023-04-26 20:29:29] invert_log2(), computing 2^x
INFO [2023-04-26 21:06:27] 

	STEP 15: computing tumor subclusters via leiden

INFO [2023-04-26 21:06:27] define_signif_tumor_subclusters(p_val=0.1
INFO [2023-04-26 21:06:27] define_signif_tumor_subclusters(), tumor: all_observations
Calculating gene variances
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating feature variances of standardized and clipped values
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Centering and scaling data matrix
  |======================================================================================================| 100%
PC_ 1 
Positive:  NOTCH4, HLA-DRA, HLA-DRB5, HLA-DRB1, HLA-DQA1, HLA-DQB1, HLA-DQA2, TAP2, MTF2, TMED5 
	   CCDC18-AS1, DR1, ABL2, FNBP1L, DNTTIP2, ARHGAP29, GCLM, NR4A2, RPRM, ARL6IP6 
	   GPD2, PRPF40A, CYTIP, TOR3A, PKP4, DAPL1, TANC1, FAM20B, BAZ2B, MARCH7 
Negative:  C11orf24, KMT5B, LRP5, CHKA, PPP6R3, TCIRG1, GAL, SCAND1, NDUFS8, ROMO1 
	   NFS1, PHF20, CNBD2, NORAD, RBM39, RBM12, EPB41L1, CPNE1, ALDH3B1, SPAG4 
	   CPT1A, DLGAP4, ERGIC3, UQCC1, EIF6, EDEM2, MYL9, TRPC4AP, UNC93B1, GSS 
PC_ 2 
Positive:  SMYD2, PROX1, CENPF, KCTD3, ANGEL2, GPATCH2, RRP15, FLVCR1, LYPLAL1, EPRS 
	   TATDN3, IARS2, NSL1, ATF3, RAB3GAP2, NENF, PPP2R5A, C1orf115, LPGAT1, DUSP10 
	   SLC30A1, SIPA1L2, TSNAX, NTPCR, MIA3, EGLN1, KCNK1, SPRTN, COA6, TARBP1 
Negative:  KMT2B, EIF1AD, BANF1, SART1, CST6, SF3B2, PACS1, RAB1B, YIF1A, BRMS1 
	   COX6B1, B4GAT1, MRPL11, DPP3, ZDHHC24, RBM42, CTSF, CCS, RBM14, RBM4 
	   RCE1, TMEM147, RHOD, KDM2A, GRK2, ANKRD13D, DMKN, SSH3, USF2, RAD9A 
PC_ 3 
Positive:  POLG, FANCI, ABHD2, ANPEP, MFGE8, AP3S2, ISG20, MRPS11, MRPL46, AKAP13 
	   ARPIN, PDE8A, ZNF592, IDH2, SEC11A, SEMA4B, NMB, WDR73, TM6SF1, CIB1 
	   BTBD1, NGRN, C15orf40, IQGAP1, WHAMM, CRTC3, RPS17, IL16, ABHD17C, FURIN 
Negative:  NPW, SLC9A3R2, ZNF598, NTHL1, GFER, TSC2, TBL3, PKD1, SNHG9, TRAF7 
	   RPS2, MLST8, PGP, NDUFB10, ECI1, RNPS1, MSRB1, ATP6V0C, AMDHD2, PDPK1 
	   FAHD1, KCTD5, SRRM2, HAGH, ZG16B, PRSS22, NUBP2, FLYWCH2, SPSB3, TNFRSF12A 
PC_ 4 
Positive:  MDFIC, TMEM168, IFRD1, TFEC, ZNF277, TES, IMMP2L, DOCK4, DNAJB9, CAV2 
	   THAP5, PNPLA8, CAV1, LAMB1, MET, LSM8, CAPZA2, TSPAN12, DLD, ING3 
	   CPED1, CBLL1, FAM3C, AASS, CADPS2, NDUFA5, BCAP29, WASL, ZNF800, COG5 
Negative:  MT1M, MT1A, MT1E, MT1F, MT2A, MRPL48, COA4, MT1G, OGFOD1, PAAF1 
	   RAB6A, NUDT21, UCP2, PLEKHB1, AMFR, PPME1, FAM168A, MT1H, CES1, PGM2L1 
	   RELT, KCNE3, LPCAT2, FCHSD2, MT1X, POLD3, ATG16L2, MMP2, RNF169, NUP93 
PC_ 5 
Positive:  POLB, IKBKB, PLAT, AP3M2, KAT6A, GPAT4, SEC62, MYNN, GPR160, PHC3 
	   MECOM, GOLGA7, PRKCI, SKIL, GOLIM4, CLDN11, SERPINI1, PDCD10, SLC7A14, BCHE 
	   SFRP1, RPL22L1, NMD3, KPNA4, IDO1, EIF5A2, TRIM59, SMC4, ADAM9, SLC2A2 
Negative:  IGLC2, IGLC3, IGLC1, IGLC7, IGLV2-11, IGLV2-14, BCR, GRK3, PRAME, SNRPD3 
	   PPM1F, GUCD1, MAPK1, HPS4, PPIL2, SPECC1L, SDF2L1, CHCHD10, YDJC, CABIN1 
	   SRRD, MMP11, DDT, SMARCB1, TFIP11, UBE2L3, DERL3, MIF, TPST2, PITPNB 
Computing nearest neighbor graph
Computing SNN
INFO [2023-04-27 12:30:00] ::plot_cnv:Start
INFO [2023-04-27 12:30:00] ::plot_cnv:Current data dimensions (r,c)=8490,232361 Total=1975382217.61418 Min=0.648741183664771 Max=2.54576230571394.
INFO [2023-04-27 12:30:14] ::plot_cnv:Depending on the size of the matrix this may take a moment.
INFO [2023-04-27 12:33:11] plot_cnv(): auto thresholding at: (0.847739 , 1.154935)
INFO [2023-04-27 12:36:03] plot_cnv_observation:Start
INFO [2023-04-27 12:36:03] Observation data size: Cells= 232361 Genes= 8490
INFO [2023-04-27 12:36:03] clustering observations via method: ward.D
Error in seq_len(max(obs_annotations_groups)) : 
  argument must be coercible to non-negative integer
In addition: Warning message:
In max(nchar(obs_annotations_names)) :
  no non-missing arguments to max; returning -Inf

**Comment by dipingxian431** [comment]
Hello, I also have the same question. Did you resolve it? Thank you!
