### ISSUE TITLE
ERROR: configuration failed for package ‘rjags’

### ISSUE THREAD

**Issue by archana433** [broadinstitute/infercnv#553]
hi, I am getting this error
configure: WARNING: pkg-config file for jags 4 unavailable
configure: WARNING: Consider adding the directory containing `jags.pc`
configure: WARNING: to the PKG_CONFIG_PATH environment variable
configure: Attempting legacy configuration of rjags
checking for jags... no
configure: error: "automatic detection of JAGS failed. Please use pkg-config to locate the JAGS library. See the INSTALL file for details."
ERROR: configuration failed for package ‘rjags’

i have tried below suggestion also , but no luck
 Unix/Linux: pkg-config
------------------------

If you have pkg-config installed then you can use it to detect the
JAGS library and set the compiler and linker flags for rjags. You
can test this capability in a unix shell by typing

pkg-config --modversion jags

If this does not detect your JAGS installation then it means that the
file 'jags.pc' installed is not on the search path of pkg-config. In
this case you should add it by setting the environment variable
PKG_CONFIG_PATH. For example if the full path to 'jags.pc' is
'/usr/local/lib64/pkgconfig/jags.pc', then set

export PKG_CONFIG_PATH=/usr/local/lib64/pkgconfig

before installing rjags.

**Comment by GeorgescuC** [comment]
Hi @archana433 ,

Do you have JAGS installed? It is a non-R dependency that `rjags` is an interface to. If that is the issue, you can install it [from here](https://sourceforge.net/projects/mcmc-jags/files/JAGS/4.x/)

Regards,
Christophe.

**Comment by archana433** [comment]
Hi,
Thanks for the reply. Yes , when I installed  and loaded JAGS, it's working now.
