### ISSUE TITLE
Problem retrieving infercnv.observations.txt and infercnv.references.txt output files

### ISSUE THREAD

**Issue by RoyPollak** [broadinstitute/infercnv#605]
Hey InferCNV team, thank you very much for making this bioinformatic tool easily and freely accessible! :)

After running the run() function, I didn't manage to find infercnv.observations.txt and infercnv.references.txt output files in the output directory.

This is the code I ran: 
run(male_only_infercnv_obj,
                              out_dir = 'InferCNV_output',
                              cutoff = 1, 
                              cluster_by_groups = TRUE,
                              denoise = TRUE,
                              HMM = FALSE,
                              window_length = 101)

I will be very happy if you could instruct me how can I retrieve this file, or else, what am I doing wrong?

With many thanks.
Roy

**Comment by ywh517** [comment]
Your answer is very helpful to me, thank you Roy
