### ISSUE TITLE
After Running InferCNV, dendrogram and other files missing

### ISSUE THREAD

**Issue by carmelo7a** [broadinstitute/infercnv#632]
I am following along the user guide example, and got to the "run infercnv" step but after running it my "InferCNVrun_outputs" folder doesn't have the proper files that I've seen others have. My code was as follows:

`Userguide_10xBreastCancer_infCNV = infercnv::run(Userguide_10xBreastCancer_infCNV, 
+                                                  cutoff=0.1, out_dir="./InferCNVrun_outputs", 
+                                                  cluster_by_groups=FALSE,HMM = FALSE, 
+                                                  denoise=TRUE)`

<img width="921" alt="image" src="https://github.com/broadinstitute/infercnv/assets/156477686/b2f8b032-d672-40cd-81c5-2787373524d8">

This is the return I get, which to see is free of errors. However, once in my directory, I only see the following:
<img width="770" alt="image" src="https://github.com/broadinstitute/infercnv/assets/156477686/1513a9c9-aedd-4d36-947d-a4b7ba682955">
I am missing the dendrogram as well as my denoised png file which I need to continue on with the tutorial. I assume I should be looking for something similar to below, which I found on a forum while researching this issue.
<img width="340" alt="image" src="https://github.com/broadinstitute/infercnv/assets/156477686/3d46edc8-622e-4eac-8140-3cc5b5ca377d">

Any suggestions or leads would be very helpful.

**Comment by sigalgrabois** [comment]
hi. how did you solve this?

**Comment by carmelo7a** [comment]
add "write_expr_matrix = T,
       write_phylo = T" inside your infercnv run code
