### ISSUE TITLE
About the cluster_by_groups=T option

### ISSUE THREAD

**Issue by kysbbubbu** [broadinstitute/infercnv#64]
Hello

When i tried the new version of inferCNV with cluster_by_groups=T option, it seems that inferCNV results were not classified according to the identity in the annotation file, but only the number of each cluster was identical to the number of each identity in the annotation file.

I find this problem by inspecting infercnv.observation_groupings.txt file.

The grouping of the cell barcodes in the  infercnv.observation_groupings.txt file is not identical to one in the cell annotation file.

When I tried one with cluster_by_groups=F, it went well.

I uploaded the relevant files. Please check the problem. Thanks 

[RefseuratintermediateF0F10.txt](https://github.com/broadinstitute/inferCNV/files/2638866/RefseuratintermediateF0F10.txt)
[infercnv.observation_groupings.txt](https://github.com/broadinstitute/inferCNV/files/2638867/infercnv.observation_groupings.txt)
![infercnv](https://user-images.githubusercontent.com/38550028/49365634-a55fb480-f72a-11e8-86f0-dbe6a7816eb6.png)

**Comment by GeorgescuC** [comment]
Hi @kysbbubbu ,

I see the issue in the output file you provided but have not been able to reproduce something similar with the classification you provided using a mock matrix.
Could you provide me with the script/commands you ran please?

If possible, could you also provide me with a copy of the input data format? The expression values within the matrix can be shuffled/changed for data privacy, but the column and row names should be preserved as I expect the issue to be related to reading/sorting based on column/row names.

Best,
Christophe.
