### ISSUE TITLE
infercnv step 18

### ISSUE THREAD

**Issue by shubham-koirala** [broadinstitute/infercnv#641]
I am running inferCNV using 5000 highly variable genes and 80,000 cells. Around 40,000 are controls and 40,000 are diseased. I am stuck in step 18 for a longer time. It never proceeds and the job gets killed. I am running it on hpc.
"""
        STEP 18: Run Bayesian Network Model on HMM predicted CNVs

INFO [2024-02-22 10:42:30] Initializing new MCM InferCNV Object.
INFO [2024-02-22 10:42:30] validating infercnv_obj
INFO [2024-02-22 10:42:31] Total CNV's:  6006
INFO [2024-02-22 10:42:31] Loading BUGS Model.
INFO [2024-02-22 10:43:04] Running Sampling Using Parallel with  4 Cores
"""

**Comment by shubham-koirala** [comment]
I later increased the #SBATCH parameters related to resources.

**Comment by archana433** [comment]
hi @shubham-koirala  which parameters have you changed exactly ? I am also working on HPC and step 18 is taking longer time and it gets killed. I tried to resolve by incerasing memory and also reduced/increased number of cores. For some samples it worked but for  > 1,00,000 cells , it is still a problem. 
NFO [2024-03-21 10:17:43] Initializing new MCM InferCNV Object.
INFO [2024-03-21 10:17:43] validating infercnv_obj
INFO [2024-03-21 10:17:44] Total CNV's:  9694
INFO [2024-03-21 10:17:44] Loading BUGS Model.
INFO [2024-03-21 10:18:21] Running Sampling Using Parallel with  28 Cores

**Comment by shubham-koirala** [comment]
Hi @archana433,
I used:
.....
#SBATCH --nodes=4
#SBATCH --ntasks-per-node=5
#SBATCH --cpus-per-task=20
#SBATCH --mem=300G
#SBATCH --time=72:00:00
.....
It took me around 17 hours to complete the run for matrix of 23,000 genes and 90,000 cells. You can also subset the matrix with 5k highly variable genes. 

Also, if you are considering big matrix size see: https://github.com/broadinstitute/infercnv/wiki/Infercnv-runs-successfully-and-generated-plots-but-they-are-blank

**Comment by archana433** [comment]
Thanks @shubham-koirala

**Comment by zhangqt23** [comment]
> Hi [@archana433](https://github.com/archana433), 

i am also using HPC, if this is your setting:
```
#SBATCH --nodes=4
#SBATCH --ntasks-per-node=5
#SBATCH --cpus-per-task=20
#SBATCH --mem=300G
#SBATCH --time=72:00:00
```
i wondering what is your "num_threads = "setting in infercnv::run ?
```
infercnv_obj <- infercnv::run(
  infercnv_obj,
  cutoff = 0.1,
  out_dir = infercnv_dir,
  cluster_by_groups = FALSE, 
  HMM = TRUE,
  denoise = TRUE,
  analysis_mode = "subclusters",
  tumor_subcluster_partition_method = "leiden",
  leiden_resolution = 0.01,
  num_threads = 50,
  output_format = "png",
  write_expr_matrix=TRUE
)

```

**Comment by zhangqt23** [comment]
hi @shubham-koirala 
i am also using HPC, if this is your setting:

```
#SBATCH --nodes=4
#SBATCH --ntasks-per-node=5
#SBATCH --cpus-per-task=20
#SBATCH --mem=300G
#SBATCH --time=72:00:00
```
i wondering what is your "num_threads = "setting in infercnv::run ?

```
infercnv_obj <- infercnv::run(
  infercnv_obj,
  cutoff = 0.1,
  out_dir = infercnv_dir,
  cluster_by_groups = FALSE, 
  HMM = TRUE,
  denoise = TRUE,
  analysis_mode = "subclusters",
  tumor_subcluster_partition_method = "leiden",
  leiden_resolution = 0.01,
  num_threads = 50,
  output_format = "png",
  write_expr_matrix=TRUE
)

```
