### ISSUE TITLE
error on "ngchm" function

### ISSUE THREAD

**Issue by helianthuszhu** [broadinstitute/infercnv#66]
Hi, 
   ngchm() is a good function to figure out which rows have similar CNVs. However, when I tried to run it I got the following errors. It seems something is wrong with "ShaidyRMapGen". My system is mac 10.13.4. Does that matter? Very appreciated if anyone can give me some suggestions. Thanks.
> ngchm(infercnv_obj=infercnv_obj ,
+       out_dir              = ".",
+       path_to_shaidyMapGen = "./ShaidyMapGen.jar",
+       gene_symbol          = "bio.gene.hugo")
INFO [2018-12-09 22:12:59] Creating NGCHM as infercnv.ngchm
INFO [2018-12-09 22:13:09] Saving new NGCHM object
Sun Dec 09 22:13:09 2018	PROGRESS	:Writing specification:	50	creating specification directory
Sun Dec 09 22:13:09 2018	PROGRESS	:Writing specification:	80	writing extra support files
Exception in thread "main" java.lang.UnsupportedClassVersionError: mda/ngchm/datagenerator/ShaidyRMapGen : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
Error in NGCHM::chmExportToFile(hm, file_path, overwrite = TRUE, shaidyMapGen = path_to_shaidyMapGen) : 
  export to ngchm failed

**Comment by brownmp** [comment]
Hello, 

Are you making sure to load the NGCHM library before running the ngchm() function?
```R
library(NGCHM)
```

**Comment by helianthuszhu** [comment]
Hi, Mr. Brown,
    Thanks for your reply. Yes, I have loaded the library of NGCHM. Also, I realized that this function was tested on R 3.4. I have checked my R version (3.5.1). Does that matter?

**Comment by zhuxqdoctor** [comment]
Also, I have tried to run NGCHM in linux Rstudio but got another errors like this. I totally have no idea how to fix this. Hope you can give some advice. Thanks you so much.
> library(NGCHM)
> ngchm(infercnv_obj=infercnv_obj , out_dir= ".",path_to_shaidyMapGen = "./ShaidyMapGen.jar",gene_symbol          = "bio.gene.hugo")
INFO [2018-12-10 14:56:44] Creating NGCHM as infercnv.ngchm
INFO [2018-12-10 14:57:02] Saving new NGCHM object
Mon Dec 10 02:57:02 HKT 2018	PROGRESS	:Writing specification:	50	creating specification directory
Mon Dec 10 02:57:02 HKT 2018	PROGRESS	:Writing specification:	80	writing extra support files
Warning: No heat map description provided in properties : chm.info.caption.
Warning: Row label type (axisTypes where = row or both) not specified.  Will use generic linkouts menu

START Data Generator Heat Map Generation: Mon Dec 10 14:57:04 HKT 2018
Exception in thread "main" java.awt.AWTError: Can't connect to X11 window server using ':0' as the value of the DISPLAY variable.
	at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
	at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65)
	at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:115)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
	at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
	at java.awt.image.BufferedImage.createGraphics(BufferedImage.java:1181)
	at mda.ngchm.datagenerator.HeatmapDataGenerator.buildTnThumbnail(Unknown Source)
	at mda.ngchm.datagenerator.HeatmapDataGenerator.processHeatMap(Unknown Source)
	at mda.ngchm.datagenerator.ShaidyRMapGen.main(Unknown Source)
Error in NGCHM::chmExportToFile(hm, file_path, overwrite = TRUE, shaidyMapGen = path_to_shaidyMapGen) : 
  export to ngchm failed

**Comment by brownmp** [comment]
@helianthuszhu The issue looks to be caused by your current version of Java. The expected Java version should be 1.8.

**Comment by brownmp** [comment]
@zhuxqdoctor Are you running an X server when using inferCNV.

**Comment by helianthuszhu** [comment]
Thanks you so much. I have changed the java version as you suggested. Up to now, I can run the function of NGCHM and trying to further explore the data in NGCHM viewer. Thanks again.

**Comment by brownmp** [comment]
This issue has been solved by using the newest version of the NGCHM viewer. The link to the NGCHM viewer on the Wiki has been updated to the newest version.

**Comment by hdesai6** [comment]
Hello, currently working on a gene expression project to create heat maps. Data consists of 68 rows and 1099 columns. Using the script and changing the range numbers, I am at the part chmExportToFile . I keep running into the following error:


Exception instantiating RowColData Object: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at mda.ngchm.datagenerator.RowColData.constructOrderArrayFromFile(Unknown Source)
	at mda.ngchm.datagenerator.RowColData.constructOrderArray(Unknown Source)
	at mda.ngchm.datagenerator.RowColData.<init>(Unknown Source)
	at mda.ngchm.datagenerator.ImportData.setHeatmapProperties(Unknown Source)
	at mda.ngchm.datagenerator.ImportData.<init>(Unknown Source)
	at mda.ngchm.datagenerator.HeatmapDataGenerator.processHeatMap(Unknown Source)
	at mda.ngchm.datagenerator.ShaidyRMapGen.main(Unknown Source)
FATAL ERROR: Importing Heat Map Configuration Data. Index 1 out of bounds for length 1
ERROR in ShaidyRMapGen e= BUILD ERROR: Importing Heat Map Configuration Data. Index 1 out of bounds for length 1
Error in chmExportToFile(heatMap1, "/Users/hdesai6/Documents/CholGenes/firstHeatMap.ngchm",  : 
  export to ngchm failed


What am I doing wrong?

**Comment by brownmp** [comment]
hello @hdesai6,

Sorry to hear you having troubles. Would you be able to share the data set you are working with so that I may attempt to see why this problem is occurring. in particular would you be able to send me the infercnv object "preliminary.infercnv_obj". All information shared would be kept private. My email is mbrown@broadinstitute.org.

-Maxwell

**Comment by ccruizm** [comment]
Good day!

I am trying to create a ngchm object for interactive visualisation. After running successfully infercnv, I am using the `infercnv_obj` to create the ngchm file but I am getting the following error:

My code:
```
ngchm(infercnv_obj          = infercnv_obj,
       out_dir              = "output_dir_inferCNV",
       path_to_shaidyMapGen = "/home/cruiz/10x_scRNAseq/markers-and-databases/ShaidyMapGen.jar",
       gene_symbol          = "bio.gene.hugo")
```

Error:
```
INFO [2019-07-30 11:10:47] Creating NGCHM as infercnv.ngchm
INFO [2019-07-30 11:10:47] Initializing new NGCHM InferCNV Object.
Error in (function (cl, name, valueClass) : 'cuts_color' is not a slot in class "ngchmLayer"
Traceback:

1. ngchm(infercnv_obj = infercnv_obj, out_dir = "output_dir_inferCNV", 
 .     path_to_shaidyMapGen = "/home/cruiz/10x_scRNAseq/markers-and-databases/ShaidyMapGen.jar", 
 .     gene_symbol = "bio.gene.hugo")
2. Create_NGCHM(infercnv_obj = infercnv_obj, path_to_shaidyMapGen = path_to_shaidyMapGen, 
 .     out_dir = out_dir, title = title, gene_symbol = gene_symbol, 
 .     x.range = x.range, x.center = x.center)
3. setCutsColor(hm)
4. setCutsColor(hm)
5. (function (cl, name, valueClass) 
 . {
 .     ClassDef <- getClass(cl)
 .     slotClass <- ClassDef@slots[[name]]
 .     if (is.null(slotClass)) 
 .         stop(gettextf("%s is not a slot in class %s", sQuote(name), 
 .             dQuote(cl)), domain = NA)
 .     if (.identC(slotClass, valueClass)) 
 .         return(TRUE)
 .     ok <- possibleExtends(valueClass, slotClass, ClassDef2 = getClassDef(slotClass, 
 .         where = .classEnv(ClassDef)))
 .     if (isFALSE(ok)) 
 .         stop(gettextf("assignment of an object of class %s is not valid for @%s in an object of class %s; is(value, \"%s\") is not TRUE", 
 .             dQuote(valueClass), sQuote(name), dQuote(cl), slotClass), 
 .             domain = NA)
 .     TRUE
 . })(structure("ngchmLayer", package = "NGCHM"), "cuts_color", 
 .     "character")
6. stop(gettextf("%s is not a slot in class %s", sQuote(name), dQuote(cl)), 
 .     domain = NA)
```

What do you think might be the issue here? Thanks in advance for your help!

**Comment by brownmp** [comment]
Hello @ccruizm,

Sorry to hear you are having problems generating the NGCHM heat map. 
What version of R and NGCHM are you currently using?
Also, could you please run `getClass("ngchmLayer")` in R after loading the NGCHM library and report what you see.

Best,
Maxwell

**Comment by ccruizm** [comment]
Hello @brownmp,

Thank you for your quick reply! This is the info of my session:

```
R version 3.5.1 (2018-07-02)
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: Gentoo/Linux

Matrix products: default
BLAS/LAPACK: /home/cruiz/anaconda3/envs/r_env/lib/R/lib/libRblas.so

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] infercnvNGCHM_0.1.0 NGCHM_0.11.14       infercnv_1.1.2     
[4] data.table_1.12.2   dplyr_0.8.3         Seurat_3.0.2 
```

and this is the info I obtained after running `getClass("ngchmLayer")`:

```
Class "ngchmLayer" [package "NGCHM"]

Slots:
                                                                  
Name:                 name                data              colors
Class:           character               shaid       ngchmColormap
                          
Name:  summarizationMethod
Class:           character
```

I noticed that I could not run `ncghm` loading only the library `NGCHM`. I had to load `infercnvHGCHM` as well to be able to use the function.

**Comment by brownmp** [comment]
Thanks! Looks like the slot for the class `ngchmLayer` is missing. 
I would attempt to reinstall the package `NGCHMR` to get the latest updates. 
The function `ngchm` is a function in the package `infercnvNGCHM` and therefore needs to be loaded. 

Best, 
Maxwell

**Comment by kerimsecener** [comment]
Hi,

I am re-opening this issue because I am facing the exact same problem, although I have the latest versions for NGCHMR and infercnvNGCHM.
Here is the sessionInfo():

R version 3.6.1 (2019-07-05)
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /home/asecene/miniconda3/envs/seurat/lib/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Seurat_3.1.1        NGCHM_0.11.14       infercnvNGCHM_0.1.0
[4] infercnv_1.3.1

getClass("ngchmLayer") gives me this:

Class "ngchmLayer" [package "NGCHM"]

Slots:
                                                                  
Name:                 name                data              colors
Class:           character               shaid       ngchmColormap
                          
Name:  summarizationMethod
Class:           character

**Error:**
INFO [2019-11-27 16:43:50] Creating NGCHM as infercnv.ngchm
INFO [2019-11-27 16:43:50] Initializing new NGCHM InferCNV Object.
Error in (function (cl, name, valueClass)  : 
  ‘cuts_color’ is not a slot in class “ngchmLayer”

Do you have any idea why this might happen ?

Thanks,

Kerim

**Comment by brownmp** [comment]
@kerimsecener,

When installing NGCHMR, use `devtools::install_github("bmbroom/NGCHMR", ref="master")`.

- M. Brown

**Comment by beemilmlo** [comment]
> @helianthuszhu The issue looks to be caused by your current version of Java. The expected Java version should be 1.8.

Hi,

I think I have the correct version of Java...Is there something I need to do after downloading and installing the application? I'm having the exact same problem.

Best,
Ros
