### ISSUE TITLE
cell groups consisting of just one cell

### ISSUE THREAD

**Issue by plijnzaad** [broadinstitute/infercnv#67]
Dear all,

I'm playing with `infercnv` (v0.8.2) and run into some problems. They seem to have to do with cell groupings that are represented by just one cell. I managed to get rid of some of the crashes using `,drop=FALSE`  (see the patch below; this is against 699187cf93899d63eca9d4894540512b46256942), but there is one that still gives problems when calling `plot_cnv()`

```
Error in heatmap.cnv(obs_data, Rowv = obs_dendrogram, Colv = FALSE, cluster.by.row = TRUE,  : 
  'RowIndividualColors' must be a character vector of length nrow(x)
In addition: Warning messages:
1: In cbind(row_groupings, get_group_color_palette()(length(table(hcl_obs_annotations_groups)))[hcl_obs_annotations_groups]) :
  number of rows of result is not a multiple of vector length (arg 2)
2: In cbind(obs_annotations_names, get_group_color_palette()(length(table(hcl_obs_annotations_groups)))) :
  number of rows of result is not a multiple of vector length (arg 2)
3: In cbind(split_groups, row_groupings[, 1], hcl_obs_annotations_groups,  :
  number of rows of result is not a multiple of vector length (arg 3)
```

I notice that in `.plot_cnv_observations` the singleton groups are skipped, would this perhaps result in an inconcistent state of the `obs_data` object? ? 

```
            if (num_genes_in_group < 2) {
                flog.info(sprintf("Skipping group: %d, since less than 2 entries", i))
                next
            }
```

When the thing crashes , the contents of `RowIndividualColors` look like:

```
Browse[2]>

RowIndividualColors
       row_groupings          
  [1,] "#8DD3C7"     "#8DD3C7"
  [2,] "#8DD3C7"     "#8DD3C7"
  [3,] "#8DD3C7"     "#8DD3C7"
  ...
[629,] "#8DD3C7"     "#D1C2D2"
[630,] "#8DD3C7"     "#D1C2D2"
[631,] "#8DD3C7"     NA       
[632,] "#8DD3C7"     NA       
[633,] "#8DD3C7"     NA       
[634,] "#8DD3C7"     "#8DD3C7"
[635,] "#8DD3C7"     "#8DD3C7"

```
which probably has to do with it.  I can merge the singletons into something bigger prior to loading, but would prefer to keep them, or is that meaningless?

Kind regards, Philip

[patch.txt](https://github.com/broadinstitute/inferCNV/files/2687080/patch.txt)

**Comment by GeorgescuC** [comment]
Hi @plijnzaad ,

It looks like the part of code you pointed to is the one relevant to your issue. I made a new branch to try to fix the issue if you would like to test it. Also, feel free to contribute your patch as a PR.

The branch is the following:
https://github.com/broadinstitute/inferCNV/tree/one_cell_group_fix

Regards,
Christophe.

**Comment by plijnzaad** [comment]
Hi @GeorgescuC , 

thanks for looking into it, I just created the pull request (which is just the little patch I send).  I'm happy to look at you fix branch.    Having said that I'm not clear on how meaningful the singleton groups are in this  context, the grouping used just for visualisation, or also for the CNV inference itself ?

**Comment by plijnzaad** [comment]
Hi, I had a quick look  with your branch,  but I still get this:

```
INFO [2018-12-18 13:39:11] plot_cnv_observation:Writing observation groupings/color.
Error in heatmap.cnv(obs_data, Rowv = obs_dendrogram, Colv = FALSE, cluster.by.row = TRUE,  : 
  'RowIndividualColors' must be a character vector of length nrow(x)
In addition: Warning messages:
1: In cbind(row_groupings, get_group_color_palette()(length(table(hcl_obs_annotations_groups)))[hcl_obs_annotations_groups]) :
  number of rows of result is not a multiple of vector length (arg 2)
2: In cbind(obs_annotations_names, get_group_color_palette()(length(table(hcl_obs_annotations_groups)))) :
  number of rows of result is not a multiple of vector length (arg 2)
3: In cbind(split_groups, row_groupings[, 1], hcl_obs_annotations_groups,  :
  number of rows of result is not a multiple of vector length (arg 3)

```
It seems there are still a few `,drop=FALSE`'s missing, I'll send another pull request (which however still doesn't fix it)

**Comment by GeorgescuC** [comment]
Hi @plijnzaad ,

I have merged your PR to the branch with the attempt at fixing the issue to work based on it.
After going through the part that was giving errors the main issue was with getting the dendrogram for annotations with only 1 cell, as there is no straight forward way of making a 1 branch dendrogram object. A "fake" dendrogram object is now manually built and merged with the other annotations dendrograms.
I modified the example we provide to have 2 annotations with only 1 cell and it ran to the end generating the correct plot for me. Let me know if this fixes the issue for you too. The fix is on the same "one_cell_group_fix" branch.

Regards,
Christophe.

**Comment by plijnzaad** [comment]
Many thanks, I'll have a look!

Ph

**Comment by nlaillerbms** [comment]
Hi @plijnzaad,

Did you manage to have it working? I am hitting the same error as you with the latest version of InferCNV.
Thanks!

**Comment by plijnzaad** [comment]
ow, sorry, no, I haven't tried :-/

**Comment by plijnzaad** [comment]
Has this issue been resolved, or has it resurfaced? I get the exact same error with singleton groups in version 1.10.1.

**Comment by marlaherr** [comment]
I get the same error although I do not have any singleton groups in my inferCNV object, my smallest group has 37 cells. I tried "random trees" and “leiden" subclustering but got the same error message. I also tried lower leiden_resolution (0.5) but it didn’t help. 
Would appreciate any help. Thanks!

**Comment by Nisanity007** [comment]
> Has this issue been resolved, or has it resurfaced? I get the exact same error with singleton groups in version 1.10.1.
> 
> edit: when I remove the cells that belong to these singleton groups, things seem to work fine.

I met the same error, however, there is no such error before(version 1.14); I will try the 'cluster_by_groups = FALSE' or install it again to try it.
