### ISSUE TITLE
Problem in loading ngchm file in standalone viewer

### ISSUE THREAD

**Issue by julienvibert** [broadinstitute/inferCNV#76]
Hi,
I have created a ngchm object with inferCNV. However, when I try to load it into the standalone viewer, nothing happens...
I have followed instructions on the Wiki to create the ngchm object. However I wonder if it is related to the fact that I had to change the name of the file "infercnv.observation_groupings.txt" (one of the output from inferCNV) into "observation_groupings.txt", as the former name was not recognized by the ngchm function?
I have also noticed that the ngchm I created is composed of "tile" files, whereas the sample TCGA ngchm object available online (that I can view) is composed of bin files.
Thank you for your help!
Julien

**Comment by brownmp** [comment]
Hello Julien,

Thank you so much for bringing this to our attention. I have adjusted the name for the input file 'infercnv.observation_groupings.txt'. 
What version of NGCHM are you currently using?

Best, 
Maxwell

**Comment by julienvibert** [comment]
Hello Maxwell,
Thank you very much for your quick reply and fix! (And sorry for the delay in answering)
The versions I am using are:
infercnv_0.8.2  and NGCHM_0.11.14
Best,
Julien

**Comment by brownmp** [comment]
Hi Julien, 
Sounds like something is wrong with the rendering. What version of Java are you currently using? 
Should be running with Java-1.8
Best,
Maxwell

**Comment by julienvibert** [comment]
Hi Maxwell, I don't have my computer in front of me but I know I checked for the Java version and it was 1.8 if I remember well. Moreover I had no problem to open the sample ngchm object with TCGA data. I noticed however that my ngchm object is composed of tile files, while the sample TCGA ngchm object is in bin files, is the issue related to this? Thank you for your help! Best, Julien 

Envoyé depuis Yahoo Mail pour Android 
 
  Le ven., févr. 15, 2019 à 18:48, M. Brown<notifications@github.com> a écrit :   
Hi Julien,
Sounds like something is wrong with the rendering. What version of Java are you currently using?
Should be running with Java-1.8
Best,
Maxwell

**Comment by brownmp** [comment]
Hello Julien, 

Its possible that it could be an issue with your ShaidyMapGen. Would you be able to share the data set you are working with so that I may attempt to see why this problem is occurring. All information shared would be kept private. My email is mbrown@broadinstitute.org. 

-Maxwell

**Comment by brownmp** [comment]
This issue has been solved by using the newest version of the NGCHM stand alone viewer. The link to the NGCHM stand alone viewer has been updated.
