### ISSUE TITLE
Error in .mask_DE_genes

### ISSUE THREAD

**Issue by FBoulogne** [broadinstitute/inferCNV#77]
Dear all,

I have been working with InferCNV and ran into a small error while using the noise_filtering and the one_cell_group_fix branches. 

The 'DE_results' obtained by looping over the 'all_DE_results' list is a vector containing the tumor indices. Therefore the '$ operator is invalid for atomic vectors' error appears when trying to extract the tumor indices from the 'DE_results'. 

for (DE_results in all_DE_results) {
  if (length(DE_results$tumor_indices) < min_cluster_size_mask) {
    all_DE_genes_matrix[, DE_results$tumor_indices] = num_normal_types
}

I suppose this is very easy to fix, but I would just like to point it out.

Kind regards,
Floranne Boulogne

**Comment by FBoulogne** [comment]
Dear all, 

I have had a more in-depth look into this error and it turns out that the arguments given to the .mask_DE_genes function are defined in the wrong order. More strictly defining the arguments and removing the 'tumor_groupings' argument in the mask_non_DE_genes_basic function seem to have done the trick! I will upload these changes as a pull request. 

Kind regards,
Floranne

**Comment by brianjohnhaas** [comment]
Thx!  The code is under heavy development and we're working primarily off
the devel branch.  We'll just update it directly.

-via googleFi

**Comment by brianjohnhaas** [comment]
got it.  fixed under devel (on my fork... will go into the main repo soon)
