### ISSUE TITLE
[Bug] Cutoff option only accepts integers

### ISSUE THREAD

**Issue by wflynny** [broadinstitute/inferCNV#8]
In the Wiki page [Analysis with Controls](https://github.com/broadinstitute/inferCNV/wiki/Analysis-with-Controls), it suggests using `--cutoff 4.5`.  However, this gets truncated to `4` by the script as the options parser is configured to only accept integers (scripts/inferCNV.R, line 157).

**Comment by GeorgescuC** [comment]
Hi @wflynny ,

Thanks for pointing it out! Now fixed in ace7d1a00bfe2bc94439324d8539e84755a80e25 .

Regards,
Christophe.
