### ISSUE TITLE
matrix output from inferCNV 

### ISSUE THREAD

**Issue by danshu** [broadinstitute/inferCNV#85]
Hi,

I have run inferCNV and have a few questions.
What are values in the output cell matrix? Are they transformed expression values? Does InferCNV output CNV profiles? If not, how can I generate CNV profiles?

Best,
Danshu

**Comment by brianjohnhaas** [comment]
Hi

Right now it reports the heatmap containing residual intensities.  We'll be
releasing a new version in a couple of weeks that does cnv prediction too.

-via googleFi

**Comment by danshu** [comment]
Thanks!
